### ISSUE TITLE
Running build script fails to compile

### ISSUE THREAD

**Issue by alvesl** [marmelab/admin-on-rest#1001]
Hello,

I've run into a problem trying to compile for distribution:
```
yarn build v0.27.5
$ react-scripts build
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

 	./node_modules/admin-on-rest/src/util/HttpError.js:1

Read more here: http://bit.ly/2tRViJ9

error Command failed with exit code 1.
```

Following `create-react-app`'s link, it seems to be related to NodeJS modules and stuff. Which I find weird since the problem occurs on AoR. Also, checking out the file, there is not much into it, just maybe a reference to `class` that fails to minify? What am I missing?

Thanks a lot for the help.

**Comment by alvesl** [comment]
Update: After some reading, it seems create-react-app is not supposed to transpile ES6 code, nor it intends to do so in the future.
This really confuses me, why does admin-on-rest have ES6 code? should it have a dist version in which everything is pre-built and transpiled?
Also, I have no idea how the demo source works, to me it feels like it should fail for the same reason above...

**Comment by fzaninotto** [comment]
It seems you're including non transpiled code, which is weird. How do you include aor components in your code?

**Comment by djhi** [comment]
create-react-app does transpile ES6 code, it even includes a custom babel preset

**Comment by fzaninotto** [comment]
Yes, but not on the dependencies

**Comment by alvesl** [comment]
Yea, took me a while to figure this out.. Apparently I imported the HttpError module from the src files, which will not get transpiled (and it makes sense to me why that happens now)... 
My bad on this, AoR works perfectly like intended and I should not use the module in that way.

Closing this now, thank you so much for looking into it, keep up the awesome project!
