### ISSUE TITLE
ReferenceInput not populating in Create

### ISSUE THREAD

**Issue by anttyc** [marmelab/admin-on-rest#1002]
Hi, I've encountered a situation where ReferenceInput is not rendering when I'm in the Create form in version 1.2.2. It renders fine in the Edit form.

Here are the snippets that re relevant and screenshots of the form field.

```
<Create {...props}>
        <SimpleForm>
            <ReferenceInput source="venue_id" reference="venue" label="Venue">
                <SelectInput optionText="name"/>
            </ReferenceInput>
            <TextInput source="name" />
            <LongTextInput source="description" />
            <LongTextInput source="additional_details" />
            <NumberInput source="price_tax_percent"/>
            <NumberInput source="price_base" label="Base Price of Package" />
            <NumberInput source="price_per_pax" label="Price Per Pax" />
            <NumberInput source="pax_min" label="Min Pax" />
            <NumberInput source="pax_max" label="Max Pax" />
            <DropzoneInput source="cover_photo_url"/>
        </SimpleForm>
    </Create>
```

```
<Edit {...props} actions={<EditActions />}>
        <SimpleForm>
            <ReferenceInput source="venue_id" reference="venue" label="Venue">
                <SelectInput optionText="name"/>
            </ReferenceInput>
            <TextInput source="name" />
            <LongTextInput source="description" />
            <LongTextInput source="additional_details" />
            <NumberInput source="price_tax_percent"/>
            <NumberInput source="price_base" label="Base Price of Package" />
            <NumberInput source="price_per_pax" label="Price Per Pax" />
            <NumberInput source="pax_min" label="Min Pax" />
            <NumberInput source="pax_max" label="Max Pax" />
            <DropzoneInput source="cover_photo_url"/>
        </SimpleForm>
    </Edit>
```

<img width="1029" alt="screen_shot_2017-09-06_at_8_44_46_pm" src="https://user-images.githubusercontent.com/933885/30112551-561008b2-9344-11e7-8c2d-8ed72d4db0b6.png">

Both Edit and Create are defined and exported from the same js file. Anyone else encountering this issue?

**Comment by djhi** [comment]
Have you tried adding the [`allowEmpty`](https://marmelab.com/admin-on-rest/Inputs.html#referenceinput) prop ?

**Comment by ilovebioz** [comment]
I got the same problem even added allowEmpty prop. I must refresh the page again to make the value appear correctly on Edit page.

**Comment by djhi** [comment]
Can you both provide a repository with enough code to reproduce the issue ? I can't reproduce it on the sample app

**Comment by anttyc** [comment]
allowEmpty={true} fixed my issue! thanks @djhi!

**Comment by djhi** [comment]
@ilovebioz Please open a separate issue and provide a repository with enough code to reproduce the problem.

**Comment by anttyc** [comment]
@djhi that said - the field is a required field for the model, allowEmpty would technically allow the user to submit with an empty value. is this behaviour (for ReferenceInput) intended and should i handle validation on submission?
