### ISSUE TITLE
User is redirected to list after failed UPDATE/DELETE. Success notification is shown

### ISSUE THREAD

**Issue by mstmustisnt** [marmelab/admin-on-rest#101]
When server error occurs on CRUD UPDATE `Element updated` notification is shown. Error is ignored. 
 
Can be reproduced in example project. 
No error on failed DELETE as well.

Will appreciate any help. 

**UPD**. Actually error is shown. But for a moment. It's hard to notice without debugging. User should not be redirected to list after failed UPDATE/DELETE

**Comment by fzaninotto** [comment]
Was the problem only on your side?

**Comment by mstmustisnt** [comment]
@fzaninotto thanks for your answer.. I was using outdated version. Sorry. There is no such issue with new one
