### ISSUE TITLE
Auto clear data in Edit Page

### ISSUE THREAD

**Issue by congaductq** [marmelab/admin-on-rest#1016]
I created a dialog that contains a Create Form inside a Edit Form.
When I click on "New relationship" button, the dialog will be shown, but I don't know why the `records` in Edit form also be cleared.

Before click show Dialog:
[![Before click show Dialog][1]][1]

When click show Dialog:
[![When click show Dialog][2]][2]

After click show Dialog:
  [![After click show Dialog][3]][3]

Here is my code: 

    export class CaregiverEdit extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            open: false,
        };
    }

    handleOpen = () => {
        this.setState({open: true});
    };

    handleClose = () => {
        this.setState({open: false});
    };

    render() {
        const style = {
            margin: 12,
        };
        const actions = [
            <FlatButton
                label="Ok"
                onClick={ this.handleClose }
            />,
        ];
        var id = this.props.location.pathname.split('/')[2];
        const propsCreate = Object.assign({}, this.props, { authParams : {resource : "rela", route : "create"},
            location : {pathname : "/rela/create"}, match : { path : "/rela/create", url : "/rela/create"}, resource : "rela" });
        return (
            <div>
                <Edit title={<CaregiverTitle />} {...this.props}>
                    <SimpleForm>
                        <DisabledInput source="id"/>
                        <ImageField source="profile_photo" />
                        <TextInput source="profile_photo" />
                        <TextInput source="name" />
                        <TextInput source="email" validate={email}/>
                        <TextInput source="phone" />
                        <BooleanInput source="status" label="Active"/>
                        <CardTitle title="* Relationship" titleStyle={{'fontSize':'18px'}}/>
                        <RaisedButton label="New relationship" onClick={this.handleOpen} style={style}/>
                        <GridField uid={id} {...this.props} />
                        <Dialog
                            title="New relationship"
                            actions={actions}
                            modal={false}
                            open={this.state.open}
                            onRequestClose={this.handleClose}
                            autoScrollBodyContent={true}>
                            <div>
                                <br/>
                                <Create {...propsCreate} title=" " actions="">
                                    <SimpleForm  redirect={"/caregiver/" + id}>
                                        {/*<ReferenceArrayInput>*/}
                                        <DisabledInput source="user" defaultValue={id} label="Caregiver ID"/>
                                        <ReferenceInput label="Centre" source="centre" reference="centre" sort={{ field: 'name', order: 'ASC' }} allowEmpty>
                                            <SelectInput optionText="name" />
                                        </ReferenceInput>
                                        <DependentInput dependsOn="centre">
                                            <SubGenreInput source="current_group" optionText="label" optionValue="id" type="classgroup"/>
                                        </DependentInput>
                                        <DependentInput dependsOn="current_group">
                                            <SubGenreInput source="student_id" optionText="fullname" optionValue="id" type="student"/>
                                        </DependentInput>
                                        {/*</ReferenceArrayInput>*/}
                                        <RadioButtonGroupInput source="account_type"  defaultValue={10} choices={[
                                            { id: 10, name: 'Caregiver' },
                                            { id: 20, name: 'Guardian' },
                                        ]} optionText="name" optionValue="id" />
                                        <TextInput source="relationship" label="Relationship"/>
                                    </SimpleForm>
                                </Create>
                            </div>
                        </Dialog>
                    </SimpleForm>
                </Edit>
            </div>
        )
    }

Note: My Create form point to different resource with the Edit form.

  [1]: https://i.stack.imgur.com/UtijI.png
  [2]: https://i.stack.imgur.com/ZEoyx.png
  [3]: https://i.stack.imgur.com/Acqee.png

@djhi's answer on Stackoverflow:

`That's because all forms in aor have the same name: record-form. I think that after a create operation, we send a reset action for the form in order to support the "save and create new" scenario. Please open an issue so that we can discuss this.`

**Comment by congaductq** [comment]
I'm not sure is it a bug or not:
In that Edit Form, I also created a List that point to different resource with Edit Form.

In the first access to caregiver "1", the data of List have not been shown:

https://imgur.com/JVAVccz

After that, I click on refresh button or refresh the whole page, the data in database is shown correctly:

https://imgur.com/EYPPkxP

Then I go to another caregiver (Caregiver "2"), the data of caregiver "1" still be cached, because the list of Caregiver "1" and caregiver "2" is different in database:

https://imgur.com/mckCjR9

Here is my code:

`Edit Page`: 

```
export class CaregiverEdit extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            open: false,
        };
    }

    handleOpen = () => {
        this.setState({open: true});
    };

    handleClose = () => {
        this.setState({open: false});
    };

    render() {
        var id = this.props.location.pathname.split('/')[2]; //Get caregiver ID
        const propsCreate = Object.assign({}, this.props, { authParams : {resource : "rela", route : "create"},
            location : {pathname : "/rela/create"}, match : { path : "/rela/create", url : "/rela/create"}, resource : "rela" });
        return (
            <div>
                <Edit title={<CaregiverTitle />} {...this.props}>
                    <SimpleForm>
                        *****
                        <TextInput source="phone" />
                        <BooleanInput source="status" label="Active"/>
                        <CardTitle title="* Relationship" titleStyle={{'fontSize':'18px'}}/>
                        <RaisedButton label="New relationship" onClick={this.handleOpen} style={style}/>
                        <GridField uid={id} {...this.props} />
                    </SimpleForm>
                </Edit>
            </div>
        )
    }
}
```


``
```
class GridField extends React.Component {
    constructor(props){
        super(props);
    }

    render() {
        console.log("Render Grid");
        const id = this.props.uid; // From caregiver ID, get all the relationship of this caregiver and students;
        const newProps = Object.assign({}, this.props, { authParams : {resource : "rela", route : "list"},
            location : {pathname : "/rela", search: "?filter={\"_keyword\":" + id + "}&order=DESC&page=1&perPage=100&sort=id"}, match : { path : "/rela", url : "/rela"}, resource : "rela", basePath: "rela"  });
        return (
            <div>
                <List title=" " {...newProps}  actions={<RelaAction/>}>
                    <Datagrid>
                        *****
                        <TextField source="id" sortable={false} />
                        <TextField source="relationship" sortable={false}/>
                        *****
                    </Datagrid>
                </List>
            </div>
        )
    }
}
```

**Comment by fzaninotto** [comment]
`<CreateForm>` isn't intended to be used outside of aor routes. I suggest you use another component if you want to use it inside a modal. Same for `<List>` inside another component.

**Comment by congaductq** [comment]
I want to manage n-to-n relationship between caregiver and student.
In Database, I have `Teacher_Student` table that link `Teacher` and `Student`
It's not easy for user to use if I create `Teacher_Student` resource :(
