### ISSUE TITLE
Add installation instructions for the example

### ISSUE THREAD

**Issue by alexdmejias** [marmelab/admin-on-rest#102]
Can we add installation instructions for the included example? I ran `npm install` on the directory but I'm not sure where to go from there.  It also looks like the webpack configuration relies on an old version, but I'm not 100% sure since I suck at webpack :P

**Comment by jpetitcolas** [comment]
Indeed, we should add a line on how to launch demo. Normally, just executing a `make run` should be enough. Can you try and open a PR? :)

**Comment by alexdmejias** [comment]
I would love to send a PR but I'm neither familiar with make or webpack :P
