### ISSUE TITLE
NullableBooleanInput problem in filters

### ISSUE THREAD

**Issue by hamidfzm** [marmelab/admin-on-rest#1021]
NullableBooleanInput filter value only updates when switching from "Yes" state to "No" or "Null" not when switching from "No" to "Null" or "Null" to "No".
I'm using following versions:
- "admin-on-rest": "^1.2.3"
- "react": "^15.6.1"

Here is a sample of my code:
```jsx
import React from "react";
import {
    BooleanField,
    Datagrid,
    Filter,
    List,
    DeleteButton,
    EditButton,
    TextField,
    TextInput,
    DateField,
    NullableBooleanInput,
} from "admin-on-rest";
import {datetimeFormatter}  from "../../helpers/formatter";
import config from "../../helpers/config";

const AdministratorFilter = (props) => (
    <Filter {...props}>
        <TextInput label="Search" source="search" alwaysOn/>
        <NullableBooleanInput label="Active" source="active"/>
    </Filter>
);

export default (props) => (
    <List perPage={config.PER_PAGE} filters={<AdministratorFilter/>} {...props}>
        <Datagrid>
            <TextField source="title" sortable={false} />
            <BooleanField source="active"/>
            <DateField source="created_at" format={datetimeFormatter} showTime locales={config.LOCAL}/>
            <DateField source="updated_at" format={datetimeFormatter} showTime locales={config.LOCAL}/>
            <EditButton/>
            <DeleteButton/>
        </Datagrid>
    </List>
);
```

And here is sample screenshots:

This is when there is no filter applied:
<img width="1440" alt="screen shot 1396-06-21 at 5 22 36 pm" src="https://user-images.githubusercontent.com/5591800/30326831-0ef9363e-97df-11e7-9bcb-9403e8edc425.png">

This is when a filter applied as "Yes" (just take a loot at the Active filter url in browser):
<img width="1440" alt="screen shot 1396-06-21 at 5 22 45 pm" src="https://user-images.githubusercontent.com/5591800/30326868-32ccce0e-97df-11e7-8045-fa407fd9fcde.png">

And this is when we apply "No"
<img width="1440" alt="screen shot 1396-06-21 at 5 22 52 pm" src="https://user-images.githubusercontent.com/5591800/30326930-7692776a-97df-11e7-9bf3-32022f7d6c34.png">

And this is when at last we apply "Null":
<img width="1440" alt="screen shot 1396-06-21 at 5 22 57 pm" src="https://user-images.githubusercontent.com/5591800/30326988-b2091484-97df-11e7-9d94-e50f2bd73d70.png">

As you can see active filter is still remaining as False but if we switch to "Yes" everything is returning to normal.

**Comment by djhi** [comment]
Is it still relevant in `1.3.1` ?

**Comment by hamidfzm** [comment]
@djhi  I update my project to aor  to `1.3.1`. The bug is fixed now. Thanks.
