### ISSUE TITLE
Translatable fields management

### ISSUE THREAD

**Issue by YannickB** [marmelab/admin-on-rest#1023]
Hello all,

I'm wondering if there is a way to manage translatable fields in aor ? I mean a text field which on my webservice can have different value depending of the specified locale. I need this to manage the translated descriptions of some objects in my API.

I know aor had translations but I don't think there is a translatable feature. This would be nice to have for such a tool like aor.

Best regards,

**Comment by fzaninotto** [comment]
Hi,

No, there is no such thing in aor. I suggest you create a standalone field and ping us when you publish it!
