### ISSUE TITLE
Creating own Menu component with <MenuItemLink /> results in "Warning: React.createElement: type is invalid..." error

### ISSUE THREAD

**Issue by quicklikerabbit** [marmelab/admin-on-rest#1024]
Trying to implement a custom menu with the following code: 

    // in src/Menu.js
    import React from 'react'; 
    import { MenuItemLink } from 'admin-on-rest';
   
    export default ({ resources, onMenuTap, logout }) => (
        <div>
            <MenuItemLink to="/spaces" primaryText="Spaces" onTouchTap={onMenuTap} />
            {logout}
        </div>
    );

    // in src/App.js
    import Menu from './Menu';

    const App = () => (
        <Admin menu={Menu} restClient={restClient}>
            // ...
        </Admin>
    );

Results in the following error in the Chrome console: 

`proxyConsole.js:56 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check your code at Menu.js:6.`

`Menu.js:6` is the MenuItemLink component. If I remove that from my Menu.js file, the error goes away, and I get a sidebar with just a logout button. Am I doing something wrong?

**Comment by djhi** [comment]
I can't reproduce this problem. Can you provide a repository reproducing it?

**Comment by djhi** [comment]
You can find a complete working example on the demo app: https://github.com/marmelab/admin-on-rest-demo/blob/master/src/Menu.js

**Comment by quicklikerabbit** [comment]
The issue is that I'm using an older version of admin-on-rest (1.1.0). Looks like MenuItemLink was introduced in 1.2.0.
