### ISSUE TITLE
Pagination broken on <List /> with no filter props

### ISSUE THREAD

**Issue by ArnaudD** [marmelab/admin-on-rest#103]
Hi,

Pagination seems to be broken on `<List>` components with no `filter` prop. When clicking on page "2", the new data is loaded and displayed but we are immediatly redirected to page "1".

It can easily be reproduced on the example projet. The bug only happens when filter are set in the url, so you may need to go to page "2", back to page "1", and page "2" again to reproduce the issue.

It seems that after the `CRUD_GET_LIST_SUCCESS` action, the component receives new props and calls `setFilters` [here](https://github.com/marmelab/admin-on-rest/blob/1c5c6d5c4d6baaa5b783b831a695dad2593a2ed2/src/mui/list/List.js#L38) because it receives a new `filters` prop (which has the same "value" `{}` but is a different object).

I'm not sure how to solve this bug, but if you give me directions I will be happy to submit a PR.

Thanks for your awesome project(s) !

**Comment by mivion** [comment]
Hi,

I have exactly the same problem.

**Comment by ebusi** [comment]
I also confirm this issue, it looks like a regression of the version 0.4 because in the previous it works fine.

**Comment by fzaninotto** [comment]
I can reproduce the bug. I will investigate.
