### ISSUE TITLE
defaultValue in Filters is ignored when alwaysOn

### ISSUE THREAD

**Issue by matteolc** [marmelab/admin-on-rest#1032]
Hi again.. is it only me who's not able to set anymore the defaultValue property in any *Input inside a List Filter ..?
For example the default value "test" does not appear:
`const ListFilters = (props) => (
    <Filter {...props} >
      <TextInput label="test" source="test" alwaysOn defaultValue="test" />                             
    </Filter>
);`
Thanks..

**Comment by djhi** [comment]
Can't reproduce this problem on the example app. Can you set up a repository reproducing it ?

**Comment by djhi** [comment]
Sorry, I reproduced it only when the input also have the `alwaysOn` prop

**Comment by matteolc** [comment]
when are you going to merge into master or should i rollback to a working version in the meantime? 
thanks

**Comment by matteolc** [comment]
:) Ok!

**Comment by matteolc** [comment]
-didn't mean to close

**Comment by tomdeman** [comment]
is it intended behavior for an API request to be made without the default filter values initially, immediately followed by one with the default filter values?

I am seeing 2 requests when List component initially loads.
however, coming back to it after that initial load only triggers 1 request.

**Comment by fzaninotto** [comment]
@tomdeman No, that would be a bug. Can you open a new Issue with a reproducible test case?
