### ISSUE TITLE
AutocompleteInput can not be changed once a value is selected

### ISSUE THREAD

**Issue by warp** [marmelab/admin-on-rest#1046]
There appears to be a regression with AutocompleteInput in the latest 1.3.0 release once a value is selected it cannot be changed or cleared.

**Comment by natrim** [comment]
seconding

ie.
```
<ReferenceInput label="User" source="userId" reference="users">
  <AutocompleteInput optionText="name" translateChoice={false} />
</ReferenceInput>
```

if you try to change the value by typing, it just resets to default (record) value
it reacts on clicking on the item in list though

**Comment by fzaninotto** [comment]
Fixed by #1093

**Comment by bfintal** [comment]
Please release soon 👍

**Comment by afilp** [comment]
I have 1.3.4 and when I change the value then the old value appears again. Has this regressed? Also, I cannot "clear" this filter by typing nothing there
