### ISSUE TITLE
Wrong links in EditButton

### ISSUE THREAD

**Issue by natrim** [marmelab/admin-on-rest#1051]
EditButton (and others) uses linkToRecord to generate link

the linkToRecord  creates links by `${basePath}/${encodeURIComponent(id)}`

but in List.js the basePath is from 'react-router' by
```getBasePath() {
        return this.props.location.pathname;
```    }

which cases problem if the pathname ends with /

ie. have url http://localhost/contacts/
linkToRecord generates url like this: http://localhost/contacts//1223

**Comment by djhi** [comment]
I can't reproduce it on the demo nor the example app. Can you provide a repository reproducing the prb ?

**Comment by natrim** [comment]
you need to use broowster history instead of hash
```
import createHistory from 'history/createBrowserHistory';
const history = createHistory();
<Admin history={history}
```

**Comment by natrim** [comment]
gist: https://gist.github.com/natrim/58327ca7093cedd4f90859658c0d5d0b

just create-react-app, copy files, run app
then go to http://localhost:3000/posts/ and try to click edit button in grid

**Comment by djhi** [comment]
Sill can't reproduce the prb with the code in your gist.

**Comment by natrim** [comment]
that is weird:
here i screenshot it:
![snimek obrazovky 2017-09-21 v 9 37 12](https://user-images.githubusercontent.com/488136/30684268-c9201ac8-9eb0-11e7-9091-b094acf93049.png)

"the href contains double /"

**Comment by djhi** [comment]
I simply copy/pasted the code from your gist so it must be missing something

**Comment by natrim** [comment]
to reproduce try this:

go to PostLists
click edit
remove the number form url, but keep / ( so you have http://localhost:3000/posts/ )
try again clicking edit

or just run app, go to http://localhost:3000/posts/ and try to edit
