### ISSUE TITLE
Failed to compile.  Module not found: Error: Can't resolve 'redux-form'

### ISSUE THREAD

**Issue by Dr8g0n** [marmelab/admin-on-rest#1053]
After upgrading admin-on rest from 1.23 to 1.3.0, I got the error below everytime I run "npm run build"

Creating an optimized production build... Failed to compile.  Module not found: Error: Can't resolve 'redux-form' in '/Codes/access-ui/src'

**Comment by fzaninotto** [comment]
Cant reproduce on the aor example and demo. This is likely a problem with your code. Did you use `redux-form` in your code? In this case, it should be declared in your project dependencies.

To get help about your code using aor, please head to [StackOverflow](https://stackoverflow.com/questions/tagged/admin-on-rest).

**Comment by Dr8g0n** [comment]
I have `import { Field } from 'redux-form';`, as documented at https://marmelab.com/admin-on-rest/Inputs.html#writing-your-own-input-component

**Comment by fzaninotto** [comment]
Yep, in this case, you must install redux-form with

```npm install redux-form -S```
