### ISSUE TITLE
List.props.query cached across resources

### ISSUE THREAD

**Issue by leesei** [marmelab/admin-on-rest#1055]
Here's how the issue is reproduced:

Both ResourceA and ResourceB have reference to Order resource and can be filtered by `.orderId`.
ResourceA and ResourceB have different default sorts:
- ResourceA is sorted by `.created`
- ResourceB is sorted by `.timestamp`

Links to the filtered items are added to Order's show page:

```jsx
<Link
  to={{
    pathname: '/resourceA',
    search: stringify({
      filter: JSON.stringify({ orderId: record.id }),
      page: 1,
    }),
  }}
/>

<Link
  to={{
    pathname: '/resourceB',
    search: stringify({
      filter: JSON.stringify({ orderId: record.id }),
      page: 1,
    }),
  }}
/>
```

Click on the ResourceA's link, back, then click on the ResourceB's link.
AOR will try to fetch ResourceB's data using ResourceA's sort (`created`).

---

I added log to `<Link>`'s `mapStateToProps()`:
```js
function mapStateToProps(state, props) {
    var resourceState = state.admin[props.resource];
    console.log('mapStateToProps()', getQuery(props));
    return {
        query: getQuery(props),
        params: resourceState.list.params,
        ids: resourceState.list.ids,
        total: resourceState.list.total,
        data: resourceState.data,
        isLoading: state.admin.loading > 0,
        filterValues: resourceState.list.params.filter
    };
}
```

I found that the *first log* when I enter ResourceB has ResourceA's value in it:
```js
{
  filter: {orderId: "99389ef2-aada-4753-90b5-2c64286558df"},
  order: "ASC",
  page: "1",
  perPage: 25,
  sort: "created"
}
```

I'm guessing that since the `location.search` is the same (`?filter=%7B%22orderId%22%3A%2299389ef2-aada-4753-90b5-2c64286558df%22%7D&page=1`), selector returned the cached result across different resources.
Should we add `props.resource` to the selector?

**Comment by fzaninotto** [comment]
Where does this `<Link>` come from? It's not an aor component.

Besides, I don't understand how that's possible, the Redux store keeps query params in separate subtrees for each resource.

**Comment by leesei** [comment]
The `<Link>` use case is similar to Products link in https://marmelab.com/admin-on-rest-demo/#/categories.
Source: https://github.com/marmelab/admin-on-rest-demo/blob/master/src/categories/LinkToRelatedProducts.js
But now I've 2 related resources.

I see `<List>` fired a `CRUD_CHANGE_LIST_PARAMS` with the (incorrect) props to change the params in ResourceB.
Maybe it's better for me to reproduce that in the demo app. I'll update this issue.

**Comment by djhi** [comment]
Any news on this one ?

**Comment by leesei** [comment]
I'll try to reproduce next week.

**Comment by leesei** [comment]
Alas, I'm getting https://reactjs.org/warnings/refs-must-have-owner.html on admin-on-rest-demo's master.
Any hint? Should I use a older commit?

**Comment by alexisjanvier** [comment]
Hello @leesei 
Did you found anything new about this problem? 
Did you install the demo and reproduce the problem?

**Comment by fzaninotto** [comment]
No news for some time, closing the issue. Feel free to reopen if you can reproduce it and provide a failing scenario.
