### ISSUE TITLE
v1.3.0 npm package contains files from previous builds

### ISSUE THREAD

**Issue by ArnaudD** [marmelab/admin-on-rest#1057]
For exemple `lib/reducer/references/possibleValues.js` (moved to `lib/reducer/admin/references/possibleValues.js` in v1.3.0)

This may cause people upgrading to aor 1.3.0 to have silent errors if they were importing theses files. (I was :)

To verify :

```
wget https://registry.npmjs.org/admin-on-rest/-/admin-on-rest-1.3.0.tgz
tar -O -zxvf admin-on-rest-1.3.0.tgz package/lib/reducer/references/possibleValues.js
```

**Comment by fzaninotto** [comment]
Fixed by #1058
