### ISSUE TITLE
Unknown prop `initializeForm` on <span> tag

### ISSUE THREAD

**Issue by natrim** [marmelab/admin-on-rest#1067]
just a unknown prop thing but it just bothers me so i am reporting it

happens when using 1.3.0(1) `WithPermission` with custom menu and `MenuItemLink`
(ie. in the example in documentation)

Warning: Unknown prop `initializeForm` on <span> tag. Remove this prop from the element.

**Comment by mjanos10** [comment]
I can validate, this happens to me too.

**Comment by zifnab87** [comment]
I had referred to this issue in #1025 too

**Comment by bfintal** [comment]
Same here
