### ISSUE TITLE
Why not using Grid for layouts?

### ISSUE THREAD

**Issue by Amurmurmur** [marmelab/admin-on-rest#1075]
I was wondering why not using Grid component provided with the material UI for a responsive layout ?
Why doing `display: flex` for instance here: https://github.com/marmelab/admin-on-rest/blob/master/src/mui/layout/Layout.js#L20

If all this can be done with `Grid` component
https://material-ui-1dab0.firebaseapp.com/layout/grid/

**Comment by djhi** [comment]
Because we don't use MUI 1.0 (which is still in beta) yet

**Comment by lighth7015** [comment]
`material-ui/GridList` is available in the current MUI.

**Comment by fzaninotto** [comment]
See the `next` branch: we're using the styles advised by mui 1.0 to support [permanent drawers](https://material-ui-next.com/demos/drawers/)

**Comment by lighth7015** [comment]
Does this also mean that the header and the sidebar stay fixed in the `next` branch?
