### ISSUE TITLE
Update menu section in docs 

### ISSUE THREAD

**Issue by clay-morgan** [marmelab/admin-on-rest#1076]
https://marmelab.com/admin-on-rest/Admin.html#menu

Providing `onMenuTap` as prop to `MenuItemLink` causes the following: 

- Menu does not close on tap for mobile view 

- error message: Unknown prop `onMenuTap` on span tag

- error message: The prop `onClick` is marked as required in `MenuItemLinkComponent`, but its value is `undefined`

Providing `onMenuTap` function to `onClick` prop on `MenuItemLink` removes error messages and expected behaviour occurs

**Comment by fzaninotto** [comment]
True, with the switch to [material-ui 0.19](https://github.com/callemall/material-ui/releases/tag/v0.19.0), we need to replace calls to `onTouchTap` by `onClick` everywhere - including in the documentation.
