### ISSUE TITLE
[Feature] ES6 module with rollup

### ISSUE THREAD

**Issue by kopax** [marmelab/admin-on-rest#1077]
## Issue Type

- [x] Feature

## Description

I am trying to implement ES6 module. This has many advantage and the library can detect the source of the imports normally in IDE like IntelliJ. It will also provide tree shaking and advanced integration.

![image](https://user-images.githubusercontent.com/1866564/30774454-e8c45742-a0ac-11e7-8a2b-09ddf862a022.png)

I have tried to configure the rollup using my own module bundler but couldn't make it work I don't know why so If somebody want to help:

https://github.com/kopax/admin-on-rest

I also tried to downgrade from `stage-0` to `stage-2` as most of `stage-0` is too experimental and most of the features used are from `stage-2`.

## Steps to reproduce

Run the following:

```
git clone git@github.com:kopax/admin-on-rest.git
cd admin-on-rest
npm install
npm run build:dist
```

Current error : 

	dka@dev-01:[~/workspace/github.com/kopax/admin-on-rest]: npm run build:dist

	> admin-on-rest@1.3.1 build:dist /home/dka/workspace/github.com/kopax/admin-on-rest
	> rollup -c && rollup -c --environment PRODUCTION

	Creating development bundle...

	src/index.js → dist/admin-on-rest.js, dist/admin-on-rest.es.js...
	[!] (babel plugin) SyntaxError: /home/dka/workspace/github.com/kopax/admin-on-rest/src/index.js: Unexpected token, expected { (5:7)
	src/index.js (5:7)
	SyntaxError: /home/dka/workspace/github.com/kopax/admin-on-rest/src/index.js: Unexpected token, expected { (5:7)
	    at error (/home/dka/workspace/github.com/kopax/admin-on-rest/node_modules/rollup/dist/rollup.js:185:14)
	    at Object.error (/home/dka/workspace/github.com/kopax/admin-on-rest/node_modules/rollup/dist/rollup.js:9407:6)
	    at promise.then.previous (/home/dka/workspace/github.com/kopax/admin-on-rest/node_modules/rollup/dist/rollup.js:9416:32)
	    at <anonymous>
	    at process._tickCallback (internal/process/next_tick.js:188:7)
	    at Function.Module.runMain (module.js:611:11)
	    at startup (bootstrap_node.js:158:16)
	    at bootstrap_node.js:598:3

	npm ERR! code ELIFECYCLE
	npm ERR! errno 1
	npm ERR! admin-on-rest@1.3.1 build:dist: `rollup -c && rollup -c --environment PRODUCTION`
	npm ERR! Exit status 1
	npm ERR! 
	npm ERR! Failed at the admin-on-rest@1.3.1 build:dist script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

	npm ERR! A complete log of this run can be found in:
	npm ERR!     /home/dka/.npm/_logs/2017-09-23T15_12_03_012Z-debug.log
	dka@dev-01:[~/workspace/github.com/kopax/admin-on-rest]: 

# Versions

- AOR: 1.3.1
- Node/NPM: 8.5.0/5.4.2

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by kopax** [comment]
@fzaninotto, to be fair, it's not a exactly an "How To" question. This is addressed directly to the Github author.

**Comment by fzaninotto** [comment]
I don't understand your comment. You're asking about how to configure Rollup, which we don't use ourselves. We use webpack and it works, so there is no bug in admin-on-rest. Or am I missing something?

**Comment by kopax** [comment]
@fzaninotto I don't think you use webpack. You only use Babel. 
You use babel and it work. However you don't produce ES6 modules. 
Here are some resource you can read about the topic:
- https://medium.com/@Rich_Harris/small-modules-it-s-not-quite-that-simple-3ca532d65de4
There's a lot of advantage to offer your module as CommonJS and  ES6 Modules.
Rollup can help you importing existing CommonJS modules through a plugin and convert them back to ES6.

**Comment by fzaninotto** [comment]
Oh we do use webpack, cf [example/webpack.config.js](https://github.com/marmelab/admin-on-rest/blob/master/example/webpack.config.js).

Admin-on-rest doesn't care about the module bundler you use. It's your responsibility to configure it.
