### ISSUE TITLE
[RFC] CustomApp example does produce an error

### ISSUE THREAD

**Issue by kopax** [marmelab/admin-on-rest#1078]
## Issue Type

- [x] Bug

## Description

I was trying to achieve the **Custom App** example using the [react-boilerplate](https://github.com/react-boilerplate/react-boilerplate/tree/dev/app) the 3.5 version from dev branch. 

They use `immutablejs` for creating immutable store and I wonder if it's not related.

Injecting the reducer using `adminReducer` :
![image](https://user-images.githubusercontent.com/1866564/30776103-c4649416-a0ca-11e7-97cf-9517b83766ef.png)

produce an unexpected error:

    warning.js:12 The previous state received by the reducer has unexpected type of "Array". Expected argument to be an object with the following keys: "resources", "loading", "notification", "record", "references", "saving", "ui"

![image](https://user-images.githubusercontent.com/1866564/30776107-d3f0fa82-a0ca-11e7-9758-8ee31e1e84cb.png)

## Steps to reproduce

Follow the [documentation](https://marmelab.com/admin-on-rest/CustomApp.html) instruction

![image](https://user-images.githubusercontent.com/1866564/30776202-81589968-a0cc-11e7-857a-e9e2b47a423a.png)

and apply these change in [app/reducers.js](https://github.com/react-boilerplate/react-boilerplate/blob/dev/app/reducers.js#L47) : 

```jsx harmony
export default function createReducer(injectedReducers) {
  return combineReducers({
    route: routeReducer,
    language: languageProviderReducer,
    // this bellow create the bug \\
    admin: adminReducer([{
      name: 'users'
    }, {
      name: 'roles'
    }, {
      name: 'oAuthClients'
    }]),
    locale: localeReducer(),
    form: formReducer,
    ...injectedReducers,
  });
}

```

# Versions

- AOR: 1.3.1
- Node/NPM: 8.5.0/5.4.2

**Comment by kopax** [comment]
I solved the issue with : 

```jsx harmony
export default function createReducer(injectedReducers) {
  return combineReducers({
    route: routeReducer,
    language: languageProviderReducer,
    admin: adminReducer,
    locale: localeReducer(),
    form: formReducer,
    ...injectedReducers,
  });
}
```

**Comment by kopax** [comment]
Just submitted a PR for this. By the way, I think you didn't an awesome job with this AOR, good job :+1:

**Comment by kopax** [comment]
It look like the documentation hasn't been updated for a while: 

**Before**
https://github.com/marmelab/admin-on-rest/blob/3caaa89e8465d14b57498e8b505fa44ced9a0eba/src/reducer/admin/index.js
**After**
https://github.com/marmelab/admin-on-rest/blob/master/src/reducer/admin/index.js

**Comment by fzaninotto** [comment]
Fixed by #1079

**Comment by kopax** [comment]
![image](https://user-images.githubusercontent.com/1866564/31053295-b482487c-a6c4-11e7-9932-e227fab6fb0e.png)

I think this needs to be reopened because this didn't really help. How do we declare the entities in the store ?

**Comment by fzaninotto** [comment]
refixed in #1115
