### ISSUE TITLE
translate doesn't work

### ISSUE THREAD

**Issue by kopax** [marmelab/admin-on-rest#1099]
I am using admin on rest 1.3.1 and I am reading at this documentation : 

https://marmelab.com/admin-on-rest/Translation.html#translation-messages

It says that you can import a **translate** method like so:

```jsx harmony
// in src/MyHelloButton.js
import React, { Component } from 'react';
import PropTypes from 'prop-types';

class MyHelloButton {
    render() {
        const { translate } = this.context;
        return <button>{translate('myroot.hello.world')}</button>;
    }
}
MyHelloButton.contextTypes = {
    translate: PropTypes.func,
};
```
I have a `<IntlProvider />` wrapping my react app and messages are fully loaded but:

- Using `translate` throw error : 

> Warning: Failed context type: The context `translate` is marked as required in `getContext(MyHelloButton)`, but its value is `undefined`.
    in getContext(MyHelloButton) (created by HomePage)

I have read at the **react-intl** documentation here https://github.com/yahoo/react-intl/wiki/API#injectintl and they provide a HoC `injectIntl` that can be used to retrieve messages. 

This is how I fixed `translate.js` with `injectIntl`:

```jsx harmony
import React from 'react';
import { compose } from 'redux';
import { connect } from 'react-redux';
import { injectIntl } from 'react-intl';

export default (Component) => {
  function TranslateComponent(props) {
    const { intl, ...rest } = props;
    return (
      <Component {...rest} translate={(id) => intl.formatMessage({ id })} />
    );
  }

  return compose(
    connect(),
    injectIntl,
  )(TranslateComponent)
}
```

I am using `react-intl` 2.4.0.

- Why did AOR added such method ?
- Which one I should use ?
- It's a shame to only use translate if we can't access [formatDate](https://github.com/yahoo/react-intl/wiki/API#formatdate) and other helpers so I think `injectIntl` should be use.

Also if anybody know why I have this error, thanks:!

**Comment by djhi** [comment]
Also explained in the [documentation](https://marmelab.com/admin-on-rest/Translation.html#translating-your-own-components). I'll have to check the first method explained though, it looks wrong. Thanks for reporting it

```js
// in src/MyHelloButton.js
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import { translate } from 'admin-on-rest';

class MyHelloButton {
    render() {
        const { translate } = this.props;
        return <button>{translate('myroot.hello.world')}</button>;
    }
}

MyHelloButton.propTypes = {
    translate: PropTypes.func.isRequired,
};

export default translate(MyHelloButton);
```

**Comment by kopax** [comment]
@djhi I am not using `<Admin />` and this clash with `injectIntl`, why don't you use the latest ?
Is AOR not dependant of `react-intl` ? Yes it look wrong, translate is used once with a React.element and once with a String.

**Comment by djhi** [comment]
We don't use `react-intl`

**Comment by djhi** [comment]
Also please, don't double post here and on SO. It double the work for us

**Comment by kopax** [comment]
Ok, just one more important think.

I am not using `<Admin />`, it is the one responsible for creating this context and Admin is supposed to be optional. 

What is gonna happen to the call made by AOR source of translate if Admin is absent ?

**Comment by djhi** [comment]
As they use the `translate` HOC, you'll have to ensure it will find the props it expects in the context: https://github.com/marmelab/admin-on-rest/blob/master/src/i18n/translate.js#L6.

It will then be your responsibility to do the translation

**Comment by kopax** [comment]
Ok that's what I thought. Is it a volontary behavior ?
Correct me if I am wrong, but the `<Admin />` is optional. But not for internationalization ? Also why not use the same location for the context as in react-intl ?
So the solution is to create an extra context for AOR ? Or do you recommend another thing in my case ?
Otherwise, is it ok if I submit a PR changing the bahovior ?

**Comment by djhi** [comment]
> Ok that's what I thought. Is it a volontary behavior ?

Yes

> Correct me if I am wrong, but the <Admin /> is optional. But not for internationalization ? Also why not use the same location for the context as in react-intl ?

`Admin` is optional, but we have documented how to include AOR in a custom app and the example includes the `TranslationProvider` because it **is required**: https://marmelab.com/admin-on-rest/CustomApp.html

> So the solution is to create an extra context for AOR ? Or do you recommend another thing in my case ?

Depends. If you really want to use `react-intl` instead of `polyglot`, you'll have to supply the expected translation context one way or another. Otherwise, see the previous point.

> Otherwise, is it ok if I improve the compatibility with react-intl in a PR ?

Can you elaborate ?

**Comment by kopax** [comment]
@djhi thanks for the CustomApp link, I've read it and implemented and I didn't noticed that it was required.

I am reluctant to have two context to handle the same thing. The idea would be to mock the context in `translate.js` so the one from `react-intl` fits the context of `TranslationProvider`  [see](https://github.com/marmelab/admin-on-rest/blob/master/src/i18n/translate.js#L6)

The thing is, it isn't clear right now. In your example you call the same method with two differents arguments, how is it supposed to be called at the first place ?

**Comment by djhi** [comment]
I see why you are confused: there are two different `translate` functions here.

The example could be rewritten like this:

```jsx
import React from 'react';
import { translate as giveTranslationPowers } from 'admin-on-rest';

const MyHelloButton = ({ translate }) => (
    <button>{translate('myroot.hello.world')}</button>
);

export default giveTranslationPowers(MyHelloButton);
```

**Comment by kopax** [comment]
How about this implementation:

```jsx
import React from 'react';
import PropTypes from 'prop-types';
import { getContext } from 'recompose';

const translate = (BaseComponent) => {
  const TranslateComponent = getContext({
    translate: PropTypes.func,
    locale: PropTypes.string,
    intl: PropTypes.object,
  })((props) => {
    const { translate: translatePolyglot, locale: localePolyglot, intl, ...rest } = props;
    const translate = !intl ? translatePolyglot : (id) => props.intl.formatMessage({ id });
    const locale = !intl ? localePolyglot : props.intl.locale;
    return (
      <BaseComponent translate={translate} locale={locale} {...rest} />
    );
  });
  TranslateComponent.defaultProps = BaseComponent.defaultProps;

  return TranslateComponent;
};

export default translate;
```

**Comment by djhi** [comment]
> I am reluctant to have two context to handle the same thing.

You don't have to. Just swap the default `TranslationProvider` with a custom one injecting the same props inside the context but using `react-intl`.

**Comment by djhi** [comment]
> How about this implementation

No, we are not going to try to be compatible with every possible way to do i18n. It should be easy to swap the `TranslationProvider` with a custom one as explained in previous comment

**Comment by kopax** [comment]
> You don't have to. Just swap the default TranslationProvider with a custom one injecting the same props inside the context but using react-intl.

I honestly thing it should be the over way arround, let me explain: the widely used `IntlProvider` does exactly the same job as the `TranslationProvider`. Also `context` should not be used too much so swapping `TranslationProvider` and `IntlProvider` to create multiple context to be able to use AOR translation and `react-intl` is not really an option.  I've managed to inject the AOR messages in our `IntlProvider` but the only peace of code that will break is when you call internally `translate`.

So let sum up my choices:

- Add a TranslationProvider that work with AOR and give up `react-intl`

**Comment by djhi** [comment]
> swapping TranslationProvider and IntlProvider to create multiple context to be able to use AOR translation and react-intl is not really an option

Why multiple context ? You will **replace**  the context completely, so you won't have multiple contexts.

**Comment by kopax** [comment]
TBH, my solution handle more case, more compatible, less integration. It's just a better idea. If you are afraid of multiple compatibility to handle, I can add test and implement it in a way it can be removed and restored easely.
I am blocking on this implementation, it is always frustrating when you have to do the wrong choice.

**Comment by djhi** [comment]
A custom translation provider that can use react-intl would look something like this:

```jsx
import { Children } from 'react';
import PropTypes from 'prop-types';
import { connect } from 'react-redux';
import { compose, getContext, withContext } from 'recompose';

const withReactIntlContext = getContext({
    locale: PropTypes.string.isRequired,
    formatMessage: PropTypes.func.isRequired,
});

const withI18nContext = withContext(
    {
        translate: PropTypes.func.isRequired,
        locale: PropTypes.string.isRequired,
    },
    ({ locale, formatMessage }) => {
        return {
            locale,
            translate: formatMessage,
        };
    },
);

const TranslationProvider = ({ children }) => Children.only(children);

TranslationProvider.propTypes = {
    children: PropTypes.element,
};

const mapStateToProps = state => ({ locale: state.locale });

export default compose(
    connect(mapStateToProps),
    withReactIntlContext,
    withI18nContext,
)(TranslationProvider);
```

Wouldn't this work ?

**Comment by kopax** [comment]
I guess so. Correct me if I am wrong but this will duplicated the context ?

**Comment by djhi** [comment]
You can probably remove the `locale` prop as it will be injected by the `IntlProvider`. `translate` will indeed be a *duplicate* (by reference) of `formatMessage`

**Comment by kopax** [comment]
`formatMessage` parameter is an object with `id` and `defaultProps` while aor `translate` expect a string. I've updated my example to reflect the change and I will have a try. 
I am still not sure if it's the choice of performance. Would you mind reopening it see what people says ?

**Comment by djhi** [comment]
ping @fzaninotto

**Comment by fzaninotto** [comment]
I agree with @djhi, we can't support every translation frameworks. I don't want to create an abstraction layer for that, and I don't think that there is a standard that we can rely upon.

I'd say that the use of polyglot is not optional. But as @djhi explained, nothing prevents you from creating a custom `< TranslationProvider>` that uses react-intl in the background, so I think there is no issue here.

**Comment by kopax** [comment]
I've been using `react-intl` for almost 2 years and it's context never change.

> I'd say that the use of polyglot is not optional.

Can you develop that part ?

**Comment by fzaninotto** [comment]
"I'd say that the use of polyglot is not optional" means "If you don't want to use polyglot, then do it on your own, it's not supported by the core team."

But thanks to the component-based architecture, you technically can, by writing a custom provider. So I really don't see the problem.

**Comment by kopax** [comment]
We have decided to use both, IntlProvider and TranslationProvider. Sorry for making a debate and thanks a lot for the open source project.

**Comment by kopax** [comment]
@fzaninotto , I've just wrote the following adapter for v2 and that's the proof `react-admin` can support both `polyglot` to support `react-intl` without any additional maintenance cost.

I use it over the original `TranslationProvider`, this way I don't need to change anything else in the `ra-core`.

```js
/*
 *
 * LanguageProvider
 *
 * this component connects the redux state language locale to the
 * IntlProvider component and i18n messages (loaded from `app/translations`)
 */

import React, { PureComponent, Children, cloneElement } from 'react';
import PropTypes from 'prop-types';
import { connect } from 'react-redux';
import { injectIntl } from 'react-intl';
import { compose, withContext } from 'recompose';
import { createStructuredSelector } from 'reselect';
import { IntlProvider } from 'react-intl';
import defaultMessages from 'ra-language-english';

import { selectLocale, selectMessages } from './selectors';

/* eslint-disable no-restricted-syntax, no-continue */
export const fromPolyglot = (obj) => {
  const toReturn = {};
  for (const i in obj) {
    if (!Object.prototype.hasOwnProperty.call(obj, i)) continue;
    if (typeof obj[i] === 'object') {
      const flatObject = fromPolyglot(obj[i]);
      for (const x in flatObject) {
        if (!Object.prototype.hasOwnProperty.call(flatObject, x)) continue;
        toReturn[`${i}.${x}`] = flatObject[x];
      }
    } else {
      toReturn[i] = obj[i];
    }
  }
  return toReturn;
};

class TranslationProvider extends PureComponent {
  render() {
    return cloneElement(Children.only(this.props.children), { intl: this.props.intl });
  }
}

const withI18nContext = withContext(
  {
    translate: PropTypes.func.isRequired,
  },
  (props) => {
    return {
      translate: (id, opts) => console.log(opts) || props.intl.formatMessage({ id }, opts),
    };
  }
);

const ConnectedTranslationProvider = compose(injectIntl, withI18nContext)(
    TranslationProvider
);

// eslint-disable-next-line react/prefer-stateless-function
export class LanguageProvider extends PureComponent {
  render() {
    return (
      <IntlProvider locale={this.props.locale} key={this.props.locale} messages={fromPolyglot(this.props.messages) || fromPolyglot(defaultMessages)}>
        <ConnectedTranslationProvider>
          {this.props.children}
        </ConnectedTranslationProvider>
      </IntlProvider>
    );
  }
}

LanguageProvider.defaultProps = {
  locale: 'en',
};

LanguageProvider.propTypes = {
  locale: PropTypes.string,
  messages: PropTypes.object,
  children: PropTypes.element.isRequired,
};

const mapStateToProps = createStructuredSelector({
  locale: selectLocale,
  messages: selectMessages,
});

const withI18nContext2 = withContext(
  {
    locale: PropTypes.string.isRequired,
    messages: PropTypes.object,
  },
  (props) => {
    return {
      locale: props.locale,
      messages: props.messages,
    };
  }
);

export default compose(connect(mapStateToProps), withI18nContext2)(
    LanguageProvider
);
```
I know we have been on that topic before but we are already polyglot and we will proceed to `i18n` translation.

If you want to have both compatibility just say it and I can spend time trying to merge that for the community. Otherwise we are happy with this on our fork.

**Comment by fzaninotto** [comment]
Nice work. But we are not interesting in supporting it in the core.

**Comment by kopax** [comment]
@fzaninotto Just for your information, I have made a version that use next changes and polyglot was removed for react-intl here : 

https://github.com/yeutech/react-admin

I didn't had to change anything except 1 or 2 files.

I've also made a script that converts polyglot files to i18n files.

Work fine all unit and e2e test pass (https://travis-ci.org/yeutech/react-admin)

There is [optionaldependencies](http://npm.github.io/using-pkgs-docs/package-json/types/optionaldependencies.html) which are a powerful feature for such implementation.

> This is a map of package name to version or URL, just like the dependencies object. The difference is that build failure do not cause the installation to fail.

I can try to make something clean and documented. That way you can clearly announce react-admin support both polyglot and react-intl for internationalization. That could be automated.

It's a bit pushy but if you think twice, you will have double users and you only have to consider once by reviewing the pull request. I can be at your disposal afterward and take care of maintenance. We are already supporting that feature. 

Because i18n as a much larger community.
