### ISSUE TITLE
Authorization based on rules

### ISSUE THREAD

**Issue by johanestsusanto** [marmelab/admin-on-rest#1100]
Hi, good day.

I'm looking for a framework for backend apps, after reading the documentations, I found out that this framework is enable to do some permission/authorization by hardcode. Is there any samples to do the authorization based on the data from API (able to custom the authorization from backend) ?

**Comment by djhi** [comment]
Can you elaborate on *by hardcode* ?

The `authClient` **must** return a promise, so you can do whatever you like when implementing yours, including calling an API.

- [authClient](https://marmelab.com/admin-on-rest/Authentication.html#configuring-the-auth-client)
- [Authorization](https://marmelab.com/admin-on-rest/Authorization.html)

**Comment by fzaninotto** [comment]
We also have a simple implementation based on local storage in the `example`:

https://github.com/marmelab/admin-on-rest/blob/master/example/authClient.js
