### ISSUE TITLE
CustomApp not working anymore?

### ISSUE THREAD

**Issue by carlson** [marmelab/admin-on-rest#111]
I followed the [CustomApp](https://github.com/marmelab/admin-on-rest/blob/master/docs/CustomApp.md) instructions with version 0.3.1 and everything worked fine. 
After updating to  0.4.0 (same code) the Edit form doesn't display data or changes to input fields.

![screen shot 2016-10-27 at 6 36 38 pm](https://cloud.githubusercontent.com/assets/60451/19788132/b2f86f1e-9c74-11e6-993b-21bec3b5f837.png)

Switch back to the previous version and everything works fine:

![screen shot 2016-10-27 at 6 35 59 pm](https://cloud.githubusercontent.com/assets/60451/19788154/cb00bf6c-9c74-11e6-9113-edc399c655d0.png)

Note: did a test with the [Tutorial](https://github.com/marmelab/admin-on-rest/blob/master/docs/Tutorial.md) (non-custom app) and everything works as expected. Did I miss a requirement moving from 0.3.1 to 0.4.0?

**Comment by ArnaudD** [comment]
Hi @carlson, You now need to include redux-form in your reducers like this :

```javascript
import { routerReducer } from 'react-router-redux';
import { adminReducer } from 'admin-on-rest';
import { reducer as formReducer } from 'redux-form';

export default combineReducers({
  routing: routerReducer,
  form: formReducer,
  admin: adminReducer([{ name: 'resource1' }, { name:  'resource2' }]),
});
```

**Comment by carlson** [comment]
Thanks for your help @ArnaudD, that fixed it. Great project.

**Comment by fzaninotto** [comment]
Reopening, since the doc must be updated.
