### ISSUE TITLE
Special characters in resource IDs not encoded on Safari with jsonServerRestClient

### ISSUE THREAD

**Issue by dimitrovs** [marmelab/admin-on-rest#1114]
On Safari on Mac when using the jsonServerRestClient (haven't tried other clients) if the resource id has special characters they will not be encoded prior to sending the HTTP request. On backends such as AWS Cloudfront this leads to error 400 for all GET & PUT requests.
Works fine in Chrome.

As a workaround for the resource that has special characters in the id I am manually using the fetch API and calling encodeURIComponent on the id. It works.

**Comment by alexisjanvier** [comment]
Your workaround is a working way to solve that problem. 
But a more *aor idiomatic* way would be to `decorate` your `rest client` as described in this part of the documentation : [Decorating your REST Client (Example of File Upload)](https://marmelab.com/admin-on-rest/RestClients.html#decorating-your-rest-client-example-of-file-upload).
