### ISSUE TITLE
render is called multiple times in List and in Edit mode

### ISSUE THREAD

**Issue by zifnab87** [marmelab/admin-on-rest#1116]
according to this commit in my repo:
https://github.com/zifnab87/admin-on-rest-demo/commit/ad104b034cdff1967164a5bc0574c57cd2559d23

I can see in the log the rendering happening multiple times - something seems not be right..
for list:

![image](https://user-images.githubusercontent.com/526062/31055936-3c2492b8-a6d3-11e7-9d3d-a33013eb2d93.png)

for edit:

![image](https://user-images.githubusercontent.com/526062/31055940-51cae838-a6d3-11e7-9f06-8723bd5e9734.png)

I imagine similar behavior for create

I realized this was an issue when debugging my component-factory described here: #1109 - it was called multiple times! If this is the case it should improve performance too when fixed

**Comment by fzaninotto** [comment]
It's normal: the list is first rendered empty, then rerendered with the loading state, then rerendered again once the data arrives. 

The subcomponents (datagrid, fields, inputs etc) are optimized to skip rerendering if their props haven't changed. For more information, see the blog post I wrote on admin-on-rest optimization: https://marmelab.com/blog/2017/02/06/react-is-slow-react-is-fast.html

**Comment by zifnab87** [comment]
What if there is data coming asynchronously in chip fields will it rerender
for those as well? I am asking this because I saw in Edit 23 rerenders
because had more than 16 attached images through ImageInput

**Comment by fzaninotto** [comment]
Maybe there is a performance problem for one particular component. In that case, I invite you to open an issue for that component.

That being said, there is no Chip field in ImageInput...

**Comment by zifnab87** [comment]
obviously I am not using Chipfield in ImageInput.. I am curious if any
request to async data either resulting in Chipfields or ImageFields
rerenderes the whole List/edit components.. that would be unforutnate

2017-10-03 19:09 GMT+03:00 Francois Zaninotto <notifications@github.com>:
