### ISSUE TITLE
[RFC] Navbar bug on mobile media query when using Custom App

### ISSUE THREAD

**Issue by kopax** [marmelab/admin-on-rest#1118]
We have detected a bug on the UX when we reduce our size to mobile media:

![image](https://user-images.githubusercontent.com/1866564/31089128-29c450e0-a7cd-11e7-8a60-a234a9bb492e.png)

We have implemented AOR without `<Admin />` in an existing app.

It can disappear with a css rules, but shouldn't be in the dom.

version: 1.3.1

**Comment by djhi** [comment]
I suppose you don't use the default Layout either, right ?
In this case, see https://github.com/marmelab/admin-on-rest/blob/master/src/mui/layout/Layout.js#L46

**Comment by kopax** [comment]
Yes we don't use the default Layer. 
I have tried to add to my `MuiThemeProvider` and play with the L46 value and I didn't see any change on the UI.

```jsx
<MuiThemeProvider muiTheme={getMuiTheme({
  wrapper: {
    // Avoid IE bug with Flexbox, see #467
    display: 'flex',
    flexDirection: 'column',
  },
  main: {
    display: 'flex',
    flexDirection: 'column',
    minHeight: '100vh',
  },
  body: {
    backgroundColor: '#edecec',
    display: 'flex',
    flex: 1,
    overflowY: 'hidden',
    overflowX: 'scroll',
  },
  bodySmall: {
    backgroundColor: '#fff',
  },
  content: {
    flex: 1,
    padding: '2em',
  },
  contentSmall: {
    flex: 1,
    paddingTop: '3em',
  },
  loader: {
    position: 'absolute',
    top: 0,
    right: 0,
    margin: 16,
    zIndex: 1200,
  },
})}>
  <App />
</MuiThemeProvider>
```

Was that the fix you were referencing ? otherwise, what about L46?
