### ISSUE TITLE
[RFC] Filters get rerendered and change value on typing

### ISSUE THREAD

**Issue by kopax** [marmelab/admin-on-rest#1120]
# issue type

- [x] bug

# description

We have implemented the CustomApp example so we are not using `<Admin />`.

When we try to type in any filter fields, the input text is replaced constantly making the typing inconvenient.

![out](https://user-images.githubusercontent.com/1866564/31112190-7c51547e-a83c-11e7-9e0e-5468723f7cce.gif)

I think this is due to the filter setting the URL that trigger the `@@router/LOCATION_CHANGE`.

Version 1.3.1

Thanks again for the awesome lib.

**Comment by fzaninotto** [comment]
The reducer part seems to be outdated in the CustomApp tutorial. Can you try the following:

```js
// replace
const reducer = combineReducers({
    admin: adminReducer,
    locale: localeReducer(),
    form: formReducer,
    routing: routerReducer,
});

// with
import { createAppReducer } from 'admin-on-rest';
const reducer = createAppReducer({});
```

?

**Comment by kopax** [comment]
I have replaced

```jsx
import { combineReducers } from 'redux';
import { routerReducer } from 'react-router-redux';
import { reducer as formReducer } from 'redux-form';
import { adminReducer, localeReducer } from 'admin-on-rest';
export default function createReducer(injectedReducers) {
  return combineReducers({
    route: routerReducer,
    admin: adminReducer,
    locale: localeReducer(),
    form: formReducer,
    ...injectedReducers,
  });
}
```

with

```jsx
import { routerReducer } from 'react-router-redux';
import { createAppReducer } from 'admin-on-rest';

export default function createReducer(injectedReducers) {
  return createAppReducer({
    route: routerReducer,
    ...injectedReducers,
  });
}
```

But this didn't solve anything.

**Comment by fzaninotto** [comment]
I really don't know where it comes from. This works fine with the standard `<Admin>` app. I suggest you look at the code of `<Admin>` and `<Resource>` to see the differences with your implementation.

**Comment by fzaninotto** [comment]
wait, `createAppReducer` already includes the router reducer. You're adding it twice...

**Comment by kopax** [comment]
The `createAppReducer` indeed contain the `routing` store. But now it's exactly the same as before except I am using `routing` for `route`. 
Our only way around was to use the `<Admin />` and stick to `mui` for the frontend. :(
I have no clue either why it is going crazy like this, do you want me to create a GitHub reproduction ?

**Comment by fzaninotto** [comment]
Any news about this one?

**Comment by kopax** [comment]
@fzaninotto unfortunately no, I wish this would have worked better. Are you hitting the same issue?

Instead of installing `adminonrest` in our application, we had to use our application into `adminonrest`, it's pretty much the same except we needed to customize some components like `Admin`, `AdminRoutes`, `Layout` in order to hook our application boot logic.

**Comment by fzaninotto** [comment]
No, sorry, I can't reproduce the issue on the demo. Please provide a codesandbox demonstrating the problem.

**Comment by kopax** [comment]
I'll gladly try again when 2.0 is out. I rather not use `<Admin />` at all. Do you know when it'll be out?

**Comment by fzaninotto** [comment]
2.0.0-beta2 is out, and it's quite close to the final result.

**Comment by kopax** [comment]
@fzaninotto I've been trying to implement a custom app again using the manual in `2.0.0-beta4` but the documentation is outdated.
Is it possible for you to update the code sample with v2 change so I can try to reproduce this in v2?

**Comment by fzaninotto** [comment]
The documentation in `next` was updated, can you describe the problem you have with the snippet included in the new `CustomApp.md` file?

**Comment by kopax** [comment]
@fzaninotto Thanks for updating. I'll start having a look now and I will let you know.

**Comment by fzaninotto** [comment]
This is a bit too much code to be sure of the problem origin. Could you release a minimal app with only one resource and nothing else customized to let us isolate the problem more easily?

**Comment by kopax** [comment]
This is already a minimal app. If you want it more miminal, you should comment one or two resources up to your choice.

**Comment by kopax** [comment]
@fzaninotto I have updated the demo repo to make it more minimalistic (by deleting `./src/User` and `./src/Comment`).

This is the issue : 

![image](https://user-images.githubusercontent.com/1866564/38507598-29f3a1f6-3c47-11e8-978c-d34e29cd31f1.png)
