### ISSUE TITLE
Demo app fails on edit orders 

### ISSUE THREAD

**Issue by activist** [marmelab/admin-on-rest#1122]
When trying to edit orders on the demo app it fails with "Cannot read property 'data' of undefined".

![aor-edit-orders](https://user-images.githubusercontent.com/88418/31126234-58681b92-a84b-11e7-8a56-11511fd79ea6.PNG)

Not sure if this is where I should report error for the demo app. If not, please let me know where to send the issue.

**Comment by djhi** [comment]
Yes, please report it on the demo repository: https://github.com/marmelab/admin-on-rest-demo
