### ISSUE TITLE
Handle CTRL-Click events on menu items

### ISSUE THREAD

**Issue by Kmaschta** [marmelab/admin-on-rest#1123]
**Related version:** 1.3.1

## Steps to reproduce

1. Go on the demo https://marmelab.com/admin-on-rest-demo/
2. CTRL + Click on a menu item

**Expected behavior:** The requested page should be open in a new tab
**Actual behavior:** The page is opened on the same page

It is especially as frustrating as the expected behavior works on most of the other buttons.

**Comment by Phocea** [comment]
Few questions about this one :)

- Does the solution still need to use the `<MenuItem>`? According to our designer ([and material ui docs](http://www.material-ui.com/#/components/menu#menuitem-properties)), `<ListItem>` should be used for navigation menu, `<MenuItem`> for popup, temporary menu.
- Does the solution need to still use onTouchTap ?

**Comment by fzaninotto** [comment]
Ideally yes, we should use material-ui components as much as possible.

We don't use `onTouchTap` anymore since the 1.3.0 - `onClick` works fine.

Possibly related to https://github.com/callemall/material-ui/issues/2720

**Comment by Phocea** [comment]
Ctrl+Click work if you follow [this implementation](https://github.com/DaxChen/material-ui-Link-within-MenuItem), but didn't you go the `containerElement `way before ?

ListItem is a material-ui component, but this was just a side remarks as it's not directly related to this problem.

**Comment by djhi** [comment]
Actually that was the first implementation. We changed it to use `onClick` because of https://github.com/marmelab/admin-on-rest/issues/642

**Comment by Phocea** [comment]
Thanks @djhi, i knew I read this somewhere :)
Bit of a vicious circle as it seems that several possibilities exists:

- Use `containerElement`, but this will break your #642 fix
- Use `<Link to="/something"><ListItem  primaryText="xsadasds"/>/Link>`..with possible side effects
- Using `onTouchTap`/`onClick`, and you loose some of the native functionality

**Comment by sagarvd01** [comment]
The open in new tab will happen only if there is an href attribute and it is an a tag. Here, you are using a click event listener on a span. So, it won't open in new tab

**Comment by djhi** [comment]
Fixed in `next`
