### ISSUE TITLE
Cannot navigate to edit order - Date filters on reviews not working

### ISSUE THREAD

**Issue by thodwris** [marmelab/admin-on-rest#1126]
Hello,

I want to report some issues I found on demo.

When I am on orders list view, I cannot navigate inside of edit page of a specific order.
Blank page is returned.

[see here](https://marmelab.com/admin-on-rest-demo/#/commands/572)

-----

I want to filter the reviews with posted since field, but it is not working as expected.

[see here](https://marmelab.com/admin-on-rest-demo/#/reviews?filter=%7B%7D&order=DESC&page=1&perPage=25&sort=date)

**Comment by fzaninotto** [comment]
Please open this issue on the `admin-on-rest-demo` repository/
