### ISSUE TITLE
[RFC] `make lint` reports 145 problems.

### ISSUE THREAD

**Issue by DanThomson** [marmelab/admin-on-rest#1128]
I want to start contributing to `admin-on-rest`, so I forked master, ran through the setup, then ran `make test`. I got some errors from the linter. This leaves me with a dilemma. Do fix the code in master so that the linter does not produce errors, or do I write small pull requests which are easy to read but violate [`.github/CONTRIBUTING.md`](https://github.com/marmelab/admin-on-rest/blob/master/.github/CONTRIBUTING.md#coding-style)?

**What you were expecting:**
I expected master to be clean of test errors.

**Steps to reproduce:**
```
$ git clone git@github.com:marmelab/admin-on-rest.git
$ cd admin-on-rest
$ npm install
$ make lint | tee lint-results
```

**What happened instead:**
```
✖ 145 problems (70 errors, 75 warnings)
  67 errors, 0 warnings potentially fixable with the `--fix` option.

make: *** [lint] Error 1
```

**Other information:**
I can make the full results available if needed, but reproducing my results should be trivial. If you cannot reproduce this please let me know.

**The advice from .github/CONTRIBUTING.md would clean up some but not all of these errors**
>### Coding style
>
>You must follow the coding style of the existing files. Admin-on-rest uses eslint and [prettier](https://github.com/prettier/prettier). You can reformat all the project files automatically by calling
>
> ```sh
> make prettier
> ```

Btw, "must" is a pretty strong word given the results shown above and those which follow.

```
$ make prettier | tee prettier-results

success formatting 16 files with prettier-eslint
224 files were unchanged

$ git diff

On branch master
Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   src/auth/withPermissionsFilteredChildren.js
        modified:   src/i18n/TranslationUtils.js
        modified:   src/mui/field/SelectField.js
        modified:   src/mui/form/TabbedForm.js
        modified:   src/mui/input/CheckboxGroupInput.js
        modified:   src/mui/input/Labeled.js
        modified:   src/mui/input/RadioButtonGroupInput.js
        modified:   src/mui/input/ReferenceArrayInput.js
        modified:   src/mui/input/ReferenceInput.js
        modified:   src/mui/input/SelectInput.js
        modified:   src/mui/layout/Layout.js
        modified:   src/mui/list/Datagrid.js
        modified:   src/mui/list/DatagridBody.js
        modified:   src/mui/list/DatagridHeaderCell.js
        modified:   src/mui/list/List.js
        modified:   src/util/FieldTitle.js
```

Should I make a pull request with these changes?

**Even after running `make prettier` there are errors**
```
$ make lint | tee lint-results-post-prettier

✖ 79 problems (4 errors, 75 warnings)

make: *** [lint] Error 1
```

**Environment**
* Admin-on-rest version:
`master branch`
`release v1.3.2`
`commit 07452f0efe31fda3309710f74e11f5988595206c`

* React version:
`15.6.2`

* Node version:
`v8.6.0`

* NPM version:
`5.3.0`

**Research into which version was the last passing version**
* Spoiler: no version has passed `make lint`

```
$ git reset HEAD --hard
HEAD is now at 07452f0 Prepare 1.3.2

$ git checkout  fe62e71
Note: checking out 'fe62e71'.
HEAD is now at fe62e71... Update changelog

$ make lint | tee lint-results-one-version-prior

✖ 142 problems (70 errors, 72 warnings)
  67 errors, 0 warnings potentially fixable with the `--fix` option.

make: *** [lint] Error 1
```

```
$ git checkout b9a7dd1
Previous HEAD position was fe62e71... Update changelog
HEAD is now at b9a7dd1... Prepare v1.2.3


$ make lint | tee lint-results-v1.2.3
make: *** No rule to make target `lint'.  Stop.
```

**Comment by fzaninotto** [comment]
This is due to an update in `prettier` rules, and an wrong versioning (not semver compliant) in one of the babel plugins we use. We'll see if we fix the prettier version, or fix the formatting rules.

**Comment by DanThomson** [comment]
Thanks, I'll go forward with writing my RFC/RFR for the changes I want and work on the presumption that I'll merge an updated master into my feature branch before creating a pr.
