### ISSUE TITLE
Support params in resource

### ISSUE THREAD

**Issue by mstmustisnt** [marmelab/admin-on-rest#113]
Currently resource is taken from `path` passed to `<CrudRoute/>`
For example endpoint to resource is `users/:id/messages`. 
I create crudRoute 

```
<CrudRoute path="users/:id/messages"  list={MessagestList}/>
```

In this case `resource` will be the same as path.
Is there any way to pass resource separately with proper value instead of route param? Without making changes in `rest-client` to avoid wrong requests.

Will appreciate any help. Thank you!

**Comment by fzaninotto** [comment]
Hi mstmustisnt ,

No, currently if you want to make a mapping between the `resource` and a custom `path`, you have to do it in the `restClient`.

**Comment by mstmustisnt** [comment]
@fzaninotto thank you!
