### ISSUE TITLE
Refresh button does not refresh data in <ReferenceManyField>

### ISSUE THREAD

**Issue by Dr8g0n** [marmelab/admin-on-rest#1131]
Please do not submit support requests or "How to" questions here. For that, go to [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest).

**What you were expecting:**

Refresh button should refresh data in ReferenceManyField

**What happened instead:**

Data in ReferenceManyField is not refreshed (no API call) when Refresh button click

**Steps to reproduce:**

Add ReferenceManyField with reference="xyz" target="zyx", Datagrid, and TextField. Click on Refresh button.

**Comment by amitkumar1992** [comment]
I am facing the same problem. need help.

**Comment by Joshuaf91** [comment]
I am having similar issues.

**Comment by fzaninotto** [comment]
Are you in an Edit or Show view?

**Comment by amitkumar1992** [comment]
In edit view

**Comment by fzaninotto** [comment]
Confirmed, it's a bug. Looking for a fix.
