### ISSUE TITLE
refreshView undefined when using custom actions in list

### ISSUE THREAD

**Issue by natrim** [marmelab/admin-on-rest#1133]
In documentation is said:

```
import { CardActions } from 'material-ui/Card';
import FlatButton from 'material-ui/FlatButton';
import NavigationRefresh from 'material-ui/svg-icons/navigation/refresh';
import CreateButton from '../button/CreateButton';

const cardActionStyle = {
    zIndex: 2,
    display: 'inline-block',
    float: 'right',
};

const PostActions = ({ resource, filters, displayedFilters, filterValues, basePath, showFilter, refresh }) => (
    <CardActions style={cardActionStyle}>
        {filters && React.cloneElement(filters, { resource, showFilter, displayedFilters, filterValues, context: 'button' }) }
        <CreateButton basePath={basePath} />
        <FlatButton primary label="refresh" onClick={refresh} icon={<NavigationRefresh />} />
        {/* Add your custom actions */}
        <FlatButton primary label="Custom Action" onClick={customAction} />
    </CardActions>
);

export const PostList = (props) => (
    <List {...props} actions={<PostActions />}>
        ...
    </List>
);
```

which is obviously outdated as it reports deprecation warning

BUT it also throws error on `this.props.refreshView();` because `this` is null in onClick event
(and does not refresh list)

(using new way with connect works)

**Comment by recepkocur** [comment]
+1

**Comment by natrim** [comment]
@djhi it's technically bug thought, because it breaks the app (scope error)

**Comment by djhi** [comment]
Is it related to https://github.com/marmelab/admin-on-rest/pull/1033 ?

**Comment by natrim** [comment]
it's caused by it

**Comment by djhi** [comment]
If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

* CodeSandbox (https://codesandbox.io/s/ElxGNxBY0)
* A sample application via GitHub

**Comment by natrim** [comment]
example is in opening post

custom `actions` get's `refresh` prop, which is not bound so inside `refresh` `this` is null causing `this.props.refreshView();` to fail

**Comment by djhi** [comment]
Oh I see now. Thx for reporting. The fix is easy though: in `src/mui/list/List.js`, replace `refresh()` by `refresh = () =>`. Can you make a PR ?

**Comment by djhi** [comment]
> example is in opening post

No, we now require runnable example, hence the codesandbox. Please remember it for your next issue ;)

**Comment by natrim** [comment]
@djhi purred as #1148

**Comment by djhi** [comment]
It has been added recently. Thx for the PR !
