### ISSUE TITLE
be able to specify which attribut of the current object is used in the deletion message confirmation

### ISSUE THREAD

**Issue by sfenollosa** [marmelab/admin-on-rest#1134]
Delete component has a title parameter but if write my own remove component like this :
`export const UserDelete = (props) => (
	<Delete title={something} {...props}/>
)`
I don't receive the full objet in the props, only it's id, so I can not build a title with the user name for instance.

The Delete component does a crudGetOne in the componentWillReceiveProps, so that would be nice if the defaultTitle could be built with another thing than the id.

For instance, if the Delete component had a "source" parameter, I could write this :

`export const UserDelete = (props) => (
	<Delete source='name' {...props}/>
)`

and have a message like 'Remove User Samuel' instead of 'Remove User #zievhzevkzeùvkj'.

**Comment by djhi** [comment]
Simply connect your component with redux and retrieve the resource using its id. Check this [part](https://github.com/marmelab/admin-on-rest/blob/master/src/mui/delete/Delete.js#L141) of the Delete component for inspiration.
