### ISSUE TITLE
"Cannot use 'in' operator to search for 'id' in undefined" error when delete a record

### ISSUE THREAD

**Issue by Dr8g0n** [marmelab/admin-on-rest#1136]
Record is deleted with this error "Cannot use 'in' operator to search for 'id' in undefined" shows in notification

**Environment**

* Admin-on-rest version: 1.3.1
* React version: 15.6.2
* Stack trace (in case of a JS error):
Cannot use 'in' operator to search for 'id' in undefined
(anonymous) @ crudResponse.js:147
r @ runtime.js:65
(anonymous) @ runtime.js:303
e.(anonymous function) @ runtime.js:117
b @ proc.js:302
u @ proc.js:261
O @ proc.js:544
E @ proc.js:425
b @ proc.js:306
r @ proc.js:378
u @ proc.js:456
t @ channel.js:73
(anonymous) @ channel.js:161
(anonymous) @ channel.js:182
t @ channel.js:26
(anonymous) @ middleware.js:67
dispatch @ applyMiddleware.js:35
(anonymous) @ utils.js:250
(anonymous) @ proc.js:479
r @ scheduler.js:19
u @ scheduler.js:60
o @ scheduler.js:33
T @ proc.js:476
E @ proc.js:425
b @ proc.js:306
r @ proc.js:378
(anonymous) @ proc.js:441

**Comment by djhi** [comment]
How are you referencing admin-on-rest on your project ? It looks like a failed transpilation error to me

**Comment by Dr8g0n** [comment]
`const App = () => (
    <Admin loginPage={Login} authClient={authClient} theme={getMuiTheme(myTheme)} title="App Admin" dashboard={Dashboard} restClient={appApiRestClient} customRoutes={customRoutes} >
        <Resource name="users" list={UserList} edit={UserEdit} create={UserCreate} remove={Delete} icon={UserIcon} />
    </Admin>
);

export default App;`
