### ISSUE TITLE
NumberInput allows the character 'e'

### ISSUE THREAD

**Issue by bfintal** [marmelab/admin-on-rest#1137]
**What you were expecting:**
Only numbers are allowed.

**What happened instead:**
Pressing e is accepted
![e](https://d26dzxoao6i3hh.cloudfront.net/items/312J0m3f3N1f41003j27/Screen%20Recording%202017-10-08%20at%2009.45%20PM.gif?v=5057a826)

**Steps to reproduce:**
This is just a normal NumberInput field

**Environment**

* Admin-on-rest version: 1.3.2
* React version: 15.6.1

**Comment by fzaninotto** [comment]
It's not a bug, it's a feature™. This is in the HTML spec for the `<input type="number">`, see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number. The objective is to allow big numbers, like 1.234e12.

**Comment by bfintal** [comment]
Ah I see, thanks for clarifying this!
