### ISSUE TITLE
Pressing Enter on a SelectInput option does not close it

### ISSUE THREAD

**Issue by bfintal** [marmelab/admin-on-rest#1138]
**What you were expecting:**
The options would close after hitting enter.

**What happened instead:**
![doesn't close](https://d26dzxoao6i3hh.cloudfront.net/items/190R2O1T170w252w0S1a/Screen%20Recording%202017-10-08%20at%2009.52%20PM.gif?v=2482444c)

**Related code:**
```
<ReferenceInput label="Payment Mode" source="payment_mode" reference="payment_modes" allowEmpty validation={{ required: true }}>
    <SelectInput/>
</ReferenceInput>
```

**Environment**

* Admin-on-rest version: 1.3.2
* React version: 15.6.1

**Comment by fzaninotto** [comment]
Reproduced, it's a bug. It doesn't come from material-ui, which closes the list of items correctly on enter. Perhaps a side effect of redux-form, or of performance optimizations we did.

**Comment by RiccardoF** [comment]
I've the same problem, has someone found a solution?

**Comment by wagnerdelima** [comment]
Have anyone found a solution?

**Comment by djhi** [comment]
Tracked it down to the `autoWidth` prop we set on the `SelectField`. On the demo app, if I remove it, everything works as expected

**Comment by djhi** [comment]
Until we figure out a solution for this, here is a workaround

```
<ReferenceInput label="Payment Mode" source="payment_mode" reference="payment_modes" allowEmpty validation={{ required: true }}>
    <SelectInput options={{ autoWidth: false }} />
</ReferenceInput>
```

**Comment by djhi** [comment]
https://github.com/mui-org/material-ui/issues/9834

**Comment by RiccardoF** [comment]
This workaround is working in order to close the select input, but you lose the focus on the dropdown you closed, so you cannot move with tab key on the next dropdown.

**Comment by djhi** [comment]
Still, the issue is on MUI side. Nothing we can do about it here. Please upvote the issue on their repository
