### ISSUE TITLE
react16 SelectArrayInput autocomplete not working

### ISSUE THREAD

**Issue by xiaomingplus** [marmelab/admin-on-rest#1139]
Please do not submit support requests or "How to" questions here. For that, go to [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest).

**What you were expecting:**

I hope SelectArrayInput can select autocomplete value.
**What happened instead:**

in react 16.0.0 ,SelectArrayInput autocomplete not working
**Steps to reproduce:**

**Related code:**

```
            <SelectArrayInput choices={[
                {
                    id:1,
                    name:'xxx'
                },
                {
                    id:2,
                    name:'yyy'
                }
            ]} optionText="name"/>
```

**Other information:**

In react15.4,SelectArrayInput autocomplete it's ok 

**Environment**

* Admin-on-rest version:^1.3.2
* Last version that did not exhibit the issue (if applicable):15.4
* React version:16.0
* Browser:chrome
* Stack trace (in case of a JS error): no error

**Comment by djhi** [comment]
https://github.com/callemall/material-ui/releases/tag/v0.19.4 is now compatible with React 16. We should be able to makt the move too

**Comment by fzaninotto** [comment]
I think this is dependent on an upgrade of `material-ui-chip-input` to work with React 16. Can you also report the bug to https://github.com/TeamWertarbyte/material-ui-chip-input?

**Comment by djhi** [comment]
It already has been updated to support r16

**Comment by fzaninotto** [comment]
It still doesn't work with react 16 and material-ui-chip-input 0.18.1 (tested on the `next` branch). So the problem lies in the `material-ui-chip-input` package IMO.

**Comment by natrim** [comment]
when i look in redux dev tool
it seems to send the redux-form/CHANGE with the value
but then it send redux-form/BLUR which removes the value

**Comment by leMaik** [comment]
@fzaninotto I'm trying to fix this bug right now. :+1:

**Comment by VTopoliuk** [comment]
I have the same issue reproducible with `SelectArrayInput` inside `ReferenceArrayInput`. Any updates or workarounds? 
P.S. It sounds like a **bug** not **enhancement**

**Comment by natrim** [comment]
just a something i noticed
when you try to click on the item to select, it does not work
but if you move to the item by keys and press enter, then it works

```
    <ReferenceArrayInput
      source="categories_ids"
      reference="categories"
      sort={{ field: 'name', order: 'ASC' }}
      perPage={100}
      allowEmpty
    >
      <SelectArrayInput optionText="name" />
    </ReferenceArrayInput>
```

**Comment by natrim** [comment]
if i remove `componentWillReceiveProps` in https://github.com/marmelab/admin-on-rest/blob/master/src/mui/input/SelectArrayInput.js#L67

and make `handleAdd` and `handleDelete` use function type of `setState`, then it seems to work
```
 handleAdd = newValue => {
        this.setState((prevState) => {
                const values = [prevState.values, newValue];
                return { values };
        }, () => {
                this.handleChange(this.state.values);
        });
    };

    handleDelete = newValue => {
        this.setState((prevState) => {
                const values = prevState.values.filter(v => v.value !== newValue);
                return { values };
        }, () => {
                this.handleChange(this.state.values);
        });
    };
```

**Comment by leMaik** [comment]
> material-ui-chip-input seems to work fine in their storybook for all cases

Yup, no problems with react@16 on our end. :thinking:

**Comment by VTopoliuk** [comment]
@natrim nice investigation!

**Comment by eghernqvist** [comment]
Any update on this?

**Comment by samhiddenhand** [comment]
Just curious if there's at least a workaround discovered for this in the meantime?

**Comment by larasulfo** [comment]
as a workaround solution, you can add this  clearOnBlur={false} 
for example:
            <SelectArrayInput source="source" choices={choices} optionText="name" optionValue="id" clearOnBlur={false} />

**Comment by samhiddenhand** [comment]
@larasulfo hmm, I just tried that, and it didn't make a difference.

**Comment by larasulfo** [comment]
@samhiddenhand You're right, It has worked for me, but after some implementations, It has stopped. I'm deleting my comment to not confuse anyone.
,
<img width="1018" alt="screen shot 2017-12-14 at 13 32 13" src="https://user-images.githubusercontent.com/11397468/33987814-4ad5b168-e0d3-11e7-8a71-7b03014349eb.png">

**Comment by bevinhex** [comment]
For the moment as a work around, you can use CheckboxGroupInput, it is working for me

**Comment by llioor** [comment]
Same issue here... checkbox can not be a solution for me. I have 50+ choices

**Comment by llioor** [comment]
I run yarn upgrade and update all versions.
It is still not working on my side.
```
<ReferenceArrayInput label="Managers" source="managers_ids" reference="admin/managers"
                                 allowEmpty>
              <SelectArrayInput  optionText={optionManagersRenderer}/>
            </ReferenceArrayInput>
```
Here is a video of the Redux log: https://ufile.io/qdivw

**Comment by djhi** [comment]
Can you provide a [codesandbox](https://codesandbox.io/) reproducing the issue ?

**Comment by llioor** [comment]
Hi @djhi 
This is the same project as I sent you today: https://bitbucket.org/llioor/aor-test/src
You can see on edit I have the Select and on the create I have the Checkbox.
We don't have the same API so it will be problematic for you.
I added another video to show the checkbox: https://ufile.io/xinhz

**Comment by natrim** [comment]
btw. the commit with this "fix" is still not released so yarn upgrade will not work .)

**Comment by llioor** [comment]
@natrim Thank for the update.. actually I didn't see it.. I just saw this case was closed yesterday and that the version was merged. 
> merged 1 commit into master from fix_mui_chip_input a day ago

**Comment by tgeorges** [comment]
Hi,
I experienced the same issue with react 16.2 & aor 1.3.4 with a very similar use case (referencearrayinput + selectArrayInput). I have double check the version of material chip.
Do you have an idea ?

**Comment by eghernqvist** [comment]
I managed to make it work now with some trial and error debugging. What made it work was disabling the `onBlur` function on line 183 in [SelectArrayInput], see theory below.

Here's what I found:
I started off by making my own copy of [SelectArrayInput], and I found that when clicking an element in the list the component triggers `handleAdd` followed by `handleBlur`.
On line 95 `handleAdd` calls `this.setState`, and since `handleBlur` uses this.state.values for setting the value and `handleBlur` gets called before the component has received the new values in the state it sets the values immediately to `[]`.

**Removing `onBlur` from [ChipInput] didn't work, but setting the `onBlur` function to `() => {}` seems to do the trick.**

Unsure if doing this causes any issues, I couldn't find any direct problems.

**Comment by tgeorges** [comment]
Great workaround @eghernqvist ! Tested and approved 👍 

In practice : 

```jsx
<ReferenceArrayInput
          source="peoples"
          reference="Person"
          label="People"
          allowEmpty
        >
          <SelectArrayInput optionText="email" options={{ onBlur: () => {} }} />
</ReferenceArrayInput>
```
