### ISSUE TITLE
Items in lists don't update after search input is cleared

### ISSUE THREAD

**Issue by mstmustisnt** [marmelab/admin-on-rest#114]
If we try to search through resource everything is ok, except for the case when we clear the search input and expect to see unfiltered resource items, but no request is sent to server and we see no changes (old filtered list)

**Comment by alexborisov** [comment]
It looks like this isnt just search. I've noticed that when you create or remove a record the list view does not reflect the change. Clicking refresh fires off a network request, but it seems it never updates the list. Only reloading the list view seems to update it. Perhaps it's my REST client implementation, but i've just forked it off the basic one provided...

**Comment by fzaninotto** [comment]
I can confirm this is a bug and it's present on master. Will investigate.
