### ISSUE TITLE
Use secondary color to style internal links (including ReferenceField)

### ISSUE THREAD

**Issue by marcquark** [marmelab/admin-on-rest#1155]
**What you were expecting:**
In a ReferenceField, links should be styled according to the theme (as displayed in a screenshot in the documentation: https://marmelab.com/admin-on-rest/Fields.html#referencefield )

**What happened instead:**
The link is not styled/themed at all
![Screenshot](https://user-images.githubusercontent.com/23556080/31575172-b8e72db2-b0e0-11e7-8b6d-a9cebc4b42f3.png)

**Steps to reproduce:**
Display any ReferenceField type in your list
or
Open the live demo and display Orders

**Environment**
* Admin-on-rest version: 1.3.2
* React version: 15.6.2, 16.0.0 (same behaviour with both versions)
* Browser: Chrome 61.0.3163.100, Firefox 56.0

**Comment by fzaninotto** [comment]
There is no `<Link>` component in material-ui. But I guess you mean that links should use the secondary color, as explained in https://material.io/guidelines/style/color.html#color-color-system

**Comment by marcquark** [comment]
Are you sure this is not a bug? It seems to have used the secondary color at some point in time, at least when i look at the screenshot in the documentation that i've linked, it looks like it has...

**Comment by fzaninotto** [comment]
It may have worked in the past, I don't remember. It doesn't matter much anyway if it's a bug or a feature.
