### ISSUE TITLE
Table widget

### ISSUE THREAD

**Issue by dekhaus** [marmelab/admin-on-rest#1158]
Hi All

What table 'widget' does admin-on-rest use 'out of the box' ?

Thanks
Dave

**Comment by Phocea** [comment]
https://github.com/marmelab/admin-on-rest/blob/master/src/mui/list/Datagrid.js

**Comment by fzaninotto** [comment]
If you want to see the features of admin-on-rest, I recommend you try the demo

https://marmelab.com/admin-on-rest-demo/
