### ISSUE TITLE
It is not possible to have 2 filters on the same resource/source 

### ISSUE THREAD

**Issue by sfenollosa** [marmelab/admin-on-rest#1163]
I create this issue as requested in stackoverflow here : 
https://stackoverflow.com/questions/46785195/admin-on-rest-2-filters-with-same-source

I am using 1.3.2 version.

I want to create two filters on the same resource and the same source with referenceInputs but for different queries, like this :

```jsx
<Filter>    
    <ReferenceInput  source="productCode" reference="product" filterToQuery=
 {searchText => ({ name: searchText+'*' })}>
        <AutocompleteInput optionText="name" allowEmpty/>
    </ReferenceInput>,  
    <ReferenceInput source="productCode" 
    label='resources.product.fields.code' reference="product" filterToQuery={searchText => ({ code: searchText+'*' })}>
        <AutocompleteInput optionText="code" allowEmpty  />
    </ReferenceInput>
</Filter>
```

But I get an error : proxyConsole.js:56 Warning: flattenChildren(...): Encountered two children with the same key, .$productCode. Child keys must be unique;

and the second filter is not rendered.

I tried to add distinct "key" parameters on referenceInputs and/or AutoCompleInputs but I still have the error.

**Comment by djhi** [comment]
This scenario won't be supported. However, you can achieve something similar with a custom input. Please ask this question on StackOverflow and I'll provide an example. This way, the answer will be easier to find for others.

**Comment by tasnim-truly** [comment]
> This scenario won't be supported. However, you can achieve something similar with a custom input. Please ask this question on StackOverflow and I'll provide an example. This way, the answer will be easier to find for others.

Hi @djhi I'm currently trying to achieve something similar which seems to work but the same console error appears. I checked the stackoverflow question which doesn't have any suggestions on how to custom create this feature. Would you still be interested in providing an example?

I've added a gif to show how I am filtering on a foreign resource in 2 separate filter inputs which results in the console error mentioned in the original question.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/75998468/127867125-a09f909b-0dfd-49b4-b92e-18245d0804a2.gif)

```
    <Filter {...props}>
        <ReferenceArrayInput source="serviceIds" reference="services">
            <SelectArrayInput optionText="name" />
        </ReferenceArrayInput>
        <ReferenceArrayInput source="serviceIds" reference="services">
            <SelectArrayInput optionText="supplierName" />
        </ReferenceArrayInput>
    </Filter>

```
