### ISSUE TITLE
Vertical scroll on a page not working in IE11 when e.g number of elements in a list exceeds the screen height

### ISSUE THREAD

**Issue by activist** [marmelab/admin-on-rest#1165]
Test/see screenshot from page https://marmelab.com/admin-on-rest-demo/#/customers on IE11 where no scrollbar appears even though height of page/number of elements in the list is taller than viewport. 
![ie11_vert_scroll_bug](https://user-images.githubusercontent.com/88418/31735252-9fd4e10c-b441-11e7-8f89-829e32a371e8.png)

This is related to `flex:1` on the `body` in `Layout.js`. Fix is setting it to `flex: 1 1 auto;`

**Comment by fzaninotto** [comment]
Fixed by #1166
