### ISSUE TITLE
broken react-router-redux 5.0.0-alpha.7 pulled in

### ISSUE THREAD

**Issue by ztane** [marmelab/admin-on-rest#1168]
The [broken](https://github.com/ReactTraining/react-router/issues/5640) `react-router-redux 5.0.0-alpha.7` is pulled in by the very unfortunate `react-router-redux ~5.0.0-alpha.6` pinning, resulting in 

    Module not found: Error: Cannot resolve 'file' or 'directory' ./selectors in 
    /.../node_modules/admin-on-rest/node_modules/react-router-redux

**Comment by fzaninotto** [comment]
Can you open a PR against master removing the `~` from the dependency?

**Comment by nguiard** [comment]
This was fixed in alpha.8 a few hours ago
