### ISSUE TITLE
NumberField and BooleanField misalignment issue when used in Create/Edit form

### ISSUE THREAD

**Issue by giokokos** [marmelab/admin-on-rest#1171]
I'm using `Fields` in `Create/Edit` form for read-only properties.

**What you were expecting:**
`<NumberField/>` and `<BooleanField/>` are expected to be left-aligned in `Create/Edit` form. `DataGrid` seems more appropriate to decide whether to align right or center based on the type of the child `Field`.

**What happened instead:**
`<NumberField/>` is right-aligned and `<BooleanField/>` is center-aligned in a `Create/Edit` form.

* CodeSandbox https://codesandbox.io/s/k3rv1rzoj7 please navigate to https://k3rv1rzoj7.codesandbox.io/#/posts/13 and go to Miscellaneous Tab.

![image](https://user-images.githubusercontent.com/3083746/31833479-5ee612e0-b5d3-11e7-8949-e0150cfc14e2.png)

**Environment**

* Admin-on-rest version: ~1.3.2
* React version: ~15.5.4
* Browser: Latest Chrome

**Comment by zifnab87** [comment]
indeed! this causes alignment issues to the field components created by component factory in create or edit mode: https://github.com/zifnab87/ra-component-factory

**Comment by fzaninotto** [comment]
I'm aware if this, and this is not something we're going to fi in 1.0, as you can set the style using the `style` and `elStyle` props, as in [the example](https://github.com/marmelab/admin-on-rest/blob/next/packages/ra-example/posts.js#L280-L281).

I'll keep it for 2.0, because since we break BC, we can imagine default styles for grid and vertical layout.

**Comment by zifnab87** [comment]
awesome @fzaninotto  thanks! when is a rough estimate of  version 2 release?

**Comment by fzaninotto** [comment]
When it's done

**Comment by remi13131** [comment]
Just for info, this had been answered in past as well : #570

**Comment by fzaninotto** [comment]
This is fixed in `next` (see #1268). It won't be fixed in `master`, because it requires a backwards compatibility break. So I'm closing this issue.
