### ISSUE TITLE
Is it one permission per users or can we do multiple role ? What is the type of permissions?

### ISSUE THREAD

**Issue by kopax** [marmelab/admin-on-rest#1173]
I have a backend spring with multiple role per users.

I am trying to implement client side ui with permissions.

I have a list of role `roleList["ROLE_AUTH","ROLE_USER_MANAGEMENT","ROLE_USER_MANAGEMENT_MANAGE_USER"]` ...

In the [documentation](https://marmelab.com/admin-on-rest/Authorization.html) it doesn't says the type of `role` but in the example, I only see one role `admin`.

Also, the switch seems to accept a single value. 

What is the exact type of role ?

**Comment by fzaninotto** [comment]
`permissions` is whatever your `authClient` returns when calling `AUTH_GET_PERMISSIONS`. You're free to store an array there.

**Comment by trsteel88** [comment]
@fzaninotto my authClient returns an array of permissions but it looks like it is been given back to me as a string.

e.g. my roles are ['ROLE_USER', 'ROLE_ADMIN']. However, inside the admin component I get "ROLE_USER,ROLE_ADMIN".

Would be good to see some example docs for multiple roles.

Any help would be much appreciated.

**Comment by trsteel88** [comment]
Actually, I discovered the issue. localstorage was changing it to a string. Needs to convert to json or just decode directly in the check.
