### ISSUE TITLE
How to change labels from capital case to small case in the main grid of admin on rest

### ISSUE THREAD

**Issue by donno13** [marmelab/admin-on-rest#1174]
how do i make admin on rest main grid labels in regular case .as my application requires too many columns in the grid and all together it looks very bad and messy .i have created an en.json file and it's taking the value from there that is if the property is channelType and I have given in en.json as "channelType": "Channel ", its showing "CHANNEL" itself in the grid but I want it to be in regular case such as "Channel", what should I do

**Comment by fzaninotto** [comment]
Using aor `<Datagrid>`, you can't. I suggest you roll up your own datagrid component for that.

**Comment by donno13** [comment]
can you give a example for that

**Comment by djhi** [comment]
Please don't double post here questions in StackOverflow
