### ISSUE TITLE
Responsive helper for material-ui v1

### ISSUE THREAD

**Issue by RWOverdijk** [marmelab/admin-on-rest#1175]
For our project (not using aor), I'm using material-ui@next, which works differently when it comes to sizing. I've created a new `<Responsive />` component. Some changes with the one currently in this project:

* Added the exact prop, to allow only showing components for exact size matches.
* Allow functions to be passed in. This is better for performance as it only renders what is needed, instead of everything.

```js
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import withWidth from 'material-ui/utils/withWidth';

export class Responsive extends Component {
  static propTypes = {
    xs   : PropTypes.oneOfType([PropTypes.element, PropTypes.func]),
    sm   : PropTypes.oneOfType([PropTypes.element, PropTypes.func]),
    md   : PropTypes.oneOfType([PropTypes.element, PropTypes.func]),
    lg   : PropTypes.oneOfType([PropTypes.element, PropTypes.func]),
    xl   : PropTypes.oneOfType([PropTypes.element, PropTypes.func]),
    width: PropTypes.string,
    exact: PropTypes.bool
  };

  static defaultProps = {
    exact: false
  };

  render() {
    const { xs, sm, md, lg, xl, width, exact, ...rest } = this.props;

    let component;

    // Bail if exact mode and none was provided.
    if (exact && !this.props[width]) {
      return null;
    }

    switch (width) {

      case 'xs':
        component = xs || sm || md || lg || xl;
        break;

      case 'sm':
        component = sm || md || lg || xl || xs;
        break;

      case 'md':
        component = md|| lg || xl || sm || xs ;
        break;

      case 'lg':
        component = lg || xl || md || sm || xs;
        break;

      case 'xl':
        component = xl || lg || md || sm || xs;
        break;

      default:
        throw new Error(`Unknown width ${width}`);
    }

    // Allow functions for better performance, and render JIT.
    if (typeof component === 'function') {
      component = component();
    }

    return React.cloneElement(component, rest);
  }
}

export default withWidth()(Responsive);
```

I couldn't make a PR for this because the project isn't using v1 yet. It's not an issue but... You know, feel free to close this so the code is at least archived for when the time comes.

**Comment by fzaninotto** [comment]
Excellent ! Could you open a PR against [the material-ui-1 branch](https://github.com/marmelab/admin-on-rest/tree/material-ui-1) (yes, the migration has begun!)

**Comment by RWOverdijk** [comment]
@fzaninotto I'll do that whenever I start using it. I have to be precise in my contributions to be able to explain it at work. :) I could just paste it in, but it's being used internally and I don't know what I might break.
