### ISSUE TITLE
[RFC] Add example in documentation AdminOnRest for writing UI controllers.

### ISSUE THREAD

**Issue by pnepe6** [marmelab/admin-on-rest#1176]
On an `<EditView />` I am using `<ReferenceArrayField />` to display an edit form of checkbox.

I need to fill the form with the data, but the checkbox list is so far implemented using the response entities from the `ReferenceArrayField`.

1. I have an the `user` entity fetched by the `<EditView/>` 
1. In `<EditView/>` I am fetching related data using `<ReferenceArrayField />
1. I write a custom grid using the `<ReferenceArrayField />` data
1. **I want to fill** the `checked` props of my checkbox **depending on values** present in `user`.

This would be some trivial controller logic for the UI but documentation has completely no information.

So far I am only able to have one `record` by scope which means that every data displayed on the UI would be from a single entity and no controller logic can be written in between.

## Use case

```jsx

    const CheckboxGrid = ({ ids, data, basePath }) => (
      <div style={{ margin: '1em' }}>
        {ids.map(id =>
          <div key={id}>
            <h2><TextField record={data[id]} source="description" /></h2>
            <label>
              <input type="checkbox" name="authority[]" disabled checked={true} />{' '}
              <TextField record={data[id]} source="role.description" />
            </label>
            {data[id].siteFunctionList.map((siteFunction) => (
              <div key={siteFunction.description} className="pl-3">
                <h3><TextField record={siteFunction} source="description" disabled /></h3>
                <label>
                  <input type="checkbox" name="authority[]" disabled />{' '}
                  <TextField record={siteFunction} source="role.description" />
                </label>
              </div>
            ))}
          </div>
        )}
      </div>
    );
    
    CheckboxGrid.defaultProps = {
      data: {},
      ids: [],
    };
    
    
    export class AuthorityList extends React.Component {
      render() {
        const resourceName = 'users';
        const resourceId = this.props.match.params.id;
        return (
          <Edit {...this.props} resource={resourceName} id={resourceId}>
            <SimpleForm>
              <ReferenceArrayField reference="siteServices" source="siteServiceIdList">
                <CheckboxGrid />
              </ReferenceArrayField>
            </SimpleForm>
          </Edit>
        );
      }
    }
```

The user have a list of values that would match some of the values present in `data`.

## Fact

- I do not have access to the `<Edit .../>` record in the scope of checkbox grid.

- I have seen that there is in `redux` a `form['record-form'].values` where the entity is store so I could access it with custom selectors:

EX:

```jsx
    const mapStateToProps = createStructuredSelector({
      record: makeSelectFormRecordFormValues(),
    });
    const withConnect = connect(mapStateToProps);
    const CheckboxGridConnect = compose(
      withConnect,
    )(CheckboxGrid);
```

- There is also a store for each resources declared in admin on rest. It store the entities fetched with `<ReferenceArrayField />` but I don't see these stores scalable in case we use more than one  `<ReferenceArrayField />` for the same resource.

_Should I directly pick in the store and inject my self the entities ?_

I haven't find anything like this in the documentation and I think it is a major feature because it is competely not possible to write a completely customizable UI without the possibility to do this.

**Environment**

* Admin-on-rest version: 1.3.2
* React version: 16.0.0

**Comment by fzaninotto** [comment]
That's because you're not using the right component - try `<ReferenceArrayInput>` instead.

**Comment by pnepe6** [comment]
@fzaninotto That's true. But that doesn't answer the question, we manage by creating a `AuthorityShowLayout` tu display a form with the logic I wanted.

We didn't found how to map the checkbox field with the record.

**Comment by kopax** [comment]
@fzaninotto I am encountering the same issue.

I basically need to get N request result before displaying  a form. So far I manage with the following structure : 

`ReferenceField > Grid > ReferenceField > Grid > Display.`

This work fine as long as you have less than 2 or 3 requests but if you have many of async request it is almost impossible to write readable code.

I am thinking of creating an `<AsyncResourcesLoader />` that would take an array of ReferenceField and prepare the data.

Is there another possibility?
