### ISSUE TITLE
Sub Menus in Custom SideBar are broken

### ISSUE THREAD

**Issue by skoschik** [marmelab/admin-on-rest#1180]
Sub-menus do not work in new versions.  I just upgraded from 1.2.1 to 1.3.2 and noticed that the sub-menu's in my custom SideMenu does not open correctly.

This isn't my work but it serves as a good example.  
https://codesandbox.io/s/88ok152q08

If you upgrade the AOR dependency you'll notice the submenu's stop working in that example.

No errors appear in console.
Was wondering if it had something to do with
https://github.com/marmelab/admin-on-rest/commit/5ffc5930e22449a148d2ee2053a3736f99ab6e1c#diff-4dcdeb55123fbfee64dc81e955e184a0
 but I haven't had a chance to tinker.

**Comment by djhi** [comment]
Just remember to update the material-ui dependency, along with aor addons. See https://codesandbox.io/s/vmr20jzlw5
