### ISSUE TITLE
Have permissions available in custom List Actions

### ISSUE THREAD

**Issue by danejorgensen** [marmelab/admin-on-rest#1186]
**What you were expecting:**
I would like to access permissions in custom List Actions.

**What happened instead:**
permissions are not available from the List container actions prop

**Related code:**
```
<List actions={<CustomActions permissions={permissions} />} ...>
  <Datagrid>
    /* columns */
  </Datagrid>
</List>
```

**Other information:**
https://stackoverflow.com/questions/46986582/admin-on-rest-permissions-in-custom-list-actions

**Environment**

* Admin-on-rest version: 1.3.2
* React version: 15.X
* Browser: Chrome

**Comment by fzaninotto** [comment]
ping @djhi I guess it's possible using the new `<WithPermissions>` component, right?

**Comment by djhi** [comment]
It will be in `next` yes without having to use `WithPermissions` as permissions will be injected in the container:

```jsx
const PostList = ({ permissions, ...props }) => (
    <List actions={<CustomActions permissions={permissions} />} ...>
        <Datagrid>
            /* columns */
        </Datagrid>
    </List>
);
```

)
