### ISSUE TITLE
Resource with filters to no filters bug

### ISSUE THREAD

**Issue by Toosick** [marmelab/admin-on-rest#1192]
**What you were expecting:**
Put some filters on the resource. Refresh the page just incase. Click the resource link which removes all the filters. The page doesn't update.

**Related code:**
The List getQuery functions need to be altered to my knowledge.

**Demo:**
[![https://gyazo.com/ad9c9bc109a4d84b590cc162784d0a36](https://i.gyazo.com/ad9c9bc109a4d84b590cc162784d0a36.gif)](https://gyazo.com/ad9c9bc109a4d84b590cc162784d0a36)

* Admin-on-rest version: 1.3.2
* React version: 15.5.4
* Browser: Chrome

**Comment by fzaninotto** [comment]
It's not a bug, it's a feature™.

The resource link doesn't remove all the filters, it keeps them. This is a UX choice motivated by the fact that, if a user has a filtered list of commands, and clicks on a customer name, then return to the list of commands, they expect it to be just like when they left it - filtered.

**Comment by Toosick** [comment]
In my opinion, to get back to the filtered list you should use the back and forward buttons. The URL should correspond to what you are seeing on the screen. Clearly the filtered list doesn't correspond to the barebones resource URL when you click the menu.

**Comment by rossedfort** [comment]
@Toosick, I completely agree.

@fzaninotto If this truly is a "feature™", is there at least be a way to disable it?

**Comment by nacimgoura** [comment]
This feature would be very useful.

**Comment by fzaninotto** [comment]
- Solution 1: Write a custom menu item, which links to the resource with an empty filter.
- Solution 2: Write a "reset filters" button that resets the part of the redux store storing the filters for that resource
