### ISSUE TITLE
<Provider> in Admin.js problem

### ISSUE THREAD

**Issue by rohanricky** [marmelab/admin-on-rest#1198]
`<Provider> does not support changing `store` on the fly. It is most likely that you see this error because you updated to Redux 2.x and React Redux 2.x which no longer hot reload reducers automatically.`

I think this error is due to `<Provider store={store}>` in Admin.js

I am also getting this warning:
 `You cannot change <Router history>`

**Environment**

* Admin-on-rest version: 1.3.2
* Last version that did not exhibit the issue (if applicable):
* React version: 16.0.0
* Browser: Google Chrome 62.0
* Stack trace (in case of a JS error):
[gg.log](https://github.com/marmelab/admin-on-rest/files/1437542/gg.log)

**Comment by fzaninotto** [comment]
React 16.0 isn't supported for now. Also, please respect the issue template, we can't determine if the error is on your side or on aor's side with so few details.
