### ISSUE TITLE
SelectInput doesn't close using the keyborad

### ISSUE THREAD

**Issue by RiccardoF** [marmelab/admin-on-rest#1199]
**What you were expecting:**
When I click on the "Tab" key to move through the menu voices in the select and I click "Enter" key to select a value, I expect that the dropdown will be closed.

**What happened instead:**
The dropdown is not closed, so when I click again on the "Tab" key to move to the next field, what I get is that the select is still open and if I have more select in the form, I will get in situation where I will have every select opened at the same time. 

**Steps to reproduce:**
```
<ReferenceInput
  label="Status"
  source="status"
  reference="domains/statuses"
  perPage={0}
  allowEmpty>
    <SelectInput optionText="name" />
</ReferenceInput>
```

**Environment**
* Admin-on-rest version: ^1.3.1
* React version: ^15.6.1

Thank you very much!
Riccardo

**Comment by wagnerdelima** [comment]
Hi everyone. What @RiccardoF said is true. There is a bug in the component. Is there any idea when this will be fixed?

**Comment by fzaninotto** [comment]
It is fixed in the `next` branch

**Comment by djhi** [comment]
Won't be fixed in `master`. Related to https://github.com/mui-org/material-ui/issues/6080.

There is a workaround if you use `options` and passes

```js
<SelectInput ... options={{ dropDownMenuProps: {animated: false } }}
```

However, it will throw errors as explained in https://github.com/mui-org/material-ui/issues/6260
