### ISSUE TITLE
Future front-end framework suggestion

### ISSUE THREAD

**Issue by TheAndroidGuy** [marmelab/admin-on-rest#1200]
Hello guys,
I have suggestion for future front-end framework you can build with [Vue.js](http://vuejs.org) and [Element.io](http://element.eleme.io/#/en-US/component/form). I love your other frameworks but unfortunately i don't have experience with React or Angular.
Let me know what you think.

`Sorry for posting this as an issue. I tried contacting you by email but it is not working.`

**Comment by fzaninotto** [comment]
No, this is not how open-source works. You’ve taken us for a developer charity by mistake. If you need something, build it.
