### ISSUE TITLE
Support custom styles on DashboardMenuItem

### ISSUE THREAD

**Issue by AlexandrKnyazev1395** [marmelab/admin-on-rest#1201]
My task is changing color of active resource. 
I use my own menu. I can change background-color of MenuItemLink:
```
const styles = {
...
  button: {
    backgroundColor: 'red',
  }
...
};
...
<MenuItemLink
    style={ isActive ? styles.button : null}
    primaryText={item} 
    key={item}
    to={`/${item}`}
    onClick={()=>{this.handlerCLickResource(item)}} 
    leftIcon={icons[item] || null}
/>
...
          )
```
It works:
![screenshot-localhost-3000-2017-11-03-12-28-37-104](https://user-images.githubusercontent.com/15632220/32367251-919c1daa-c092-11e7-9537-60991f06c964.png)
But if I add it in DashboardMenuItem, it doesn't work;
```
        <DashboardMenuItem 
          style={styles.button}
          onClick={()=>{this.handlerCLickResource('Dashboard')}} 
        />
```
Maybe the reason is that in [admin-on-rest/src/mui/layout/MenuItemLink.js](url) you pass properties (line 24,  27)
And in [admin-on-rest/src/mui/layout/DashboardMenuItem.js](url) you don't do it.

**Comment by fzaninotto** [comment]
You can already pass custom style to the `DashboardMenuItem` component in the `next` branch. In addition, We'll implement a custom style for the current menu natively in the `next` version (see #1487).
