### ISSUE TITLE
Store language in localStorage to support hard refresh

### ISSUE THREAD

**Issue by zifnab87** [marmelab/admin-on-rest#1205]
## Problem

Language is reset when the whole application is refreshed with F5 / Shift+F5 / Refresh button of browser

## Solution

language configuration needs to be stored in the localStorage so when someone hits refresh in the browser it won't lose the selected translation

It can be seen at https://marmelab.com/admin-on-rest-demo/#/

**Environment**
* Admin-on-rest version: 1.3.2

**Comment by fzaninotto** [comment]
We don't store the language. What prevents you from doing it in userland?

**Comment by zifnab87** [comment]
since aor provides changeLocal doesn't it make sense to also store it in localStorage? What is the point of revisiting an app after a while and see that your language is reset?

**Comment by fzaninotto** [comment]
It's the job of the `i18nProvider` (in the `next` version). You'll still have to do it in userland, but it should be straightforward. 

Closing as we won't implement it in core.
