### ISSUE TITLE
[RFC] Separate "source" and "name" for input?

### ISSUE THREAD

**Issue by marcw** [marmelab/admin-on-rest#1206]
I currently have a pretty big compatibility problem with AOR and my API. I am not sure how to fix this problem without touching to the core. I am willing to contribute but I'd like to get your opinion on the solution first. If this is not the right place to discuss this, please close this issue. 

My API (which is powered by api-platform/core) sends documents like this: 

```
{
  '@id': '/api/my_resource/123,
  'Name: 'Foobar',
  'association': {
     '@id': '/api/my_other_resource/456',
     'title': 'my-other-resource-456',
  } 
}
```

I configure an Edit page for `my_resource` like this:

```
<Edit>
<SimpleForm>
<ReferenceInput
    source="association.@id"
    reference="my_other_resource"
    allowEmpty
>
    <SelectInput optionValue="@id" optionText="title" />
</ReferenceInput>
</SimpleForm>
</Edit>
```

As the API returns embedded objects instead of ID relations, I have to put `source="association.@id"` for AOR to fill the `SelectInput` with the current value. If I don't do it, the Select doesn't get populated with the current value.

When I choose a different association with the Select field, and that I submit the form, the submitted data obviously looks like this:

```
{
  '@id': '/api/my_resource/123,
  'Name: 'Foobar',
  'association': {
     '@id': '/api/my_other_resource/789',
     'title': 'my-other-resource-456'
  } 
}
```

When the API received this payload, it interprets it as:
- Change `association` to point to MyOtherResource#789
- Set the title of MyOtherResource#789 to 'my-other-resource-456'

Which is of course, something I do not want. 

I basically need AOR to send this data: 

```
{
  '@id': '/api/my_resource/123,
  'Name: 'Foobar',
  'association': '/api/my_other_resource/789',
}
```

But right now it doesn't seem to be doable as the "name" of the input field is equal to the "source" value. I am not sure what is the correct solution here. Should I create a custom ReferenceInput for my own sake that handle this case? Should we add to the core an optional props `inputName` that takes precedence to `source` if it is defined? What do you think?

**Comment by fzaninotto** [comment]
If I understand correctly, the `my_other_resource` id is never exposed outside of the association? Your API can't expose something like:

```
{
  '@id': '/api/my_resource/123,
  'Name: 'Foobar',
  'association@id': '/api/my_other_resource/789',
}
```

If that's the case, I see 2 options:

1. Change your `restClient` to flatten the response from API platform
2. Write a custom input for that case.

I'm -1 for adding more configuration in the inputs. Mapping to the API is the `restClient`'s responsibility.

I'm closing this as it's an RFC (and I try to keep the number of open issues down), but I'm interested in reading other opinions on this one.

**Comment by marcw** [comment]
I think you are right with your solution 1. I'll try. Thanks François!
