### ISSUE TITLE
Docs missing details on OData client for Admin on Rest

### ISSUE THREAD

**Issue by rvramesh** [marmelab/admin-on-rest#1209]
**What you were expecting:**
I was looking for how to use OData with Admin on Rest

**What happened instead:**
The [documentation](https://github.com/marmelab/admin-on-rest/blob/master/docs/RestClients.md) mentions OData is supported by Admin On Rest. 

But unable to find details on whether the default Rest client itself supports OData or we need a custom rest client or if there is already OData Rest Client Available.

Search for OData in repo also returns only the documentation link

I did not create a SO question as I believe this comes under documentation issues. Please let me know if any additional information is required.

**Comment by fzaninotto** [comment]
Any authentication is possible, because aor exposes an API you can just plug in to. But it's your job to match aor's API with your auth provider.

**Comment by rvramesh** [comment]
OData is not authentication but data transfer standard. As per the documentation my understanding is that it supports out of box. But I did not find any. So please update the doc mentioning it needs custom rest client implementation

**Comment by PtwHub** [comment]
Hi Francois, any update on this OData standard rest data provider aspect for AOR (not OAuth)? Thanks!

**Comment by fzaninotto** [comment]
My bad, OData is a REST standard, not an authentication standard. 

But that doesn't change my answer: it's your job to write an adapter to an OData API. Admin-on-rest won't implement it in core.
