### ISSUE TITLE
GET_ONE Response Information Not Being Used

### ISSUE THREAD

**Issue by malisbad** [marmelab/admin-on-rest#1212]
**What you were expecting:**
When going to an individual record via a list, the `GET_ONE` response's data is used to update the state of the record, and all data in this record is available.

**What happened instead:**
The data was not available. Specifying the expected `source` attribute on a component did not throw errors. Examining the record that was being provided to the components, any additional information that had keys not matching keys from the `GET_LIST` response were missing.

**Steps to reproduce:**
Have a resource that returns additional information for a specific record (`GET_ONE`) against what is returned for a list of records (`GET_LIST`).

**Related code:**
Data that isn't available to the state in the `GET_LIST` call are not available despite being part of the `GET_ONE` call. E.g. If your `GET_LIST` returns:
```javascript
{
  "id": "someUser"
}
```

but `GET_ONE` returns:
```javascript
{
  "id": "someUser",
  "roles": {
    "someRole": true
  }
}
```

The roles key and contained object will not be available to the various field components. The record that is passed to child components will be:
```javascript
{
  "id": "someUser"
}
```

**Other information:**

**Environment**

* Admin-on-rest version: 1.2.1
* Last version that did not exhibit the issue (if applicable):
* React version: 16
* Browser: Chrome 61.0.3163.100 (stable)
* Stack trace (in case of a JS error):

**Comment by malisbad** [comment]
An additional issue that may be caused by the `GET_ONE` issue is that accessing a resource directly without visiting the list (e.g. sharing a `<baseUrl>/<resource>/<resourceId>/show` link with someone who is logged in, and authorized, will yield an empty and broken view.

**Comment by malisbad** [comment]
After examining this further, there was a bug in my code where the ID was malformed and a key was being added to the store under the resource as undefined.

**Comment by filipsuk** [comment]
I had the same issue. Turned out by backend was returning different resource id than expected. Thanks for pointing that out.
