### ISSUE TITLE
Customize List and other component

### ISSUE THREAD

**Issue by mivion** [marmelab/admin-on-rest#122]
Hi,

Thanks for your work!
Is there any way to customize styles in List component?
Or any way to customize styles for admin-on-rest components?

**Comment by djhi** [comment]
Does this help ? https://github.com/marmelab/admin-on-rest/pull/120

**Comment by mivion** [comment]
Look good.
Is there style for List component?
Also, how to add/change features in List, like add totals or change pagination?

**Comment by djhi** [comment]
You'll have to build your own List component

**Comment by mivion** [comment]
Is there are guide or example?

**Comment by djhi** [comment]
https://github.com/marmelab/admin-on-rest/blob/master/src/mui/list/List.js ?

**Comment by mivion** [comment]
I'v tried this way, but how to import internal modules like ../../reducer/resource/list/queryReducer?
Also there are some other problems related to internal dependencies of admin-on-rest.

**Comment by mivion** [comment]
For example: may I create new MyList component extends from List, and customize render or other fuaters?

**Comment by fzaninotto** [comment]
Since you'll be the first to do it, you'll be the ost qualified to write a tutorial for it 😉 

As for internal modules, if they are not exposed in the various `index.js`, don't hesitate to ask for them, we'll expose them. `queryReducer` was jut exposed in 7cfab94.

**Comment by mivion** [comment]
Hi,
first of all I'll try to write one custom component, after that make an example.
Then tutorial, with your help.

**Comment by mivion** [comment]
Sorry, I've tried, but without result.
Also, this feature does't need any more, as custom style arrives in new version.
