### ISSUE TITLE
When redirect in custom toolbar - all EditButtons have bad pathways

### ISSUE THREAD

**Issue by AlexandrKnyazev1395** [marmelab/admin-on-rest#1220]
I am located in `<Edit />` component where I have `<ReferenceManyField>` with `<Datagrid />`:
```
                  <ReferenceManyField label="Extension" reference="ext" target="user_id">
                    <Datagrid>
                      <TextField source="exten" />
                      <BooleanField source="authorized_only" />
                      <EditButton />
                    </Datagrid>
                  </ReferenceManyField>
```
![545](https://user-images.githubusercontent.com/15632220/32783341-6e08fe8a-c95c-11e7-9039-98af0a371f53.png)

When we go to console we see link and see that all good, it is correct link.
![3333](https://user-images.githubusercontent.com/15632220/32783180-e441a512-c95b-11e7-9413-885db17dda7c.png)
OK, I go to `<Edit>` form of ext/90, where I set up custom tollbar:
```
const EditToolbar = props => {
      const { from } = this.state;
      const redirect = from ? `/user/${user_id}` : 'list';
      return (
        <Toolbar {...props}>
          <SaveButton
            label="Save Voicemail"
            redirect={redirect}
          />
        </Toolbar>
      )
    }
```
![image](https://user-images.githubusercontent.com/15632220/32783429-bdf85f8a-c95c-11e7-8897-d33374123de2.png)

This redirect works, we areback to form `<Edit>` where we located in beginning. But now all links in Datagrids of `<Edit>` component lose their pathways. 
As you see now the same link have correct id, but there must be "ext" table, not user.
![2017-11-14 16-59-19](https://user-images.githubusercontent.com/15632220/32783674-9d973684-c95d-11e7-806f-f3ed9e6a89a1.png)

![2017-11-14 17-02-01](https://user-images.githubusercontent.com/15632220/32783654-8cde1038-c95d-11e7-8ab9-f972f7ea24b1.png)

And I can tell it about all datagrids in my Edit component.

**Comment by djhi** [comment]
If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

* CodeSandbox (https://codesandbox.io/s/ElxGNxBY0)
* A sample application via GitHub

**Comment by AlexandrKnyazev1395** [comment]
@djhi Sorry, but I think I can't.
If my example isn't clearly, I just want to ask you add in documentation something about redirect to routes. Now I gound only examples where redirect = "show" and {false}.

**Comment by AlexandrKnyazev1395** [comment]
@djhi Sotty, but it's look like this mistake is only in my project. So, you can close this issue

**Comment by djhi** [comment]
No problem. I'm glad you found a solution!
