### ISSUE TITLE
Can't redirect to the same route with custom redirect toolbar

### ISSUE THREAD

**Issue by remi13131** [marmelab/admin-on-rest#1221]
**What you were expecting:**

Using custom redirect toolbar, we should be able to redirect to the same route.  

This is particularly useful for multiple creation of the same resources : you create, say, a new user, hit the button "save and create again", then you have a new user creation page with empty fields ready to fill again. 

**What happened instead:**

Instead the resource gets saved but the redirection doesn't work. 

**Steps to reproduce:**

Fork aor-blog-example, add a custom tootlbar with ```redirect="create"``` to the Create view of Posts resource, then create a new post with button "Save then create" again. 

**Related code:**

[https://codesandbox.io/s/8zxqyw5k70](https://codesandbox.io/s/8zxqyw5k70)

**Environment**

* Admin-on-rest version: 1.3.2 (in my project, but in the codesandbox 1.2.1)

* Last version that did not exhibit the issue (if applicable): 

   I thought this was working in earlier version of AOR when this feature was first implemented, [but the feature was in 1.2.0 millestone](https://github.com/marmelab/admin-on-rest/pull/692) and codesandbox uses 1.2.1 so I guess it was there at the beginning already. 

* Stack trace (in case of a JS error):

```
Warning: Hash history cannot PUSH the same path; a new entry will not be added to the history stack  proxyConsole.js:68:15
	qo/console[e] proxyConsole.js:68:15
	Ee/console[e] index.js:25:4
	warning https://8zxqyw5k70.codesandbox.io/node_modules/warning/browser.js:49:9
	push/< https://8zxqyw5k70.codesandbox.io/node_modules/history/createHashHistory.js:213:10
	confirmTransitionTo https://8zxqyw5k70.codesandbox.io/node_modules/history/createTransitionManager.js:44:7
	push https://8zxqyw5k70.codesandbox.io/node_modules/history/createHashHistory.js:191:5
	routerMiddleware/</</< https://8zxqyw5k70.codesandbox.io/node_modules/react-router-redux/middleware.js:25:9
	sagaMiddleware/</< https://8zxqyw5k70.codesandbox.io/node_modules/redux-saga/lib/internal/middleware.js:72:22
	dispatch https://8zxqyw5k70.codesandbox.io/node_modules/redux/lib/applyMiddleware.js:45:18
	wrapSagaDispatch/< https://8zxqyw5k70.codesandbox.io/node_modules/redux-saga/lib/internal/utils.js:265:12
	runPutEffect/< https://8zxqyw5k70.codesandbox.io/node_modules/redux-saga/lib/internal/proc.js:490:19
	exec https://8zxqyw5k70.codesandbox.io/node_modules/redux-saga/lib/internal/scheduler.js:25:5
	flush https://8zxqyw5k70.codesandbox.io/node_modules/redux-saga/lib/internal/scheduler.js:66:5
	asap https://8zxqyw5k70.codesandbox.io/node_modules/redux-saga/lib/internal/scheduler.js:39:5
	runPutEffect https://8zxqyw5k70.codesandbox.io/node_modules/redux-saga/lib/internal/proc.js:487:6
	runEffect https://8zxqyw5k70.codesandbox.io/node_modules/redux-saga/lib/internal/proc.js:436:184
	next https://8zxqyw5k70.codesandbox.io/node_modules/redux-saga/lib/internal/proc.js:317:9
	currCb https://8zxqyw5k70.codesandbox.io/node_modules/redux-saga/lib/internal/proc.js:389:7
```

**Comment by fzaninotto** [comment]
How about using `redirect={false}`, as [explained in the documentation](https://marmelab.com/admin-on-rest/CreateEdit.html#redirection-after-submission)?

**Comment by remi13131** [comment]
Oh... absolutely ! My bad, sorry for this...
