### ISSUE TITLE
Autocomplete in ReferenceInput doesn't reset after saving with redirect=false

### ISSUE THREAD

**Issue by MadalenaGoncalves** [marmelab/admin-on-rest#1222]
**What you were expecting:**
When saving with `redirect={false}`, AutocompleteInput inside a ReferenceInput value is cleared.

**What happened instead:**
AutoCompleteInput maintained the previously entered value (although on saving that input is empty)

**Steps to reproduce:**
Create a custom toolbar with a SaveButton with redirect=false
Apply the toolbar to a SimpleForm with an AutocompleteInput inside a ReferenceInput
On the first render of the SImpleForm, AutocompleteInput is empty
Select a value and Save
The AutocompleteInput has the previous value

**Related code:**
Here is my custom toolbar where a "Save and Add" button saves without redirecting
```
<Toolbar {...props}>
    <SaveButton label="Save" redirect="list" />
    <SaveButton label="Save and Add" redirect={false} submitOnEnter={false} />}
</Toolbar>
```

And the Create component with the AutocompleteInput
```
<Create {...props}>
  <SimpleForm toolbar={<CustomToolbar />} redirect="list">
    <ReferenceInput label="User" source="user_id" reference="users" allowEmpty>
      <AutocompleteInput optionText={(v) => `${v.firstname} ${v.lastname}`} />
    </ReferenceInput>
  </SimpleForm>
</Create>
```

**Environment**

* Admin-on-rest version: 1.3.1
* React version: 15
* Browser: tested in Chrome, Firefox and Safari

**Comment by djhi** [comment]
Can't reproduce anymore on `1.3.4`. Feel free to reopen if needed
