### ISSUE TITLE
Thoughts on migrating from Material UI to something based on material-components-web?

### ISSUE THREAD

**Issue by drbago** [marmelab/admin-on-rest#1223]
First of all, thanks to everyone for the work and passion that has gone into what is currently a beautiful and powerful framework.

[material-components-web](https://github.com/material-components/material-components-web) is a set of React components, developed by Google, to replace [MDL](https://github.com/google/material-design-lite) -- essentially Google's reference implementation of Material Design.

Currently, AOR is based on [Material UI](https://github.com/callemall/material-ui) -- which is [approaching v1](https://material-ui-next.com/).  [Migration of AOR to material-ui v1](https://github.com/marmelab/admin-on-rest/tree/material-ui-1) is already underway.

Internally, [Material UI has considered integrating material-components-web](https://github.com/callemall/material-ui/issues/6799), but it seems to be a plan for the distant future.  [React-MDL](https://github.com/react-mdl/react-mdl), a competing set of components, already has a port called https://github.com/react-material/react-material.  Even more alternative sets of components libraries are also emerging:
* https://github.com/kradio3/react-mdc-web
* https://reactmaterial.com/
* https://github.com/react-material-design

To me, the most obvious and compelling draw of using material-components-web is the prospect of synergy with the Google community.  Material UI has put this off in favor of their specific vision.  So, in AOR's current direction with Material UI, we forego those direct benefits.  

However, it is possible that Material UI has different goals in mind than are pertinent to admin-on-rest.  I am considering doing some experiments with AOR and material-components-web to explore the contrast.

Is there existing research or discussion on this?

**Comment by fzaninotto** [comment]
We've been doing some research a year and a half ago, when aor was just an idea, and material-ui was a clear winner at that time (API coverage, documentation, quality, support). We've done it again a couple months ago, when we considered the migration to material-ui 1.0, and once again, I saw no serious competitor. The three sites you linked to are at their infancy when compared to material-ui. 

So we made the decision to migrate to material-ui for the next major release. The migration is 90% done. We won't consider a new change in material-design framework for a long time now - at least a couple years.

**Comment by dandv** [comment]
While the alternative React MDC libraries proposed in the OP were in their infancy (and haven't made much progress since), the MDC readme lists two libraries that are near the 400 GitHub stars mark:

* [Preact Material Components](https://github.com/jamesmfriedman/rmwc)
* [RMWC: React Material Web Components](https://github.com/jamesmfriedman/rmwc)

**Comment by fzaninotto** [comment]
Using another UI kit will be greatly facilitated in admin-on-rest 2.0 / react-admin.

**Comment by ItsLeeOwen** [comment]
Google's react material-design lib is coming along.  https://github.com/material-components/material-components-web-react
