### ISSUE TITLE
Show view

### ISSUE THREAD

**Issue by yoonwaiyan** [marmelab/admin-on-rest#123]
Hi there, I wonder is there any way I can add or customize a "view" page of a resource? View/show page is a common feature in other admin plugins from other frameworks of other languages.

Currently we can see the records in a list but sometimes we want to view some details or even an array of has-many relationships for that particular record without editing the record, hope that I don't need to embed the list inside the edit page or override many source code here just to make a view page work.

Thanks in advance. I like this interface.

**Comment by fzaninotto** [comment]
In fact, you can (almost) do it already. Just use `<Field>` components inside the `<Edit>` view. It'll work, but you'll still have a save button.

We need to make it possible, so I'm tagging that as feature request.

**Comment by pimschaaf** [comment]
I've been trying to use the <Show> view as per example but run into warnings when I include more than one `<TextField>` in the `<Show>` component:

>Warning: Failed prop type: Invalid prop `children` of type `array` supplied to `Show`, expected a single ReactElement.

_App.js_
```javascript
    import React from 'react';
    import { jsonServerRestClient, Admin, Resource } from 'admin-on-rest';
    import { Delete } from 'admin-on-rest/lib/mui';
    import { TaxationList, TaxationCreate, TaxationShow, TaxationEdit } from './views/Taxations';

    const App = () => (
    <Admin dashboard={Dashboard} menu={Menu} messages={messages} restClient={jsonServerRestClient('http://localhost:3004')}>
        <Resource name="taxations" list={TaxationList} create={TaxationCreate} edit={TaxationEdit} show={TaxationShow} remove={Delete}/>
    </Admin>
    );

    export default App;
```

_Taxations.js_
```javascript
export const TaxationShow = (props) => (
  <Show {...props}>
      <TextField source="id" />
      <TextField source="details" />
  </Show>
);
```

When I only include a singular `<TextField source="id" />` in `<Show>` the ID is shown, but the field styling is not as I would expect.

![Image of Show with ID Textfield only](http://i.imgur.com/5Tu0Lsc.png)

I'm new to admin-on-rest, so I might be making a rookie mistake. Let me know if I can provide more relevant information.

Thanks

**Comment by fzaninotto** [comment]
You didn't look at [the example](https://github.com/marmelab/admin-on-rest/blob/fcfbfce3422d61ef833bd146cc4c08bdc1a2db9d/example/posts.js#L158-L181) carefully enough: `<Show>` expects only one child, which is a layout component.

**Comment by pimschaaf** [comment]
@fzaninotto Thanks! Indeed I missed that. I stumbled on the `<Show>` component through the [Reference](https://github.com/marmelab/admin-on-rest/blob/master/docs/Reference.md), working from the assumption that `<Show>` would work like `<Edit>`, then missed the details in the commit referenced here.

I suppose the Reference could use a PR with more details about the implementation of `<Show>`?

**Comment by fzaninotto** [comment]
Great idea!
