### ISSUE TITLE
Allow to override List Header Style 

### ISSUE THREAD

**Issue by malisbad** [marmelab/admin-on-rest#1230]
**What you were expecting:**
The ability to customize the `List` component's header style by passing in styles.

**What happened instead:**
Unable to customize the `List` header by setting the `styles` prop. Writing it in to a custom mui theme doesn't work either.

If you edit the `List` component directly in `List.js`, there is a `styles` object declared after the imports. If you add a `backgroundColor: '#000000'` here under the `header` value in the object, the background color of the header changes.

**Steps to reproduce:**
1. Add style/styles prop to the `List` component with the key `header`, and the key/value `backgroundColor: '#000000'`. The `List` component's header should go black.
```
styles={{
  header: {
    backgroundColor: '#000000'
  }
}}
```
2. Reload

**Other information:**
This is an improvement request. "should" means "I would like"

**Environment**

* Admin-on-rest version: 1.3.2
* React version: 16
* Browser: Chrome 62

**Comment by fzaninotto** [comment]
Fixed by #1268
