### ISSUE TITLE
Be able to redirect to a proper path after deleting

### ISSUE THREAD

**Issue by rgazelot** [marmelab/admin-on-rest#1237]
I have a `Member` resource which is basically a member of a `Team` resource. I included the list of `Member` into my `Team` show component and I'm able to delete one of them in the `Datagrid`. I want to come back to the `Team` show page after the deletion of a member, but the default behavior is to redirect to the resource's list view as specified [here](https://github.com/marmelab/admin-on-rest/blob/master/src/actions/dataActions.js#L78). I don't have any list for this resource and I don't want to have one.

In the `<Delete/>` component, I'm not able to redirect to another path after the deletion as the `crudDelete()`function  is called without taking care of any `redirectTo` props ([see the call](https://github.com/marmelab/admin-on-rest/blob/master/src/mui/delete/Delete.js#L61))

What about be able to give to the component a prop `redirectTo` to handle this case?

**Comment by rgazelot** [comment]
Could I have some feedbacks on this issue to be able to propose a PR? Thanks guys.

**Comment by rgazelot** [comment]
Hi guys, any feedback here?

**Comment by fzaninotto** [comment]
Fixed by #1087
