### ISSUE TITLE
Project name

### ISSUE THREAD

**Issue by tkvw** [marmelab/admin-on-rest#1248]
I see in [package.json](https://github.com/marmelab/admin-on-rest/blob/89bc505fb884fdd518c06b4bd012a6141a8416c1/package.json#L3) of next that the name is changed back to `react-admin` . Is this going to be the official package release name? Or is going to be reversed to [`admin-on-rest`](https://github.com/marmelab/admin-on-rest/blob/89bc505fb884fdd518c06b4bd012a6141a8416c1/package.json#L3)?

**Comment by djhi** [comment]
Yes, it is going to be the official package name :)
