### ISSUE TITLE
ReferenceInput to resource currently editing

### ISSUE THREAD

**Issue by vantox** [marmelab/admin-on-rest#1249]
Im doing category manager in aor. One field is parent category. I created edit view with referenceinput and selectinput referencing to categories inside. GET LIST for categories returns list of objects with id and name only. GET ONE for categories returns some additional data. when i enter edit from list view everything is ok but after refresh GET LIST action on categories overrides my data from GET ONE request . in result i see only name field.

**What you were expecting:**
I was expecting for edit view to stay the same after refresh

**What happened instead:**
After refresh GET ONE is called which downloads my additional data for edit view and then GET LIST for referenceInput happens and overrides my data from GET ONE.

**Steps to reproduce:**
Create edit view for some resource and add one field referenceinput with select input, referencing to the same resource. make GET LIST return list of objects with for examlep id and name and GET ONE returning id name and extraValue.
when edit accessed from list view extravalue will be filled after refresh it will be gone (from store aswell)
**Related code:**

```
export const CategoriesEdit = (props) => {
  return (
    <Edit title={<CategoriesTitle />} {...props}>
      <SimpleForm toolbar={<EditToolbar />} >
        <ReferenceInput allowEmpty label="Parent category" source="parentId" reference="categories">
          <SelectInput optionText="name" />
        </ReferenceInput>
      </SimpleForm>
    </Edit>
  );
};
```

**Environment**

* Admin-on-rest version: 1.2.2
* React version:15.6.1
* Browser: chrome

**Comment by fzaninotto** [comment]
I think you're looking for `aor-dependent-input`: https://github.com/marmelab/aor-dependent-input

Feel free to reopen if this doesn't solve your issue.
