### ISSUE TITLE
[Question] Roadmap to React Admin 2.0

### ISSUE THREAD

**Issue by marcw** [marmelab/admin-on-rest#1253]
It would be very nice to have a roadmap to share for the upcoming 2.0 release. I noticed for example that `SelectArrayInput` need to be rebuilt. 

What is the roadmap to 2.0? What need to be done and how can I help you with this?

**Comment by fzaninotto** [comment]
We're almost there. We want to add support for `className` in every component, to make styling with JSS more powerful. We'll skim through the enhancement requests that require a BC break, and work on the most useful ones. We'll iron out the documentation and the upgrade guide. We probably won't port `SelectArrayInput` as it relied on a dependency which is not updated, but you're welcome to help us on this one. 

My team will dedicate some time on the 2.0 in the next couple weeks, and I expect a release before Christmas.

**Comment by marcw** [comment]
Thanks for this update François. I am excited for the 2.0 release.

I guess you are talking about `material-ui-chip-input`. The people behind are working on updating for MUI 1.0 (see https://github.com/TeamWertarbyte/material-ui-chip-input/issues/88). I fear it might not fit the RA release schedule though. I understand that you want to ship, and not be dependent of an outdated dependency but IMHO it would be weird to drop `SelectArrayInput` from the core. I'll look into it.

**Comment by afilp** [comment]
Can we now use v2.0.0-beta1 that is released?! Will it be published to NPM?

Thanks!

**Comment by fzaninotto** [comment]
Yes! And it is published on npm (with the next tag)

**Comment by mattaylor** [comment]
Please verify this. 

Both `npm install react-admin@next` and npm install admin-on-rest@next`  fail due to missing version identifies in package.json

**Comment by fzaninotto** [comment]
I can't reproduce your issue. What's your node/npm version? what's the error message?

**Comment by nik-lampe** [comment]
Same for me.

Trying to run npm install admin-on-rest@next to get the v2.0.0-beta1, but doesn't work.
Error message is:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for admin-on-rest@next
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

Node version is 9.4.0
npm version is 5.6.0

**Comment by djhi** [comment]
`admin-on-rest` has been renamed `react-admin` for `2.0`

**Comment by djhi** [comment]
You can try `npm install react-admin@2.0.0-beta1`
