### ISSUE TITLE
[Question]- I want to create a dynamic column in <Datagrid>

### ISSUE THREAD

**Issue by whoait** [marmelab/admin-on-rest#1254]
I want to create a dynamic column in <Datagrid> based on the columm returned number of the api, it looks like <Datagrid> does not support this.

If yes please give me an example

**Comment by fzaninotto** [comment]
No, this is not supported by the `<Datagrid>` commponent, you'll have to write your own grid component for that. the `<List>` component will inject the `data` props, it's up to you to display it as you see fit.

**Comment by whoait** [comment]
Thank you for your support, i hope it will have a next version
