### ISSUE TITLE
SelectArrayInput does not work with react >= 16

### ISSUE THREAD

**Issue by NikitaVlaznev** [marmelab/admin-on-rest#1255]
Values does not appear inside the component after selecting them in the dropdown menu, they are expected to appear.

Can be reproduced by running admin-on-rest-demo with this dependencies:

        "react": "^16.2.0",
        "react-dom": "^16.2.0",
        "react-router-dom": "^4.2.2",
        "react-tap-event-plugin": "^3.0.2",

May be it is because admin-on-rest depends on material-ui-chip-input@~0.17.2, which does not support react 16, it's latest version is 0.18.3.

It seems that the onBlur event handler receives an empty array as the 'event' argument when called by ChipInput.
Redux state log shows that the selected value is added to the array after CHANGE event but removed after BLUR event.

**Environment**
Admin-on-rest version 1.3.2
React 16 or 16.2
Google Chrome 58.0.
Ubuntu 16.04

**Comment by eghernqvist** [comment]
Related > #1139

**Comment by larasulfo** [comment]
Is there any workaround solution?

**Comment by larasulfo** [comment]
as a workaround solution, you can add this  clearOnBlur={false} 
for example:
            <SelectArrayInput source="source" choices={choices} optionText="name" optionValue="id" clearOnBlur={false} />

**Comment by samhiddenhand** [comment]
@larasulfo does that workaround actually work for you? It doesn't for me.

**Comment by larasulfo** [comment]
@samhiddenhand You're right, It was working, but after some implementations, It didn't work. I'm deleting my comments to not confuse anyone. I should find out, how this is working  :)
<img width="1018" alt="screen shot 2017-12-14 at 13 32 13" src="https://user-images.githubusercontent.com/11397468/33988980-066f6286-e0d7-11e7-9243-7d9e8b615b74.png">

**Comment by bevinhex** [comment]
Same here, somehow stop working after I updated to latest weeks ago
