### ISSUE TITLE
Is the documentation on custom rest client understandable?

### ISSUE THREAD

**Issue by te-online** [marmelab/admin-on-rest#1256]
**What you were expecting:**

A short, yet comprehensible documentation on how to create a custom rest client for admin on rest.

**What happened instead:**

The documentation states that it's very easy, but I didn't find it very easy. Maybe this is my fault, but maybe also the documentation could be improved.

**Steps to reproduce:**

Imagine you're new to admin-on-rest. Try to understand how to create a custom rest client from this guide https://github.com/marmelab/admin-on-rest/blob/master/docs/RestClients.md#writing-your-own-rest-client.

----

It feels like the documentation was written to be friendly and helpful. But after using it extensively, I have to say that it sometimes says something is simple, when it's instead rather difficult and this makes me feel stupid (see also http://bradfrost.com/blog/post/just/).

Take for example this statement in the docs for creating a custom rest client:
> But don't be afraid, it's easy!

Personally, I didn't find it easy at all.

My proposal is therefore to add the following to the documentation of custom rest clients:
* Add that you need to adjust the imports when copying from the original simple rest client as stated here https://stackoverflow.com/questions/44745113/creating-a-custom-rest-client-admin-on-rest.
* Add that you need to update this file every time admin-on-rest is updated and the simple rest client might get any optimizations.
* Add context to the snippets under the respective “Examples:” paragraphs.
* Rephrase “But don't be afraid, it's easy!” to “Follow the guide below to create a custom rest client”.

I'm sorry in case I can't articulate well enough what I mean, but there are a few more places where I had this feeling when reading the docs (e.g. https://github.com/marmelab/admin-on-rest/blob/master/docs/Fields.md#writing-your-own-field-component). Writing this, I hope you understand it as constructive feedback. :-)

**Comment by Phocea** [comment]
Myself and my team followed the documentation and also looked at the several existing examples and plugins. We had zero problems. 

You should raise a PR with the documentation update you suggested, it would be faster than listing it here :)

**Comment by djhi** [comment]
I agree with Thomas, we should not assume anything is easy in the documentation. I'll work on it asap

**Comment by djhi** [comment]
But as @Phocea said, a PR will be welcome :)

**Comment by te-online** [comment]
> I agree with Thomas, we should not assume anything is easy in the documentation. I'll work on it asap

Thank you so much, for considering this :-)

> We had zero problems.

Okay, maybe I **am** indeed stupid 😅 (Or you guys are just very good at what you do.) 😉

Here we have the pull request https://github.com/marmelab/admin-on-rest/pull/1264, you asked for. Please, go ahead and rip it apart... 🤓

**Comment by ariveralee** [comment]
Speaking from experience as someone who just started using AOR, The documentation is very different from the example that is referenced in it for creating a custom rest client. This led to confusion and frustration :(

**Comment by te-online** [comment]
@ariveralee Can you eloborate on that? Is it about the request/response examples that are not implemented like depicted there in the simple rest client? I didn't check them all, because I just copied from simple rest client.

**Comment by fzaninotto** [comment]
Rewrote the doc in #1311. Hope that makes the experience smoother.

**Comment by te-online** [comment]
@fzaninotto Looks good to me, seems to include full examples and neutral language. One question: So, Rest client will be renamed to Data Provider?

**Comment by djhi** [comment]
Yes because you're not limited to REST
