### ISSUE TITLE
ImageInput doesnt works for uploading

### ISSUE THREAD

**Issue by jagrawat** [marmelab/admin-on-rest#1262]
i am trying to achieve Image Upload using <ImageInput/> 
First Image will be stored to data storage backend is working file.
while comes to storing file from front facing the issue.

**Comment by jpetitcolas** [comment]
It looks more like a support request (how to store an uploaded file on my backend) rather than a technical issue with admin-on-rest. I suggest you open it on [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest). Moreover, your issue misses details to respond it properly. :)
