### ISSUE TITLE
Upgrading to material ui v1

### ISSUE THREAD

**Issue by mehrdaad** [marmelab/admin-on-rest#1267]
I explored the repo, apparently there isn't any pr for the next version of material ui but found 2 branches named ``next`` and ``material-ui-1``.  
Which one to use to aim material ui 1?  
Is it production ready?  
Any related info please?  
Thank you for your efforts and time. Sincerely appreciate it.

**Comment by djhi** [comment]
It's happening in `next`. The `material-ui-1` branch is probably one that was tight to a PR and not removed once merged into `next`. Please note that we are still working on it.

**Comment by mehrdaad** [comment]
Thank you

**Comment by afilp** [comment]
@djhi I see that v2.0.0-beta1 is just released. "BETA" means that features are frozen and only bugs are fixed. May we assume that you can make "next" public through NPM and start using it immediately?

Also, is "aor-loopback" compatible with this v2.0.0?

Thanks!

**Comment by fzaninotto** [comment]
Yes, this version is both public and released to npm. As for aor-loopback, it should still be compatible as we didn’t change the REST client API.

**Comment by afilp** [comment]
@fzaninotto I most likely miss something, but I cannot find the v2.0.0.beta1 version in NPM for "admin-on-rest":

https://www.npmjs.com/~fzaninotto

Could you please advice? Thanks!

**Comment by tkvw** [comment]
Admin-on-rest is changed to `react-admin`. 
https://unpkg.com/react-admin@2.0.0-beta1/

**Comment by afilp** [comment]
@tkvw @fzaninotto Thanks, the public npm package is still very old though, so how can we use it now?

https://www.npmjs.com/package/react-admin

**Comment by fzaninotto** [comment]
try `npm install react-admin@next`

**Comment by afilp** [comment]
@fzaninotto I did this, then replaced all imports from "admin-on-rest" to "react-admin". I do not know if anything else needs to be changed (is there a migration guide or is it too soon I assume?).

When I run it, I get the following "material-ui" error:

````
TypeError: Cannot read property 'prepareStyles' of undefined
Paper.render
E:/myproject/node_modules/material-ui/Paper/Paper.js:101
````

**Comment by fzaninotto** [comment]
Yes, there is a migration guide: [UPGRADE.md](https://github.com/marmelab/admin-on-rest/blob/next/UPGRADE.md).
