### ISSUE TITLE
Auth saga implementation question/discussion 

### ISSUE THREAD

**Issue by tkvw** [marmelab/admin-on-rest#1272]
I have a question about the auth saga. As it seems to me only the authClient is given an opportunity to clean up it's state when a `USER_CHECK` fails or `fetchError` occurs. 
https://github.com/marmelab/admin-on-rest/blob/07c313b7095323d5b6aace351c0721ada5cb124e/packages/react-admin/src/sideEffect/saga/auth.js#L57

So a USER_CHECK fails => the credentials in authClient are cleared and the user is presented the login screen (because of a redirect or because of the `<Restricted>` component), but the redux store data is still available! I think this is dangerous, because the user sees a login prompt while there could potentially be sensitive data available in the redux store. This can easily be fixed by issuing a redux action `RA/UNAUTHENTICATED` (I think it should be different from `RA/USER_LOGOUT`) and listen for it in `resettableAppReducer` . Maybe `RA/AUTHENTICATED` could be added as well. This can be used when a authentication is restored from authClient without login. 

It would also be very useful to have a reducer for authentication, something like `authenticated:<integer>`. The integer is 0 when not authenticated and is incremented (versioned) when the authentication status changes (login/ switchuser). This allows me to easily SCU on a custom menu which uses `<WithPermissions>` and the authentication status changes. 

What do you think?

**Comment by vbogd** [comment]
The auth saga issues a redux action USER_LOGIN_SUCCESS in case of successful authentication. May be it shoud issue a redux action USER_LOGOUT_SUCCESS after authClient with AUTH_LOGOUT payload is called? The redux store data could be cleared by dispatching this new USER_LOGOUT_SUCCESS action.

**Comment by tkvw** [comment]
Not entirely sure what's difference in your suggestion vs my suggestion? I think `RA/UNAUTHENTICATED` name is better than `USER_LOGOUT_SUCCESS`, because the latter suggests that a triggered logout was successful, but this is not the case when a user gets invalidated because of a USER_CHECK.  The `resettableAppReducer` is responsible for clearing the redux store, so this one needs to listen for the new action as well.

**Comment by vbogd** [comment]
I've got a slightly different use case. I need a saga that is run when a user logs in or logs out (is invalidated, actually). I my proposal I have to listen for USER_LOGIN_SUCCESS, USER_LOGOUT_SUCCESS actions. I your proposal I have to listen for USER_LOGIN_SUCCESS, RA/UNAUTHENTICATED.

**Comment by fzaninotto** [comment]
Already done in #676

**Comment by tkvw** [comment]
Nope, `AUTH_LOGOUT` !== `USER_LOGOUT`. So if a `USER_CHECK` fails, the user is presented with a login page, but the redux store is not reset.

**Comment by fzaninotto** [comment]
it is now, see #1306
