### ISSUE TITLE
Toolbar hovers over content on mobile

### ISSUE THREAD

**Issue by tkvw** [marmelab/admin-on-rest#1274]
I think this shouldn't be `fixed` but `static`.  The toolbar's width is 100%, position fixed and background white so it overflows the content on small screens. Or maybe there's some css trickery I am not aware of to fix this. 
https://github.com/marmelab/admin-on-rest/blob/9f4138a75ce23ffe17075abb50d5db4cb025d4e4/src/mui/form/Toolbar.js#L9

**Comment by djhi** [comment]
Can you show the problem with a screenshot ?

**Comment by tkvw** [comment]
Sure, you can see "Your message" disappear when switching between mobile/desktop.  
![2017-12-08_12-50-45](https://user-images.githubusercontent.com/621098/33764834-7cd45802-dc16-11e7-8738-ab0fe1e15250.gif)

**Comment by tkvw** [comment]
and https://github.com/marmelab/admin-on-rest/blob/9f4138a75ce23ffe17075abb50d5db4cb025d4e4/src/mui/form/Toolbar.js#L29
`noGutter` is replaced with `disableGutters` in material-next.

**Comment by fzaninotto** [comment]
Fixed by #1324
