### ISSUE TITLE
ReferenceArrayInput - filter is ignore when searching

### ISSUE THREAD

**Issue by congaductq** [marmelab/admin-on-rest#1276]
I'm using this ReferenceArrayInput to get list of group that have status = 1
```
<ReferenceArrayInput source="group_id" reference="group" label="Group" filter={{ status: 1 }} allowEmpty validate={required}>
    <SelectArrayInput optionText="label" />
</ReferenceArrayInput>
```
The returned array is correct when the TextField is empty.
But when I type a word on the TextField, the returned data is not filtered by status anymore.

**Comment by djhi** [comment]
If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

* CodeSandbox (https://codesandbox.io/s/ElxGNxBY0)
* A sample application via GitHub

**Comment by djhi** [comment]
Can't reproduce. Feel free to reopen if you can provide a codesandbox
