### ISSUE TITLE
devTools dispatcher go to reducer but not to saga

### ISSUE THREAD

**Issue by llioor** [marmelab/admin-on-rest#1279]
**What you were expecting:**
Dispatch action manually with devTools:
```
{
type: 'app/locales/GET_LOCALES'
}
```
I expect to see in the inspector 3 actions:
```
app/locales/GET_LOCALES
app/locales/GET_LOCALES_LOADING
app/locales/LOCALES_RECEIVED
```
**What happened instead:**
Action is caught by reducer but not by the custom saga.
When dispatching the action creator from `componentWillMount()` by `mapDispatchToProps` it works the issue is just with devTools!

** operations.js > Saga file **
```
import types from './types';
import actions from './actions';
import { all, call, put, takeEvery } from 'redux-saga/effects';
import axios from './../../utils/axios';

function* getLocalesSaga() {
  try {
    yield put(actions.loadingLocales());
    let locales;
    locales = yield call(fetchLocales);
    yield put(actions.localesReceived(locales.languages));
  } catch (error) {
    console.log('error:', error);
     yield put(actions.failedLocales(error));
  }
}

function* getProfileSaga() {
  ...
}

function fetchLocales() {
  return axios.get('locales')
      .then(function (response) {
        return response.data;
      })
      .catch(function (error) {
        console.log(error);
      });
}

function fetchProfile() {
  ...
}

export default function* localesSaga() {
  yield all([
    takeEvery('GET_PROFILE', getProfileSaga),
    takeEvery(types.GET_LOCALES, getLocalesSaga),
  ]);
}
```

** action.js > Actions creator file **
```
import types from "./types";

const getLocales = () => ({
  type: types.GET_LOCALES
});

const loadingLocales = () => ({
  type: types.GET_LOCALES_LOADING
});

const localesReceived = (locales) => ({
  type: types.LOCALES_RECEIVED,
  payload: locales,
});

const failedLocales = (error) => ({
  type: types.GET_LOCALES_FAILURE
});

export default {
  getLocales,
  loadingLocales,
  localesReceived,
  failedLocales,
};
```

** App.js file **
When I load the Admin component I add the custom saga as described in Docs `customSagas={ [localesSaga] }`

Again, it is working when I dispatch action via the mapDispatchToProps but not via the devTools.

**Other information:**
devTools version: 2.5.2

yarn list v0.27.5
└─ webpack@3.8.1

npm v 5.3.0

**Environment**
Windows 

* Admin-on-rest version:  "admin-on-rest": "^1.3.2",
* React version: "react": "^16.2.0",
* Browser: chrome

Thank you in advanced.

**Comment by djhi** [comment]
If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

* CodeSandbox (https://codesandbox.io/s/ElxGNxBY0)
* A sample application via GitHub

**Comment by llioor** [comment]
Hi @djhi , thank for your replay.

I created duplication of my project here: https://bitbucket.org/llioor/aor-test/src

I have 2 issues:
1. I'm manually dispatching the `app/locales/GET_LOCALES` action with the redux devTool but only the reducer get the action.
2. I have another issue if you don't mind to help.. 
As you can see I have `<Initialization/>` component in my dashboard  page.

2.A. First, I dispatch `getProfile()` action creator which will go to the `profielSaga()` and then will fetch the profile of the logged user. I'm using axios to fetch the data from my Laravel API. The issue is that in axios instance I'm using the token from the `localStorage` which I set after `AUTH_LOGIN` return a response (in my authClient file). The problem is that `getProfile()` is dispatching before the AUTH_LOGIN was completed and the Authorization header is empty on the first request. When I refresh the page the axios has the the correct token. Any advice please?

2.B. Second, I'd like to know where is the best place to add this component, right now just for the test I set in the Dashboard page, should I add it to a custom `menu` component because I want that the user will see the App locales all the time. https://marmelab.com/admin-on-rest/Admin.html#menu

Many thanks!!!
Leo.

**Comment by fzaninotto** [comment]
I think this is a bug either with the DevTools, or with Redux-saga. I advise you to make a smaller example, without admin-on-rest, to reproduce and locate the issue.

Closing this bug as it's not an admin-on-rest bug. Feel free to reopen if I'm wrong.
