### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by alexborisov** [marmelab/admin-on-rest#131]
Could we get a new release for npm?

Is it perhaps possible to setup some sort of continuous delivery for the release? Seeing as everything thats pushed to master is being treated as stable?

**Comment by fzaninotto** [comment]
Soon my friend, soon

In the meantime, use master.

**Comment by fzaninotto** [comment]
v0.5.0 is out!

**Comment by alexborisov** [comment]
and a push to npm? 😻  btw any chance you could update the README with a quick how-to on how to correctly build this project from source?

**Comment by fzaninotto** [comment]
Yes! use v0.5.1 on npm (I forgot to `make build` for v0.5.0).
