### ISSUE TITLE
Unexplainable rerenders in Menu

### ISSUE THREAD

**Issue by tkvw** [marmelab/admin-on-rest#1330]
Spend a couple of hours figuring this out, and finally saw your comment in the code. Did you find out why this is happening?  
https://github.com/marmelab/admin-on-rest/blob/3300939a0e53859846cb4d87d993539d10fddab6/packages/react-admin/src/mui/layout/Sidebar.js#L31
I think it's related to Drawer, but couldn't find the cause of this. If I wrapped my Menu with `recompose`'s `pure` HOC the rerender still happens (no state change), but if I change the Menu to `PureComponent` it finally stops the rerenders.

**Comment by fzaninotto** [comment]
No, I don't. Feel free to keep us posted if you discover the cause...
