### ISSUE TITLE
See "Props" or data

### ISSUE THREAD

**Issue by eyalabadi98** [marmelab/admin-on-rest#1331]
I want to know how to debug, and get the information coming from my server. In a way, I want to be able to do this.props and see all my props.

The issue is that its all stored somewhere and gets called or "seen" with source="..."

Thank you

**Comment by paulorsbrito** [comment]
I think you'll want to checkout redux store. The data comming from your server will hang there, and the rect componentes of your project are tied to them via redux' connect function. So, when the store changes, the components get rendered reflecting the new data.

Take a look at the redux plugin for your browser.
