### ISSUE TITLE
"setSidebarVisibility" is not resolved (Bug?)

### ISSUE THREAD

**Issue by afilp** [marmelab/admin-on-rest#1342]
Please do not submit support requests or "How to" questions here. For that, go to [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest).

In this line:
https://github.com/marmelab/admin-on-rest/blame/master/docs/Theming.md#L234

**What you were expecting:**

``setSidebarVisibility`` should be resolved

**What happened instead:**

``setSidebarVisibility`` is **not** resolved (seems to be missing from ``lib``, while it exists on ``src``)

* Admin-on-rest version:   1.3.3
* Last version that did not exhibit the issue (if applicable):
* React version: 16.2.0

**Comment by fzaninotto** [comment]
I can't reproduce the issue:

[![Edit export setSidebarVisibility works](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zqpkj4qy64)

Feel free to reopen if you have a reproducible test case.
