### ISSUE TITLE
[Q]: Usage of React.cloneElement

### ISSUE THREAD

**Issue by tkvw** [marmelab/admin-on-rest#1343]
I am curious why you're using `React.cloneElement` all over the place instead of render props?
For example: 
https://github.com/marmelab/admin-on-rest/blob/a0eda07ebe8527c0aad9ff3110141b0bb738da87/packages/react-admin/src/mui/layout/Responsive.js#L22

Why not use React.createElement: 
```
return React.createElement(component,rest)
```
The usage would be: 
```
<Responsive small={props=> <MyComponent {...props}/>}/>
```
or 
```
<Responsive small={MyComponent}/>
```

I think this is cheaper, because the components are initialized lazy.

**Comment by fzaninotto** [comment]
That's because we are cloning an element, not a component. 

https://reactjs.org/blog/2015/12/18/react-components-elements-and-instances.html

The variable isn't properly named, though, I'll fix that.
