### ISSUE TITLE
QUESTION: How can I allow members to access and edit profile page only?

### ISSUE THREAD

**Issue by kgish** [marmelab/admin-on-rest#1346]
I've created an admin dashboard for administrating members. As an admin I can login in do everything.

I need also to allow these members (regular users) to login, be redirected to their profile page and be able to edit a subset of their properties.

I've searched through the documentation but have been unable to figure how best to accomplish this.

Is there a standard way, and if there is how can do this?

**Comment by Kmaschta** [comment]
We don't provide support through GitHub issues. If you need advice on using or debugging your own project based on admin-on-rest, please use [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This said, you can take a look to the related documentation: [Restricting Access To Resources or Views](https://marmelab.com/admin-on-rest/Authorization.html#restricting-access-to-resources-or-views)

**Comment by kgish** [comment]
See: https://stackoverflow.com/questions/48080739/how-can-i-allow-members-to-access-and-edit-profile-page-only
