### ISSUE TITLE
change Datagrid style

### ISSUE THREAD

**Issue by mosasiru** [marmelab/admin-on-rest#136]
Can I change Datagrid (table) style?
or should I create a own component like Datagrid?
Each column seems a bit wide, I want to change the width.

**Comment by mstmustisnt** [comment]
and just wonder why header and body are two separate tables.. Very difficult to synchronize `td` with corresponding `th`

**Comment by fzaninotto** [comment]
#150 reduces column widths. As for changing datagrid style, the only way is to build your own datagrid component. Start by copying admin-on-rest's [`<Datagrid>`](https://github.com/marmelab/admin-on-rest/blob/f311a0c44dac6849c342639773b1390ea572802d/src/mui/list/Datagrid.js), and adjust it at will.
