### ISSUE TITLE
Redirect to correct page after Delete

### ISSUE THREAD

**Issue by rahul169sharma** [marmelab/admin-on-rest#1370]
I have a List with default pagination. Each entry in the List can be deleted using the Delete button. The Delete button is the admin-on-rest Delete. Clicking Delete button takes me to a new page where the user is asked to confirm the action. On confirm, the user is redirected back to the page the item was on, so if the item was on page 2 of the list, they are redirected back to page 2 after the confirmation. This is the default behaviour of the admin-on-rest Delete.

The problem is, if page 2 has only one item and it is deleted, it redirects me to page 2 with an empty table and no arrows to navigate to first page. I have to do a browser refresh to fix it.

I noticed that in admin-on-rest version 1.3.3 there is a prop called "redirect" that the Delete accepts. I can set the redirect path of the previous page if the the row to be deleted is the only row on the page. But I cant figure out how to get the number of rows on the page. The admin-on-rest List component does not expose the pagination component which keeps information about the current page like page number, rows in the page etc.

If Delete is taking care of redirection I would expect it to redirect to the correct page by default. And if it isn't the default behaviour, then some page related information needs to be exposed.

**Comment by djhi** [comment]
The problem here is that we can't rely on the pagination data we had before the delete as it can have changed too (not only because of the delete but maybe because of other changes unrelated to the user currently using the app).

So it mean that the List component should automatically redirect to the previous page if the current one is empty. Right ?

**Comment by rahul169sharma** [comment]
@djhi I don't think that this is something the List component should do. The List itself will never display an empty 2nd (or 3rd or 4th or ..) page, unless redirected to by another component, in this case the Delete. Delete is already handling the redirection after the crud operation, so it should be responsible for redirecting to the correct page, and not the List.

> The problem here is that we can't rely on the pagination data we had before the delete as it can have changed too (not only because of the delete but maybe because of other changes unrelated to the user currently using the app).

I am having trouble imagining a case where what you mentioned can happen. Can you please give me an example?

**Comment by djhi** [comment]
> I am having trouble imagining a case where what you mentioned can happen. Can you please give me an example?

- Another process, server side for example, also has updated this resource.
- Another user also has updated this resource.

**Comment by rahul169sharma** [comment]
@djhi I see. Makes sense to make List component handle the redirection then. Like you suggested,

> the List component should automatically redirect to the previous page if the current one is empty

**Comment by rahul169sharma** [comment]
@djhi are we doing anything about this?

**Comment by djhi** [comment]
As soon as I'll find the time. Feel free to give it a try :)
