### ISSUE TITLE
Fixed toolbar hiding content on mobile

### ISSUE THREAD

**Issue by MadalenaGoncalves** [marmelab/admin-on-rest#1371]
**What you were expecting:**
On Mobile, SimpleForm and TabbedForm can display all inputs and the fixed toolbar.

**What happened instead:**
With too many inputs, the fixed toolbar that has the Save button overlaps the last input.

**Steps to reproduce:**
1. Create a SimpleForm/TabbedForm with enough inputs so that scrolling is necessary on mobile.
2. Confirm that some inputs are hidden by the toolbar on mobile (but not on desktop)

**Related code:**
Here is an example: https://9213q40zjy.codesandbox.io/#/comments/11

**Environment**
* Admin-on-rest version: 1.3.3
* React version: 15
* Browser: Chrome, Firefox, Safari
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
Is it the same problem as #1274?

**Comment by djhi** [comment]
True
