### ISSUE TITLE
Feature: Conditional columns in List/Datagrid?

### ISSUE THREAD

**Issue by te-online** [marmelab/admin-on-rest#1381]
**What you were expecting:**
I can conditionally show/hide a TextField or ...Field in a Datagrid, wrapped by a List.

**What happened instead:**
Conditional field is visible when condition applies on page load, but not dynamically.

**Steps to reproduce:** / **Related code:**
```
const ConditionalFilterTextField = (props) => {
    const show = ... // if filter is set in URL
    return (show) ? <TextField {...props} /> : null
}

...

<List {...props} filters={<MyFilter />}>
  <Datagrid>
    ...
    <ConditionalFilterTextField sortable={false} source="filter_field" label="My Label" />
    ...
  </Datagrid>
</List>
```

I started a question on StackOverflow, but got no response so far. (see https://stackoverflow.com/questions/48211984/is-it-possible-to-have-conditional-columns-in-a-list-datagrid-in-admin-on-rest) So I guess that I either overlooked something or this is not possible right now. If it is not possible, I'd like to start a feature request. Please bear with me if it's just my React incompetence, we can immediately close this issue then.

**Environment**

* Admin-on-rest version: 1.3.3
* React version: 16.2.0
* Browser: Current Chrome & Firefox

**Comment by djhi** [comment]
Answered on StackOverflow.

**Comment by te-online** [comment]
Thanks a lot!

**Comment by kidphys** [comment]
I stump upon this issue and couldn't change vibisility dynamically neither. The example in Stackoverflow work with filter, but not with a toggle button via setState. Any recommendation?

**Comment by djhi** [comment]
https://github.com/fizix-io/ra-customizable-datagrid ?

**Comment by te-online** [comment]
> I stump upon this issue and couldn't change vibisility dynamically neither. The example in Stackoverflow work with filter, but not with a toggle button via setState. Any recommendation?

Do you have any example of your idea via setState? I think it could work as well, but haven't tried. Using a filter is actually also just changing state (or props), but probably through a reducer...

**Comment by afilp** [comment]
@fzaninotto advised against using a Filter for this flag but using an Action instead:
https://github.com/marmelab/react-admin/issues/1965

I did it as he said, only "downside" (compared with the filter) is that the Action is not "remembered" when the user refreshes the page (while the filter is, because it is part of the query string).

**Comment by te-online** [comment]
Couldn't you set a query parameter within your action or is it predefined?
