### ISSUE TITLE
Authparams dashboard

### ISSUE THREAD

**Issue by tkvw** [marmelab/admin-on-rest#1395]
https://github.com/marmelab/admin-on-rest/blob/7b8994f8e358644abf1026085abef0b8597407ee/packages/react-admin/src/AdminRoutes.js#L118

Shouldn't this be `/s/route: 'dashboard'/resource: 'dashboard'`?

**Comment by fzaninotto** [comment]
ping @djhi

**Comment by djhi** [comment]
No: what if you have a resource named `dashboard` ?
