### ISSUE TITLE
Update the project to material-ui next

### ISSUE THREAD

**Issue by batiste** [marmelab/admin-on-rest#1397]
Good day,

Is there any plan to update the framework to the new version of material-ui next?
The first beta version is out since 15 Aug 2017.

Any plans in the pipe? Anybody working on it?

**Comment by djhi** [comment]
See the `next` branch ;)

**Comment by djhi** [comment]
PS: we also released an alpha and the project has been renamed `react-admin`.

Try it:

```sh
npm i react-admin@2.0.0-beta1

yarn add react-admin@2.0.0-beta1
```

This one has known issues which will be fixed in next beta release, hopefully coming very soon.

**Comment by batiste** [comment]
yarn add react-admin@2.0.0-beta1
yarn add v0.21.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "react-admin@2.0.0-beta1" has incorrect peer dependency "react@^15.4.0 || ~16.0.0".
warning "react-admin@2.0.0-beta1" has incorrect peer dependency "react-dom@^15.4.0 || ~16.0.0".
warning "material-ui-chip-input@0.17.2" has incorrect peer dependency "react@^15.3.2".
warning "material-ui-chip-input@0.17.2" has incorrect peer dependency "react-dom@^15.3.2".
warning "react-router@4.1.2" has incorrect peer dependency "react@^15".
warning "react-router-dom@4.1.2" has incorrect peer dependency "react@^15".
warning "material-ui-chip-input@0.18.5" has incorrect peer dependency "material-ui@>= 0.19.1 < 1.0.0".
[4/4] 📃  Building fresh packages...
success Saved 0 new dependencies.
✨  Done in 5.04s.

**Comment by djhi** [comment]
Yes ?

That reminds me we should remove the `material-ui-chip-input` dependency until it has been updated with autocomplete

**Comment by batiste** [comment]
I am trying to run the demo with the next branch... Is that possible at this point in time?

Thanks for your quick replies?

**Comment by djhi** [comment]
Well, it requires to upgrade the demo as specified in the upgrade guide. We are working on it but it may require some time.

**Comment by batiste** [comment]
This is as far as I got

![screen shot 2018-01-18 at 14 21 29](https://user-images.githubusercontent.com/66927/35100138-ee2b3ee4-fc5a-11e7-8820-27d94a650b5c.png)

**Comment by djhi** [comment]
https://github.com/marmelab/admin-on-rest/pull/1399

**Comment by batiste** [comment]
Sorry to bother you again but now this is where I am stuck

<img width="545" alt="screen shot 2018-01-19 at 14 33 32" src="https://user-images.githubusercontent.com/66927/35153207-cf9f6768-fd25-11e7-8de0-8f11679c2b42.png">

**Comment by djhi** [comment]
Sorry but I'll need more context. Do you have a repository for your project ?

**Comment by batiste** [comment]
@djhi I basically had the demo project with the master version of admin-on-rest. I installed the next version locally (changed the package name to admin-on-rest and yarn link it) and followed some of the fixes in the UPGRADE file.

Here is the project on github https://github.com/batiste/admin-on-rest-test

Thanks!

**Comment by djhi** [comment]
Have you seen the PR I referenced earlier ? #1399 

I won't have time to debug your project. 

I remember having troubles on the first beta because we have a loose dependency to material-ui (using `~`). This is a problem because later versions had several breaking changes. You can enforce the version used by adding a fixed dependency to mui in your project (`1.0.0-beta.17`, without `^` nor `~`).

**Comment by batiste** [comment]
@djhi thanks for you support anyway. I think I got it running at this point. Mostly a few errors on my part. The admin section seems to run, but the data doesn't seems to come through. I did things like indicated in the UPGRADE docs:

```javascript
import simpleRestClient from 'ra-data-simple-rest';
<Admin dataProvider={simpleRestClient('http://localhost:3000')}>
```

The in the admin I get:

<img width="240" alt="screen shot 2018-01-19 at 17 12 45" src="https://user-images.githubusercontent.com/66927/35160134-9511ab44-fd3c-11e7-8472-2f3e14aec7c5.png">

Any idea?

**Comment by batiste** [comment]
Oki I managed to make it work finaly think I found some kind of bug inside the  2.0.0-beta1 release.

I have 

"react-admin": "2.0.0-beta1",
"ra-data-json-server": "2.0.0-beta1"

But it seems there is a small mismatch in ra-data-json-server here:

                const query = {
                    ...flattenObject(params.filter),

I copied this client and changed it to

                const query = {
                    ...fetchUtils.flattenObject(params.filter),

And now it works

**Comment by djhi** [comment]
I'm glad you did :) Anyway, a new beta should be released this week. It will also contain the demo app in the new `examples` folder.
