### ISSUE TITLE
Possibility to receive custom params in restClient

### ISSUE THREAD

**Issue by serhiipalash** [marmelab/admin-on-rest#1403]
Can you add possibility to pass custom params from `<Edtin>` or `<Create>` to restClient?

We have two types of data in db. One stored under random ids and another - under some property in the record.

For example, our `/daily_tips` stored under `/daily_tips/{day_number}/`, and in Tip we have `day` property that is equal to parent key.
For this type of data `UPDATE` event with changed `day` property will be more like `MOVE`.

And we have regular data, for example `/videos`, that stored under `/videos/{random_id}`

Right now we have to hardcode all first type resources in restClient and check if `UPDATE` raised for one of them, and then run `moveHandler()`.

It will be good if I can just pass custom params in `<Edit>` or `<Create>` for different types of data and then get them in restClient.
Something like this

```
<Edit restClientOptions={{ saveUnderProp: 'day' }}>
    ...
</Edit>
```
and in our restClient use it
```
function async restClient(type, resource, params) {
   switch (type) {
       case EDIT: {
           const saveUnderProp = params.restClientOptions.saveUnderProp

          if (saveUnderProp && params.data[saveUnderProp] !== params.previousData[saveUnderProp]) {
               return moveHandler(resource, params)    
          } else {
               return updateHandler(resource, params)
          }
      }
   }
}
```

I think need to add some logic in `crudCreate` and `crudUpdate` data actions.
here
<img width="698" alt="screen shot 2018-01-20 at 20 03 07" src="https://user-images.githubusercontent.com/14208343/35186650-0c57a09e-fe20-11e7-996d-56deca73a337.png">

I understand that this is not typical case and maybe not much people need this, but it will be great if you can do this.

Thanks in advance!

**Comment by fzaninotto** [comment]
Ni, we won’t implement this. Your rest client already has access to the resource, so you can change the path according to the resource there - and it’s the right place to do it.
