### ISSUE TITLE
Support components in SimpleForm redirect

### ISSUE THREAD

**Issue by kerma** [marmelab/admin-on-rest#1404]
**What you were expecting:**
Possibility to use component in SimpleForm redirect.

**What happened instead:**
Warning: Failed prop type: Invalid prop `redirect` supplied to `SimpleForm`.

**Related code:**

```
<SimpleForm redirect={<GetUrl {...props}/>}>
```

**Other information:**

I'm trying to generate a redirect URL based on the record. As it's not directly available in my create/edit component I need to call something with props to construct it. I cannot figure out any other option to do that. 

I tried to achieve the same with Toolbar without much luck either. Also I don't think HOC is a solution here. API wise it would make sense that there is a support for dynamic URLs.

Please do correct me if I'm wrong.  

**Environment**

* Admin-on-rest version: 1.3.3

**EDIT**
It seems someone is trying to tackle it in #1384 ?

**Comment by djhi** [comment]
I fail to see the value of a component here. #1384 is still a work in progress but I'm confident it'll be in version 2.

**Comment by kerma** [comment]
How would you solve the issue at hand without a component? Use case is pretty simple, I have a resource with one-to-many relationship. Show page displays it in all detail. Resource and it's children have separate edit pages. Once editing the child I want to send user back to main resource show view. I don't even have a list/show for the child. so I need to have access to resource somehow to construct the url: `/parents/${record.parent_id}/show`. Sounds at least a little valuable, no?
