### ISSUE TITLE
Authentication Documentation AUTH_ERROR status code correction

### ISSUE THREAD

**Issue by zifnab87** [marmelab/admin-on-rest#1408]
**What you were expecting:**
as also noted in https://github.com/marmelab/admin-on-rest/issues/1095
I had to use the Error internals to extract the status as it is not directly on params (as stated in the docs: https://github.com/marmelab/admin-on-rest/blob/master/docs/Authentication.md#catching-authentication-errors-on-the-api)
```js
if (type === AUTH_ERROR) {
        const status  = params.message.status;
        if (status === 401 || status === 403) {
             localStorage.removeItem('token');
            return Promise.reject({message: 'Authentication Error: Token Expired or Forbidden'});
        }
        return Promise.resolve();
		
    }
```
**What happened instead:**
In documentation it states: 
```js
if (type === AUTH_ERROR) {
        const { status } = params;
        if (status === 401 || status === 403) {
            localStorage.removeItem('token');
            return Promise.reject();
        }
        return Promise.resolve();
    }
```

**Comment by djhi** [comment]
Can you make a PR to fix it ? :)

**Comment by zifnab87** [comment]
#1409 please have a look - not sure if message can be null or if there is any edge case
