### ISSUE TITLE
Cannot set empty value on ReferenceInput

### ISSUE THREAD

**Issue by alexborisov** [marmelab/admin-on-rest#141]
I can't seem to figure out a way to add a blank row in my `ReferenceInput` `SelectInput`. Any suggestions how I could do this short of modifying my REST client to prepend a `{id:null}` row?

**Comment by fzaninotto** [comment]
It's currently only possible if you provide your own `<SelectInput>` implementation, but I'll make it easier.

**Comment by alexborisov** [comment]
Sweet thanks!
