### ISSUE TITLE
Specify key property Datagrid uses.

### ISSUE THREAD

**Issue by rweindl** [marmelab/admin-on-rest#142]
Datagrid expects an `id` property provided by each data field. This `id` property is used as key for each displayed row. In case of a non relational database like MongoDB the `id` field is mostly called `_id` which results in the following React error:

```
bundle.js:9452 Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `Datagrid`. See https://fb.me/react-warning-keys for more information.
```

Is there a way to specify a custom property which should be used as key? When starting to inspect the code and create a PR for this I got stuck in the `src/mui/list/Datagrid.js` file since not understanding where the `ids` array is getting generated and than provided as property.

Clarification on both questions would be useful and really appreciated.

Thanks and Best Regards
Robert

**Comment by fzaninotto** [comment]
Hi Robert,

Your rest client function MUST provide records with an `id` field. If the API returns an `_id` field, the rest client must map it to an `id` field. This is explained in detail in http://marmelab.com/admin-on-rest/RestClients.html.

**Comment by fzaninotto** [comment]
This question is quite common, so we've added the response to our FAQ : https://marmelab.com/admin-on-rest/FAQ.html#can-i-have-custom-identifiers-primary-keys-for-my-resources
