### ISSUE TITLE
Previous data persist while loading new data

### ISSUE THREAD

**Issue by arkkanoid** [marmelab/admin-on-rest#1423]
Hi, 
Loading a page list or datagrid it shows me the previous data while react fetches the new data from the api.
It's only 1-2 seconds but is not elegant. I would prefer to only show a loading bar and show the fresh data when it's loaded.
It's posible to do?

Thanks

**Comment by djhi** [comment]
It's a feature, called Optimistic rendering :) And it's not possible to disable it.
