### ISSUE TITLE
No 'lib' folder created when using the 'master' or 'next' in package.json

### ISSUE THREAD

**Issue by afilp** [marmelab/admin-on-rest#1433]
I want to use the latest master (or 'next') branch, so I have the following line in package.json:
`` "admin-on-rest": "git+https://github.com/marmelab/admin-on-rest.git",``

**What you were expecting:**
'lib' to be in ``node_modules\admin-on-rest`` after ``npm i``

**What happened instead:**
'lib' is not created in ``node_modules\admin-on-rest`` after ``npm i``

**Environment**

Windows 10 Pro

**Comment by tkvw** [comment]
the builds aren't published in the git repository, they are available on npm. If you want to create a snapshot build, you have to build the packages yourself before you can use them.

**Comment by af-inf** [comment]
@tkvw Thanks, when do you expect to release a new version on npm? Also "next" is not on npm, is it?

**Comment by djhi** [comment]
Hopefully this week
