### ISSUE TITLE
New Feature: AUTH_CHECK should pass resource id so authClient can decide on per-resource access

### ISSUE THREAD

**Issue by benglass** [marmelab/admin-on-rest#1434]
Currently, when authClient() is called it is passed 2 arguments: type and payload.

When type is AUTH_CHECK, I am proposing that payload should include the id of the resource when available. For example, during an edit or delete. This would allow more complex authorization logic such as only allowing the owner of a resource to edit or delete it.

**Comment by fzaninotto** [comment]
You're probably mixing up authentication and authorization. Admin-on-rest handles it in a different way, see https://marmelab.com/admin-on-rest/Authorization.html.
