### ISSUE TITLE
defaultValue not working when applied "per-field" in a "NumberInput"

### ISSUE THREAD

**Issue by afilp** [marmelab/admin-on-rest#1435]
**What you were expecting:**
defaultValue to be "0"

**What happened instead:**
Nothing appears, no 0

**Steps to reproduce:**
**Related code:**
````
            <NumberInput label="Threshold" source="securityThreshold" step={1}
                         defaultValue={0}
            />
`````

**Environment**

* Admin-on-rest version:  "admin-on-rest": "^1.3.4",
* Last version that did not exhibit the issue (if applicable):
* React version: "react": "^16.2.0",
* Browser:
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
Can't reproduce. Please create a codesandbox showcasing the issue.

**Comment by djhi** [comment]
Feel free to reopen once you have a codesandbox
