### ISSUE TITLE
AutocompleteInput, cannot change its value

### ISSUE THREAD

**Issue by afilp** [marmelab/admin-on-rest#1437]
I have a similar issue to this on the latest release:
https://github.com/marmelab/admin-on-rest/issues/1046

Once I add a value, I cannot change it anymore. Neither make it null. 

* Admin-on-rest version:     "admin-on-rest": "^1.3.4",

**Comment by djhi** [comment]
Can't reproduce. Please create a codesandbox showcasing the issue.

**Comment by djhi** [comment]
Feel free to reopen once you have a codesandbox
