### ISSUE TITLE
Support material ui 0.20.0 in master

### ISSUE THREAD

**Issue by AlexandrKnyazev1395** [marmelab/admin-on-rest#1438]
Now you have 0.19 but there are many new features in 0.20

**Comment by djhi** [comment]
Unfortunalty, the 0.20 introduces breaking changes. We might upgrade our code but all addons, custom inputs and fields may break and we cannot release a major version yet (we're working on the 2.0 already)

**Comment by Phocea** [comment]
@djhi any chance of getting a beta2 pushed to npm, on the 2.0 branch then, please ?

**Comment by djhi** [comment]
Hopefully this week :)

**Comment by afilp** [comment]
@djhi Also, same with master? (1.3.5?)
