### ISSUE TITLE
<ReferenceField> in <List> only renders on second request - Admin On Rest

### ISSUE THREAD

**Issue by sharonovd** [marmelab/admin-on-rest#1446]
Please do not submit support requests or "How to" questions here. For that, go to [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest).

**What you were expecting:**
Reference field would be displayed by Datagrid during first page render.

**What happened instead:**
Reference field is rendered as infinitely loading. If a component is refreshed - e. g. via clicking 'Create' or 'Edit' buttons and returning - everything is rendered correctly.
![incorrect_render](https://user-images.githubusercontent.com/31623709/35560708-3298d2e0-05bf-11e8-93cd-4d264c20272b.png)
![correct_render](https://user-images.githubusercontent.com/31623709/35560738-44424a30-05bf-11e8-95f4-bf66ca740699.png)

Requests to back-end are identical and look correct in both cases.

**Steps to reproduce:**
Add a list with a reference field, pointing to another resource - just like in the doc.

**Related code:**

```
export const ContactList = (props) => (
    <List {...props} title="Contacts" filters={<ContactFilter />}>
        <Datagrid>
            <NumberField source="contact_id" />
            <TextField source="type" />
            <TextField source="value" />
            <ReferenceField label="profile" source="profile_id" reference="profiles">
                <TextField source="last_name" />
            </ReferenceField>
            <EditButton />
        </Datagrid>
    </List>
);

<Resource name="contacts" list={ContactList} edit={ContactEdit}
                      create={ContactCreate} remove={Delete}/>
```

**Other information:**
Also described here:
https://stackoverflow.com/questions/47751401/referencefield-in-list-only-works-on-second-request-admin-on-rest?rq=1

**Environment**

* Admin-on-rest version: tried on 1.3.1 and 1.3.4
* Last version that did not exhibit the issue (if applicable):
* React version: 15.6.1
* Browser: tried chrome, safari and firefox
* Stack trace (in case of a JS error): console is empty

**Comment by djhi** [comment]
1. Please don't double post here and on SO
2. I can't reproduce your issue, so please provide a codesandbox showcasing it

**Comment by sharonovd** [comment]
1. It's not a double-post: question on SO is not mine, and it is not answered in two months.
2. Will try to provide sample app.

**Comment by djhi** [comment]
> It's not a double-post: question on SO is not mine, and it is not answered in two months.

Fair enough, my apologies :)

**Comment by valentinchevalier** [comment]
I had the same issue, and i resolve it by debugging the GET_MANY handling in my REST client.

**Comment by valentinchevalier** [comment]
I had the same issue, and i resolve it by debugging GET_MANY in my custom REST client.

My custom REST Client transform API data field **_id** to **id** and I forgot to handle this transformation in my GET_MANY. So, the **id** field that is required by AOR was not initialised when fetching GET_MANY.

I hope it will help
