### ISSUE TITLE
[react-admin@v2.0.0-beta1]Missing translation keys in ra-language-french

### ISSUE THREAD

**Issue by vdieulesaint** [marmelab/admin-on-rest#1464]
Some translation keys are missing in package ra-language-french ; it triggers some warnings in the console : 
- Warning: Missing translation for key: "ra.message.loading"
- Warning: Missing translation for key: "ra.page.loading"

**Environment**

* Admin-on-rest version: v2.0.0-beta1

**Comment by alexisjanvier** [comment]
Fix in #1465
