### ISSUE TITLE
ChipField - Source replaced by label when label set

### ISSUE THREAD

**Issue by vdieulesaint** [marmelab/admin-on-rest#1468]
When setting a label on Chipfield, the source will no longer be showed. It displays the label instead of source.

```
<List ... >
  <Datagrid>
    <ChipField label="Operating System" source="os" /> 
    <ChipField source="os" /> 
  </Datagrid>
</List>
```
=> generates the following ouput

| Operating System | os | 
| ------------- |:-------------:| 
| Operating System      | ios | 
| Operating System     | android | 
...

**Environment**

* Admin-on-rest version: v2.0.0-beta1
* Material-ui: material-ui@1.0.0-beta.31

**Comment by alexisjanvier** [comment]
closed with #1470
