### ISSUE TITLE
Query params are lost when 'Save' or 'Delete' redirects

### ISSUE THREAD

**Issue by afilp** [marmelab/admin-on-rest#1471]
**What you were expecting:**
I have this URL:
http://localhost:4000/movements?page=1&perPage=25#/movementAssets/5a74d10417d980ea78fdb769?kind=vehicles

I need the query param ``?kind=vehicles`` so that when I go to 'list' I can filter the list only with the ``vehicles`` kind (In other words, I want to do CRUD in a filtered subset of the "movementAssets" as a whole, I have a special menu item for this "Vehicles").

I want my query param to be retained after I use "Save" and "Delete", it is not.

**What happened instead:**
The query param is not retained after redirect, it is lost (so now I am not in just ``Vehicles`` anymore but in all ``movementAssets``, which is not what I want)

**Environment**

* Admin-on-rest version:  "admin-on-rest": "1.3.4",

**Comment by alexisjanvier** [comment]
The list filters are kept after a `save` or a `delete` redirection, but they are not kept from query params. They are kept in the redux's state.

![capture d ecran de 2018-02-06 12-07-50](https://user-images.githubusercontent.com/547706/35856486-70c7b01e-0b36-11e8-9b73-66e41824fc0a.png)

**Comment by fzaninotto** [comment]
So there is no bug...

**Comment by afilp** [comment]
@alexisjanvier Thanks, this could work, but what if the user hits "Refresh" on the browser? Shouldn't the query params somehow be filled in the URL after redirect to cover this case?

I had to use localStorage (very ugly solution) to keep this info intact from user refreshes as well as other cases. The URL also acts as a "sharing" solution (to give it to a colleague for example), so losing this info from the URL causes problems. Note that my use case is not to have the custom filters in the URL but a very important "permanent" filter that gives a subset of the dataset (see `?kind=vehicles`). If this is lost, then the URL denotes the "generic" dataset while the REDUX state solution (or localStorage one) gives the subset. Sharing you the URL after a SAVE gives different results to you than in my computer.

Not sure if i make the problem clear here.

**Comment by fzaninotto** [comment]
Doing what you ask has many undesirable side effects (I know because that's the solution we've used for ng-admin, the precursor of admin-on-rest), and we don't want to go that way.

After you apply a filter/sort/pagination, you can copy the link and share it. You can also create a button linking to the list with a query parameter, and share this link. As for hitting the Browser refresh button, this resets the store by construction. If you want to refresh just the data, all views have a refresh button.

**Comment by afilp** [comment]
@fzaninotto Thanks for taking the time to explain.
