### ISSUE TITLE
React admin / ImageField unable to override style

### ISSUE THREAD

**Issue by vdieulesaint** [marmelab/admin-on-rest#1480]
The image style does not seems overridable in ImageField.
I am unable to resize the image.

```
const styles = {
    image: {
        height: 50,
        width: 50,
    },

    <List {...props}>
        <Datagrid>
            <ImageField source="thumbnail_url" className={classNames(classes.image)}/> 
        </Datagrid>
    </List>
```

**Environment**

* Admin-on-rest version: v2.0.0-beta1

**Comment by djhi** [comment]
Can't reproduce the issue. Can you post the full component or, even better, set up a codesandbox ?

**Comment by vdieulesaint** [comment]
I am preparing a codesanbox. 
I am stuck for now because I cannot install ra-data-json-fakerest. See #1484

**Comment by vdieulesaint** [comment]
=> codesanbox : https://codesandbox.io/s/rmvq4ooxzq

**Comment by djhi** [comment]
I see, the Css API documentation for many components is not done yet. Here is my fork solving your issue: https://codesandbox.io/s/n7n176k71m

**Comment by tomgekeerd** [comment]
@djhi Your codesandbox is not available anymore, would you be willing to share your solution again?

**Comment by FACOLOMBANI** [comment]
Same issue for me while adding a small svg, i need to set a minWidth but it is not working.

**Comment by brownieboy** [comment]
I went old school to work around this one.  I put a className on my `<ImageField>,` and then styled the child `<img>` tag in my App.css file.

So here's my `<ImageField>`:
```html
<ImageField source="thumbFullUrl" className="thumbNailView" />
```
And here's the entry in my App.css:
```css
.thumbNailView img {
  height: 60px;
  width: 60px;
  border-radius: 50%
}
```

As I said, old school, but it works for me.
