### ISSUE TITLE
Re-implement SelectArrayInput in next

### ISSUE THREAD

**Issue by fzaninotto** [marmelab/admin-on-rest#1483]
material-ui 1.0 supports `Select` with the `multiple` tag, see https://material-ui-next.com/demos/selects/#multiple-select. So we no longer need to depend on `material-ui-chip-input`.

It's now time to reintroduce the `SelectArrayInput`, knowing that it doesn't handle autocomplete (which is a BC break), but works for cases with a limited number of choices nonetheless.

**Comment by tkvw** [comment]
Just a heads up, I created a draft proposal for this: https://github.com/marmelab/admin-on-rest/pull/1430

**Comment by fzaninotto** [comment]
Fixed by #1495
