### ISSUE TITLE
React admin / Unable to install dependency ra-data-json-fakerest

### ISSUE THREAD

**Issue by vdieulesaint** [marmelab/admin-on-rest#1484]
I am currently not able install the following dependency : ra-data-json-fakerest

npm install --save ra-data-json-fakerest

npm ERR! code E404
npm ERR! 404 Not Found: ra-data-json-fakerest@latest

**Comment by djhi** [comment]
Have you tried `npm install --save ra-data-json-fakerest@2.0.0-alpha1` ?

**Comment by vdieulesaint** [comment]
Yes, I got the same error.

**Comment by djhi** [comment]
This is weird as it is published on npm. See https://www.npmjs.com/package/ra-data-fakerest

**Comment by fzaninotto** [comment]
Can't reproduce either on another machine. Please try on another machine and check your setup.

**Comment by vdieulesaint** [comment]
Finally, i have it working by running : npm i ra-data-fakerest
weird.
