### ISSUE TITLE
Need to add 'title' attribute to all fields and inputs

### ISSUE THREAD

**Issue by AlexandrKnyazev1395** [marmelab/admin-on-rest#1494]
Every field and Input should be able to add 'title' attribute. This is especially needed in wide tables where we have not opportunity to add long labels.

**Comment by djhi** [comment]
Won't be done in v1 but is already possible in v2 beta

**Comment by AlexandrKnyazev1395** [comment]
@djhi Maybe I do it myself and I will make pull request in v1? I very need it in my current project

**Comment by djhi** [comment]
Sorry @AlexandrKnyazev1395, I actually misread your question. You can override the datagrid labels for each field using the `label` prop in v1 already.

Just specify the `label` prop like this:

```js
export const PostList = (props) => (
    <List {...props}>
        <Datagrid>
            <TextField source="id" />
            <TextField source="title" label="My custom label" />
        </Datagrid>
    </List>
);
```

Note that we'll try to translate it if you need. So you can supply either a default translation for the field (which will be used everywhere: create, edit, show, list) or use a custom one. You can find an example in the [demo](https://github.com/marmelab/admin-on-rest-demo/blob/master/src/visitors/index.js#L51)
