### ISSUE TITLE
Could we support Tabs by default in Form and ShowLayout?

### ISSUE THREAD

**Issue by zifnab87** [marmelab/admin-on-rest#1504]
I am curious if there could be an improvement about the "API" of admin-on-rest in some cases being defensive.

For example `<SimpleForm>` and `<TabbedForm>` could be just `<Form>` and work with Tabs by default
also `<SimpleShowLayout>` and `<TabbedShowLayout>` could be just `<ShowLayout>` that works with `Tabs` if they exist or with no tabs if they don't. 
Any thoughts on the technical difficulties and the reason why they are specialized containers? Thank you!

I am happy to see that Scrollable will be the default for tabs in 2.0.0: https://github.com/marmelab/admin-on-rest/pull/1318

**Comment by djhi** [comment]
I like this idea: we do some children introspection in `TabbedForm` and `TabbedLayout` already so might do it in a `Form` and `ShowLayout` component.

**Comment by fzaninotto** [comment]
I'm -1 for this idea: `<SimpleForm>` expects `<Field>` children, while `<TabbedForm>` expects tabs. That's two different components, because two different signatures. Besides, I don't want to inspect children and decide a different render strategy - each time we did that, we regreted it.
