### ISSUE TITLE
When navigating to / without being authenticated - it tries to fetch stuff for Dashboard without AUTH_CHECK before that

### ISSUE THREAD

**Issue by zifnab87** [marmelab/admin-on-rest#1505]
**What happened:**

When navigating to / without being authenticated- it tries to fetch stuff for Dashboard

**What was expected:**

It should first check if the user is authenticated with AUTH_CHECK etc, then redirect instead of trying to fetch what is needed for Dashboard..

**How to replicate:**

Navigate here: https://marmelab.com/admin-on-rest-demo/ - (make sure you are logged-out)
As can be seen from the image it tries to fetch what is needed for Dashboard!
![image](https://user-images.githubusercontent.com/526062/35938225-203dc36a-0c51-11e8-9e09-580ca9607226.png)

I can replicate it with my app as well

![image](https://user-images.githubusercontent.com/526062/35938293-53ea89aa-0c51-11e8-9bd8-f7686e400c16.png)

* Admin-on-rest version: 1.3.4

**Comment by fzaninotto** [comment]
The `AUTH_CHECK` call is asynchronous, and the response can come with a long delay. We choose to render the dashboard even though the response from the `AUTH_CHECK` call hasn't come yet. We've adopted this strategy for performance reasons (it's called optimistic rendering).

Apart from the errors in the console, how is this a problem for you?

**Comment by zifnab87** [comment]
Thanks for the reply!  I understand your strategy but I am curious why AUTH_CHECK could have a long delay since it is just checking localStorage (at least in my case)

// called when the user navigates to a new location
    else if (type === AUTH_CHECK) {
        if (UserHandler.isLoggedIn()) {
            return Promise.resolve();
        } 
        else {
            UserHandler.logoutCallback();
            return Promise.reject({message: 'Authentication Error: Token Expired or Forbidden'});  
        } 
    }


```
    static isLoggedIn() {
        return localStorage.getItem('username') &&
            localStorage.getItem('csrf_token')
    }
```
While hitting the database 5-10 times in the meantime is more expensive for my case at least

**Comment by fzaninotto** [comment]
Because the local AUTH token can be expired, and require a new round trip with the AUTH server to confirm the AUTH status. 

So the auth_check call can be long.

**Comment by zifnab87** [comment]
makes sense! I am just logging out in that case - cool!

**Comment by christiaanwesterbeek** [comment]
It seems the current demo app is not affected. That means it does not show the dashboard for a brief moment when unauthenticated, but the login dialog immediately. I couldn't identify how that was accomplished and I hope you can help me. See my question on SO:

https://stackoverflow.com/questions/62383779/how-to-prevent-flash-of-dashboard-content-while-unauthenticated-in-react-admin
