### ISSUE TITLE
Scoped packages

### ISSUE THREAD

**Issue by tkvw** [marmelab/admin-on-rest#1506]
Is it an idea to create scoped npm packages (like @babel) https://docs.npmjs.com/misc/scope?
Something like `@marmelab\react-admin`, etc..

**Comment by djhi** [comment]
I don't know: why ?

**Comment by tkvw** [comment]
To make sure there are no naming collisions and to ensure people know they are working on packages published by you. From a security standpoint there are real issues that people install wrong packages because of mistyping a package names (just check `cross-env` vs `crossenv` package). 
Also, the `node_modules` folder looks so much cleaner... 

I really love having all the `@babel` packages in a single folder (V7).

**Comment by fzaninotto** [comment]
I see no real interest, especially since it requires breaking BC again in `next`. Thanks for the suggestion, though.
