### ISSUE TITLE
defaultValue does not work

### ISSUE THREAD

**Issue by Iwark** [marmelab/admin-on-rest#1509]
Hi, thanks for the great library.

I found a problem that the `defaultValue` is not set under certain conditions.
Here is the code:

```
export const ClientCreate = (props) => (
  <Create title="Create a Client" {...props}>
    <SimpleForm>
      <TextInput source="name" />
      <TextInput source="redirect_url" defaultValue="http://hogehoge.com" />
    </SimpleForm>
  </Create>
);
```

When I refresh the page, it works good, but when I come from the other page, the default value is not set.

If I specify `defaultValue` to `SimpleForm` it works like a charm:

```
const postDefaultValue = { name:"", redirect_url: "http://hogehoge.com" };
export const ClientCreate = (props) => (
  <Create title="Create a Client" {...props}>
    <SimpleForm defaultValue={postDefaultValue}>
      <TextInput source="name" />
      <TextInput source="redirect_url" />
    </SimpleForm>
  </Create>
);
```

**Environment**

* Admin-on-rest version: 1.3.4
* React version: 16.2.0
* Browser: Chrome 63.0.3239.132

Thank you.

**Comment by djhi** [comment]
I can't reproduce your issue. Please provide a codesandbox: https://codesandbox.io/s/ywwkr0327z (in which it works)
