### ISSUE TITLE
Unable to use format on ReferenceArrayField

### ISSUE THREAD

**Issue by ReservedDeveloper** [marmelab/admin-on-rest#1517]
**What you were expecting:**
When using the ReferenceArrayField, I want to be able to use the format attribute to convert records to the format expected by the field

**What happened instead:**
I receive the following error: `Cannot read property 'data' of undefined`

**Steps to reproduce:**
1. Create a record with an array property of nested objects, ex:

```javascript
{
  name: "My record"
  tags: [{id: 1}, {id: 2}]
}
```
2. Make sure Resources exist both for your object and the nested record
3. In your List view, add a ReferenceArrayField for the given property
4. Add a format attribute to map the nested object properties to a flat array of ids expected by the field

```javascript
format={tags => tags.map(tag => tag.id)}
```
**Related code:**
You can find a short instance here: https://codesandbox.io/s/yp7r693759

**Other information:**
It seems like the EmbeddedArrayField from [MhdSyrwan/aor-embedded-array ](https://github.com/MhdSyrwan/aor-embedded-array) may be what I want to use instead, but it seems like the format/parse attributes should allow me to handle nested structures.

**Environment**

* Admin-on-rest version: 1.4.0
* React version: 16.2.0
* Browser: Chrome 64.0.3282.140

**Comment by fzaninotto** [comment]
Thanks for your suggestion.

But adding a `format` prop to all components isn't the admin-on-rest way. Any transformation of data from your API format to the format expected by admin-on-rest should take place in the `restClient`. 

We won't add the `format` prop to the `<ReferenceArrayField>`.

**Comment by ReservedDeveloper** [comment]
Understood. I was just under the impression that most of the fields sat on top of Redux Forms fields, which I know can support that property, and your docs seemed to suggest support as well, at least [from the input side](https://marmelab.com/admin-on-rest/Inputs.html#transforming-input-value-tofrom-record). That said, I'll look in to the aor-embedded-array library. Thanks!

**Comment by fzaninotto** [comment]
Indeed, the `format` option is supported on *input* components, not *field* components.
