### ISSUE TITLE
FileField prop target=“_blank” does not work with AdBlock enabled

### ISSUE THREAD

**Issue by Cicus** [marmelab/admin-on-rest#1528]
**What you were expecting:**

Display the files attached to FileInput component, in a new tab, instead of the current page.

**What happened instead:**

The document is not displayed in a new tab nor in the current one.

**Steps to reproduce:**
- Set up a common `FileInput` component with `FileField`
- Set `FileField` prop `target` to `_blank`
- Add AdBlock extension
- Try to open the attached files

**Other information:**

The issue is caused by AdBlock extension, so I don't know if it actually makes sense to look for a solution, I mean, you can simply disable the extension.

**Environment**

* Admin-on-rest version: 2.0.0-beta2
* Last version that did not exhibit the issue (if applicable):
* React version: 16.2.0
* Browser: Chrome

**Comment by fzaninotto** [comment]
It's not the responsibility of admin-on-rest to deal with all the possible values that you can pass in a prop.
