### ISSUE TITLE
'Next': Permissions and Admin component

### ISSUE THREAD

**Issue by afilp** [marmelab/admin-on-rest#1565]
* Admin-on-rest version:       "react-admin": "^2.0.0-beta2"
Related to your UPGRADE guide: https://github.com/marmelab/admin-on-rest/blob/next/UPGRADE.md

I could not find somewhere in the UPGRADE guide what to do with the new **permissions** logic in the ``Admin`` component.

My OLD code (``admin-on-rest``):

````
const App = () => (
  <Admin
    customRoutes={customRoutes}
    menu={Menu}
    dataProvider={loopbackRestClient(window.apiUrl)}
    authProvider ={authClient(`${window.apiUrl}/users/login`)}
    dashboard={Dashboard}
    appLayout={OurLayout}
    locale="el"
    i18nProvider={i18nProvider}
  >
    {permissions => [
      <Resource name="directorates" />,
      <Resource name="deptTypes" />,
      <Resource name="regions" />,
      <Resource name="prefectures" />,
...etc...
````
Is this now a prop of ``Admin``? If yes, this should be mentioned in the guide and show us how to refactor the above code. You did a great job explaining with the ``AdminRouter`` cases, I do not see any instructions on the plain ``Admin`` case.

Thank you!

**Comment by djhi** [comment]
That's because nothing changed for the `Admin` component so this should still work (as shown by the `examples/simple` app). Did you hit an issue ?

**Comment by afilp** [comment]
Thanks, I cannot really test this because I get the following error message after upgrading:

``The context `muiTheme` is marked as required in `Paper`, but its value is `undefined`.``

And nothing appears (i.e. my upgrade fails, but I do not know what I may have done wrong since the error message is kind of "cryptic" to me). Any ideas?

Thanks!

**Comment by fzaninotto** [comment]
Sounds like you’re using an old version of material ui. Can you paste the mui version?

**Comment by afilp** [comment]
Indeed that was the problem. Thanks.

**Comment by fzaninotto** [comment]
You’re free to use any React version backward compatible with React 16.
