### ISSUE TITLE
Add state property for Edit, Create, Delete Buttons to use it in reactr-router

### ISSUE THREAD

**Issue by AlexandrKnyazev1395** [marmelab/admin-on-rest#1576]
When I use Edit Button I often want to use not only property 'to' of Link component, but also I want to pass 'state' property with some data.

**Comment by djhi** [comment]
This is already possible in the `next` branch (`2.0.0`). The `to` prop is passed to React-Router `Lin` and can be an object.

See https://codesandbox.io/s/pp0o4x40p0. The relevant code parts are:

* the `CreateCommentButton` component inside `src/posts.js`
* the `CommentCreate` component inside `src/comments.js` (note how we set the `defaultValue` prop on `SimpleForm`)
