### ISSUE TITLE
SelectInput not working with React 

### ISSUE THREAD

**Issue by rweindl** [marmelab/admin-on-rest#158]
The new release of admin-on-rest `0.5.2` requires `react 15.4.0` and so `react-dom 15.4.0`. Unfortunately, the `SelectInput` elements are no longer clickable with that release.

**Comment by clems71** [comment]
Hi,

I have the same issue - I see you closed it, did you find a solution, or was it a mistake in your code.

Thanks in advance!

**Comment by rweindl** [comment]
Hi @clems71 after removing my node_modules directory completely and installed all modules again it seems to work. Maybe you try the same and if not just reopen the ticket.
