### ISSUE TITLE
Next: Custom menu using withPermissions does not show the extra "permitted" items

### ISSUE THREAD

**Issue by afilp** [marmelab/admin-on-rest#1586]
Admin-on-rest version: "react-admin": "^2.0.0-beta3"

I use a custom `menu`: 

````
  <Admin
    menu={Menu}
````

...and then I use `permissions` in menu to show extra menu items if `permissions === 'admin'`.

In `stable` version this used to work (the extra menu items were shown).

In `next` version no extra items appear (when `admin` is loggedin).

I did what you say in UPGRADE guide:

````
const Menu = ({resources, onMenuClick, logout}) => {
  return (
    <div>

      <MenuItemLink
        to="/"
        primaryText="Αρχική / Οδηγίες"
        onClick={onMenuClick}
        leftIcon={<HomeIcon />}
      />

      <Divider />

      <WithPermissions>
        {permissions =>
          permissions === 'admin'
            ? <Fragment>
              <MenuItemLink
                to={{
                  pathname: '/users',
                  search: stringify({page: 1, perPage: 25}),
                }}
                primaryText="Users"
                onClick={onMenuClick}
                leftIcon={<UserIcon />}
              />

              <MenuItemLink
                to={{
                  pathname: '/departments',
                  search: stringify({page: 1, perPage: 25}),
                }}
                primaryText="Departments"
                onClick={onMenuClick}
                leftIcon={<BusinessIcon />}
              />
              <Divider />
            </Fragment>

            : null
        }
      </WithPermissions>

... etc...
````

Note that I used a simple case too, without `Fragment`, just the `MenuItemLink`, still it does not show. If I take the same `MenuItemLink` outside the `WithPermissions` section then it shows. So the problem is not with the `MenuItemLink` but something in the render logic of `WithPermissions`.

**Comment by djhi** [comment]
It should not be too difficult to create a sandbox to show this issue: https://codesandbox.io/s/ywwkr0327z

In the `authClient`, return a role depending on the `username` as we did in our simple example.

**Comment by djhi** [comment]
Sorry, I meant this codesandbox: https://codesandbox.io/s/q7r99p8349

**Comment by afilp** [comment]
@gjhi https://codesandbox.io/s/5mvk6jp55l

**Comment by afilp** [comment]
It appears that the entire problem was with the documentation, which caused me to believe that there was a bug with the code (mine or react-admin). The code is OK. 

Please check this PR that fixes the documentation:
https://github.com/marmelab/admin-on-rest/pull/1592
