### ISSUE TITLE
Unused component AdminRouter in react-admin

### ISSUE THREAD

**Issue by tkvw** [marmelab/admin-on-rest#1591]
I don't see this component being used: 

https://github.com/marmelab/admin-on-rest/blob/f3eb6e0eae5b6407a7d8e4817ebbd6db217509ea/packages/react-admin/src/AdminRouter.js#L1-L10

Is this an oversight and should it be passed to `Admin` or should it be removed?

**Comment by djhi** [comment]
It's not used by us but may be used by people making a custom app

**Comment by tkvw** [comment]
But shouldn't it be used by you, because the default implementation uses `ra-ui-materialui`?

**Comment by djhi** [comment]
We just define the loading default prop here for those who want to use `AdminRouter` but not `Admin` which also define this default. That's why we don't use it directly

**Comment by tkvw** [comment]
Ah, an oversight on my side, didn't notice the loading on `Admin`. 👍
