### ISSUE TITLE
Add support to DELETE action in resource add reducer

### ISSUE THREAD

**Issue by igor0ser** [marmelab/admin-on-rest#1596]
I am trying to delete resource item and it is not updated on the page AJAX-request success.
Can you please add some `removeRecords` case in `/src/reducer/admin/resource/data.js`?

**Comment by Kmaschta** [comment]
I didn't understand what you mean.. The DELETE verb is supported by AOR.

Can you provide an working example with the CodeSandbox?
You can find it in the [issue template](https://github.com/marmelab/admin-on-rest/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by igor0ser** [comment]
ok, I will try

**Comment by igor0ser** [comment]
so basic example of what I need:
```jsx
import { crudGetOne, crudDelete } from 'admin-on-rest';

const LoadBtn = props => (
  <button onClick={() => props.crudGetOne("posts", props.id)} />
);

export const LoadBtnConnected = connect(null, { crudGetOne })(LoadBtn);

const DelBtn = props => (
  <button onClick={() => props.crudDelete("posts", props.id)} />
);

export const DelBtnConnected = connect(null, { crudDelete })(DelBtn);
```

In this case, `crudGetOne` will work fine - ajax-request is sent and redux state is updated.
In case of `crudDelete` - only request is sent, but removed item is still in redux state, even if request is successfully resolved.

**Comment by fzaninotto** [comment]
Admin-on-rest 2.0 will use optimistic rendering at a whole new level (see #1859), which will solve this issue.
