### ISSUE TITLE
Filter labels covered by Select combo arrow

### ISSUE THREAD

**Issue by afilp** [marmelab/admin-on-rest#1604]
**What you were expecting:**
The filter labels to be clearly shown

**What happened instead:**
The filter labels have small width, so they are not clearly shown:
![image](https://user-images.githubusercontent.com/7850073/36874926-8125f08c-1db6-11e8-8109-8d1e34403061.png)

**Related code:**

    <ReferenceInput label="ΤΙΜΟΛΟΓΙΟ" source="invoice_id" reference="invoices" alwaysOn
                      sort={{field: 'name', order: 'ASC'}}
                      perPage={100}
      >
        <SelectInput optionText={optionInvoiceRenderer} />
      </ReferenceInput>

**Environment**

* Admin-on-rest version:  ^2.0.0-beta3

**Comment by fzaninotto** [comment]
Fixed by #1651
