### ISSUE TITLE
'Save' button causes Warning: Received true for a non-boolean attribute pristine

### ISSUE THREAD

**Issue by afilp** [marmelab/admin-on-rest#1608]
When using the `Save` button, we get a warning:

`Warning: Received true for a non-boolean attribute pristine.`

**What you were expecting:**
No warning

**What happened instead:**

![image](https://user-images.githubusercontent.com/7850073/36952545-16d30cc2-201a-11e8-862d-c8c8f0d3974d.png)

**Steps to reproduce:**

**Related code:**

```
<SaveButton label="post.action.save_and_add" redirect={false}
                 submitOnEnter={false} variant="flat"
  />
```

**Environment**

* Admin-on-rest version:  'next' latest BETA

**Comment by fzaninotto** [comment]
I can't reproduce the bug on `next`. 

Feel free to reopen if you manage to find a way to reproduce it in the simple demo.
