### ISSUE TITLE
<DateInput> for next: Proposal

### ISSUE THREAD

**Issue by afilp** [marmelab/admin-on-rest#1609]
I am aware that MUI provides only the native date picker in their '1.0.beta' that is used in 'next'.
(as mentioned here: https://github.com/mui-org/material-ui/issues/4787 )

The problem is that this is too restrictive. It does not show the dates in non-US locale (even though I have a Greek locale in my Windows 10). And there seems to be no solution out there to change the locale (it has to be based on the user's environment and this does not work in my case, in Windows 10).

May I recommend that we add the following Date Picker (just the date picker would work) in 'react-admin'?
https://github.com/dmtrKovalenko/material-ui-pickers

**What you were expecting:**
Better date picker

**What happened instead:**
No locale supported in native picker

**Environment**

* Admin-on-rest version:   'next'

**Comment by djhi** [comment]
We won't provide it by default. You're free to create an addon for it though.

**Comment by afilp** [comment]
Thanks for the answer. 
I was kind of worried because I do not see any activity (commits, etc.) for the last 9 days. 

Is the project still active?

**Comment by fzaninotto** [comment]
You mean there has been no commits for *an entire week*? You're right, everything indicates that the project is dead already. Those contributors have probably switched to Vue.js or something.

**Comment by fzaninotto** [comment]
OK, @djhi told me that I'm a bit harsh. I apologize, and I didn't want to upset you. It's just that your question sounded a bit ridiculous, especially considering all the work we've poured into admin-on-rest already.

Rest assured (pun intended), admin-on-rest is live.

**Comment by afilp** [comment]
@fzaninotto Hey Francois, I apologize if it sounded like this, I did not have this intention, just worried if the project will slow down.

Personally I try to contribute with (possible) bug reports or minor changes for 'next', it is just very difficult to contribute with better code since there are so many concepts at stake to be understood. This is why some feedback from you may also help us (contributors/users) to help you, hopefully without distracting you.

Thanks again.
