### ISSUE TITLE
Support another UI component framework

### ISSUE THREAD

**Issue by mivion** [marmelab/admin-on-rest#161]
Hi,

Is there any plans/ideas to support another UI component framework, like [Semantic-UI](https://github.com/semantic-org/semantic-ui/), which supports react components.

Thanks for your work!

**Comment by fzaninotto** [comment]
Hi,

No, not rom the core team, but the loosely coupled architecture should make it fairly easy: keep the actions and redcers, and use your own components (replacing the ones under `mui/`).
