### ISSUE TITLE
Linking from page with form to another page with form destroys the redux-form

### ISSUE THREAD

**Issue by nik-lampe** [marmelab/admin-on-rest#1613]
**update**

All the debugging lead me to this:
https://github.com/erikras/redux-form/issues/3435

It is a problem with React 16 and the way redux-form handles the initializing and destroying of the forms in their components lifecycle 

**What you were expecting:**
I am linking from an edit page with a form to a create page with a form passing some values by the query parameters. I am trying to fill these parameters as default values to the form. That's how I found this.

**What happened instead:**
It looks like the destroyOnUnmount function of redux-form destroys the form **after**  it has been initalized.

Maybe this comes somewhere between redux-form 6.6.3 which is used in aor 1.2.1 and redux-form 7.0.4

**Related code:**
See an example application here:
https://github.com/nik-lampe/admin-on-rest-form-destruction

I had problems recreating this bug in the older version of admin-on-rest which is included in the CodeSandbox you're refering to: https://codesandbox.io/s/ElxGNxBY0

It seems to work with admin-on-rest 1.2.1. I have made a branch in the repo for this.

But updating the dependencies in the CodeSandbox seem to break the code, that's why I just created the sample application.

**Steps to reproduce:**
1. Click on comments list.
2. Click an create.
3. See the initial value for the body.

Then:
1. Click on posts list. 
2. Edit any Post.
3. Click on "Add Comment" in the action bar.
4. The body value should have a default value 'Test Body' but it doesnt. (I am not actually using any of the query parameters, I made this link just to show me use case for why I built it)
5. Debugging the redux store shows the destruction of the record-form

1.4.0:
![admin-on-rest 1.4.0](https://user-images.githubusercontent.com/2122212/37032338-7118326a-2142-11e8-953a-af5846050d68.png)

1.2.1:
![admin-on-rest 1.2.1](https://user-images.githubusercontent.com/2122212/37032333-6c9c6bca-2142-11e8-9f6c-c547be105b11.png)

**Environment**

* Admin-on-rest version: 1.5.0
* Last version that did not exhibit the issue (if applicable):

**Comment by nik-lampe** [comment]
As I am using a customized version of admin-on-rest anyway I hacked together a temporary fix which is mentioned here https://github.com/erikras/redux-form/issues/3435#issuecomment-359371803

This is **not a fix**, just a very hacky workaround

**Comment by jpetitcolas** [comment]
We just found a way to fix it. We are working on it tomorrow. Should be ready in next release.

**Comment by fzaninotto** [comment]
It's fixed for the filter form in https://github.com/marmelab/admin-on-rest/pull/1616/files#diff-0c7e48ec3f03db5532bb24babd4872b8R184. We need to fix it in the create and edit forms.

**Comment by fzaninotto** [comment]
Fixed by #1618
