### ISSUE TITLE
injectTapEventPlugin() Called Twice in My Application

### ISSUE THREAD

**Issue by yoonwaiyan** [marmelab/admin-on-rest#162]
```injectTapEventPlugin(): Can only be called once per application lifecycle.\n\n\
It is recommended to call injectTapEventPlugin() just before you call \
ReactDOM.render(). If you are using an external library which calls injectTapEventPlugin() \
itself, please contact the maintainer as it shouldn\'t be called in library code and \
should be injected by the application.
````
I understand that we can use `admin-on-rest` on any application not just as a standalone app, but it seems like the injectTapEventPlugin() is causing my Meteor pages not loading with this error because my Meteor application is using MaterialUI as well. I have tried patching both Admin.js and Layout.js to remove the injectTapEventPlugin() call in Layout, but this doesn't work either.

I suspect it's because it's already been called when the export statements are being called, because I'm still importing components from `admin-on-rest/lib/mui` which exports `Layout` as well. Opening this issue to see whether it's possible to have any workaround on this package first as we have tried different workarounds on our Meteor app itself but nothing seems to work, and the plugin error itself mentioned to contact package maintainer if this issue arises.

**Comment by ArnaudD** [comment]
I have the same problem. My workaround was to duplicate `admin-on-rest/src/mui` in my sources and comment one line :

```js
export * from 'admin-on-rest/lib/mui/button';
export * from 'admin-on-rest/lib/mui/detail';
export * from 'admin-on-rest/lib/mui/field';
export * from 'admin-on-rest/lib/mui/input';
// export * from 'admin-on-rest/lib/mui/layout';
export * from 'admin-on-rest/lib/mui/list';
export Delete from 'admin-on-rest/lib/mui/delete/Delete';
```

**Comment by fzaninotto** [comment]
I suppose you're using React v15.4.0. It recently introduced a regression, and we can't upgrade yet (see #155 for an explanation). So I suggest you use react v15.3.2 instead.

**Comment by yoonwaiyan** [comment]
Apparently tried both solutions but it seems way too complex to make it work in the Meteor application, but removing the function call entirely from the application and let the Layout do the same job for our local MaterialUI seems to work now. 

Closing this for now, hopefully the newer updates in the near future will solve the problem.
