### ISSUE TITLE
Ability to set "Body background" colour to a custom colour

### ISSUE THREAD

**Issue by angshuman-agarwal** [marmelab/admin-on-rest#1620]
Can the body background be exposed such that it can be set without writing a custom layout ? 

Currently, it is hardcoded as `backgroundColor: '#edecec'` [here](https://github.com/marmelab/admin-on-rest/blob/master/src/mui/layout/Layout.js#L30)

Or is there a workaround to overcome this currently (apart from supplying own layout just for setting colour) ?

**Comment by mbj36** [comment]
This would really be a good feature!

**Comment by fzaninotto** [comment]
In the `next` version, the body background uses the theme background color. Change the theme, and this changes the background color.

We won't be implementing new features on `master`, so I'm closing this issue.

**Comment by angshuman-agarwal** [comment]
Thanks. When would that version be expected ?

**Comment by fzaninotto** [comment]
You can already test the beta 3, which is close to the final version.
