### ISSUE TITLE
Undoable edit and refresh

### ISSUE THREAD

**Issue by tkvw** [marmelab/admin-on-rest#1626]
When you refresh an edit resource you'll get unexpected behaviour using `undoable` edits, see the behaviour below: 
![2018-03-09_11-04-00](https://user-images.githubusercontent.com/621098/37202044-b91d286a-2389-11e8-8e0b-a03586f9547a.gif)
There should be a check if the resource is empty.

**Comment by fzaninotto** [comment]
Yes, that's a side effect I've noticed. As we invite users to use the aor Refresh button instead, I consider it's not a blocker.

**Comment by fzaninotto** [comment]
Fixed by #1728
