### ISSUE TITLE
Issue with run-graphcool-demo

### ISSUE THREAD

**Issue by codergr** [marmelab/admin-on-rest#1628]
**What you were expecting:**

Test run-graphcool-demo

**What happened instead:**

Application starts however i get an Unhandled rejection message

**Steps to reproduce:**

make run-graphcool-demo
login to application
after a 1-2 seconds 

**Other information:**

![dashboard](https://user-images.githubusercontent.com/9359043/37216446-0f755986-23bb-11e8-99a5-0125474a93cd.gif)

**Environment**

* Admin-on-rest version: lerna ( commit 73414972c9b62207ccc64f429d1a96b9b13d8c70 )
* React version: 16.0.0
* Browser: Chrome

**Comment by fzaninotto** [comment]
Fixed by #1663
