### ISSUE TITLE
Have resource render it's own route

### ISSUE THREAD

**Issue by tkvw** [marmelab/admin-on-rest#1629]
Is there a specific reason to map each child and create the `Route` for it instead of simply having the `Resource` to create it's own route? This would allow to create `Resources` anywhere (just like `react-router`). 
https://github.com/marmelab/admin-on-rest/blob/73414972c9b62207ccc64f429d1a96b9b13d8c70/packages/ra-core/src/RoutesWithLayout.js#L31-L41

The reason I am asking this is that I want to allow other type of components inside `<Admin>` that would render it's own routes. (I know of customRoutes).

**Comment by fzaninotto** [comment]
`<Switch>` only accepts `<Route>` children. If we cloned the `<Resource>` and let it create a `<Route>`, the switch wouldn't work.

https://reacttraining.com/react-router/core/api/Switch

Does it answer your question?

**Comment by tkvw** [comment]
Yeah, off course *brain fart*, thanks for the feedback
