### ISSUE TITLE
Filter `classes` prop does not apply styles

### ISSUE THREAD

**Issue by afilp** [marmelab/admin-on-rest#1632]
**What you were expecting:**
`<Filter>` to use the styles of the `classes` prop:

```javascript
<Filter {...props} classes={{form: {backgroundColor: 'yellow'}}}>
```

Based on docs: https://github.com/marmelab/admin-on-rest/blob/next/UPGRADE.md#customizing-styles

**What happened instead:**
No effect in styling. I get `[object Object]` as className.

![image](https://user-images.githubusercontent.com/7850073/37236963-2731f542-2416-11e8-8589-e7ce2b54a4a0.png)

**Related code:**
```javascript
<Filter {...props} classes={{form: {backgroundColor: 'yellow'}}}>
```

**Environment**

* Admin-on-rest version:  'next', latest commit
* React version:  16.2

P.S. If I may ask, is there a way to provide styles for `FilterForm` too?

**Comment by in19farkt** [comment]
```
import { Filter } from 'react-admin';
import { withStyles } from 'material-ui/styles';
const styles = {
    form: { backgroundColor: 'yellow' },
};
const CustomFilter = ({ classes, ...props }) => (
    <Filter {...props} classes={classes}>
);
export default withStyles(styles)(CustomFilter);
```

**Comment by afilp** [comment]
@in19farkt Thank you. I assume we cannot do the same for the internal components, like `FilterForm`, unless we recreate the Filter code in userland.

**Comment by afilp** [comment]
@djhi

If we also send `classes` as a prop here (it is not on `rest` prop anymore as it was destructured), wouldn't we then be able to customize `FilterForm` through our apps?

https://github.com/marmelab/admin-on-rest/blob/next/packages/ra-ui-materialui/src/list/Filter.js#L84-L86

Do you agree with this change or I am missing something bigger?
