### ISSUE TITLE
Toolbar overflows outside screen by the size of the drawer, hiding part of the button label

### ISSUE THREAD

**Issue by afilp** [marmelab/admin-on-rest#1637]
UPDATE: I submitted a PR for this: https://github.com/marmelab/admin-on-rest/pull/1638

**What you were expecting:**
Toolbar at bottom (with 'Save' buttons) not to overflow outside the screen when the drawer is semiopen or fully open and the window is not small or very large.

**What happened instead:**
Toolbar overflows, so the 2nd `Save` button label gets out of the screen

![image](https://user-images.githubusercontent.com/7850073/37259027-7796d416-2589-11e8-9004-ef23c1f5b770.png)

![image](https://user-images.githubusercontent.com/7850073/37259029-7d840362-2589-11e8-92fd-c9a752d5c6f9.png)

**Steps to reproduce:**
Experience this in Sandbox for `next`:
https://codesandbox.io/s/0y4pqp3nwn

Resize the window.

**Related code:**

This is why it happens, in `small` it goes like that (but the drawer does not disappear in the same `small` range.
```
const styles = {
    mobileToolbar: {
        position: 'fixed',
        bottom: 0,
        width: '100%',
        backgroundColor: 'white',
        justifyContent: 'flex-end',
        zIndex: 2,
    },
};
```

**Other information:**

**Environment**

* Admin-on-rest version:  'next' (latest commit), same in BETA-2

**Comment by fzaninotto** [comment]
Fixed by #1656
