### ISSUE TITLE
Integrating Admin-On-Rest 2.0 in a current app but with Material-UI 1.0 throws some errors and a never Ending Error appears.

### ISSUE THREAD

**Issue by ngerolami** [marmelab/admin-on-rest#1642]
**What you were expecting:**
Using Admin-On-REst 2.0 inside a current react application I was expecting to have displayed the site as an inner site. 

**What happened instead:**
Adding the <Admin dataProvider={...}> it display a Loading message and it never ends.

**Environment**

* Admin-on-rest version: 2.0
* Last version that did not exhibit the issue (if applicable): 1.4
* React version: 16.0.0
* Browser: Chrome, IE 10

**Comment by fzaninotto** [comment]
Hi Nicolas,

Your issue doesn't contain enough elements for us to help you. 

Did you read the upgrade guide? 

Could you add:

- the precise admin-on-rest version (aor version 2 wasn't released yet)
- the relevant part of the code where you insert admin-on-rest inside your application
- the error you're seeing in the console

**Comment by fzaninotto** [comment]
No news for some time, closing. Feel free to reopen if you still have the problem.
