### ISSUE TITLE
Resources disappear after page refresh (only works after second login)

### ISSUE THREAD

**Issue by szokolb** [marmelab/admin-on-rest#1652]
I'm trying to dynamically generate the resources (menu items) for my admin app but the `<Resource .../>` elements are not there after the first login

Sample code (App.js) below

```

.....
componentWillMount() {
    let that = this;
    this.fetchModules().then(() => {
          console.log("Load finished");
          that.setState({loadFinished: true});
      });
});
....

```

I have a function that loads the mapped resources into state

```

....
fetchModules() {
    let that = this;
    if (App.isLoggedIn()) {
      axios.get(`${process.env.REACT_APP_BACKEND}/modules`, {
        headers: {
          'Authorization': "Bearer " + App.token
        }
      }).then((response) => {
         that.setState({modules: response.data});
      }).catch((e) => {
         console.log(e);
      });
    }
  }
.....

```

and I have the render method below where the modules from the state are mapped like this:

```
....

render() {
    let loadFinished = this.state && this.state.loadFinished;
    console.log("loadFinished", loadFinished);
    return (
    <Admin dashboard={Dashboard} authClient={authClient} restClient={myApiRestClient} loginPage={Login}>
    {
      loadFinished &&
      this.state.modules.map((module, i) => {
        return <Resource key={i} name={module.name} list={GeneralList} edit={GeneralEdit} create={GeneralCreate} remove={Delete} />
      })
    }
  </Admin>)
  }

....
```

All the mapped resources are available in both the `fetchModules` and the `render`  functions if I try to console.log() them but the left side menu remains empty.

On the other hand if I press logout, then log back in all the previously hidden menuitems are there. That is until I press F5 again because after that they disappear again.

I also noticed that in the global state `state.admin.resources` is an empty object the first time logging in.
After logging in the second time all the resources are there as well

**Environment**

* Admin-on-rest version: ^1.4.0
* React version: ^15.4.0
* Browser: Chrome 64
* Stack trace (in case of a JS error):

There's only one error in the console. I'm not sure if it's related:

```
<Provider> does not support changing `store` on the fly. It is most likely that you see this error because you updated to Redux 2.x and React Redux 2.x which no longer hot reload reducers automatically. See https://github.com/reactjs/react-redux/releases/tag/v2.0.0 for the migration instructions.
```

**Comment by fzaninotto** [comment]
Admin-on-rest supports another way of doing that, see https://marmelab.com/admin-on-rest/Authorization.html#restricting-access-to-resources-or-views
