### ISSUE TITLE
FieldTitle - Does not update the Foreground colour based on custom mui theme

### ISSUE THREAD

**Issue by angshuman-agarwal** [marmelab/admin-on-rest#1654]
The [FieldTitle](https://github.com/marmelab/admin-on-rest/blob/49a616c93d1ee5ea0bfa3c5f7abea0bb29c8d01c/src/util/FieldTitle.js) is a `span`. Not able to style it from custom mui Theme.

**Use case:**

So, when I am applying a custom muiTheme, the _Label_ colour of [TextInput](https://github.com/marmelab/admin-on-rest/blob/master/docs/Inputs.md#textinput) never gets updated. And when I click on the Text Input to type, the _Label_ seems to be taking the` Primary Colour` .

Is there a way to set the style/colour for the `FieldTitle` of  any type of [Input](https://github.com/marmelab/admin-on-rest/blob/master/docs/Inputs.md) including [DisabledInput](https://github.com/marmelab/admin-on-rest/blob/f10a9f4da632a4ad7924ec7cdf3eb89bcea9872a/src/mui/input/DisabledInput.js) ?

**Comment by fzaninotto** [comment]
I don't understand your problem. Can you add screenshots? 

A `<span>` takes the background color of the enclosing element, which is the `<Input>` component. If the Input components use the theme, you should be able to override the label, too. But that's a materiel-ui question more than an admin-on-rest question IMO.

By the way, which version of admin-on-rest are you using?

**Comment by angshuman-agarwal** [comment]
_>> Can you add screenshots?_
Not able to upload one atm, getting github error saying "we can't process the file" - although it is a 10KB jpg.

_>> If the Input components use the theme, you should be able to override the label, too_
OK, let me put it simply like this -  How do I style the AOR  `TextInput` where I can control the FieldTitle colour separately ? Will be great if you could you share a sample please ? 

>>But that's a materiel-ui question more than an admin-on-rest question IMO.
So, when I click on a `TextInput` how does the `FieldTitle` automatically takes the `PrimaryColor` 

_>>By the way, which version of admin-on-rest are you using?_
1.4.0

**Comment by fzaninotto** [comment]
You can't control the `FieldTitle` color. That's not a feature of admin-on-rest. 

As for styling the `label` of a material ui input, I invite you to check the material ui documentation. 

I'm closing this as I think there is no bug. Feel free to reopen if you think otherwise.

**Comment by angshuman-agarwal** [comment]
Hi,
I think this is a Bug. Please find the screenshot. I just modified the sample from tutorial with custom theme.

`
// in src/App.js
import React from 'react';
import { jsonServerRestClient, Admin, Resource } from 'admin-on-rest';
import getMuiTheme from 'material-ui/styles/getMuiTheme';
import { PostList, PostEdit } from './posts';
import spacing from 'material-ui/styles/spacing';

const myTheme = {
  spacing: spacing,
  fontFamily: 'Roboto, sans-serif',
  palette: {
    primary1Color: '#FF8C00',
   // primary2Color: cyan700,
    //primary3Color: grey400,
    //accent1Color: pinkA200,
    //accent2Color: grey100,
    //accent3Color: grey500,
    textColor: '#FFFFFF',
//    alternateTextColor: '#FFFFFF',
    canvasColor: '#000000',
    //borderColor: grey300,
    //disabledColor: fade(darkBlack, 0.3),
    //pickerHeaderColor: cyan500,
    //clockCircleColor: fade(darkBlack, 0.07),
    //shadowColor: fullBlack,
  },
};

const App = () => (
    <Admin theme={getMuiTheme(myTheme)} restClient={jsonServerRestClient('http://jsonplaceholder.typicode.com')}>
        <Resource name="posts" list={PostList} edit={PostEdit}/>
    </Admin>
);

export default App;

`


![1](https://user-images.githubusercontent.com/1796126/37434045-2a91b0b0-27d6-11e8-9d49-3d87911e2256.png)
![2](https://user-images.githubusercontent.com/1796126/37434055-2f27a6de-27d6-11e8-9e84-b101ebb2b381.png)
![3](https://user-images.githubusercontent.com/1796126/37434061-33d7a26a-27d6-11e8-8997-245e1123459a.png)

**Comment by fzaninotto** [comment]
I suggest you try with just Material UI components, without admin-on-rest. My opinion is that if there is a bug, it is on their side. Admin-on-rest does not alter the color of the field title in any way.

**Comment by angshuman-agarwal** [comment]
Hi,
Thanks. It is not just one use case. Please see the 3rd screenshot. I believe it is the way Theming is being handled in AOR (which internally uses MaterialUI components). Is there a way to customise the Theme more elegantly with AOR or some pointers which you can provide by means of some source code ?

_>>I suggest you try with just Material UI components, without admin-on-rest._
Sorry, I did not understand this. As you can see I am using AOR components as I am building upon that library.

**Comment by fzaninotto** [comment]
As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by angshuman-agarwal** [comment]
Done - https://stackoverflow.com/questions/49296717/aor-bug-in-theming-when-applying-custom-themes

**Comment by angshuman-agarwal** [comment]
Referring to the comment here - https://github.com/marmelab/admin-on-rest/issues/1654#issuecomment-373289906
_>>Admin-on-rest does not alter the color of the field title in any way._

`BooleanInput' does alter label colour internally - https://github.com/marmelab/admin-on-rest/blob/0208d9d32d8ef9165ff9d23dca92f91e0156422f/src/mui/input/BooleanInput.js which is causing more issues. 

Any way to udpate this ?
