### ISSUE TITLE
Delete Action does not allow to add custom page title like List and Edit

### ISSUE THREAD

**Issue by angshuman-agarwal** [marmelab/admin-on-rest#1661]
On `DELETE`, [the page title](https://github.com/marmelab/admin-on-rest/blob/b8215cde6113041f1a3c2ca15e31f177d3178dcf/src/i18n/messages.js#L25) by default is coded like this :
`delete: 'Delete %{name} #%{id}'`

Since it takes the `name` from the `Resource` component, the Title on the Delete page rendered by AOR is not user-friendly. Instead it should read the `Title` directly from the `page` (Edit/List) and if not found then fallback on name.

**Comment by fzaninotto** [comment]
Are you referring to the `master` branch? In `next`, there is only a notification about deletion now.

**Comment by angshuman-agarwal** [comment]
I am using version `1.4.0`

**Comment by fzaninotto** [comment]
You can use a custom `Delete` component and give it the wording you like. 

Besides, we won't add new features to the 1.x branch. Check the `next` branch for a better user experience.

**Comment by angshuman-agarwal** [comment]
_>> You can use a custom Delete component and give it the wording you like._
Thank you, could you point me to a sample or link for this ?

**Comment by angshuman-agarwal** [comment]
Thanks a lot !
