### ISSUE TITLE
BooleanInput alters the label colour internally

### ISSUE THREAD

**Issue by angshuman-agarwal** [marmelab/admin-on-rest#1667]
`BooleanInput` alters the [label colour](https://github.com/marmelab/admin-on-rest/blob/0208d9d32d8ef9165ff9d23dca92f91e0156422f/src/mui/input/BooleanInput.js#L11) internally - which is causing issues when used in a dark theme

No suitable way to update the Colour.

**Comment by fzaninotto** [comment]
Can you update your issue using the Issue template please?

**Comment by angshuman-agarwal** [comment]
Please do not submit support requests or "How to" questions here. For that, go to [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest).

**What you were expecting:**
BooleanInput control's Title should show up clearly like other controls when a custom DarkTheme is applied. Or I should be able to set the Label colour

**What happened instead:**
The label did not render correctly as it got merged with background - See code: https://github.com/marmelab/admin-on-rest/blob/0208d9d32d8ef9165ff9d23dca92f91e0156422f/src/mui/input/BooleanInput.js#L11

**Steps to reproduce:**


**Related code:**


```
insert short code snippets here
```

**Other information:**


**Environment**
Windows 7 OS

* Admin-on-rest version: 1.4.0
* Last version that did not exhibit the issue (if applicable): NA
* React version: 
 "react": "^16.2.0",
  "react-dom": "^16.2.0",
* Browser: Chrome Version 64.0.3282.119 (Official Build) (64-bit)
* Stack trace (in case of a JS error): NA

**Comment by fzaninotto** [comment]
It's fixed in `next`. Must be fixed on `master`.

**Comment by angshuman-agarwal** [comment]
Thanks.

>> Must be fixed on master.
So will you release a patch i.e. 1.4.1 ?

>> It's fixed in next.
When will next go out of "pre"
