### ISSUE TITLE
Checkbox select and unselect issue in List page

### ISSUE THREAD

**Issue by santhosh1190** [marmelab/admin-on-rest#1674]
Hi,
I am facing the checkbox issue in List page.

I have selected the some rows from list. After that If I click any place on the page which means outside of Grid, the selected checkbox became unselect.
I do not understand why it is happening like this.

Due to this problem, After selected rows I am not able to click the button to perform action on selected rows.
Someone help me please!

![test](https://user-images.githubusercontent.com/11721441/37611538-9a8baa88-2bc8-11e8-8c66-c13b2daf4a95.png)

**Comment by fzaninotto** [comment]
Can't reproduce on `next`.

Can you please use the issue template and answer all the questions, which are really necessary for us to determine where the problem is?

**Comment by santhosh1190** [comment]
I am really sorry fzaninotto,  Now I have read the issue template. Below I have answered the all the questions of issue template. Please take a look.

**What you were expecting:**

1. Added the Checkbox in Grid view.
2. Selected some rows from the list.
3. I added a button name called CLONE on the top right corner of the table.
4. Click on the button, I wanted to get the selected rows ID's list.

**What happened instead:**

1. Added the Checkbox in Grid view
2. Selected some rows from the list
3. I added a button name called CLONE on the top right corner of the table.
4. Click on the button, the selected rows have been unchecked automatically. This is happening click on the outside of GRID any place on the page.

**Steps to reproduce:**

1. Create a list page with the selectable checkbox.
2. Select the one or more rows from the list.
3. Click outside of the GRID any place on the page, then selected checkbox would unselect automatically. 

**Related code:**

`class CustomDataGrid extends Component{

    handleRowClick = (rowArr) => {
        const {ids, data, handleSelection} = this.props;
        if (Array.isArray(rowArr)) {
            handleSelection(rowArr.map(row => data[ids[row]]));
        } else {
            const dataArr = rowArr == 'all' ? data : [];
            handleSelection(dataArr);
        }
    }

    render(){
        return <Datagrid headerOptions={{ adjustForCheckbox: true, displaySelectAll: true }} 
                    bodyOptions={{ displayRowCheckbox: true }} 
                    rowOptions={{ selectable: true }} 
                    options={{ multiSelectable: true, onRowSelection: this.handleRowClick}}
                    {...this.props}
                >
                    <TextField source="id" />
                    <TextField source="name" />
                    <TextField source="username" />
                    <EmailField source="email" />
                </Datagrid>
    }
}

const PostActions = ({ resource, filters, displayedFilters, filterValues, basePath, showFilter }) => (
    <CardActions style={cardActionStyle}>
        <CloneButton resource={resource} filters={filters} />
    </CardActions>
);

class UserList extends Component{

    handleSelection(data){
        console.log(data);
        debugger;
    }

    render(){
    return <List title="All users" {...this.props} actions={<PostActions />} >
                <CustomDataGrid handleSelection={this.handleSelection} />
            </List>
    }
}

export default UserList;`

**Other information:**

**Environment**

1. Admin on rest version - 1.3.4
2. React version - 16.2.0
3. Browser - Chrome Version 60.*

**Comment by fzaninotto** [comment]
Bulk actions (with the checkbox in the datagrid) aren't supported in version 1.x. We've implemented them in `next`, though.
