### ISSUE TITLE
Create and ReferenceInput does not show

### ISSUE THREAD

**Issue by kairda** [marmelab/admin-on-rest#1678]
I have done the Tutorial with JSONPlaceholder.
When I click on Create on the Posts, I get to the "Create" Page, but the User SelectField is not selectable and does not show any of the available users.
I can see, that a request for the users has been performed.

I have the same issue with another sample project where I am trying to select some other users.
If the record already exists, the selection works fine -> In the edit view, the users selection is possible, but not when creating new entries?

**Comment by kairda** [comment]
I just found another post stating the same issue.
By adding 
allowEmpty={true}
to the ReferenceInput the Data can be selected.
(This is not what I expected, but at least this makes my example workable)
Suggestion: You should probably add this to the tutorial description.
And thanks for the great appliation!

**Comment by djhi** [comment]
Thanks for reporting this issue :)
