### ISSUE TITLE
Editable record[source] for field input

### ISSUE THREAD

**Issue by iyobo** [marmelab/admin-on-rest#170]
I am trying to create a custom field input ([FileInput](https://github.com/iyobo/jollofjs/blob/master/lib/admin/client/fields/file/FileInput.jsx)) such that the field needs to be able to set it's own values that make it to the final REST Post/put call in my [RestClient](https://github.com/iyobo/jollofjs/blob/master/lib/admin/client/rest/jollofRestClient.js).

In FileInput (~line 35), after the user selects the file and the preview is loaded, I am setting 
`this.props.record[this.props.source] = file;` However upon creating, I don't see the fileinput's value in my restClient's params.data (~line 117)  I know `this.props.input.value` is read-only, but I set it just as well anyway for sanity reasons.

What's the most elegant way to achieve this?

This is doubly important for when ArrayFieldInputs become a thing i.e. dynamically adding/removing from the nested value of a record in the input field before it is json stringified and pushed out from the restClient's end. This would be the next input type I will be creating and I intend to make it accessible to the community or as a PR.

**Comment by fzaninotto** [comment]
Did you look at out own attempt at implementing a `FileInput` (#77)?

**Comment by iyobo** [comment]
Actually, discovered that since this uses redux-forms, the correct way to go about it is `this.props.input.onChange(file)`.
Likewise `this.props.input.onChange('')` to clear the file input.

Thanks for showing that FileInput PR. I didn't know it existed before I figured it out.

**Comment by iyobo** [comment]
I'll probably stick with my implementation because the next Field type I'm creating is a generic ArrayField that allow for automatic adding, removal, and drag-drop-sorting of ANY field input type.

I'll share that one when done.

**Comment by christianpbrink** [comment]
@iyobo did you finish this? Would love to use and perhaps build on it.

**Comment by iyobo** [comment]
@christianpbrink sorry I did, but since then I pivoted into creating my own full admin UI for a NodeJS framework I created... [JollofJS](http://github.com/jollofjs).

**Comment by christianpbrink** [comment]
Cool! Bad link, though. Is it private?

**Comment by fzaninotto** [comment]
Note that `<FileInput>` is now one of the core aor input types (see [`<FileInput>` documentation](https://marmelab.com/admin-on-rest/Inputs.html#fileinput).

**Comment by iyobo** [comment]
@christianpbrink Sorry tyo. Link is [JollofJS](http://github.com/iyobo/jollofjs).
