### ISSUE TITLE
Custom Id for Datagrid failed with Module parse failed

### ISSUE THREAD

**Issue by grantliu** [marmelab/admin-on-rest#1702]
Please do not submit support requests or "How to" questions here. For that, go to [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest).

**What you were expecting:**
Use custom id as key of Datagrid

**What happened instead:**
Module parse failed: Unexpected token (134:49)
You may need an appropriate loader to handle this file type.
|                 
|                 return {
|                     data: json.map(resource => { ...resource, id: resource.jobId } ),
|                     total: 20
|                 };

**Steps to reproduce:**
Modify simple.js to the following, to allow custom id.

switch (type) {
            case _types.GET_LIST:
            case _types.GET_MANY_REFERENCE:
...
                
                return {
                    data: json.map(resource => { ...resource, id: resource.jobId } ),
                    total: 20
                };
            case _types.CREATE:
                return { data: (0, _extends4.default)({}, params.data, { id: json.jobId }) };
            default:
                return { data: json };
        }

**Related code:**

**Other information:**

**Environment**

* Admin-on-rest version: 1.5.1

**Comment by asliwinski** [comment]
It's a syntax error and it has nothing to do with AOR.
Try:
`data: json.map(resource => ({ ...resource, id: resource.jobId }) ),`
