### ISSUE TITLE
Login form layout in IE11

### ISSUE THREAD

**Issue by pavyarov** [marmelab/admin-on-rest#1705]
**What you were expecting:**
Login form displayed in the center of screen.
![image](https://user-images.githubusercontent.com/25486791/37997062-7d759f98-3222-11e8-80e1-ef65166f151d.png)

**What happened instead:**
Login form displayed at top of the screen.
![image](https://user-images.githubusercontent.com/25486791/37996971-31dccd2c-3222-11e8-9634-dd37e7255dd3.png)

**Steps to reproduce:**
Clone and install the minimal example app and try to login in ie11

**Other information:**
It's well-known IE bug: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/101414/
Workaround described here: https://github.com/philipwalton/flexbugs/issues/231

**Environment**
Admin-on-rest version: 1.4.0
React version: 16.2.0
Browser: IE 11

**Comment by pavyarov** [comment]
#1706

**Comment by fzaninotto** [comment]
Fixed by #1706
