### ISSUE TITLE
the command "make prettier" never finishes

### ISSUE THREAD

**Issue by JacquesBonet** [marmelab/admin-on-rest#1710]
Please do not submit support requests or "How to" questions here. For that, go to [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest).

**What you were expecting:**

I want to fomat my code.

I launch "make prettier" on the root folder 

Nothing happen.

**What happened instead:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Environment**

* Admin-on-rest version:
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by JacquesBonet** [comment]
There is also a problem on the pattern matching

Its specified "packages/ra-admin/src/**/*.js" than "packages/**/src/**/*.js"

**Comment by JacquesBonet** [comment]
Its seem to be a problem on my code.

**Comment by fzaninotto** [comment]
Fixed by #1711
