### ISSUE TITLE
Error engine `node` is incompatible when installing with yarn

### ISSUE THREAD

**Issue by tinhnguyen-ea** [marmelab/admin-on-rest#172]
When we install `admin-on-rest` with yarn, we're currently facing with this error:
```
error parchment@1.0.1: The engine "node" is incompatible with this module. Expected version "^5.3".
error Found incompatible module
```

I created a PR [here](https://github.com/marmelab/admin-on-rest/pull/171) to fix this issue.

**Comment by fzaninotto** [comment]
Fixed by #171
