### ISSUE TITLE
linkType on all components that use a link 

### ISSUE THREAD

**Issue by overburn** [marmelab/admin-on-rest#1726]
I would expect to have a linkType on all components that use the Link component to link to a resource. 
As of now I think only ReferenceField has it, not very consistent.

**Comment by fzaninotto** [comment]
Can you be more specific? Which component using Link are you thinking about?

**Comment by overburn** [comment]
SimpleList for example.

**Comment by fzaninotto** [comment]
`SimpleList` already has a `linkType` in `next`. Any other component?

**Comment by overburn** [comment]
Ah, it hasn't been published to npm yet. My bad, thanks!
