### ISSUE TITLE
Tab label not translatable

### ISSUE THREAD

**Issue by esoulution** [marmelab/admin-on-rest#1731]
I mix interface & domain translations as described here
https://github.com/marmelab/admin-on-rest/blob/master/docs/Translation.md

For List I get "Stations", for Tab "APP.STATIONS"

```
    <Tabs>
    <Tab label="app.stations">
        <List title="app.stations" {...props}>
```

**Environment**

* Admin-on-rest version: 1.4.0

**Comment by djhi** [comment]
That's because the `Tab` component from `admin-on-rest` is different from the one supplied by `material-ui` and should only be used insided a `TabbedShowLayout`.

Here you're mixing `Tabs` from `material-ui` and `Tab` from `admin-on-rest`.

Can you describe your use case ?

**Comment by fzaninotto** [comment]
Please share a larger part of your code. We need to know:

- where are you using a tab (in the Edit view? in the Show view?)
- where did you import the `Tab` from (admin-on-rest? material-ui?)

**Comment by esoulution** [comment]
My bad, used Tabs from material-ui, will try TabbedShowLayout instead
