### ISSUE TITLE
Every component should have a style property!

### ISSUE THREAD

**Issue by daumann** [marmelab/admin-on-rest#1732]
Hey guys, I love your work and really appreciate your efforts but I don't understand why some components do not have a style parameter.

I now have several "custom" components cloned in my code just so I can add a style property. What is your reasoning not to include a style property for let's say the `<Notifications />` component?

**Comment by fzaninotto** [comment]
Hi Dieter,

Thanks for the kind words. 

There is no reasoning behind having a custom style or not. We added one when we needed one.

There will be no change in `master`, but the `next` branch uses JSS, which makes ALL the admin-on-rest components customizable from a CSS standpoint. 

So I'm closing this issue as it's not relevant anymore in `next` and it will not be fixed on `master`.
