### ISSUE TITLE
Custom LoginPage / authClient not redirecting to actual List page after authentication

### ISSUE THREAD

**Issue by angshuman-agarwal** [marmelab/admin-on-rest#1733]
Please do not submit support requests or "How to" questions here. For that, go to [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest).

**What you were expecting:**
To get redirected to List page after authentication

**What happened instead:**
The  app stays on `/login`, but, if I `F12 (Dev tools)`, request has gone through and I get json data back in response successfully and moreover, there are no errors reported in the Console.

**Related code:**

**Auth Client**

```
import {AUTH_GET_PERMISSIONS,
    AUTH_LOGIN,
    AUTH_LOGOUT,
    AUTH_ERROR,
    AUTH_CHECK} from "admin-on-rest";

const auth = async (type:any, params:any) => {
        if (type === AUTH_LOGIN) {
            const { username, password } = params;
            const request = new Request('https://myAuthUrl', {
                method: 'GET',
                //body: JSON.stringify({ username, password }),
                //headers: new Headers({ 'Access-Control-Allow-Origin': '*'}),
            })
            var response = await fetch(request,{mode:'no-cors', credentials: 'same-origin'});
            //if (response.status < 200 || response.status >= 300) {
              //  throw new Error(response.statusText);
            //}

            // get token
            //return response.json();
            return Promise.resolve();
        }
        if (type === AUTH_LOGOUT) {
            localStorage.removeItem('token');
            localStorage.removeItem('role');
            return Promise.resolve();
        }
        if (type === AUTH_ERROR) {
            // ...
        }
        if (type === AUTH_CHECK) {
            //return localStorage.getItem('token') ? Promise.resolve() : Promise.reject();
        }
        if (type === AUTH_GET_PERMISSIONS) {
            //const role = localStorage.getItem('role');
            return Promise.resolve();
        }
    
        return Promise.reject('Unkown method');
    };

export = auth;
```
**Login - My requirement does not need username and password - by default dispatches to the login action which causes `authClient` above to call into the Auth url inside the case  `AUTH_LOGIN` - I reckon this page needs some tweaking ?**

```
import * as React from "react";
import { connect } from 'react-redux';
import { userLogin as userLoginAction } from 'admin-on-rest';

declare namespace Auth {
    type Props = {
        userLoginAction: any
    }
}

class Login extends React.Component<Auth.Props, {}> {
    componentDidMount(){
        const credentials = { };
        this.props.userLoginAction(credentials);
    }

    render() {
        return (<div/>);
    }
};

const component = connect(undefined, { userLoginAction })(Login);
export = component;
```

**Environment**

* Admin-on-rest version: 1.4.0
* React version: 16
* Browser: Chrome
* Stack trace (in case of a JS error): NA

**Comment by djhi** [comment]
That's because you commented out the `AUTH_CHECK` handling which is called by every pages to check whether the user is logged in ([documentation](https://marmelab.com/admin-on-rest/Authentication.html#checking-credentials-during-navigation)).

**Comment by angshuman-agarwal** [comment]
I see - thanks for that.

Also, why is it adding a `"Logout"` menu on it's own on the Left Drawer panel (inspite of a custom Login component) ? Any way to **get rid of that** ?

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!
