### ISSUE TITLE
Logout button is not reloaded with correct translation when locale changes

### ISSUE THREAD

**Issue by zavadpe** [marmelab/admin-on-rest#1736]
**What you were expecting:**
Logout button to be translated when locale changes.

**What happened instead:**
Logout button remains translated to locale Logout button was loaded with.

**Steps to reproduce:**
* open configuration and change locale from en to fr
* check whether logout button translation changes together with the rest of react-admin UI

**Other information:**
Issue can be reproduced in next branch demo.
Note that when user opens/closes side menu or reloads react-admin, logout button loads with correct translation. 

**Environment**

* react-admin: 2.0.0-beta4 
* react: 16.2.0

**Comment by fzaninotto** [comment]
Fixed by #1750
