### ISSUE TITLE
What can you tell us about "next"?

### ISSUE THREAD

**Issue by lazee** [marmelab/admin-on-rest#1738]
Hi, 

I'm so excited about the next branch. The switch to Material UI next and a new package system is perfect news for the project I'm using AOR within.

Can you say anything about the overall plans, what we can do to help, and maybe something about a timeline?

/Jakob

**Comment by fzaninotto** [comment]
Hi Jakob,

Thanks for your enthusiasm!

The `next` branch is feature freeze, we're fixing bugs to prepare a stable release. Consider it a Release Candidate (event if I didn't find the time to publish the RC package).

We plan to release it as stable when material-ui stops breaking BC and publishes a 1.0. As their schedule isn't public, ours isn't either... But until the stable release, most of what we'll do will upgrade to the latest material ui version and fix the regressions (not that we're happy with it, but that's the risk of basing a release on an alpha library).

As for helping out, please beta test the `next` branch in your own projects and report bugs or problems in the documentation, please help answering the StackOverflow question, and if you really want to help a lot, please publish articles and tutorials about your experience with admin-on-rest.

Cheers,

François

**Comment by lazee** [comment]
Great! Love it 😍

I'll start embedding it ASAP...
