### ISSUE TITLE
TextInput values not displayed after upgrade to 0.5.x

### ISSUE THREAD

**Issue by MattWilliamsDev** [marmelab/admin-on-rest#174]
While using `v0.4.0`, the `input` prop passed to `TextInput` has a `value` attribute that corresponds to `record[ source ]`.  After upgrading to `v0.5`, the `value` attribute is shown as an empty string instead of the correct value from `record[ source ]`.  As a result, the `TextInput` components all appear empty.

**Note:** the `record` prop still contains the correct values returned from the record in the API call.

The issue was first noted when upgrading to `v0.5.4`, and I have confirmed it doesn't work in my app as far back as `v0.5.1`.  I only tried `v0.5.1` since the release notes seemed to suggest `v0.5.0` wouldn't work anyway.

**Comment by fzaninotto** [comment]
I can't reproduce the problem:

![image](https://cloud.githubusercontent.com/assets/99944/20806423/220d952c-b7fb-11e6-8edd-8adde61bd427.png)

Did you run `npm install` after upgrading?

**Comment by MattWilliamsDev** [comment]
i did...including deleting the `node_modules/` dir prior to reinstall.  If I revert back to `v0.4.0`, it works.  When I move up, it's broken.

**Comment by MattWilliamsDev** [comment]
The only thing that appears to have changed directly with any of the mui input elements is the `show` prop, but not sure how/why that would affect this.

**Comment by fzaninotto** [comment]
`TextInput` is now decorated by redux-form's `<Field>` component, which handles validation. But it works on the apps that we have, you must have customized something. Could you share a minimum working code to showcase the bug?

**Comment by MattWilliamsDev** [comment]
That makes much more sense then.  I had created custom `Create` and `Edit` components based on the previous incarnations of the components in `lib/mui/` so that I could add hidden input values to the submit payload for an image upload.  I will look through the changes there and see what the problem is, then I will post an update here. 

@fzaninotto Thank you for your prompt reply.  I will let you know the status soon.

**Comment by MattWilliamsDev** [comment]
@fzaninotto After comparing my customized `Edit` component, the only difference was the line concerning `hasShow` (which had no overall effect), and the bit I added in `handleSubmit`.  The same goes for `TextInput`, which I had only changed in order to change the input value to `record[ source ]` from `input.value`.

### My edits in `mui/EditComponent.jsx`

```javascript
    handleSubmit ( record ) {
        if ( !record.type || !record.name ) {
            let elements = document.querySelectorAll( 'input[type=hidden]' );
            elements.forEach( el => {
                if ( el.name !== '' && el.value !== '' ) {
                    record[ el.name ] = el.value;
                }
            });
        }
        return this.props.crudUpdate( this.props.resource, this.props.id, record, this.getBasePath() );
    }
```

I'm not sure what else has changed since then, but when I moved back to `v0.5.4` it seems to work while still using my custom `Edit` component.  I switched the `TextInput` component back to using the one provided in `lib/mui/`.  Since I am no longer seeing any issues, it seems that this issue can be closed.  Thank you for your time and replies.
