### ISSUE TITLE
No matching version found for ra-dependent-input@^2.0.0-beta4

### ISSUE THREAD

**Issue by danejorgensen** [marmelab/admin-on-rest#1741]
Please do not submit support requests or "How to" questions here. For that, go to [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest).

**What you were expecting:**
ra-dependent-input to be available in beta4 build

**What happened instead:**
```
$ npm i
npm ERR! code ETARGET
npm ERR! notarget No matching version found for ra-dependent-input@^2.0.0-beta4
```

**Steps to reproduce:**
```
//package.json
  "dependencies": {
    "react-admin": "2.0.0-beta4",
    "ra-data-json-server": "^2.0.0-beta4",
    "ra-dependent-input": "^2.0.0-beta4",
   ...
  }
```

**Other information:**
If you attempt to use ra-dependent-input@2.0.0-beta3 with the react-admin@2.0.0-beta4, it fails on `lodash.set`

```
Failed to compile.

/node_modules/ra-dependent-input/lib/DependentField.js
Module not found: Can't resolve 'lodash.set' in '/node_modules/ra-dependent-input/lib'
```

**Environment**

* Admin-on-rest version: 2.0.0-beta4
* Last version that did not exhibit the issue (if applicable):   2.0.0-beta3
* React version:   16.X
* Browser: Chrome

**Comment by danejorgensen** [comment]
Nevermind, looks like it was merged into ra-core

https://github.com/marmelab/admin-on-rest/pull/1688

**Comment by antonioparisi** [comment]
@danejorgensen how did you solve this?
