### ISSUE TITLE
Filters should reset when selecting a new/same resource from the sidebar

### ISSUE THREAD

**Issue by CAYdenberg** [marmelab/admin-on-rest#1747]
**What you were expecting:**
When clicking on a resource in the sidebar, any selected filters should revert to their default values, especially since the URL changes to the base for that resource.

**What happened instead:**
Filters remain applied, although the URL implies there are no filters present. Hence if you reload the page at that point, you get a different set of results.

**Steps to reproduce:**
In the sample app, goto customers (https://marmelab.com/admin-on-rest-demo/#/customers). Pick Add Filter, then pick Segments and choose any one. Then goto a different resource and come back to customers (or just click customers again). The filter will still be applied (and is correctly shown in the UI), but the URL is back to https://marmelab.com/admin-on-rest-demo/#/customers. Hence if you reload the page or share the link the state will not be the same or reload.

Reproducible in the demo version.

**Environment**

* Admin-on-rest version: 1.4.0
* Last version that did not exhibit the issue (if applicable):
* React version: 16.2.0
* Browser: Chromium 65.0.3325.181
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment]
That's not a bug, that's a feature™.

We see lists as Excel sheets. When you switch from one sheet to the other, you don't expect the sorting and filtering to reset.

So we *want* that filtered lists stay filtered, even if users come back to it from the menu. If the user wants to remove filters, they can do it using the cross button close to each filter.

**Comment by madecki** [comment]
@fzaninotto Is there any possibility to reset them with every route change as it's described above? Some advices?

**Comment by christiaanwesterbeek** [comment]
@madecki Do you have a snippet available that removes the filter on route change (from resource click in the sidebar) with a custom saga?

> using the cross button close to each filter

Related: https://github.com/marmelab/react-admin/issues/2564

**Comment by Koli14** [comment]
Since the question was asked React Admin changed a lot, and there are a lot of new Hooks. Is there any simpler way now?

**Comment by djhi** [comment]
Yes, you can use a wrapped `Datagrid` as the `List` child which would retrieve the `ListContext` and call its `setFilters` in a useEffect without dependencies so that it runs only on mount

**Comment by puraminy** [comment]
The filter is done in another page (resource X) and I set the filters of a link to my target resouce (resource Y), so there is nothing to remove the filter when I click on menu fpr respirce Y. I think clicking on menu on such ocations must crear flltering because the url doesn't match the filtered contents.

Suppose, I have members and in Skill Page, I have a link to members pocessing that skill, so when I click on members I expect to see whole member and not those which was filtered somewhere else.

**Comment by slax57** [comment]
@puraminy this may help: https://marmelab.com/react-admin/Menu.html#resetting-filters-on-menu-click

**Comment by puraminy** [comment]
in addition to the resetting filters on menu click suggested by @slax57,I found that if I use Filter in my list page, then after loading the page, it automatically selects those filters and the user will know that the filters are active and can remove them:

const JobSeekerFilter = (props) => (
    <Filter {...props}>
      <SearchInput source="q" alwaysOn />
      <ReferenceInput label="Skills" source="skills" reference="skills">
        <SelectInput label="Skills" optionText="name" />
      </ReferenceInput>
    </Filter>
  )

and

  <List {...props} filters={<JobSeekerFilter />}>
