### ISSUE TITLE
Declare resources without any menu items

### ISSUE THREAD

**Issue by djhi** [marmelab/admin-on-rest#18]
Sometime you might not want to show a resource in the menu but still want to use it in parent entities. 

## Use case:

We have products and orders entities. Orders use another entity, OrderProduct. We don't want crud routes and menu for them. They're only editable through their order.
Maybe that could be an option on the `<Resource />` component.

**Comment by fzaninotto** [comment]
I think it's a use case for  using a custom `<Layout>`. Isn't it simpler?

**Comment by djhi** [comment]
Right, could be
