### ISSUE TITLE
Custom Error message from server

### ISSUE THREAD

**Issue by iyobo** [marmelab/admin-on-rest#180]
Is there a way to feed in error messages from the server upon a failure instead of just "Internal Server Error"?

**Comment by fzaninotto** [comment]
Error message notifications are a side effect, and as such, are handled by `redux-saga` in admin-on-rest. If you want to display custom notifications based on certain error messages, you need to write your own sagas. And for that, you'll need to bypass the `<Admin>` component and write a custom app, as described here: http://marmelab.com/admin-on-rest/CustomApp.html
