### ISSUE TITLE
Wrong exhibition

### ISSUE THREAD

**Issue by marciobueno1** [marmelab/admin-on-rest#186]
I followed the tutorial, but my App has the same problem shown by the [tutorial image](http://marmelab.com/admin-on-rest/img/simple-post-list.png)

Only 9 item are shown although in the bottom it says that item 1-10 should be visible in this page.

The same problem occurs in every page the items shown are: 1st (100-92), 2nd (90-82), 3rd (80-72), and so on.

**Comment by fzaninotto** [comment]
This is due to something poorly documented in `jsonServer` (see https://github.com/typicode/json-server/issues/436). A fix is incoming.
