### ISSUE TITLE
There is no title when appLayout is used

### ISSUE THREAD

**Issue by insekticid** [marmelab/admin-on-rest#190]
`import MyLayout from 'admin-on-rest/lib/mui/layout/Layout';
render(
    <Admin appLayout={MyLayout}`

Warning: Failed prop type: The prop `title` is marked as required in `Layout`, but its value is `undefined`.
Warning: Failed prop type: The prop `theme` is marked as required in `Layout`, but its value is `undefined`.

Bug is here: https://github.com/marmelab/admin-on-rest/blob/master/src/Admin.js#L15
Evaluated as: 

> appLayout = _ref$appLayout === undefined ? (0, _withProps2.default)({ title: title, theme: theme })(_Layout2.default) : _ref$appLayout;

so if you define appLaout you have no way how to attach title

**Comment by fzaninotto** [comment]
Something is wrong with your code: you're using the default layout as your custom layout. You should use your own component. 

Your custom layout should define the theme and the title - there is no way admin-on-rest can determine what you'll put inside your custom layout. 

I'll update the documentation to make that more obvious.
