### ISSUE TITLE
Custom layout with mat-ui tab

### ISSUE THREAD

**Issue by binhfoto** [marmelab/admin-on-rest#191]
Hi,

I'm customizing my layout with tab. I want to use tab instead of list view in menu.
I can render the Tab base on Resource.
I put Link inside Tab label.
I want to click on Tab having same action as Menu item.
But it does not work.

And I'm also stuck on how to render Tab content, it seems that I have many different {children}s in every <Tab></Tab>.

This is rather my own issue than admin-on-rest.
I have search but no example with Tab to study.

Any help is welcome.
Thank you very much.

**Comment by fzaninotto** [comment]
Hi, 

If you're looking for an example of custom list component, take a look at the cards list in the blog example:

https://github.com/marmelab/admin-on-rest/blob/7867690db6ae118754f5011c47becd912d863a50/example/comments.js#L46-L80

If you're looking for general help regarding the material UI Tab component, I advise you to use the material ui gitter channel instead.
