### ISSUE TITLE
Filter with default value

### ISSUE THREAD

**Issue by binhfoto** [marmelab/admin-on-rest#192]
Hi,

I think this is a nice feature we should have for filter.

* Default value should be available as well for fields in filter section, so that at the first loading time, we can see filter records. Such as user can see products are sold today, not the whole week/month.
I hope that my proposal can make more and more user to use this fantastic 'admin-on-rest'.

Thanks.

**Comment by wadjeroudi** [comment]
I think it's already possible by using filterValues use the Filter component.

**Comment by naibinh** [comment]
Yeah, it is.
Thank all.

**Comment by binhfoto** [comment]
Yeah, it is.
Thank all.
