### ISSUE TITLE
[RFC] Move WYSIWYG field outside this repo

### ISSUE THREAD

**Issue by jpetitcolas** [marmelab/admin-on-rest#195]
We are currently working on a light admin project without any need of WYSIWYG features. Hence, having to include Quill is quite heavy and useless (in our case).

May it be a good occasion to move it to another repo, something like `admin-on-rest-wysiwyg-field`?

**Comment by fzaninotto** [comment]
Great idea, 👍

**Comment by fzaninotto** [comment]
We already have a first third-party package related to admin-on-rest: [marmelab/aor-json-rest-client](https://github.com/marmelab/aor-json-rest-client).

**Comment by fzaninotto** [comment]
Fixed by #218
