### ISSUE TITLE
NumberField for null value

### ISSUE THREAD

**Issue by mivion** [marmelab/admin-on-rest#196]
Hi,
I have records with number fields which may be null.
NumberField throws exception for null, as of toLocaleString() call for null.

**Comment by mlotze** [comment]
Hi, 

I had a similar problem with the DateField.  It showed "1970-01-01" for null. I imlemented my own component to fix this. 

Copy the NumberField.js from the source rename and adjust it as you need it. 

`import React, { PropTypes } from 'react';
import get from 'lodash.get';

const NullableDateField = ({ source, record, style }) => {
    const value = get(record, source);
    return <span style={style}>{value ? new Date(value).toLocaleDateString() : ''}</span>;
};

NullableDateField.propTypes = {
    label: PropTypes.string,
    record: PropTypes.object,
    source: PropTypes.string.isRequired,
    style: PropTypes.object,
};

export default NullableDateField;`
