### ISSUE TITLE
Horizontal scrollbar in list view

### ISSUE THREAD

**Issue by mlotze** [marmelab/admin-on-rest#198]
Hi! 

Is there a simple way to add a horizontal scrollbar to the list view? 

The parent div of the rendered table-element needs "overflowX: auto" like 

`function setTableParentStyle() {
    var tablinks = document.getElementsByTagName('table');
    for (var i = 0, j = tablinks.length; i < j; i++) {
        tablinks[i].parentNode.style.overflowX = 'auto';
    }
}`

**Comment by fzaninotto** [comment]
I think it's no longer necessary since #193
