### ISSUE TITLE
something like embedded_list available?

### ISSUE THREAD

**Issue by underdoeg** [marmelab/admin-on-rest#205]
Is there any input field type available that functions similar to embedded_list in ng-admin?

**Comment by fzaninotto** [comment]
Not yet, and it's low in priorities. But you're welcome to work on it on your side and send us a pull request!

**Comment by wadjeroudi** [comment]
@fzaninotto Any idea how to implement it ?
Shoudn't it be just an enhancement of ReferenceManyField, but with a new flag ? data-src=embed or rest ?

**Comment by fzaninotto** [comment]
I'd be definitely easier than in admin-on-rest, since we don't need to centralize data fetching ahead of rendering. But I didn't give much thought to it yet, you'll have to give it some brain juice on your side!
