### ISSUE TITLE
Add permanentFilters to the List component

### ISSUE THREAD

**Issue by sublimeye** [marmelab/admin-on-rest#211]
I'd like to add additional (persistent) query params to <List/> index query. 

For example, using this:
`<CrudRoute path="items" list={ItemsList} />`

I want to add `?populate=messages` for  every `GET /items?populate=messages` request. And still have sort, filter options enabled.

**Comment by fzaninotto** [comment]
I'll rename your issue title to `permanentFilters`, as it's the name of that feature in ng-admin. This is indeed a required feature.

**Comment by sublimeye** [comment]
@fzaninotto Thanks. Is there an easy way to hack CrudRoute this way or the only way is to create a duplicate "CrudRoute" with additional prop|logic?

**Comment by fzaninotto** [comment]
Fixed by #245
