### ISSUE TITLE
How to edit ListItem property from the List view?

### ISSUE THREAD

**Issue by sublimeye** [marmelab/admin-on-rest#212]
I have a list of items:
```
<List {...props}>
    <Datagrid styles={datagridStyles}>
         <TextField source="name" />
         <TextField source="status" />
    ...
```
Is there a way to add a <SelectInput/> for one of the columns and be able to change a value from the dropdown options and update the item from the list view itself? (Without going into Edit flow)

**Comment by fzaninotto** [comment]
This is not something admin-on-rest will support, but it's easy to write as a React component, and to use as a field in the datagrid.

You'll have to [write a custom field component](http://marmelab.com/admin-on-rest/Fields.html#writing-your-own-field-component) that implements a form and does the saving by itself. You can look at the `Edit` and `SimpleForm` components for inspiration.
