### ISSUE TITLE
Error in addRecords after resource update

### ISSUE THREAD

**Issue by buz-zard** [marmelab/admin-on-rest#219]
Hello everyone,

After updating resource and upon returning to the item list I'm getting an exception: `utils.js:201 uncaught at handleFetch TypeError: Cannot read property 'id' of undefined`

At [addRecords function](https://github.com/marmelab/admin-on-rest/blob/d40dd496e3f4fe43cbe46de7cea96ca19e653b9d/src/reducer/resource/data.js), 38th row.

![image](https://cloud.githubusercontent.com/assets/3521740/21822963/fd1e391e-d781-11e6-9cab-7d34c4255af6.png)

The item list still gets rendered properly.

My dependencies: 
`{
    "admin-on-rest": "^0.6.2",
    "isomorphic-fetch": "^2.2.1",
    "react": "^15.4.2",
    "react-dom": "^15.4.2"
  },`

**Comment by fzaninotto** [comment]
admin-on-rest expects a new record as response to the `CREATE` REST request. Do you REST client return one?

cf. http://marmelab.com/admin-on-rest/RestClients.html#writing-your-own-rest-client

**Comment by buz-zard** [comment]
Ahh, yes I wasn't returning any body at all. Thanks!
