### ISSUE TITLE
css cannot import by browserify (with cssify)

### ISSUE THREAD

**Issue by chungchi300** [marmelab/admin-on-rest#220]
Hi ,I used browserify as my build tool.However I get following error.

 
ParseError: Unexpected character '@'
line 1
web-consumer-portal/node_modules/admin-on-rest/lib/mui/input/RichTextInput.css
@import "~quill/dist/quill.snow.css";
^

**Comment by fzaninotto** [comment]
I know how to tell `webpack` to use a special loader for CSS, but I have no idea for browserify - I don't use it.

I suggest you read the browserify documentation about how to make it work with projects using:

```js
require('foo.css');
```

Somewhere in their code. 

As it's not an admin-on-rest problem, I'm closing the issue, but feel free to comment with the solution once you've found it - it may help future browserify users like you.
