### ISSUE TITLE
Pass route params to custom REST API

### ISSUE THREAD

**Issue by rimallo** [marmelab/admin-on-rest#222]
Continuing the #113

Please, let me know, how to pass the route URI params to custom REST API?
Ex. `folder/:folderId/messages`

I can see it in `<List {...props} />`, but how to pass to `httpClient`?

`httpClient` receives string recourse `folder/:folderId/messages`, not a real `folder/23/messages`

**Comment by fzaninotto** [comment]
This is the job of the `restClient`, please see the [REST clients documentation](http://marmelab.com/admin-on-rest/RestClients.html).

**Comment by rimallo** [comment]
This issue is about my own CUSTOM REST API.
I'm trying action type `GET_LIST` on route `folder/:folderId/messages`. This is the list, not single record.

The only params for `GET_LIST` are `pagination` `sort` `range` `filter`.

How to CATCH `:folderId` parameter?

I've tried to apply dummy middleware and log incoming params
`sagaMiddleware.run(crudSaga((p1,p2,p3,p4) => { console.log('REST CLI ',p1,p2,p3,p4) }));`
but got got only
`p1=GET_LIST` 
`p2=controller/:controllerId/agent` 
`p3=params { pagination, sort, range, filter }`

Where does `:folderId` resides in?

**Comment by fzaninotto** [comment]
I don't know what you're trying to achieve, what is the `:folderId` supposed to contain? Can you tell me more about your REST API ?

**Comment by rimallo** [comment]
App flow

1. View folders list `folder` route + API call.
` <CrudRoute path="folder" ... />` - OK, works fine.

2. Select folder from `folder/:folderId/messages` route + API call to display list of messages in the selected `:folderId` folder.
` <CrudRoute path="folder/:folderId/messages" ... />` - not working. 
Sends to my custom REST API `resource = folder/:folderId/messages`, not the parameter with exact `:folderId` numeric value.

 ... other logic

**Comment by fzaninotto** [comment]
This is not supported. See the [`<ReferenceManyField>`](http://marmelab.com/admin-on-rest/Fields.html#referencemanyfield) for a way to display a list of `messages` in the `folder` edition view.

**Comment by rimallo** [comment]
Could this issue become a "feature request" or "enhancement request"?
It just so easy to push via props the current routeParams.

**Comment by fzaninotto** [comment]
What you should do is define a `messages` resource, and tweak your REST client to transform calls to `GET /messages?filter={'folderId':123}` to `GET /folder/123/messages`.
