### ISSUE TITLE
routeParams not available for Custom REST

### ISSUE THREAD

**Issue by rimallo** [marmelab/admin-on-rest#223]
Continuing the #113 and #222, issue is not resolved, sorry for copy.

I've coded my own `restClient`.

I'm trying action type `GET_LIST` on route `folder/:folderId/messages`. 
This is the list, not single record.

The only params for `GET_LIST` are `pagination` `sort` `range` `filter`.

How to CATCH `:folderId` Route parameter (`routeParams`)?

Even tried to apply dummy middleware and log incoming params
`sagaMiddleware.run(crudSaga((p1,p2,p3,p4) => { console.log('REST CLI ',p1,p2,p3,p4) }));`
but got only
`p1=GET_LIST` 
`p2=controller/:controllerId/agent` 
`p3=params { pagination, sort, range, filter }`

Where does `:folderId` resides in?

**Comment by rimallo** [comment]
Ugly solution is to additionally parse `resource`
`let hrefParams = resource.split('/') || null;`

**Comment by fzaninotto** [comment]
Please don't duplicate issues. Feel free to continue the discussion in #222
