### ISSUE TITLE
Display custom Notification / Snackbar

### ISSUE THREAD

**Issue by rimallo** [marmelab/admin-on-rest#226]
Followed all recommendations here http://marmelab.com/admin-on-rest/CustomApp.html
Got Custom App draft.

How to display that `<Notification />` `<Snackbar>` component rendered in layout?

I need it when a user clicks on a button within row in `List`.

```
import showNotification from 'admin-on-rest/lib/actions/notificationActions';

const ButtonModeView = ({ record = {}, source }) =>
        <FlatButton
            label="VIEW MODE "
            secondary={true}
            icon={<IconActionPageView />}
            onClick={(e) => {
                showNotification('CLICK COOcoo');
            }}
        />
    ;

export const PostList = (props) => (
    <List {...props}>
        <Datagrid>
            ...
            <ButtonModeView source="locked" label="VIEW" />
        </Datagrid>
    </List>
);
```

This `showNotification` throws an error.

`Uncaught TypeError: (0 , _notificationActions2.default) is not a function`

**Comment by rimallo** [comment]
Additional research.
Converted `MyLayout` to component.

```
export class MyLayout extends Component {

    constructor(props) {
        super(props);
        this.state = {
            hideNotification: true,
            messageNotification : '123'
        }
    }

    ...

    render() {
        return (
                    ...
                    <Notification hideNotification={this.state.hideNotification} message={this.state.messageNotification} />
                    ...
        )
    }

```

Trying to 
```
                        onClick={
                            () => {
                                this.setState({ hideNotification: false });
                            }
                        }
```
Nothing happens...

**Comment by rimallo** [comment]
Solved by adding `Snackbar` to `MyLayout` render alongside original **admin-on-rest**'s `Notification`.
```
                    <Snackbar
                        open={this.state.openSnackbar}
                        message={this.state.messageNotification}
                        autoHideDuration={4000}
                    />
```

But the question stays the same. How to fire it from `CrudRoute.lis`?

**Comment by fzaninotto** [comment]
`showNotification` is an action creator, that you must `dispatch`, not call directly. You'll have to learn some  [redux](https://github.com/reactjs/redux) to do that.

**Comment by rimallo** [comment]
Thanks, @fzaninotto 
I know that in `App.js` we can `dispach` `SHOW_NOTIFICATION` action on store this way
`store.dispatch({ type: 'SHOW_NOTIFICATION', payload: { text: '12345' } })`

But how to dispatch inside list, inside layout, inside custom REST API, elsewhere.

**Comment by fzaninotto** [comment]
Inside a component: *connect* it (again, please read the redux doc).
Inside a custom REST API: you can't. But you can create a custom saga (see the redux-saga doc).

**Comment by rimallo** [comment]
I think someone would find this useful. It works fine in `Layout`. Will try in lists.
```
const mapDispatchToProps = (dispatch) => ({
    onSomeClick(id) {
        dispatch( { type: 'SHOW_NOTIFICATION', payload: { text: 'SELECTED ID ' + id } } );
    }
});
...
export class MyLayout extends Component {
                    ...
                    <ListItem
                        onClick={
                            () => {
                                this.props.onSomeClick('123');
                            }
                        }
                    />
                    ...
}
export default connect(mapStateToProps,mapDispatchToProps)(MyLayout);
```

**Comment by rimallo** [comment]
Works fine within List. The only speciality is to export connected list as a different const 
`export const visiblePostList = connect(mapStateToProps,mapDispatchToProps)(PostList);`
and import, use it inside `<CrudRoute list={visiblePostList} ... />`.
