### ISSUE TITLE
Make custom REST API call

### ISSUE THREAD

**Issue by rimallo** [marmelab/admin-on-rest#229]
I have a list of folders, maintained by `<CrudRoute list={FolderList} ... />`.
In one column of the folders list a have a button to "lock" the folder.
To lock a folder I have to POST/PATCH its `record.locked=2`.

Is it OK to do this way?

1. import my custom REST API in `FolderList` component
`import {UPDATE} from 'admin-on-rest/lib/rest/types';`
`import myApiRestClient from './restclient';`

2. call
`myApiRestClient(UPDATE,'folder',{id: record['folderId'],data: {locked: 2}});`

Looks ugly.

I'm trying the redux way - to `dispatch` `UPDATE`
```
dispatch( { type: 'UPDATE', payload: { resource: 'folder', payload: {id: record['folderId'], data: {locked: 2}} } } );
```
but nothing happens.

Component is connected and when I'm dispatching `SHOW_NOTIFICATION` with the same `onClick` it fires well.

**Comment by rimallo** [comment]
`dataActions.js` is the place to dig into?

**Comment by fzaninotto** [comment]
I'm documenting the idiomatic way to do it, and making it possible, in #235.

**Comment by fzaninotto** [comment]
Fixed by #235

**Comment by vysakh0** [comment]
@fzaninotto Is there way to get the store used by `admin-on-rest` so I could dispatch custom actions to update the admin's resource data made by `admin-on-rest`? 

Eg: 
1. The `GET_LIST` expects `{data: [], total: 0}`, to get the total pages I've to make a separate request to my api, so I would've to dispatch a custom action to update only the `total` attr of a resource like `posts`. 

2. I'm listening on a socket, and when a value changes I need to update, say there is an `users` resource with `status` attribute. So, I only need to set the `status` value of a user in the `users` resource or I could even set the entire `users` list with a new one.

**Comment by vysakh0** [comment]
@fzaninotto I'm using firebase, so to implement pagination, I need to know the last record's attr in the current page to fetch the next set of records. So, is there way to access the store data as well from inside the `myApRestClient.js` ?
