### ISSUE TITLE
Validation doesn't seem to work when using dot-notation

### ISSUE THREAD

**Issue by thedersen** [marmelab/admin-on-rest#240]
Validation doesn't not work for the first and last name inputs in the example below. Email works just fine, so I suspect it has to do with the dot notation used in source.

```
  <Create title="Create User" {...props}>
    <SimpleForm>
      <TextInput label="Firstname" source="name.first" validation={{ required: true }} />
      <TextInput label="Lastname" source="name.last" validation={{ required: true }} />
      <TextInput label="Email" source="email" type="email" validation={{ required: true }} />
    </SimpleForm>
  </Create>
```

Bug found in version 0.7

**Comment by fzaninotto** [comment]
Yep, I can reproduce it, and it's an easy fix. Just waiting for #241 to be merged to push the fix.

**Comment by thedersen** [comment]
Awesome! Thanks for the great work you are doing:)
