### ISSUE TITLE
ReferenceField : GET_MANY useless ?

### ISSUE THREAD

**Issue by wadjeroudi** [marmelab/admin-on-rest#246]
Hey,

I don't understand why you don't just use GET_ONE in case of ReferenceField.
It should only returns one result ?

**Comment by fzaninotto** [comment]
`<ReferenceField>` is used to display a field of a reference record, e.g. the author of a post. But in a list of posts, if we fetch the references authors one by one, this will result in 1+n REST queries. Instead, we aggregate the queries into one `GET_MANY`, so the final query count is 1+1.

If your REST server doesn't support something like `WHERE ID IN (...)`, then you can translate the `GET_MANY` query into multiple `GET_ONE` (as in [the `jsonServer` REST client](https://github.com/marmelab/admin-on-rest/blob/a2bb73e19687db68e4b62f687d542e650b7dd70f/src/rest/jsonServer.js#L107-L110)).

**Comment by wadjeroudi** [comment]
Thanks, nice idea to aggregate.

**Comment by fzaninotto** [comment]
More details in one of our blog posts: http://marmelab.com/blog/2016/10/18/using-redux-saga-to-deduplicate-and-group-actions.html
