### ISSUE TITLE
Disable 'link to edit' in ReferenceField

### ISSUE THREAD

**Issue by naibinh** [marmelab/admin-on-rest#247]
Hi,

First, I always to say thank every time I'm here.
Please stop by to see what you've done to us :)
nab-sale-management.herokuapp.com (user/pass: admin/changeit)

I see in source code that we use <Link/> in ReferenceField and click on it will browse us to edit page of referenced items.

It's great thing to implement, but can we add property to enable/disable it?
When disable, it should be rendered as <span/> or as same as other inline fields.
First, it can prevent user edit reference fields
Second, if there are many reference fields, there are also many blue links/hrefs in grid.

I can override this component to satisfy my need but I think it's pretty nice to improve in next release.

Thank you very much.

**Comment by fzaninotto** [comment]
Addressed by #281

**Comment by tomberek** [comment]
@naibinh can you assist with #281, I don't know when I can get to it next.

**Comment by leesei** [comment]
I believe there're three use cases:
1. link to edit
2. link to show
3. no link at all

I suggest defining a `linkType` prop with choices `['edit', 'show', 'none']`.
It defaults to `'edit'` to be consistent with the current behavior.

**Comment by leesei** [comment]
@fzaninotto I can pick up on this.
Do you agree to my suggestion above?
I think it cover all major use cases and supersedes the `addLink` prop you mentioned in #281.

**Comment by fzaninotto** [comment]
yep, let's do like you suggest, with a slight change:

* `linkType="edit"`: reference links to the Edit page (should be the default)
* `linkType="show"`: reference links to the show page
* `linkType=""` or `linkType={false}` or whatever else: reference has no link

**Comment by fzaninotto** [comment]
Fixed by #490
