### ISSUE TITLE
How do I make a production build ?

### ISSUE THREAD

**Issue by ivan-meridianbanc-com** [marmelab/admin-on-rest#248]
Dear Admin On Rest Team,

I find you project very interesting.
I want to try to use it.

I saw that when I run 
make run
The bundle.js is 4.4 MB.

I was wondering how to make a production build ?
I tried
make build

But I get error:

src/withProps.js -> lib/withProps.js
found ".." dir in relative path: ../lib
rsync error: syntax or usage error (code 1) at flist.c(2225) [sender=3.1.0]
make: *** [build] Error 1

Regards,
Ivan Stankov

**Comment by fzaninotto** [comment]
Hi Ivan,

Thanks for your kind words. 

`make build` is meant to be used for publication of the npm package. 

If you want to make a production build, you'll have to use a module bundler like webpack or browserify. You can get an example from [admin-on-rest-demo](https://github.com/marmelab/admin-on-rest-demo), which has a 2MB bundle including a 800kB module for the data (check the `gh-pages` branch). That means you can bring the bundle size down to 1.3MB easily without too much hassle. And if you're really into optimizing, you can probably go even further down (by lazy loading the rich text editor `quill`, or tree shaking).

Teaching you how to do it is outside the scope of this project.
