### ISSUE TITLE
`FormField` causes infinite update loop when given non-primitive `defaultValue`

### ISSUE THREAD

**Issue by hon2a** [marmelab/admin-on-rest#25]
I'm using a following set-up (pseudo-code cut just to demonstrate the relevant part):

```javascript
<SimpleForm>
  <SelectArrayInput source="..." defaultValue={[]} />
</SimpleForm>
```

inside a (much) larger application.

**What you were expecting:**

It should work (render and allow interactions) :)

**What happened instead:**

Application crashes with the following error:

```
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
```

I tracked the problem to `FormField`, which performs exact equality comparison on `defaultValue` in `componentWillReceiveProps` and dispatches the `initializeForm` action when it detects a difference. The action then causes update of a major part of the app, including the field, and the cycle starts again.

**Environment**

* Admin-on-rest version: 1.4.1
* React version: 16.4.0
* Browser: Chrome 67.0.3396.87
* Stack trace (in case of a JS error): not helpful (it ultimately crashes in `Route`, the update stack is short and without a trace of where the problem actually is)

```
Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at invariant (invariant.js:42)
    at scheduleWork$1 (react-dom.development.js:16099)
    at Object.enqueueSetState (react-dom.development.js:11185)
    at Route.../../node_modules/react/cjs/react.development.js.Component.setState (react.development.js:273)
    at Route.componentWillReceiveProps (Route.js:80)
    at callComponentWillReceiveProps (react-dom.development.js:11413)
    at updateClassInstance (react-dom.development.js:11605)
    at updateClassComponent (react-dom.development.js:13045)
    at beginWork (react-dom.development.js:13715)
    at performUnitOfWork (react-dom.development.js:15741)
```
```
The above error occurred in the <Route> component:
    in Route (created by AdminRoutes)
    in Switch (created by AdminRoutes)
    in AdminRoutes (created by Connect(AdminRoutes))
    in Connect(AdminRoutes) (created by getContext(Connect(AdminRoutes)))
    in getContext(Connect(AdminRoutes)) (created by Route)
    in Route (created by Admin)
    in Switch (created by Admin)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Admin)
    in TranslationProvider (created by withContext(TranslationProvider))
    in withContext(TranslationProvider) (created by Connect(withContext(TranslationProvider)))
    in Connect(withContext(TranslationProvider)) (created by Admin)
    in Provider (created by Admin)
    in Admin (created by withContext(Admin))
    in withContext(Admin) (created by DefaultAdmin)
    in  ... (app layout)
```

**Comment by hon2a** [comment]
Reward for tracing it to the source was at least finding a work-around. `defaultValue` apparently accepts a function and that is also compared for exact equality (which is also wrong). Passing in a constant getter does the trick.

```javascript
const emptyArray = () => []
const form = () => (
  <SimpleForm>
    <SelectArrayInput defaultValue={emptyArray} />
  </SimpleForm>
)
```

**Comment by fzaninotto** [comment]
That's a common React gotcha: you're passing a *new* empty array object each time the form rerenders, and specifying a default value rerenders the form. You have to define the default value as a constant (as [we've explained for the validators](https://marmelab.com/admin-on-rest/CreateEdit.html#validation), too).

**Comment by hon2a** [comment]
I'm aware the code is creating a new `Array` instance on each render. The fact that it creates infinite update loop is clearly not a "React gotcha", but a bug in how `defaultValue` is being handled - re-rendering the whole form on `defaultValue` change has nothing to do with React, it's your choice and it's not obvious in the least. (And if I needed the `defaultValue` to actually change, I'd have to do some shenanigans like keeping it in an instance property to work around this behaviour.)

I'd say this warrants a clear warning in the docs at the very least. Additionally, the setup seemed to work not too far back, so maybe this changed with some dependency update.

*Even more interesting (but unrelated) is how a function in `defaultValue` is handled. Accepting a function without arguments only makes sense if it's not expected to be pure. Then resolving it only when the _function_ changes doesn't seem to make much sense.*

**Comment by hon2a** [comment]
Btw. the docs actually contain [code](https://github.com/marmelab/admin-on-rest/blob/master/docs/CreateEdit.md#the-create-and-edit-components) [samples](https://github.com/marmelab/admin-on-rest/blob/master/docs/CreateEdit.md#per-field-default-value) with the same issue (see `defaultValue={new Date()}` and `defaultValue={() => uuid()}`), which illustrates my point pretty well.

**Comment by fzaninotto** [comment]
We're relying on redux-form for handling default values. I believe the problem lies there.

**Comment by hon2a** [comment]
Nope, you're in control of dispatching its `INITIALIZE` action. `redux-form` doesn't only reacts by re-rendering the form but doesn't control how this affects the place where you dispatch the action from.
