### ISSUE TITLE
Gist : Typescript declaration

### ISSUE THREAD

**Issue by pierre-H** [marmelab/admin-on-rest#250]
Hi,
First, thank you for your work.
I created a Typescript declaration because I love Typescript and I needed Admin on Rest, so here is the declaration file : https://gist.github.com/pierre-H/5e61fdeb6e918a2108ab968a16ce4049 .

If you could add it to the official repository it would be great !

There are interfaces which are useless for end user and are helpful for declarations and I don't know how to make them private.
I am still testing it but I think it's complete.

**Comment by fzaninotto** [comment]
Hi Pierre, 

And thanks for your contribution!

We're not users of TypeScript, so we can't add it to the repo because it would get out of date pretty quickly. I don't know if parsers have the option to accept a path for declarations, in which case you could publish these types in a third-party repository?

**Comment by djhi** [comment]
https://github.com/typings/typings ?

**Comment by hubert-associates** [comment]
The contributor above is offering to increase the quality of your interesting admin page by adding typings ... and you are not interested? Such typings make the difference between professional quality and "risky business" these days: reactjs has typings, angular has typings, apollo has typings, marmalab has "we don't use"? Please reconsider involving the contribution above.

**Comment by djhi** [comment]
That's not what @fzaninotto answered. As we are do not use TypeScript, we will not be able to keep the typings in sync with the project. We'd rather have those typings in userland, at least for now, than have countless issues about deprecated ones in our repository.

**Comment by hubert-associates** [comment]
In javascript, any typing is better than no typing.

**Comment by Vadorequest** [comment]
See https://github.com/marmelab/react-admin/issues/1617#issuecomment-595791317
