### ISSUE TITLE
Tab index resets after choosing an option using AutocompleteInput

### ISSUE THREAD

**Issue by ilaif** [marmelab/admin-on-rest#252]
After choosing an option using`<AutocompleteInput/>` the tab index resets to the base of the page (The first link in the page).

I will also have a look at the reason later, for now reporting.

**Comment by fzaninotto** [comment]
What do you mean by:

> The tab index resets

Can you provide a screencast?

**Comment by ilaif** [comment]
Here ya go:
![TabIndexReset](http://g.recordit.co/9ENnZJrOit.gif)

**Comment by fzaninotto** [comment]
We do nothing with the tab indices. This looks like a material-ui bug. Did you check that its not already reported in [their bug tracker](https://github.com/callemall/material-ui/issues)?

**Comment by ilaif** [comment]
Yes, you are totally right. It is addressed in this issue:
[[DropDownMenu] TabIndex, Close on ESC, Emitting button label / material-ui](https://github.com/callemall/material-ui/issues/3558)
