### ISSUE TITLE
Updating only changed attribtues

### ISSUE THREAD

**Issue by ilaif** [marmelab/admin-on-rest#256]
I don't know if it's good practice or not, but I always try to minimalize the external action of a process to simplify it. ATM when you perform an update to a record, it will send all of the attributes with their values even if they were not changed by the user.
This creates two problems in my opinion:
1. It's a waste of bandwidth, why send all these attributes if they were not updated.
2. For my API, it involves in unexpected behavior since my API will create special values if the parameters are not undefined, since they are not (like null etc) then it will not create special values.

I propose having some kind of comparison before updating that will check current values against the original values and only send the changes to the server.

I'm still learning React and Redux so I don't feel comfortable trying to performing changes.

What do you think?

**Comment by jpetitcolas** [comment]
We are sending all attributes as generally API doesn't handle `PATCH` but just `PUT`.

However, you can implement your diff computation in your own REST client, for instance using some decorators. You can take inspiration from [this incoming doc change](https://github.com/marmelab/admin-on-rest/pull/77/files#diff-bae839ad20ab1852a04e78aa5afe6131R172).

**Comment by ilaif** [comment]
Makes sense, thanks!
I don't quite understand how do I access the params before the change, doesn't seem like the REST Client's responsibility. Any chance for a direction on this one?
Thanks.

**Comment by fzaninotto** [comment]
The REST client is in charge of transforming a REST request (`UPDATE` in this case) into an HTTP request (`PATCH` or `PUT`, as you prefer). See examples in [simpleRestClient](https://github.com/marmelab/admin-on-rest/blob/master/src/rest/simple.js) and [jsonServerRestClient](https://github.com/marmelab/admin-on-rest/blob/master/src/rest/jsonServer.js).

**Comment by ilaif** [comment]
I understand this completely.
However, if I fetch data and display it for editing, and then do not change some field, then when the restClient receives the data to update (PUT or PATCH), it will receive all of the fields from the view, without any indication whether the field was altered or not. The only way I can think of is to create a store that saves the initial GET request that is displayed in the edit form and then compares it when and update occurs, but this sounds like quite a mess.
Thanks again.

**Comment by wow64cpu** [comment]
I have the same need. I am using [GraphQL](https://graphql.org/), the specification of which assumes no data redundancy.

In my implementation, I had to compare the data in the `dataProvider` because I couldn't find an adequate way to do it inside the form.

**Comment by christiaanwesterbeek** [comment]
Here's how I am doing it.

```ts
// decorator.ts

import { DataProvider, UpdateParams } from 'react-admin';

/**
 * Gives opportunity to alter method, resource and params before calling the original dataProvider
 */
export const decorator = (dataProvider: DataProvider) => ({
  ...dataProvider,
  update: (originalResource: string, originalParams: UpdateParams) => {
    const method = 'update';

    const { data, previousData } = originalParams;

    const changedDataOnly = Object.keys(data).reduce((acc, key) => {
      if (data[key] !== previousData[key]) {
        acc[key] = data[key];
      }
      return acc;
    }, {} as UpdateParams['data']);

    return dataProvider[method](originalResource, { ...originalParams, data: changedDataOnly });
  },
});
```

```ts
// useDataProvider.ts

import { useApolloClient } from '@apollo/client';
import pgDataProvider from 'ra-postgraphile';
import { useEffect, useState } from 'react';
import { DataProvider } from 'react-admin';
import { decorator } from './decorator';

const useDataProvider = () => {
  const [dataProvider, setDataProvider] = useState<DataProvider | null>(null);
  const client = useApolloClient();

  useEffect(() => {
    (async () => {
      if (!client) {
        return;
      }
      const dataProvider = await pgDataProvider(client);

      setDataProvider(() => decorator(dataProvider));
    })();
  }, [client]);

  return dataProvider;
};

export default useDataProvider;
```

```tsx
// App.tsx

const App = () => {
  const dataProvider = useDataProvider();

  return (
    dataProvider && (
      <Admin
        dataProvider={dataProvider}
        // ...
      >
        // ...
      </Admin>
    )
  );
};
