### ISSUE TITLE
yaml schema parsing / ezorm integration / searchkit / vue.js

### ISSUE THREAD

**Issue by roscopecoltran** [marmelab/admin-on-rest#259]
Hi guys,

Hope you are all well !

I was giving a try to your awesome boilerplate and 3 questions popped in my mind quickly :-)

**1- Admin configuration setup from orm schema (at least semi-automated)**

I was wondering how it could be possible to load the admin-configuration by parsing a yaml file generated by a tool like [ezorm](https://github.com/ezbuy/ezorm). More specially, I am writing a go-rest api (gin, grpc, gorm (dialects: mysql, sqlite3 and postgres), mongodb, redis and elasticsearch) and I wanted to get some flexibility during my tests for browsing/editing the content. 

It would be easier and cooler to edit the yaml file (eg. [blog](https://github.com/ezbuy/ezorm/blob/master/example/blog/blog.yaml)) and to add specific properties about the inputs (eg. textarea)... Can admin-on-rest parse yaml files to load in real-time new schemas to update the admin panel (of course only, in dev mode) ?

More generally, is there any go rest-api wrapping, made by you guys, for admin-on-rest or ng-admin ?

I found 2 projects wrapping your admin boilerplates but the config api is set manually:
- https://github.com/Onefootball/entity-rest-api
- https://github.com/deluan/ngago

**ps**. I wrote another question with more details about the grpc integration with one of your admin interfaces ([link](https://github.com/gogo/letmegrpc/issues/33)).

**2 - Searchkit**

My second, is about the integration of [searchkit](https://github.com/searchkit/searchkit). it would be awesome to have an advanced search features for your admin boilerplates admin-on-rest or ng-admin ([repo](https://github.com/searchkit/searchkit-demo), [demo](http://demo.searchkit.co/))

To bootstrap all of these, all together, a docker-compose would be the deal to deploy locally a cool admin gui for several kind of projects. I can do that for you guys without any problems.

**3 - Vue.js / Vue-Admin **

And last question :-), it sounds that vue.js is allowing to build non monolithic web interfaces ([article](http://www.valuecoders.com/blog/technology-and-apps/vue-js-comparision-angular-react/)), do you plan to migrate your awesome admin interfaces toward this tech ?

2 nice vue.js based projects :
1. https://github.com/vue-bulma/vue-admin
2. https://github.com/rorikurniadi/vuejs-AdminLTE

Thanks in advance for any reply or help for the question 1 in priority as I would like to start a project with admin-on-rest with ezorm soon; would like to identify  bottlenecks and tips first to save dev time ^^

Have an awesome day ! and waiting for your feedbacks, feelings and advices !

Cheers,
Richard

**Comment by fzaninotto** [comment]
Hi,

We focus on something we can finish in a reasonable amount of time, use it in our own projects, and maintain for several years. As a consequence, the answers to your feature requests are:

1. No
2. No
3. No

However, we built admin-on-rest with hackability in mind. If you give it a try, you will find that 1. and 2. are probably quite easy to achieve. As for 3, this is not something we'll ever do - we're not fond of the technology.
