### ISSUE TITLE
Uncaught Invariant Violation: addComponentAsRefTo(...)

### ISSUE THREAD

**Issue by jpetitcolas** [marmelab/admin-on-rest#26]
Following the tutorial and using last version of master, I got following error message:

> invariant.js:38 Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

**Comment by fzaninotto** [comment]
Fixed by #27
