### ISSUE TITLE
Headers should be lowercase

### ISSUE THREAD

**Issue by ftp27** [marmelab/admin-on-rest#26]
As per the [HTTP 2.0](https://tools.ietf.org/html/draft-ietf-httpbis-http2-17#section-8.1.2) spec, header names should be lowercased

Now I've got errors like 
```
The X-Total-Count header is missing in the HTTP Response. The jsonServer REST client expects responses for lists of resources to contain this header with the total number of results to build the pagination. If you are using CORS, did you declare X-Total-Count in the Access-Control-Expose-Headers header?
```

With response headers
```
access-control-allow-headers: content-type, x-total-count
access-control-allow-methods: GET
access-control-allow-origin: *
access-control-max-age: 600
content-length: 9091
content-type: application/json; charset=utf-8
date: Sun, 01 Jul 2018 23:50:46 GMT
x-total-count: 30
```

[UPD] I've found this [line](https://github.com/marmelab/admin-on-rest/blob/c15559c266d449ffc4e39563971822f2f9563bf7/src/rest/jsonServer.js#L98). Well. I don't know why I'm receiving such error

**Comment by fzaninotto** [comment]
That's because you didn't declare the `x-total-count` as a CORS header. Look for the word 'CORS' in the REST client documentation : https://marmelab.com/admin-on-rest/RestClients.html#json-server-rest
