### ISSUE TITLE
SelectInput failure when clicking on arrow

### ISSUE THREAD

**Issue by tomberek** [marmelab/admin-on-rest#265]
![jan-30-2017 09-05-17](https://cloud.githubusercontent.com/assets/178444/22435926/fa3e5f9e-e6ef-11e6-95c3-804af01c0bea.gif)

Tried to troubleshoot via the injectTapEventPlugin() and other fixes, nothing quite seemed to work. I don't have a suggested solution.

**Comment by fzaninotto** [comment]
I can't reproduce it on the demo

http://marmelab.com/admin-on-rest-demo/#/products/129?_k=6n9sl0

Can you share your code?

**Comment by tomberek** [comment]
@fzaninotto sure, here's a slight edit of the existing example project. It seems the issue occurs when SelectInput is inside a ReferenceInput.

https://github.com/tomberek/admin-on-rest/tree/selectinput_demo

```
+            <ReferenceInput label="Post" source="post_id" reference="posts" perPage={5} sort={{ field: 'title', order: 'ASC' }}>
+                <SelectInput optionText="title" />
+            </ReferenceInput>
```

**Comment by fzaninotto** [comment]
Cannot reproduce either with that code on Chrome using `master` or `next` branches. 

Perhaps it's an issue with your material ui version?

```sh
> npm ls material-ui
admin-on-rest@0.7.1 /Users/francois/git/admin-on-rest
└── material-ui@0.16.5
```

**Comment by tomberek** [comment]
material-ui@0.16.7

**Comment by fzaninotto** [comment]
Cannot reproduce with material-ui@0.16.7 either. What's your browser?

**Comment by nik-lampe** [comment]
Having the same problem.
On OSX with Chrome Version 57.0.2987.37 beta (64-bit) the SelectInput inside a ReferenceInput breaks when clicking on the arrow. When clicking on the Text I get to see the options an can choose one.
On Firefox 49.0.2 it works.

**Comment by tomberek** [comment]
OSX
Version 56.0.2924.87 (64-bit)

**Comment by fzaninotto** [comment]
OK, now I can reproduce it, I'll look into it.
