### ISSUE TITLE
How to set routes ?

### ISSUE THREAD

**Issue by kktos** [marmelab/admin-on-rest#266]
Hi,

I'm playing with this very baby and I'm quite pleased with it. Only thing I would like to change are the routes.
For the list, instead of "http://mysite.com/#/posts?", I would like a "http://mysite.com/posts?".
And for the show_one, I would like a "http://mysite.com/posts/:id".

Is there a way to change it or do I have to integrate it into an existing app to be able to customize the routes ?

TIA,
/Thierry

**Comment by fzaninotto** [comment]
Hi Thierry,

And thanks for your feedback.

The only way to customize routes is to use a custom app, as explained in http://marmelab.com/admin-on-rest/CustomApp.html
