### ISSUE TITLE
Refresh should refresh all nested reference fields.

### ISSUE THREAD

**Issue by wadjeroudi** [marmelab/admin-on-rest#279]
If you have a ReferenceManyField in an Edit component and you click refresh.
It will only update the data from the record itself.
It won't fire requests for the ReferenceManyFields.

**Comment by fzaninotto** [comment]
Confirmed, that's a bug.

**Comment by fzaninotto** [comment]
The solution is... messy

https://github.com/ReactTraining/react-router/issues/1982

React-router doesn't have a reload feature. The only thing they advise is to use `window.location.reload()`, which reloads not only the data but also the JS. It's not satisfactory.

Or we could trick Redux by dispatching an action that unmounts all components of the view then remounts them just after. This needs custom logic in each view though.

**Comment by wadjeroudi** [comment]
That's weird because on refresh list view, it does work.
