### ISSUE TITLE
The tabs do not rerender on state change

### ISSUE THREAD

**Issue by jmarucha** [marmelab/admin-on-rest#28]
The tab list only changes on first rendering of the UI. The changs of state don't cause proper rendering.

I would expect following (pseudo)code to result in one of tabs showing if and onli if this.state.isAdmin is true, however it only depends on the initial value of this state field (the `isAdmin` is loaded asynchronously).
```
<Admin ...>
    <Resource ... />
    {this.state.isAdmin ? <Resource ...> : null}
</Admin>
```
The title prop of <Admin> component however rerenders correctly, and also console.logs display proper, updated state.

* Admin-on-rest version: 1.4.1
* React version: 16.2.0
* Browser: Firefox 61.0.1 (64-bit)

**Comment by fzaninotto** [comment]
You mean menus, right?

**Comment by djhi** [comment]
For those cases, use the recipe explained [here](https://marmelab.com/admin-on-rest/Authorization.html#restricting-access-to-resources-or-views)
