### ISSUE TITLE
what does this mean?

### ISSUE THREAD

**Issue by velociwabbit** [marmelab/admin-on-rest#285]
Could  anyone please interpret these instructions for me?
 ```
# in myapp
# install admin-on-rest from GitHub in another directory  
$ cd ..
$ git clone git@github.com:marmelab/admin-on-rest.git && cd admin-on-rest && make install
# replace your node_modules/admin-on-rest by a symbolic link to the github checkout
$ cd ../myapp
$ npm link ../admin-on-rest
# go back to the checkout, and replace the version of react by the one in your app
$ cd ../admin-on-rest
$ npm link ../myapp/node_modules/react
$ make watch
# in another terminal, go back to your app, and start it as usual
$ cd ../myapp
$ npm run
```

Specifically what does 
`# replace your node_modules/admin-on-rest by a symbolic link to the github checkout`
refer to?

and how about his line?

`# go back to the checkout, and replace the version of react by the one in your app`

Alternatively could someone please give me a set of node or npm commands to accomplish this process?

Thanks

**Comment by fzaninotto** [comment]
`# replace your node_modules/admin-on-rest by a symbolic link to the github checkout` refers to the two lines just after (`npm link`)

`go back to the checkout, and replace the version of react by the one in your app` refers to the three lines after

So basically the `README` gives you the set of `npm` commands you're asking for.

By the way, as I watch this repository, I receive issues in the first version they're written. For yours, it's the one where you express your frustration in a very clumsy way. Please remain calm and polite. If you can't control your frustration, go take a walk or use another project.

**Comment by velociwabbit** [comment]
No doubt I was frustrated.  ... and thank you for admonishing me for
something that I already corrected. Perhaps you should have gone  for a
walk as well  before sending this last message.  :)

Take is as the compliment that it is. There is a great deal of potential in
this project but under the covers it still needs a bit of polishing and  I
am very willing to help  if you are so inclined.
