### ISSUE TITLE
lost the last two digits for longint

### ISSUE THREAD

**Issue by IaroslavR** [marmelab/admin-on-rest#288]
For data like:
`[
  {
    "category": "owner",
    "id": 750923888754880517
  }
]`
with `jsonServerRestClient` as rest client in 
`        <Datagrid>
            <TextField source="id"/>
`
I got 750923888754880500 instead of 750923888754880517. Of course convert id to string works like workaround for this issue, but IMHO it's a bug

**Comment by fzaninotto** [comment]
It's a JavaScript bug! You should file an issue in V8.

More seriously, there is nothing admin-on-rest can do. I advise you to use string ids.
