### ISSUE TITLE
Working custom-App demo

### ISSUE THREAD

**Issue by thachp** [marmelab/admin-on-rest#29]
I'm following the instructions in Custom-APP.md, but could not get a basic hello world app working.  I'm getting all kind of errors, figuratively...

It would help if you can provide sample codes for these components.

```
import Layout from './Layout';
import Dashboard from './Dashboard';
import { PostList, PostEdit, PostCreate } from './Post'; 
import { CommentList, CommentEdit, CommentCreate } from './Comment';
import { UserList, UserEdit, UserCreate } from './User';

```

https://github.com/marmelab/admin-on-rest/blob/master/docs/Custom-App.md

**Comment by djhi** [comment]
Documentation is a work in progress. In the mean time, take a look at the sources.

**Comment by thachp** [comment]
Your pull request here: https://github.com/marmelab/javascript-boilerplate/pull/110  has helped me get going.  Thanks.

**Comment by djhi** [comment]
I should have mentionned it. Please close this issue if you managed to get your custom app running.

**Comment by thachp** [comment]
Yes, I got it running.
