### ISSUE TITLE
Headers class not found

### ISSUE THREAD

**Issue by cipacda** [marmelab/admin-on-rest#293]
Not sure if I am doing something wrong, but I cannot add custom headers when using fetchJson client. 

When trying new Headers I get compile error that it is not defined. Does the Headers refer to the Angular Headers which will not work in my React app?

**Comment by fzaninotto** [comment]
No, it's the browser native `Header` class:

https://developer.mozilla.org/en-US/docs/Web/API/Headers

Can you give more details about your error?

**Comment by cipacda** [comment]
I am using npm 4.0.5 and get `(17,35): error TS2304: Cannot find name 'Headers'.`

**Comment by fzaninotto** [comment]
Well, that's probably because of TypeScript then. I don't see no other reason.

That makes aor not compatible with typescript, which is not a big deal for us. I advise you to switch to babel, or another parser / bundler.

**Comment by cipacda** [comment]
Indeed, for anyone seeing the problem, the fetch api needs to be imported for typescript: 
    "@types/whatwg-fetch": "0.0.33",
