### ISSUE TITLE
CustomApp Example

### ISSUE THREAD

**Issue by mantis** [marmelab/admin-on-rest#294]
The code for including in a custom app ( https://marmelab.com/admin-on-rest/CustomApp.html )has the following line:

`
const RightElement = isLoading ? <CircularProgress color="#fff" size={0.5} /> : <span />;
`
This generates an error due to the size value, as discussed in issue https://github.com/callemall/material-ui/issues/5338 and https://github.com/callemall/material-ui/issues/5277

I'm assuming this line should read:

`
const RightElement = isLoading ? <CircularProgress color="#fff" size={30} thickness={2} style={{ margin: 8 }} /> : <span />;
`

**Comment by fzaninotto** [comment]
You're absolutely right, it was changed in admin-on-rest's layout when witching to 0.16, but not in the documentation.
