### ISSUE TITLE
Check for window presence and use appropriate history

### ISSUE THREAD

**Issue by djhi** [marmelab/admin-on-rest#298]
This prevents usage of admin-on-rest in SSR scenarios.

We should only setup the devtool if inside a browser. Moreover, we could also use the memoryHistory when not inside a browser too.

**Comment by fzaninotto** [comment]
Should be much easier in `next`, now that we use react-router v4

**Comment by demetriusnunes** [comment]
+1

**Comment by fzaninotto** [comment]
Fixed by #741
