### ISSUE TITLE
Custom App Example - notifications

### ISSUE THREAD

**Issue by mantis** [marmelab/admin-on-rest#303]
Hi,

Whilst minor - most of the custom app examples are copy/paste jobs - for the page  @ https://marmelab.com/admin-on-rest/CustomApp.html - the documentation on MyLayout includes `<Notification />`. 

For this to work, I needed to import

`
import Notification from 'admin-on-rest/lib/mui/layout/Notification';
`

Where the other example doc's include import statement, it probably makes sense to also include an import statement for the menu layout example

**Comment by fzaninotto** [comment]
Fixed by 4d69913
