### ISSUE TITLE
"edit" functionality not using latest state

### ISSUE THREAD

**Issue by mantis** [marmelab/admin-on-rest#305]
Hello,

Not sure if this is happening for anyone else, but I have a datagrid that gets displays a list of records.  (/users)

If I then click on a link to go to an individual record, that does a GET request to get /users/<id> - however the data shown at this point is the data retrieved when getting the list of records (i.e. from /users).

If I then click on 'refresh', it updates to show the data from /users/<id>. So it would appeat that currently the request to /users/<id> is used as an existence check, but not to update the data already received. Is this expected behaviour??

**Comment by fzaninotto** [comment]
No, this is not the expected behavior. 

Normally, the data fetched by the list (`GER /users`) is used to display the edit page while the fresh data is fetched (`GET /users/:id`), but the refresh happens automatically.

Can you check in the network tab of the developer tools of your browser that the call to `GET /users/:id` happens as soon as you browse to the edit page?

**Comment by mantis** [comment]
Trying to get updated to 0.8.1 then will check this again

**Comment by nik-lampe** [comment]
Having the same Problem.
The GET call happens and returns the correct data. The Redux Store is also updated correctly (I guess) on the CRUD_GET_ONE_SUCCESS Action. 

When I reload the page with the URL pointing to the resource (e.g. /users/u1) then it works fine. But as @mantis said, when I navigate from the resource list into the edit view the form does not get updated. Only the fields which contain data that was available in the list view are working. The others are empty (My API does not send all the data for all the resources when calling GET on the collection)

After hitting refresh the data gets updated.

**Comment by fzaninotto** [comment]
I can't yet reproduce the issue, but I think it comes from redux-form handling of default values (which can't be updated). I'll continue to work on it.
