### ISSUE TITLE
User experience / interface feedbacks

### ISSUE THREAD

**Issue by Kmaschta** [marmelab/admin-on-rest#308]
Hello guys, love what you do! Have you heard of ng-admin? The 1.0 is out!

More seriously, I have some feedback for you [about the wonderful demo](https://marmelab.com/admin-on-rest-demo/).

### Add a shadow on mouse hover over the Datagrid
Currently, when you pass the mouse over the left menu, you have a clean shadow to tell you where you are. Is it possible the have the same shadow (with less opacity) over the Datagrid list?

### Clickable padding over all clickable elements
Most of buttons have a nice padding around:

![image](https://cloud.githubusercontent.com/assets/1819833/22922011/384cb60c-f29c-11e6-8658-2c9a645ed5d5.png)![image](https://cloud.githubusercontent.com/assets/1819833/22921886/bb3239e4-f29b-11e6-9367-183f388484cc.png)

But not all clickable elements have this feature, on the demo I have noticed:

- Reviews Like / Unlike buttons
- All the references (such as Reviews Customer, Reviews Product)

All the pages are not equals in terms of UI, it's disturbing at first sight.

EDIT: @iyobo I'm one of them!

**Comment by iyobo** [comment]
Lol. You realize these same guys created ngadmin right?

**Comment by jpetitcolas** [comment]
@iyobo: yes, and he is a member of the core team too. :p

**Comment by fzaninotto** [comment]
Datagrid stripes and hover added in #332 (but optional).

As for the buttons, `<IconButton>` from material-ui is uses as is. If you think this button deserves a hover, please open a ticket on their issue tracker.
