### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by stefsava** [marmelab/admin-on-rest#313]
I created a new repository with italian translations.

[aor-language-italian](https://github.com/stefsava/aor-language-italian)

The module is also published in npm.

If you prefer to make it an official project, I will gladly remove the mine and work on your anyway.

**Comment by djhi** [comment]
Can you make a pr creating a "Third-party translations" section at the end of the [translation](https://github.com/marmelab/admin-on-rest/blob/master/docs/Translation.md) documentation, where you mention the name and purpose of your package in a single line, then link to your README (kind of like the third-party REST clients section) ? Thanks !

**Comment by fzaninotto** [comment]
@djhi just did it myself
