### ISSUE TITLE
options.label issue?

### ISSUE THREAD

**Issue by datafibers** [marmelab/admin-on-rest#317]
I am trying to use options.label to modify what's displayed in UI. Why it is never updated (npm start).
as follows
<Resource name="v2/posts" options={{ label: 'Posts' }} list={PostList} />

**Comment by fzaninotto** [comment]
Do you use v0.8.1? It has been fixed in #315

**Comment by datafibers** [comment]
seems the title got fixed. However, the options.label still has issue in 0.8.1

**Comment by fzaninotto** [comment]
I don't understand what you mean. `options.label` modifies the menu label for a resource. This works. What else do you expect?

**Comment by fzaninotto** [comment]
Any updates on this one?

**Comment by fzaninotto** [comment]
No news for some time, closing.
