### ISSUE TITLE
Iframe as component

### ISSUE THREAD

**Issue by velociwabbit** [marmelab/admin-on-rest#319]
I am not sure whether this is a bug or pilot error but I can safely put an iframe as a replacement dashboard component but when trying to accomplish the same task as a menu option the result is a new instantiation of the admin-on-rest app.

here is the syntax for the dashboard.js file

`export default ()=>(<div dangerouslySetInnerHTML={{__html: "<iframe src='./ix.htm' />" }} />);  `

It works just fine as a substitute for the dashboard in the demo but when i try and use it for any of the resource components it just re instantiates the base url in the sub-window.

Also I have been trying to figure out how to utilize the material-ui  Drawer component as a the menu manager and am flummoxed about integrating them with admin-on-rest.  On the surface both apps look similar but Admin-on-rest has a more inscrutable means for setting up menu components.  

Any help would be appreciated.

**Comment by fzaninotto** [comment]
`iframe` is not supported. Use it at your own risk. 

If you want to use your own `Menu` component, for now you have to write a custom `Layout` component. Check out how it's done in [admin-on-rest-demo](https://github.com/marmelab/admin-on-rest-demo/blob/master/src/Layout.js).

**Comment by velociwabbit** [comment]
​is there a technical reason why?  Material-UI supports frames no problem.
Is it a limitation in your code or some other library you are using?

**Comment by fzaninotto** [comment]
No idea why, but I don't want to spend time on debbuging such a corner case.

**Comment by velociwabbit** [comment]
I just figured it out and it works fairly well.  The reason why i need it
is I am doing 3d animation and graphics with real-time data and want to
have both the graphics and the administration components consolidated.  So
I hope you are right that it is a corner case :)

The issue I was having is that directories are resolved differently in
dangerouslysetting mode. in DangerousHTML mode the  relative reference
starts at the public folder not at the local folder.  Also webpack is a bit
tricky as well....so far I have not been able to use webpack on both sets
of code..

/jpr
