### ISSUE TITLE
Remove dependency with material-ui

### ISSUE THREAD

**Issue by jeromemacias** [marmelab/admin-on-rest#32]
What about create abstract components where the render method is not defined ?
So we will be able to use them without `material-ui` style dependency.

For examaple, `Pagination` could be extended by `MaterialPagination`and so we will be able to create `BootstrapPagination` which render pagination in `Bootstrap` style.

We can even imagine a "themification" of the admin.

**Comment by fzaninotto** [comment]
All the material-ui related stuff is already inside a `mui` directory, it shouldn't be difficult to make it a standalone component - that's already the long-term goal.

However, before making the installation more complex by asking users to install 2 directories, and before making development more complex by asking developers to synchronize changes on 2 repositories, we'll continue bundling material UI components up to a stable release.

In the meantime, if you want to work on an alternative view (bootstrap?), feel free to submit a PR on this repository.

I'll close the issue as it's already something that we have in mind, but for now, admin-on-rest is material-ui only.

**Comment by jeromemacias** [comment]
Nice job, impressive !
