### ISSUE TITLE
'admin-on-rest' chinese translations 

### ISSUE THREAD

**Issue by downup2u** [marmelab/admin-on-rest#320]
'admin-on-rest'  is  the best admin frame for react  I've ever seen.*^_^*
I made a npm package named 'aor-language-chinese' with chinese translations for it.
https://www.npmjs.com/package/aor-language-chinese.

usage:
npm install aor-language-chinese

add your code:
import zhcnMsg from 'aor-language-chinese';

const messages = {
    'zh-cn': zhcnMsg,
};

**Comment by fzaninotto** [comment]
Thanks a lot for your compliments, we appreciate!

I can add a mention of your translation to the doc (https://github.com/marmelab/admin-on-rest/blob/master/docs/Translation.md#available-locales), but I suggest you to open a PR instead. That way, you'll appear in the admin-on-rest contributors list!

**Comment by downup2u** [comment]
OK,thank you,I open a PR.
