### ISSUE TITLE
"singleton" resources

### ISSUE THREAD

**Issue by underdoeg** [marmelab/admin-on-rest#324]
I'm developing an admin interface for a video player application. There I have multiple Videos and Playlists that follow a regular use case of multiple, editable items. But I also have some global settings. Where the API accepts a single PUT and GET without an ID undef /config . Is there some way to hack this into admin on rest to use an <Edit> or do I have to write my own form?

**Comment by fzaninotto** [comment]
You can add custom pages not handled by admin-on-rest. See the [custom routes documentation](https://marmelab.com/admin-on-rest/AdminResource.html#customroutes), and [an example in admin-on-rest-demo](https://github.com/marmelab/admin-on-rest-demo/blob/master/src/routes.js) with the "segments" page.

**Comment by viswanathct** [comment]
@fzaninotto Is it possible to implement this with an optional attribute, **singleton=false**? I'll be more than happy to do this.

**Comment by djhi** [comment]
There's no need to change anything in react-admin to allow that. You can use all components inside a custom page as long as you pass them the props they expect.

As this is a common question, I'll write an advanced tutorial for it very soon. In the mean time, you can see how it's possible to achieve in this [codesandbox](https://codesandbox.io/s/pk2vl9xvm).

In a nutshell, it requires a custom route, a custom menu and handling this special case in the dataProvider.
