### ISSUE TITLE
Editable list items view

### ISSUE THREAD

**Issue by mangakid** [marmelab/admin-on-rest#335]
I'm new to admin-on-rest and am wondering if it is possible to mix the admin views. For instance having a list of editable items, to avoid having to go to a new page/view for each item. Or is that something impossible with the admin-on-rest structure?

**Comment by fzaninotto** [comment]
Hi,

It is not done my admin-on-rest, but nothing prevents you from doing it yourself. See https://github.com/marmelab/admin-on-rest/issues/212#issuecomment-272447237

As a side note, nothing is impossible with the admin-on-rest structure, as it's simply a react/Redux app that you can entirely rebuild using admin-on-rest components (see https://marmelab.com/admin-on-rest/CustomApp.html).

**Comment by fzaninotto** [comment]
see #1923
