### ISSUE TITLE
Duplicate requests when using pagination / filter / sort on List View

### ISSUE THREAD

**Issue by wadjeroudi** [marmelab/admin-on-rest#337]
When using the pagination from a List View, if I hit page 2, it fires two rest calls GET_LIST (i'm not talking about preflight request). The same problem appears for sort and filters.

Maybe a bad comparison with props ?

**Comment by fzaninotto** [comment]
I can't reproduce the problem. Which version of admin-on-rest are you using? Which restClient? Which browser?

Do you reproduce the problem with [the demo](https://marmelab.com/admin-on-rest-demo/#/?_k=qzcb41)?

**Comment by wadjeroudi** [comment]
I switched from custom app to Admin component (last 0.8 version), and the problem is fixed.
