### ISSUE TITLE
Not Found custom Route

### ISSUE THREAD

**Issue by matteolc** [marmelab/admin-on-rest#340]
Hi
Because custom routes are added before every other route in the Admin component, it is not possible to define a not found route is a custom routes component (because the '*' route will match before everything else). 

Could we move the rendering of custom routes to the bottom of the route path '/' ?

Instead of:

    <Route path="/" component={Layout} resources={resources}>
       {customRoutes && customRoutes()}
       {dashboard && <IndexRoute component={dashboard} onEnter={onEnter()} />}
       ...
    </Route>

To:

    <Route path="/" component={Layout} resources={resources}>
       {dashboard && <IndexRoute component={dashboard} onEnter={onEnter()} />}
       ...
       {customRoutes && customRoutes()}
    </Route>

Thanks!

**Comment by matteolc** [comment]
Or alternatively add a default not found route in aor, if it is something you would consider.

    <Route path="*" component={PageNotFound} />

**Comment by fzaninotto** [comment]
I think the second option is better - with a `pageNotFound` prop in `<Admin>` to let you override it.

**Comment by voxbox-io** [comment]
Sounds good to me! 👍 Grazie

**Comment by fzaninotto** [comment]
Fixed by #824
