### ISSUE TITLE
Error with reference fields

### ISSUE THREAD

**Issue by leperone** [marmelab/admin-on-rest#341]
Hi all,
I'm writing a **Parse Server rest client** using the Simple REST Client as starting point.
Successfully translated the GET_MANY and GET_MANY_REFERENCE action types ( requests and  server responses seem to be ok), but when testing **ReferenceField** and **ReferenceManyField**, for every row in the datagrid i get the error :

> uncaught at handleFetch TypeError: newRecords.reduce is not a function

in `admin-on-rest/lib/reducer/resource/data.js`

```
var addRecords = function addRecords() {
...
// prepare new records and timestamp them
var newRecordsById = newRecords.reduce(function (prev, record) {
   prev[record.id] = record; // eslint-disable-line no-param-reassign
   return prev;
}, {});
...
```

Note that I used a 
```
json.replace(/objectId/g, "id");
```
in the `convertHTTPResponseToREST = (response, type, resource, params)` function,  where `objectId` is an alphanumeric string.

**Comment by wadjeroudi** [comment]
I think I had this error when I didn't have the reducer linked to the new resource I added in reference.
For example if you're using the Admin Component, need to add if you reference order-item-units
        <Resource name="order-item-units" options={{ hideInMenu: true }} />

Or if you use a custom app, don't forget to add the new resource as an admin reducer in combineReducers.

**Comment by leperone** [comment]
Unfortunately the referenced resource is already present in the Admin Component.

In fact the view is correctly rendered if I open the list of the related resource and then click on the referencing one, fetching data from the cache.
The problem shows up when refreshing the cache, despite the "GET_MANY" http requests being executed with 200 status response.

**Comment by leperone** [comment]
Ok, solved.
The problem was in the response.
It was `{'results':Record[]}` instead of `{Record[]}`.
I was fooled because the response provided to the GET_LIST action type, with the rest client expecting `{'data':Record[]}`, worked out of the box.
Sorry, my fault.
