### ISSUE TITLE
ImageInput keeps adding imagest to state

### ISSUE THREAD

**Issue by Alirun** [marmelab/admin-on-rest#349]
Hi there.

In ImageInput's sources there are lines in onDrop function
`const updatedFiles = [
            ...this.state.files,
            ...files.map(this.transformFile),
        ];`

Which keeps adding images to state and there is no way to remove unwanted ones.
You might see in this a problem too.

Thanks.

**Comment by fzaninotto** [comment]
Fixed by #472
