### ISSUE TITLE
fetch.fetchJson doesn't catch http errors

### ISSUE THREAD

**Issue by freshfunkee** [marmelab/admin-on-rest#354]
I was implementing the new authentication features added in the latest release, to which I started using `fetchJson` from the `src/utils/fetch.js` modules as shown in the [Authorisation documentation](https://github.com/marmelab/admin-on-rest/blob/master/docs/Authentication.md)

However, since my expressjs server responds with an error for 401 and 403 statuses (by default, using express-jwt middleware), the response was not handled correctly in the auth saga, due to no status code being available on what it perceived to be an `error` object.

start of returned promise chain in `fetch.js`: [Line 14](https://github.com/marmelab/admin-on-rest/blob/master/src/util/fetch.js#L14)

Maybe this is working as intended, since this can be solved by adding catch after `fetchJson` and returning a rejected promise (in which case, the documentation should be updated, as it currently doesn't reference this).

I fixed this by making a local copy of the `fetchUtil` module, and adding a `catch` clause to the end of the fetch promise chain returned from `fetchJson`.

```
return fetch(url, { ...options, headers: requestHeaders })
        .then(response => response.text().then(text => ({
            status: response.status,
            statusText: response.statusText,
            headers: response.headers,
            body: text,
        })))
        .then(({ status, statusText, headers, body }) => {
            let json;
            try {
                json = JSON.parse(body);
            } catch (e) {
                // not json, no big deal
            }
            if (status < 200 || status >= 300) {
                return Promise.reject(new HttpError((json && json.message) || statusText, status));
            }
            return { status, headers, body, json };
        })
        .catch(err => {
          return Promise.reject(err)
        });
```

**Comment by fzaninotto** [comment]
This was already reported - and fixed - yesterday in #339. It's on the master branch; a bug fix release should be published today.

**Comment by fzaninotto** [comment]
Correction: it's already been released in v0.8.2.

https://github.com/marmelab/admin-on-rest/blob/master/CHANGELOG.md#changelog

**Comment by freshfunkee** [comment]
I experienced this on v0.8.2. My sample fix noted shows it is using `HttpError` with the OR'd logic of `statusText, status`

**Comment by fzaninotto** [comment]
I don't understand your fix: you catch an error, just to re-throw it afterwards. It is no different than letting it bubble up in the first place. 

Also, the only type of error that your `catch()` would catch, is an error in the first `fetch()` call, probably a network error, resulting in in response available (and no response status either). In that case it doesn't make sense to logout the user.

So I don't understand you problem, and I don't understand the fix either...

**Comment by freshfunkee** [comment]
It's not only network errors that the `catch()` clause handles. In my case, using `expressjs` with `express-jwt`, a 401 or 403 responds with an error. 

When I tried out the example at first, I thought the uncaught error would bubble up and work as expected too, but it didn't work. Then I added in the catch and responded with the rejected promise, which works for my case.

I can do more testing, and see if I can create something reproduceable to try out after the weekend.

**Comment by fzaninotto** [comment]
Just tested again on my end: upon receiving a 401, any view redirects to the login view. So I can't reproduce your problem.

**Comment by wadjeroudi** [comment]
@fzaninotto this issue is fixed indeed.
But @freshfunkee may be speaking about an other bug. The rest errors aren't displayed anymore, I mean it doesn't show notification.

With the last version if you have a validation failed or something like that, the error isn't catched anymore. Just put to the console.

**Comment by fzaninotto** [comment]
It seems reasonable to me that a 401 or 403 error doesn't show a notification, since there is already the redirection.

And I see no regression on the 500 type errors. The related notification shows up if the HTTP response body contains a message. I agree errors should show up even if there is no body (I'll post a PR for that shortly), but it's not linked to the HttpError change.

**Comment by wadjeroudi** [comment]
#365
