### ISSUE TITLE
autocomplete selectfield

### ISSUE THREAD

**Issue by hengkyz** [marmelab/admin-on-rest#355]
i think there is little enhancement that we need to add
in select field we need to add autocomplete feature
because for example if we have one hundred thousand users then its not possible to use selectfield
we need at least to search(auto complete) before we choose which one data to select,
for now i just use autocomplete (textfield) to achieve what i want,

**Comment by fzaninotto** [comment]
It's [already possible](https://marmelab.com/admin-on-rest/Inputs.html#referenceinput):

```js
import { AutocompleteInput, ReferenceInput } from 'admin-on-rest/lib/mui'

<ReferenceInput label="Post" source="post_id" reference="posts">
    <AutocompleteInput optionText="title" />
</ReferenceInput>
```

**Comment by afilp** [comment]
@fzaninotto When used in a filter with "alwaysOn", there is no way to get rid of the filter. Even if you use no chars inside it, this does not work. Is this a bug?
