### ISSUE TITLE
Enhancement request: Option to use icon in DatagridHeaderCell

### ISSUE THREAD

**Issue by voxbox-io** [marmelab/admin-on-rest#356]
Hello,

Would it be something you consider, adding to fields an icon options:

    <TextField source="currency_code" options={{icon: {<EuroSymbol/>}} />

or on props:

    <TextField source="currency_code" icon: {<EuroSymbol/>} />

And then show the icon (if existing) in DatagridHeaderCell in place of source/label (here using props):

    {field.props.icon ? 
       	    field.props.icon
      	    :
       	    title(field.props.label, field.props.source)
    }

Thanks!

**Comment by matteolc** [comment]
Ops i opened this issue with the wrong account!

**Comment by fzaninotto** [comment]
Why don't you use utf-8 in this use case?

**Comment by matteolc** [comment]
Ah! Because I didn't think about it :) Ok, let me try, thanks.

**Comment by matteolc** [comment]
Ciao @fzaninotto 
Could you suggest me an utf-8 example with a material ui icon?
Grazie 1000

**Comment by fzaninotto** [comment]
If you want to show a currency value, use `<NumberInput>` and the the `styles` and `currency` props, [as explained in the documentation](https://marmelab.com/admin-on-rest/Fields.html#numberfield):

```js
<NumberField source="price" options={{ style: 'currency', currency: 'USD' }} />
// renders the record { id: 1234, price: 25.99 } as
<span>$25.99</span>
```

If you want to do the formatting yourself (which is a bad practice, your browser knows better), create a field of your own like that:

```js
const EuroField = ({record, source}) => <span>{record[source]}€</span>;
```

Then use it instead of `<TextField>`. No need for utf-8.

**Comment by matteolc** [comment]
Hi,
no, that's not what I meant, the euro icon example was misleading. 
I want to use any material ui SVG icon in a header cell, like in the picture attached. 
Thanks
M.

![icon](https://cloud.githubusercontent.com/assets/78274/23322393/02ef8750-fae4-11e6-9358-cc1ec7d175a0.png)

**Comment by matteolc** [comment]
Also, just to clarify, I don't do any currency formatting "by myself", i let the (rails) api do so by formatting currency fields with their corresponding currency ISO.
So I actually render any currency field as a TextField.
Thanks

**Comment by fzaninotto** [comment]
That's typically the type of use case where you should use a custom `<Datagrid>` component. It's simple: just pass it as child of `<List>`.

**Comment by matteolc** [comment]
Indeed that's what I have been doing.
