### ISSUE TITLE
Feature Request: Pass custom Menu component to Admin

### ISSUE THREAD

**Issue by voxbox-io** [marmelab/admin-on-rest#357]
Hello!

Would it be something you consider, being able to pass to Admin a custom Menu?

I found myself overriding aor default Layout mainly for this reason, and it would be nice to keep using aor built-in Layout.

Thanks!

**Comment by matteolc** [comment]
Ops i opened this issue with the wrong account!

**Comment by fzaninotto** [comment]
Yes, this is definitely something we should offer.

**Comment by matteolc** [comment]
Great! Thanks

**Comment by downup2u** [comment]
I need this feature too!
my left menu item is too much! two level menu would be nice!

**Comment by fzaninotto** [comment]
Fixed in #369
