### ISSUE TITLE
Question: AppBar toggle

### ISSUE THREAD

**Issue by matteolc** [marmelab/admin-on-rest#358]
Hello!

Is the `AppBar` toggle going to be toggleable in the next release of `Layout`?

```
class Layout extends Component { 
		
  state = { sidebarOpen: true };   
  toggleSidebar = () => this.setState({sidebarOpen: !this.state.sidebarOpen})
  
  render() { 
      ....
      return (
          ...
          <AppBar title={title} isLoading={isLoading} onLeftIconButtonTouchTap={this.toggleSidebar} />
          ...
       )
    }
}
```

Thanks!

**Comment by fzaninotto** [comment]
The sidebar yes, the `AppBar`, no. I don't understand why you would like to hide the app bar. Feel free to explain your use case even though the issue is closed.

**Comment by matteolc** [comment]
Yes, I used the wrong words, I meant the `Sidebar` to be toggleable. 
(Is the `AppBar` going to be able to toggle the `Sidebar` should have been the correct wording.)
Regards

**Comment by fzaninotto** [comment]
It is already in master, see #328
