### ISSUE TITLE
How to create a page that doesnt need authentication?

### ISSUE THREAD

**Issue by hengkyz** [marmelab/admin-on-rest#367]
i want to create a page that doesnt need authentication,
how to do that? like login page,
what i am doing right is add 1 by 1 the page in the authclient process,
but i think its not that efficient,
what i did before using AOR, i create the function that check the auth then add the function in component parameter in react router,

`<Route path="/crmCustomerTree" component={requireAuthentication(customerTree)} />`

but i dont know how to achieve that with AOR,

**Comment by fzaninotto** [comment]
Use [`onEnter`](https://github.com/ReactTraining/react-router/blob/master/docs/API.md#onenternextstate-replace-callback) on the [custom `<Route>` component](https://marmelab.com/admin-on-rest/AdminResource.html#customroutes).

**Comment by hengkyz** [comment]
thanks @fzaninotto 
i will try that
