### ISSUE TITLE
Can we use browser history instead of hashhistory?

### ISSUE THREAD

**Issue by hengkyz** [marmelab/admin-on-rest#370]
can we use browser history in admin-on-rest (React JS) instead on hashhistory? do i need change something in admin-on-rest or just set the server to handle the URL ?

**Comment by fzaninotto** [comment]
Duplicate of #30 and #327

**Comment by hengkyz** [comment]
@fzaninotto sorry i am still learning,
i already read this post #30 and i try to find the basepath in util but did not find that file,
i still did not get it from that discussion,
is it deprecated?
