### ISSUE TITLE
appbar always show in custom route?

### ISSUE THREAD

**Issue by hengkyz** [marmelab/admin-on-rest#371]
i successfully create a page that doesn't need auth base on my question #367 
but why my appbar always show in my page,
any idea to not render the appbar in my custom route like login page there is no appbar in that page

**Comment by fzaninotto** [comment]
To create custom pages that are not included in admin-on-rest's layout, you'll need to create your own Redux app, and [incorporate admin-on-rest inside it](https://marmelab.com/admin-on-rest/CustomApp.html).
