### ISSUE TITLE
TabbedForm & conditional FormTab

### ISSUE THREAD

**Issue by tgeorges** [marmelab/admin-on-rest#372]
Hi,

I'm trying your API to build a REST admin tool, as it is designed for. 
My Rest API expose Types and Sub Types. To simplify the administration process, I choose to put extra properties defined in subtypes in different FormTabs. This way the extra properties are only shown when an instance implements type A.

To do so I create a component that render an Edit form. This component is connected to Redux state in order to retrieve data and manage the creation of a Tab if data type is equal to A.

At runtime, it create a null child in children collection passed to TabbedForm and there is an error in render function in TabbedForm 

```JSX
{React.Children.map(children, (tab, index) =>
	<Tab key={tab.props.value} label={translate(tab.props.label)} value={index} icon={tab.props.icon}>
		{React.cloneElement(tab, { resource, record, basePath })}
	</Tab>
)}
```

=> In this function, tab is null with my workflow.

To workaround this, i just render different things in my component using regular ES6 if / else and 2 return statements, instead of JSX conditions. Do you think it can be fixed in your API or is it out of the scope ?

Thanks for your feedbacks 

Tony

**Comment by tgeorges** [comment]
By the way, i experienced the same error in FormTab when adding conditionally childrens (in JSX)

`
	<FormTab label="A">
		<TextInput label="Table" source="table" type="url" options={{ fullWidth: true }}/>
		<BooleanInput label="Option ?" source="optionA" />
		{data.optionA && <TextInput label="A field option" source="optionaFieldA" type="text" defaultValue="a" options={{ fullWidth: true }}/> }
	</FormTab>
`

**Comment by JulienDemangeon** [comment]
This issue is already fixed by https://github.com/marmelab/admin-on-rest/pull/323.
You can retrieve it in the next branch.

**Comment by tgeorges** [comment]
Great ! I look forward for the next version,

thank you
