### ISSUE TITLE
use aor within my own redux app, muitheme undefined

### ISSUE THREAD

**Issue by hengkyz** [marmelab/admin-on-rest#374]
i use aor within my own redux app,
i use my own layout 
    `<MuiThemeProvider muiTheme={getMuiTheme(lightBaseTheme)}>
                <div style={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }}>
                    <AppBar showMenuIconButton={true} onLeftIconButtonTouchTap={this.openDrawerMenu}  title={false} iconElementRight={AvatarUser} />
                </div>
            </MuiThemeProvider>`
i already put the muitheme in that component
but in browser still error Warning: Failed context type: The context `muiTheme` is marked as required in `Paper`, but its value is `undefined`.

**Comment by mischa-s** [comment]
@hengkyz I just tripped on this today, did you figure out what you were tripping on?

**Comment by afilp** [comment]
@hengkyz @mischa-s I have the same problem after upgrading to "react-admin beta2". Any ideas? Thanks!

**Comment by fzaninotto** [comment]
You're using an old version of material ui. Look at the warnings about peer dependencies when you `npm install` your app.
