### ISSUE TITLE
Can't use input element outside form

### ISSUE THREAD

**Issue by hengkyz** [marmelab/admin-on-rest#375]
why i cant use input element outside form tag,
when i use Textfield without form tag it wont show but if i wrap it inside form tag it show the element,

**Comment by fzaninotto** [comment]
I don't understand what you're trying to achieve.

Input elements are already used without form tacks in the list filters.

But you have to pass an `input` prop, or decorate them with redux-form's `<Field>` component.

Anyway, admin-on-rest isn't a general form framework, and the input components are supported in admin-on-rest forms only.

**Comment by hengkyz** [comment]
the example is like this,
`<SimpleForm><DateInput source="Date"/></SimpleForm>;` it will show the component
`<DateInput source="Kota"/>;` it wont show in the browser
