### ISSUE TITLE
Toggle sidebar button

### ISSUE THREAD

**Issue by rullyramanda** [marmelab/admin-on-rest#377]
In your demo app, i'm able to toggle the sidebar by clicking the "burger" button on the AppBar, but it is not working in my app, nothing happens when i clicked on it. Is there any option on how to activate the toggling action?

**Comment by wadjeroudi** [comment]
> It is already in master, see #328

**Comment by valueshimoda** [comment]
I think it's not in master. The PR was merged into `next` branch.

https://github.com/marmelab/admin-on-rest/blob/master/src/mui/layout/Layout.js
https://github.com/marmelab/admin-on-rest/blob/next/src/mui/layout/Layout.js

**Comment by fzaninotto** [comment]
Right, it's not in master, it's in `next`.

**Comment by valueshimoda** [comment]
@fzaninotto so it means it's on next release? When is it going to be released?

**Comment by jpetitcolas** [comment]
@valueshimoda: we release once a month, generally in the middle of the month.

**Comment by valueshimoda** [comment]
@jpetitcolas Thank you very much :+1:
