### ISSUE TITLE
Missing field to overload the menu label from a resource

### ISSUE THREAD

**Issue by xavier-fernandez** [marmelab/admin-on-rest#38]
Sometimes APIs include the version (i.e: `/0.4/providers`), there should be an option to override a service label in the menu.

**Comment by Kmaschta** [comment]
You can fullfill your need by configuring your admin as following:
```js
<Admin restClient={simpleRestClient('http://localhost:3000/0.4')}>
        <Resource name="posts" list={PostList} edit={PostEdit} create={PostCreate} icon={PostIcon}/>
</Admin>
```

Or create your own client which can be used as `versionedRestClient('http://localhost:3000', '0.4')`.

**Comment by Kmaschta** [comment]
Oops ! My bad

**Comment by Kmaschta** [comment]
Can't you fullfill your needs by settings your Admin as following?
```js
<Admin restClient={simpleRestClient('http://localhost:3000/0.4')}>
    // ...
</Admin>
```

Or writing a new client which can be used like `versionnedRestClient('http://localhost:3000', '0.4')`

**Comment by xavier-fernandez** [comment]
@Kmaschta Thank you a lot, that approach fixes the problem.
