### ISSUE TITLE
Populating a NestedMenu from a Rest Response

### ISSUE THREAD

**Issue by MikeFair** [marmelab/admin-on-rest#382]
I would like to understand how to instantiate a fetch through the restClient to populate a Menu.

Specifically I'd like to populate the nestedItems array for a resource on the main Menu on the left side but more generally populate other dropdowns from rest responses related to a resource or the global state.  

I exported an ```<ObjMenuItem />``` from the Objs.js file and attached it as the ```menuItem``` property on the ```<Resource />``` element in App.js.  I also added a ```menuInitiallyOpen``` property.

I then modified the local Menu.js file to be like this:
```
const Menu = ({ resources, translate, logout }) => (
    <Paper style={style}>
        <List>
            {resources
                .filter(r => r.list)
                .map(resource => {
                        return <ListItem 
                            key={resource.name}
                            containerElement={<Link to={`/${resource.name}`} />}
                            primaryText={translatedResourceName(resource, translate)}
                            leftIcon={resource.icon && <resource.icon />}

// The new stuff is here
                            initiallyOpen={resource.menuInitiallyOpen}
                            nestedItems={(resource.menuItem) ? resource.menuItem(resource) : []}
                        />
                    ;
                    }
                )
            }
        </List>
        {logout}
    </Paper>
);
```

The ```nestedItems``` property calls the resource.menuItem() function from Menu.js passing in the ```resource``` element.  Inside the Objs.js file the ```ObjMenuItem``` function needs to return the array of nestedChildren.  

This is the part I'm having trouble with.  Given a "resource" element, how do I turn that into an instantiated list of values/elements?

Thanks!

**Comment by fzaninotto** [comment]
You'll have to use a custom menu (allowed by #369, not yet in master), and hook up the Redux store. You need Redux knowledge for that.
