### ISSUE TITLE
Filter Input defaultValue not working when input has property alwaysOn

### ISSUE THREAD

**Issue by FallDi** [marmelab/admin-on-rest#386]
When I use filter with defaultValue & alwaysOn 
```
const UserFilter = props => (
  <Filter {...props}>
    <TextInput label="name" source="name" defaultValue="test" alwaysOn />
  </Filter>
);
```
then default value is not rendered.

Without alwaysOn it works like a charm!

**Comment by fzaninotto** [comment]
I don't know what you expect, and I don't think this should be a feature.

If you want an "always on" default filter, use the list `filter` prop.

Can you explain me your use case?

**Comment by FallDi** [comment]
Use-case:

1) Show list of users
2) Buy default show only "Active" users(using filter)
3) "Admin-on-rest customer" can be able to see all users(disable filter)

Maybe it not admin-on-rest functionality/feature, but I caught this unexpected behavior

**Comment by matteolc** [comment]
I actually have the same issue: I need a date input filter always on and with a default value, but the default value doesn't apply to the input when set to `alwaysOn`.

**Comment by matteolc** [comment]
Example:

```
export const MyFilter = (props) => (
    <Filter 
      {...props} 
      >
      <DateInput label="Before" source="start_stamp.leq" alwaysOn defaultValue={moment().endOf('day').format()} />
      <DateInput label="After" source="start_stamp.geq" defaultValue={moment().startOf('day').format()}/>
    </Filter>
);
```

**Comment by matteolc** [comment]
Basically there's a `componentShouldUpdate `missing somewhere when `alwaysOn `is set..

**Comment by djhi** [comment]
Can't reproduce anymore on `master`
