### ISSUE TITLE
<ImageField> breaks form when used as last form field

### ISSUE THREAD

**Issue by Natsuke** [marmelab/admin-on-rest#395]
Hi,

Just run into a problem using ImageField as last field in a form, this breaks the form display due to the `float: left` on the component.

```js
export const StorageFileEdit = (props) => (
  <Edit title={<StorageFileTitle />} {...props}>
    <SimpleForm validation={createValidation(validationSchema)}>
      <DisabledInput source='id' />
      <TextInput source='name' />
      <ImageField source='url' />
    </SimpleForm>
  </Edit>
)
```

![screenshot-0 0 0 0-3001 2017-03-07 15-06-21](https://cloud.githubusercontent.com/assets/5891633/23660284/326fc702-0349-11e7-8cc8-17c8d218938c.png)

Using a fields (TextField e.g.) after the `ImageField` one or using artifice like the code above solve the problem.

```js
export const StorageFileEdit = (props) => (
  <Edit title={<StorageFileTitle />} {...props}>
    <SimpleForm validation={createValidation(validationSchema)}>
      <DisabledInput source='id' />
      <TextInput source='name' />
      <BlockImageField />
    </SimpleForm>
  </Edit>
)

const BlockImageField = (props) => (
  <div style={{ display: 'inline-block' }}>
    <ImageField {...props} source='url' />
  </div>
)
```

But I'am asking if the `float: left` attributes is still necessary, or if so, if there is a better way to display the ImageField whitout breaking the form.

Thanks !

**Comment by jpetitcolas** [comment]
Good catch! I think a `clear: both;` in an `.image-input::after` element would solve the issue. I'll take a look on it later, unless you are volunteer to give it a try? :)

**Comment by Natsuke** [comment]
I'll do it 👍

**Comment by djhi** [comment]
Can't reproduce the problem anymore.
