### ISSUE TITLE
Package.json modification for npm start 

### ISSUE THREAD

**Issue by velociwabbit** [marmelab/admin-on-rest#397]
As a convenience for those not familiar with admin-on-rest adding a line to the package.json file would make life easier.  my suggested new package.json file would be as follows:
```

{
  "name": "redux-crud-example",
  "version": "1.0.0",
  "description": "",
  "main": "index.html",
  "scripts": {
    "start" : "webpack-dev-server",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "aor-json-rest-client": "~1.5.0",
    "aor-language-french": "~1.5.0",
    "aor-rich-text-input": "~1.0.0",
    "babel-plugin-transform-react-jsx": "^6.8.0",
    "babel-polyfill": "^6.9.1",
    "babel-preset-react": "^6.11.1"
  }
}

```
I also suggest adding an automatic install of the example from the parent npm install  and adding a line in that package.json  which is the following

  "scripts": {
    "start" : "cd example & webpack-dev-server",
    "test": "echo \"Error: no test specified\" && exit 1"
  },

**Comment by fzaninotto** [comment]
We show how to use it with `create-react-app`, if you want to use other options that's up to you.

Advocating for one single way to setup JS projects is not the purpose of admin-on-rest.
