### ISSUE TITLE
Show Edit function does not allow editing of complete document in example.

### ISSUE THREAD

**Issue by velociwabbit** [marmelab/admin-on-rest#398]
When one clicks on the edit button in the show component of comments in the example the edit panel comes up but  the text is only partially editable (the body component is not displayed or can it be edited).  If this is by design then it might be worthwhile considering  having another component example that demonstrates full text editing.

**Comment by fzaninotto** [comment]
I don't understand your bug. What are you referring to? If it's the blog demo, then the `comments` resource has no `Show` page, only an `Edit` page. 

Please be more specific, and ideally, add a few screenshots.

**Comment by velociwabbit** [comment]
I am going to close this issue as it appears that in the latest release it is fixed.

My apologies for wasting your time
