### ISSUE TITLE
Edit inline functionality on DataGrid

### ISSUE THREAD

**Issue by Buffer-Overflow** [marmelab/admin-on-rest#401]
Is it possible to edit textfields in the datagrid inline? When you click the text field, it should change into an input field, and a save button should appear behind the row. When saved it should call the same action as the edit form (create/edit view) that is currently on a separate page.

**Comment by Buffer-Overflow** [comment]
I'll create my own custom EditableTextField to accomplish this behaviour.

**Comment by jozekcore** [comment]
@pixelscripter Hi! can you show me that component? I wan't to do that but the NumberFiled

**Comment by pixelscripter** [comment]
Hi @jozekcore unfortunately I never finished this component, because we switched to building a custom admin.
