### ISSUE TITLE
cookie does not pass to other requests after authentication

### ISSUE THREAD

**Issue by mingchen** [marmelab/admin-on-rest#403]
My server listen on port 3000, backend listen on port 2339, they are different server.

I use cookie to do authentication, after login successfully, server response Set-Cookie to client.
however client does not set Cookie header in next request, it cause the next request response 403 and redirect to login page.

    export default (type, params) => {
        if (type === AUTH_LOGIN) {
            const { username, password } = params;
            const request = new Request('http://localhost:2339/api/authentication', {
                method: 'POST',
                body: JSON.stringify({username, password}),
                headers: new Headers({'Content-Type': 'application/json; charset=utf-8'})
            });

            return fetch(request)
                .then(response => {
                    if (response.status < 200 || response.status >= 300) {
                        throw new Error(response.statusText);
                    }
                    return response.json();
                })
                .then(({ id }) => {
                    console.log('login successfully. userId: ' + id);
                    localStorage.setItem('userId', id)
                });
        }

        if (type === AUTH_CHECK) {
                let userId = localStorage.getItem('userId');
                console.log('AUTH_CHECK: userId=' + userId);
                return userId ? Promise.resolve() : Promise.reject();
        }

Here is response headers:

        Set-Cookie:  sid=AQRvWju5iKtKhQcL6n7HL2UHr1ppVc; Path=/; HttpOnly
        Access-Control-Allow-Origin: http://localhost:3000
        
How to let cookie pass through after login successfully, is there any special settings ?

**Comment by wadjeroudi** [comment]
Your cookie sid seems to be a HttpOnly cookie. So it shouldn't be available to JS.

> The HttpOnly cookie is supported by most modern browsers. On a supported browser, an HttpOnly session cookie will be used only when transmitting HTTP (or HTTPS) requests, thus restricting access from other, non-HTTP APIs (such as JavaScript).

**Comment by mingchen** [comment]
Thanks for quick reply!

Even I removed HttpOnly, it still not pass cookie to next API request. It is a cross domain request, have admin-on-rest test this scenario ?

    HTTP/1.1 200 OK
    Set-Cookie:  sid=s%3Az6PI4ZRfheU2P8ev66_5cuoQHIQV9VVM; Path=/; 
    Access-Control-Allow-Origin: http://localhost:3000

**Comment by fzaninotto** [comment]
Admin-on-rest doesn't speak HTTP, it speaks REST. It is your responsibility to manage the (often cross-domain) communication between the browser and your REST API in the `restClient` function.

I don't know if it can help you, but I wrote a post about API authentication a while ago : http://www.redotheweb.com/2015/11/09/api-security.html

**Comment by mingchen** [comment]
Thanks @fzaninotto a lot.

The issue is not HttpOnly. It is due to cross domain api request, by default, cookie is not stored and passed through API requests.
For another may search to this post, the solution is rest API need add `credentials: 'include'` option.

see https://developer.mozilla.org/en-US/docs/Web/API/Request/credentials
