### ISSUE TITLE
Performance hit by using pure in crudRoute.

### ISSUE THREAD

**Issue by velociwabbit** [marmelab/admin-on-rest#410]
I was looking at the routing code and was trying to figure out what recompose.pure actually did and tried running the code without it and there is a substantial performance improvement by not using it.  

If pure is just to test whether updates are needed (as per the documentation) the point of that test is performance optimization.  Given what i found you might want to do your own test to see if what i discovered is also true generally.

If all it does is in theory improve performance then it is a good candidate for removal.

**Comment by fzaninotto** [comment]
Could you explain how you tested the performance, and how much difference you detected?

**Comment by velociwabbit** [comment]
I took the CrudRoute.js module and modified it by removing the pure wrapper (below)

I was using it on my own project and it could be that because i have been using material.ui's Master and AppNavBar in lieu of Admin / Layout   my performance might be different.

(as a aside I would be willing to contribute my code for this modification if anyone is interested. The key feature is that the menu-bar can slide and I can add many levels of expanding sub-menus.  Also column toggle for lists )

I did not benchmark the change but it is on the order of 1/2 second load times... approximately.

```
import React from 'react';
import { IndexRoute, Route } from 'react-router';
import { createRoutesFromReactChildren } from 'react-router/lib/RouteUtils';
import pure from 'recompose/pure';

const CrudRoute = () => <div>&lt;CrudRoute&gt; elements are for configuration only and should not be rendered</div>;

CrudRoute.createRouteFromReactElement = (element, parentRoute) => {
    const { path, list, create, edit, show, remove, options, onEnter = () => null } = element.props;

    // dynamically add crud routes
    const crudRoute = createRoutesFromReactChildren(
        <Route path={path}>
            {list && <IndexRoute component={list} onEnter={onEnter({ resource: path, route: 'list' })} />}
            {create && <Route path="create" component={create} onEnter={onEnter({ resource: path, route: 'create' })} />}
            {edit && <Route path=":id" component={edit} onEnter={onEnter({ resource: path, route: 'edit', scrollToTop: true })} />}
            {show && <Route path=":id/show" component={show} onEnter={onEnter({ resource: path, route: 'show', scrollToTop: true })} />}
            {remove && <Route path=":id/delete" component={remove} onEnter={onEnter({ resource: path, route: 'delete' })} />}
        </Route>,
        parentRoute,
    )[0];
    // higher-order component to pass path as resource to components
    crudRoute.component =   

///////////////////// here
 // pure(   


      ({ children }) => (
        <div> 
            {React.Children.map(children, child => React.cloneElement(child, {
                resource: path,
                options,
                hasList: !!list,
                hasEdit: !!edit,
                hasShow: !!show,
                hasCreate: !!create,
                hasDelete: !!remove,
            }))}
        </div>
    ) 


//////////////////and here
  // )     



    return crudRoute;
};
```

export default CrudRoute;

**Comment by fzaninotto** [comment]
> I did not benchmark the change but it is on the order of 1/2 second load times... approximately.

That's not enough.

When we work on performance, we profile our changes with `?react_perf` to have an objective feedback (see https://facebook.github.io/react/blog/2016/11/16/react-v15.4.0.html#profiling-components-with-chrome-timeline).

Please provide convincing evidence that `pure` degrades performance (which is very counter-intuitive).

**Comment by velociwabbit** [comment]
Suit yourself. For anyone else that has noticed a performance issue when rendering crudRoute removing pure helped for me.
