### ISSUE TITLE
TextInput - Typing Chinese with Pinyin, the first letter of Pinyin always input automatically

### ISSUE THREAD

**Issue by imaaronzhang** [marmelab/admin-on-rest#411]
In TextInput, typing Chinese with Pinyin, the first letter of Pinyin always input automatically. 
e.g. Keyboard ‘谢’ with Pinyin 'xie', it keyboard 'x谢' .
I think other languages have the same issue.
The online demo has the same issue.

It might be related to "Field" of  ''redux-form".
The login page is without TextInput has also the same issue.
`const renderInput = ({ meta: { touched, error } = {}, input: { ...inputProps }, ...props }) =>
    <TextField
        errorText={touched && error}
        {...inputProps}
        {...props}
        fullWidth
    />;
.....
    <Field
                                        name="username"
                                        component={renderInput}
                                        floatingLabelText={translate('aor.auth.username')}
                                    />` 
If remove   {...inputProps} , the issue is disappeared.

**Comment by fzaninotto** [comment]
Weird. The problem doesn't happen in French or English. 

Could that be a bug with redux-form itself? Could you test a simple `<Field>` without admin-on-rest?

**Comment by imaaronzhang** [comment]
Non-letter languages should have the issue.

It works well that a simple <Field> without admin-on-rest. I have verified that simple TextField of material-ui, redux-form and maaterial ui，they all work well.
it maybe caused by global 'onChange' or 'onFocus'.  
Are there some code that it keyboard 'Enter' automatically when a empty 'Input' first change?

I have only verified the newest version of 'redux-form', I will verified the older version.

**Comment by downup2u** [comment]
I found this issue too,but I don't know why.I cannot fix it either.

**Comment by downup2u** [comment]
with lastest 'admin-on-rest' (0.9.4) .I removed 'node_modules' directory from my project,
then 'npm install' & 'npm start', It's ok!!! @imaaronzhang try it!

**Comment by velociwabbit** [comment]
Bnbbb,

On Apr 7, 2017 5:02 AM, "Francois Zaninotto" <notifications@github.com>
wrote:

Closed #411 <https://github.com/marmelab/admin-on-rest/issues/411>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/marmelab/admin-on-rest/issues/411#event-1033978455>,
or mute
the thread

**Comment by imaaronzhang** [comment]
@downup2u Thank you. I had a try by your way, it still doesn't work. I think the issue is related with 'recompose'.
