### ISSUE TITLE
EDIT not showing on the <RESOUCE>

### ISSUE THREAD

**Issue by Tim1023** [marmelab/admin-on-rest#414]
I have follow the instruction on the website and found out the EDIT part not showing in the list page.

Here is my code.  

```js
<Resource name="Merchants" list={Merchants} options={{ label: 'store' }} icon={MerchantIcon} edit={MerchantEdit} create={MerchantCreate}  />

export const MerchantEdit = (props) => (
  <Edit {...props} title='Edit'>
    <SimpleForm>
      <DisabledInput label="Id" source="id"/>
      <TextField source="Translate[0].DisplayName" label="name"/>
      <FunctionField source="Rating" render={record => `${record.Rating / 100}`} label="rate"/>
      <TextField source="MonthlySales" label="sales"/>
    </SimpleForm>
  </Edit>
);
```

**Comment by fzaninotto** [comment]
The configuration is correct. Do you see any error message in the console?

Which version of admin-on-rest are you using?

**Comment by Tim1023** [comment]
@fzaninotto Thanks for your prompt reply. The version I am using is the latest one v0.9.0.  I also have tried v0.8.4, the same issue in that version as well.

**Comment by fzaninotto** [comment]
And do you see any error message in the console?

**Comment by Tim1023** [comment]
@fzaninotto 
nope, nothing showing in the console

**Comment by leesei** [comment]
Did you add `EditButton` to `Merchants`?

```jsx
export const Merchants = (props) => (
    <List {...props}>
        <Datagrid>
            <TextField source="id" />
             ...
            <EditButton />
        </Datagrid>
    </List>
);
```

**Comment by Tim1023** [comment]
@leesei  The problem solved, Thank you so much!
