### ISSUE TITLE
Resource name should be singular form

### ISSUE THREAD

**Issue by kimkha** [marmelab/admin-on-rest#415]
Current, with almost RESTful API, the API Url is `/vipusers/123`. Then, the resource name must be:

```
<Resource name="vipusers"
```

I think the name should be in singular form (`vipuser`, or `VipUser`). The API client should apply plural form by themselve (just use `inflection` module which include in aor by default).

**Comment by fzaninotto** [comment]
The mapping between the resource name and the API route name is the job of the `restClient`. If both your Resources and API uses plural name, then you don't need to do anything special. Otherwise, you'll have to add mapping logic yourself.
