### ISSUE TITLE
Coupled fields and deferred rendering in creation

### ISSUE THREAD

**Issue by leesei** [marmelab/admin-on-rest#423]
Suppose I'm creating a Location with District and Street.
Since each Street belongs to a District, I would like the Street selection to render *after* the user selects the District with the selected district as filter.

I only came up with this after reading the documentation:
```
export const LocationCreate = (props) => {
    return (<Create {...props}>
        <SimpleForm>
            <ReferenceInput label="District" reference="district" source="districtId" allowEmpty>
                <SelectInput optionText="name" />
            </ReferenceInput>
            <ReferenceInput label="Street" reference="street" source="streetId" allowEmpty>
                <SelectInput optionText="name" />
            </ReferenceInput>
        </SimpleForm>
    </Create>);
};
```

Any pointer as to how to implement my requirement? Thanks.

**Comment by fzaninotto** [comment]
That's actually more a React, or a `redux-form` related question.

Here are some pointers:

* https://github.com/erikras/redux-form/issues/624
* https://github.com/erikras/redux-form/issues/1500#issuecomment-238624882
