### ISSUE TITLE
Customize output of input components before submit

### ISSUE THREAD

**Issue by leesei** [marmelab/admin-on-rest#424]
Use cases:
- user input percentage as `90` and API requires `0.9`
- user select Date and API only requires `"YYYY-MM-DD"`

How should I customize user's input, preferably within the form before calling to `restClient`? Use `parse()` on `Field`?
Or it's actually `restClient`'s responsibility to transform the params per each `resource` type?

Side note, why does `DateInput` stores the selected date in string instead of `Date` object?

**Comment by fzaninotto** [comment]
Great question. My opinion is that it's `redux-form`'s job, using `parse` and `normalize`. Set these props in your Input component, admin-on-rest will pass them to [`Field`]((http://redux-form.com/6.5.0/docs/api/Field.md/)).

As for DateInput, I agree that it's counter-intuitive. Could you open a bug just for this one?

**Comment by leesei** [comment]
Thanks for the pointer.
I'll add a demo to the document after I worked it out.

Opened #426.

**Comment by leesei** [comment]
I've spent time studying redux-form, `parse` and `normalize` can handle simple use case:
```js
const percentFormatter = (v) => {
  if (v instanceof Number) {
    return v*100;
  }
};
const percentNormalizer = (v) => v/100;
<NumberInput source="percent" format={percentFormatter} normalize={percentNormalizer} label="Formatted number" />
```

However this does not work for `<DateInput>` since `record.date` is directly set within the component.

```js
const dateFormatter = (v) => {
  console.log('format:', v, v instanceof Date);
  // undefined, then "Invalid Date", then Date
  if (!(v instanceof Date) || isNaN(v)) return;

  return `${v.getFullYear()}-${v.getMonth()+1}-${v.getDate()}`;
};
const dateNormalizer = (v) => {
  // empty string, then Date
  console.log('normalize:', v, v instanceof Date);
  return new Date(v);
};
<DateInput source="date" format={dateFormatter} normalize={dateNormalizer} />
```

What's your thought on adding a pre-submit handler to `<Create>` and `<Edit>`?
Can this issue be reopened for discussion?

**Comment by fzaninotto** [comment]
well, that means that we should handle current normalization with `normalize` in `DateInput` rather than with `value`. 

More generally, I'm against replicating redux-form features in admin-on-rest.

**Comment by leesei** [comment]
I agree with your stance. But I don't think redux-form's `parse` and `normalize` can handle the 2nd use case.
Maybe I should open an issue there?

**Comment by fzaninotto** [comment]
what's the 2nd use-case?

**Comment by leesei** [comment]
The one where the source (`record.date`) is share with other components (`DatePicker` here).

```js
const dateFormatter = (v) => {
  console.log('format:', v, v instanceof Date);
  // undefined, then "Invalid Date", then Date
  if (!(v instanceof Date) || isNaN(v)) return;

  return `${v.getFullYear()}-${v.getMonth()+1}-${v.getDate()}`;
};
const dateNormalizer = (v) => {
  // empty string, then Date
  // I expect string formatted by dateFormatter() here
  console.log('normalize:', v, v instanceof Date);
  return new Date(v);
};
<DateInput source="date" format={dateFormatter} normalize={dateNormalizer} />
```

**Comment by leesei** [comment]
It turns out the above code sample is wrong, I worked out the 2nd use case.
I'm gonna test some more before adding to the doc.

**Comment by leesei** [comment]
Created #555.
