### ISSUE TITLE
`DateInput` stores the selected date in string instead of `Date` object

### ISSUE THREAD

**Issue by leesei** [marmelab/admin-on-rest#426]
Other input (e.g. `NumberInput`, `BooleanInput`) stores the native Javascript types.

**Comment by fzaninotto** [comment]
I can't reproduce the issue. Redux-form dispatches a `@@redux-form/CHANGE` action with a `Date` payload (not a string).

Can you provide a failing test case?

**Comment by leesei** [comment]
I'm following the tutorial, the log in the rest client.

```
// restClient.js

import { jsonServerRestClient, fetchUtils } from 'admin-on-rest';

// we are using `jsonServerRestClient` with custom header
const httpClient = (url, options = {}) => {
    console.log(`httpClient`, url, options);
    if (!options.headers) {
        options.headers = new Headers({ Accept: 'application/json' });
    }
    const token = localStorage.getItem('token');
    if (token) {
      options.headers.set('X-Token', token);
    }
    return fetchUtils.fetchJson(url, options);
};

export default jsonServerRestClient('http://jsonplaceholder.typicode.com', httpClient);
```

![screenshot from 2017-03-14 22-39-55](https://cloud.githubusercontent.com/assets/544400/23905807/2b71665e-0907-11e7-88ab-65da1f93285d.png)

On second thought the body is already `JSON.stringify()`-ed.
Where is the record in `crudCreate` converted to body? I lost track at `crudFetch`.
