### ISSUE TITLE
ReferenceInput do not work if there are no defaultValue in <Create/> and </Edit>

### ISSUE THREAD

**Issue by imaaronzhang** [marmelab/admin-on-rest#427]
The codes below:
```
<ReferenceInput source="category_id" reference="categories" >
                <SelectInput source="name" />
 </ReferenceInput>
```
It works well in` <Filter/>`. It is bad in `<Create/>` and `<Edit/>`, only display the label, no 'select input'. No error happens.
But it will be ok if with a defaultValue, like the codes below.
```
<ReferenceInput source="category_id" reference="categories" defaultValue={0} >
                <SelectInput source="name" />
 </ReferenceInput>
```

**Comment by fzaninotto** [comment]
in `docs/Tutorial.md:239`:

> **Tip**: The `<Edit>` and the `<Create>` components use the same `<ReferenceInput>` configuration, except for the `allowEmpty` attribute, which is required in `<Create>`.

**Comment by imaaronzhang** [comment]
Thanks
