### ISSUE TITLE
Charts and graphs

### ISSUE THREAD

**Issue by velociwabbit** [marmelab/admin-on-rest#428]
I am presently putting together a set of react-based charts for viewing historical data etc.

Before I dig myself into a hole I was wondering whether graphs and charts were going to be included in aor?

If there are plans to do them what libraries were you thinking of using?

If there are no plans to do them is there interest in having them done?

**Comment by jpetitcolas** [comment]
I don't think we are going to embed them in core directly. Indeed, each chart is generally presented in a unique way, and charts are quite specific need. Moreover, as admin-on-rest relies on React component, it should be quite easy to implement them. 

However, feel free to open an admin-on-rest package to embed your own chart, as we did with [aor-rich-text-input](https://github.com/marmelab/aor-rich-text-input) module for instance.

@fzaninotto: I let you close this issue and eventually correct my previous thought. :)

**Comment by fzaninotto** [comment]
Charts are definitely **outside the scope** of admin-on-rest. You can write your own charts using React and / or d3.js.
