### ISSUE TITLE
Responsively render more or less columns in a table

### ISSUE THREAD

**Issue by faviouz** [marmelab/admin-on-rest#432]
I have a big table with lots of columns (which will probably get bigger as development goes on) that doesn't fit in its container and is cutoff the page.

![image](https://cloud.githubusercontent.com/assets/180382/23871337/db0cb41a-0821-11e7-8731-4c491f70d2ab.png)

Can I somehow make it render more/less columns in the table in a responsive manner? Or maybe there's a better solution? Maybe I should use a different component for really big tables?

I know I can render different components at different breakpoints using `<Responsive>`, but I was hoping the components were more fluid and responsive in general.

**Comment by fzaninotto** [comment]
This is a question for the material-ui project. We're just using their Table component.
