### ISSUE TITLE
Input in a <Create> view that fetches possible values from another resource

### ISSUE THREAD

**Issue by faviouz** [marmelab/admin-on-rest#433]
In the Create Robot page I would like Company to be a select menu that fetches possible name values from the Companies resource. How can I do that?

I thought the following might work but obviously it doesn't because the robot I'm currently trying to create doesn't have a `cid` (company ID) yet, obviously.
```
<ReferenceInput reference="companies" source="cid" label="Company">
    <SelectInput optionText="name" />
</ReferenceInput>
```

It renders to the following, where the Company input is disabled and not clickable.

![image](https://cloud.githubusercontent.com/assets/180382/23871516/ae499974-0822-11e7-9457-558bf0d49c67.png)

**Comment by fzaninotto** [comment]
in `docs/Tutorial.md:239`, you can read:

**Tip**: The `<Edit>` and the `<Create>` components use the same `<ReferenceInput>` configuration, except for the `allowEmpty` attribute, which is required in `<Create>`.

**Comment by faviouz** [comment]
Thanks @fzaninotto, that does the trick!

But I don't actually want to allow it to be empty, I want it to be required. How do I accomplish that?

**Comment by fzaninotto** [comment]
Add a `validation={{ require: true }}` prop.
