### ISSUE TITLE
XSS vulnerable

### ISSUE THREAD

**Issue by faviouz** [marmelab/admin-on-rest#436]
https://marmelab.com/admin-on-rest/Authentication.html

> Tip: It’s a good idea to store credentials in localStorage, to avoid reconnection when opening a new browser tab. But this makes your application [open to XSS attacks](http://www.redotheweb.com/2015/11/09/api-security.html), so you’d better double down on security, and add an httpOnly cookie on the server side, too.

How does this make the application vulnerable to XSS? The linked article explains React avoids XSS vulnerabilities by not manipulating the DOM directly.

**Comment by fzaninotto** [comment]
Because any XSS vulnerability lets the attacked execute JS on the page, and grab credentials from localStorage.

The formulation may be misleading. What it should say is: if your application is open to XSS attacks, storing credentials in localStorage makes intrusions catastrophic.

**Comment by faviouz** [comment]
Thanks for clearing it up for me! :)
