### ISSUE TITLE
Alternative UI with react-md

### ISSUE THREAD

**Issue by tb** [marmelab/admin-on-rest#437]
Would you consider adding React-MD? It its much more feature rich then Material-UI or React-MDL, like: 
- https://react-md.mlaursen.com/components/data-tables (including great UI for bulk actions)
- https://react-md.mlaursen.com/components/dialogs (including full page dialog)
- https://react-md.mlaursen.com/components/select-fields
- https://react-md.mlaursen.com/components/pickers/date

**Comment by fzaninotto** [comment]
No, because material-ui is much more mature, and supported for a long time. 

But if you want to build an alternative library of components for admin-on-rest, it's quite easy: fork the project, and replace the `mui` folder by your own folder of components.
