### ISSUE TITLE
removing LIST filter makes fetch request doubled

### ISSUE THREAD

**Issue by az** [marmelab/admin-on-rest#443]
hi,

after removing any filter i can see 2 identical fetch requests ...
i have noticed that in my project, than i have confirmed the same behaviour on https://marmelab.com/admin-on-rest-demo/

**Comment by fzaninotto** [comment]
Confirmed, I can reproduce the bug.

**Comment by djhi** [comment]
Can't reproduce this bug on 1.0.1 anymore. @az, can you confirm ?
