### ISSUE TITLE
Filter - Display "Empty" Result

### ISSUE THREAD

**Issue by mantis** [marmelab/admin-on-rest#445]
Hi Guys,

When filtering e.g. on https://marmelab.com/admin-on-rest-demo, if you do a search that generates an empty result, no results are returned as expected - however it would be good to show that there are no results within the UI.

This would allow an end use to distinguish more easily between the difference between a slow response and no results being returned.

When using https://datatables.net/ in jquery, the table would display a "no results" message. I'm not sure if it would be possible to do similar in react.

**Comment by fzaninotto** [comment]
Nice idea, and quite easy to achieve indeed. Would you like to give it a try?

**Comment by mantis** [comment]
I think i will give it a go

**Comment by fzaninotto** [comment]
Fixed by #487
