### ISSUE TITLE
Validation errorText on SelectInput is not displayed properly

### ISSUE THREAD

**Issue by Natsuke** [marmelab/admin-on-rest#447]
Hi guys,

Like the title said, validation on an `SelectInput` is not displayed properly.

At this time this is how it looks like

![capture d ecran 2017-03-14 a 16 16 46](https://cloud.githubusercontent.com/assets/5891633/23947021/1f2aa24a-097d-11e7-84cd-38128db813ce.png)

With invastigation, the problem seems to came from `SelectInput` due to the custom [menuStyle](https://github.com/marmelab/admin-on-rest/blob/master/src/mui/input/SelectInput.js#L66) prop passed to `SelectField`

If we remove it, we retrieve the original usage of `material-ui`

![capture d ecran 2017-03-14 a 16 13 56](https://cloud.githubusercontent.com/assets/5891633/23947118/99506e74-097d-11e7-92e5-8801e04dd807.png)

As you can see, after remove, `SelectInput` looks the same, so I wonder if this property is still necessary !

**Comment by fzaninotto** [comment]
The property is necessary to display SelectInput correctly in the Filter form. But I'll find another way.
