### ISSUE TITLE
[PROPOSAL] Validation on non material-ui components

### ISSUE THREAD

**Issue by Natsuke** [marmelab/admin-on-rest#448]
Hi guys,

At this time non-material-ui don't display any validation error.
This is quite bad for UX, as you can submit a form and get no return.

We can for instance,
- Turn the `Labeled` component text `red`
- ...

**Comment by remi13131** [comment]
+1 I mentionned the same for BooleanInputs (here: https://github.com/marmelab/admin-on-rest/issues/439), didn't know it was the case for other inputs !

**Comment by fzaninotto** [comment]
Please be more specific and list the inputs that don't show validation errors.

We'll display them in a similar way as for material-ui components.

**Comment by fzaninotto** [comment]
Any updates on this one?

**Comment by fzaninotto** [comment]
No news for some time, closing.

**Comment by nik-lampe** [comment]
@fzaninotto 
I came across this issue while looking for a solution to display validation errors on custom inputs. As far as I see there is no convenient way to display errors on custom inputs at all. 

When **not** using the `Labeled` component I have the meta props on my custom component, so I might build some sort of visualization when the error field contains something. But when using the `Labeled`component it "omits" the meta prop. So I can't use it in my custom component.

But in my opininion iit should be the `Labeled` components job to display any validation errors.

What do you think?

**Comment by fzaninotto** [comment]
This will be fixed by material-ui 1.0, which offers atomic components for label, errors, etc. In the meantime, you'll have to do it by hand.
