### ISSUE TITLE
Refresh clears edit form

### ISSUE THREAD

**Issue by thedersen** [marmelab/admin-on-rest#451]
admin-on-rest version 0.9.1

Hitting refresh empties the form when editing a resource:

![refresh](https://cloud.githubusercontent.com/assets/131983/23972710/1d29e7ca-09d3-11e7-8519-6e90004bd40b.gif)

**Comment by fzaninotto** [comment]
Confirmed, it's a regression.

**Comment by fzaninotto** [comment]
This is caused by #290
