### ISSUE TITLE
ImageInput no preview onDrop

### ISSUE THREAD

**Issue by DjLeChuck** [marmelab/admin-on-rest#452]
When using `ImageInput` and `ImageField`, there is no preview onDrop because the `files` state is malformatted.

      <ImageInput source="image" label="Image" accept="image/*">
        <ImageField source="src" title="title" elStyle={imageStyle} />
      </ImageInput>

When I drop the file, `this.setState({ files: updatedFiles });` is good. My existing file and the new are simple objects with a src property.
However, when the render function loop through the files, my existing file has disappear and the new one is not anymore an object with `src` property but a JS `File` object.

I'm using admin-on-rest version 0.9.1 and react 15.4.2

Sorry for my English, I could explain better in French if needed...

**Comment by fzaninotto** [comment]
ping @jpetitcolas

**Comment by jpetitcolas** [comment]
I'm already working on it. A fix should be available later today. :)
