### ISSUE TITLE
Validation error

### ISSUE THREAD

**Issue by thedersen** [marmelab/admin-on-rest#458]
When editing a resource, validation return errors on populated fields before anything is changed:

![validation](https://cloud.githubusercontent.com/assets/131983/23973067/b927565c-09d4-11e7-9f66-dc20e4128de0.gif)

Can verify that it is related to [this bug](https://github.com/erikras/redux-form/issues/1901) in redux-form.

Upgrading redux-form fixes it.

**Comment by fzaninotto** [comment]
Fixed by #420 (upgrading to the latest redux-form release). Currently in `next` because it's a BC break.
