### ISSUE TITLE
Change the whole record from a CustomField

### ISSUE THREAD

**Issue by omidn** [marmelab/admin-on-rest#469]
I have a Edit component similar to this:

```
<Edit {...props} >
    <CustomField />
    <TextInput source="title" />
</Edit>
```
Inside the `CustomField` I want to make changes to the whole record so that the `title` changes by `CustomField` without persisting it on the on the server. 

Do you have any clue how is this possible?

**Comment by fzaninotto** [comment]
This is more a question for redux-form. I advise you to ask your question there.
