### ISSUE TITLE
Many to many and CheckboxGroupInput

### ISSUE THREAD

**Issue by Palethorn** [marmelab/admin-on-rest#470]
Hello,
I somehow need to display checkbox group to select multiple options and save them in a many-to-many relation. Any suggestions on how to do it? I saw this issue #45, and it's probably related to this one. I don't understand this framework enough to implement my own component.

**Comment by fzaninotto** [comment]
We don't provide support through GitHub issues. If you need advice on using or debugging your own project based on admin-on-rest, please use [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest).

**Comment by Palethorn** [comment]
Ok, I'll head there.
