### ISSUE TITLE
search filter and sort not working on nested objects?

### ISSUE THREAD

**Issue by knekke** [marmelab/admin-on-rest#471]
Hi,
I have a datagrid with some nested objects to populate the textfields (e.g. client.name), but it seems the search filter isn't working on these. User error, design, or bug? Same goes for sorting btw.
Thanks

**Comment by fzaninotto** [comment]
Hi,

If I try adding a filter on a nested field in the blog example:

```js
const CommentFilter = ({ ...props }) => (
    <Filter {...props}>
        <TextInput source="author.name" />
    </Filter>
);
```

Then typing the string "foobar" in the author search box issues the following REST request:

> GET_LIST comments {"filter":{"author":{"name":"logan"}},"pagination":{"page":"1","perPage":"6"},"sort":{"field":"id","order":"DESC"}}

This seems perfectly fine to me. Now it's up to your REST client to transform that into something your API can understand.

As for the sorting, if I add a nested field in my datagrid:

```js
export const CommentList = ({ ...props }) => (
    <List {...props}>
        <Datagrid>
            <TextField source="author.name" />
        </Datagrid>
    </List>
);
```

Then clicking on the author name column header does issue a proper REST query for the nested field:

> GET_LIST comments {"sort":{"field":"author.name","order":"ASC"},"pagination":{"page":"1","perPage":"6"},"filter":{}}

Once again, it's up to your restClient to turn that into something your API can understand.
