### ISSUE TITLE
Question: Access the model from the Edit component

### ISSUE THREAD

**Issue by Rulox** [marmelab/admin-on-rest#473]
Hi! First of all congratulations for this admin panel! 
I think is amazing and has saved my life!

I have the following edit component
```javascript
const UserEdit = (props) => (
  <Edit {...props}>
    <TabbedForm >
      <FormTab label="User Account">
        <DisabledInput source="id" />
        <TextInput source="email" />
        <TextInput source="password" type="password"/>
        <TextInput source="name" />
        <TextInput source="phone" />
        <SelectInput source="role" optionValue="id" choices={choices} />
      </FormTab>
      <FormTab label="Customer Information">
        <BooleanInput label="New user" source="Customer.is_new" />
        <BooleanInput label="Grandfathered user" source="Customer.grandfathered" />
      </FormTab>
    </TabbedForm >
  </Edit>
);
```

The second FormTab (Customer Information) I only need it to appear if the User model has some information associated (the JSON is something like):

```javascript
{
   id: <int>,
   name: <string>,
   ....
   Customer: {
       is_new: true,
       grandfathered: true,
   }
```

I'd like to know if I can access somehow the model information (in this case, if the Customer key is not null) in order to be able to render or not the `<FormTab>`

I've been reading the doc and I couldn't find anything, I guess it depends on how the components are built, but I'm a little bit lost with the global redux state. I know the data is in the state because I've debugged it with the Redux tools. (I tried to look in this.props but I couldn't find anything to access the state)

Thanks and sorry for creating an issue for this!

**Comment by fzaninotto** [comment]
We don't provide support through GitHub issues. If you need advice on using or debugging your own project based on admin-on-rest, please use [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest).
