### ISSUE TITLE
MultiSelect Dropdown Input

### ISSUE THREAD

**Issue by mantis** [marmelab/admin-on-rest#476]
For a long dropdown list, that could allow multiple values (e.g. when filtering) - it would be good to provide a multiselect drop down.

For instance, similar to the functionality in https://jedwatson.github.io/react-select/

Would you see this as a 3rd party component, or something the core should support?

**Comment by leesei** [comment]
See #45

**Comment by fzaninotto** [comment]
Duplicate of #45
