### ISSUE TITLE
Suggested Detail for aor docs

### ISSUE THREAD

**Issue by velociwabbit** [marmelab/admin-on-rest#477]
I am stuck on this senctence in the aor docs (see below) 

_"write the translation from the resource name to the API endpoint in your own restClient"_

```
name

Admin-on-rest uses the name prop both to determine the API endpoint 
(passed to the restClient), and to form the URL for the resource.

<Resource name="posts" list={PostList} create={PostCreate} edit={PostEdit} 
                   show={PostShow} remove={PostRemove} />
For this resource admin-on-rest will fetch the "http://jsonplaceholder.typicode.com/posts" 
endpoint for data.

The routing will map the component as follows:

/posts/ maps to PostList
/posts/create maps to PostCreate
/posts/:id maps to PostEdit
/posts/:id/show maps to PostShow
/posts/:id/delete maps to PostRemove
Tip: If you want to use a special API endpoint without altering the URL, write the 
translation from the resource name to the API endpoint in your own restClient
```
It is not that I do not understand what it means in theory but instead I am struggling to convert the advice into something concrete. So rather than complain I thought I would offer a suggestion by way of example 

```
For example
if you have a new Post requirement of say finding all posts within the post archive which  
is not presently implemented you would have to add:

/posts/archive/:id   which maps to a new component "PostListReview"

And then implement a PostListReview component to manage this process.
```
Not sure this is the correct language or even a clear explanation of for that matter a clear answer (can you simply map that new URL back into the existing list function?)

If someone helps clarify this issue with a better example or two I will gladly do the update.

**Comment by fzaninotto** [comment]
Your suggestion proves that you haven't understood, and therefore that the doc is actually badly written. The sentence 

> If you want to use a special API endpoint without altering the URL, write the translation from the resource name to the API endpoint in your own restClient

Means that if you want to keep the `/posts/` URL in admin-on-rest, but have the REAST API called at `/my-custom-post-route` instead of `/posts`, it's your job to implement the mapping, inside the `restClient`.

This is about routes and not components.

**Comment by velociwabbit** [comment]
Thanks for the clarification.  

One other solution (that I cobbled together today before reading your answer) which i borrowed  from the aor demo-master dashboard is to call the restClient directly from the component and bypass  routing altogether.  
 This works but sort of defeats the purpose of the routing code.

(BTW the routing/actions/reducers/saga code  is fairly hard for a  mere mortal like me  to follow, even  consolidated into  a single file . I  went back yesterday and re-aggregated the code again to see if i could extract a state table or some other means of viewing the code as a whole and failed miserably. 

Some of it is clean and pretty, others has lots of case statements and still others are single lines. 

Not sure what can be done but if there is I am more than willing to help in any way i can.
