### ISSUE TITLE
Markdown Field

### ISSUE THREAD

**Issue by mantis** [marmelab/admin-on-rest#478]
There is currently a richtext field ( https://marmelab.com/admin-on-rest/Fields.html#richtextfield ) - where would you see the concept of a markdown field, given markdown's popularity?

Addon components?

**Comment by leesei** [comment]
See #45

**Comment by fzaninotto** [comment]
Yep, this won't be implemented in the core (just like the rich text editor), so feel free to start your own implementation as an addon.

**Comment by maluramichael** [comment]
@mantis This is an old issue but i want to tell you that i created a simple input element for markdown.
See https://github.com/maluramichael/ra-input-markdown

**Comment by djhi** [comment]
@maluramichael Nice! Can you please open a pull request to add in our ecosystem documentation page?

**Comment by maluramichael** [comment]
@djhi alright #3204

**Comment by mantis** [comment]
nice job - markdown functionaltiy looks nice. In my case - I ended up using vue.js for my projects - found that easier to 'learn' and get my head around then react.
