### ISSUE TITLE
Specify custom field for ID

### ISSUE THREAD

**Issue by stanisfun** [marmelab/admin-on-rest#491]
I have for one resource an ID that is called differently than `id`, so framework fails at almost any step.
And have another resource that has compound id from 2 fields.

Is there a way to specify a mapper for id?

**Comment by bodo22** [comment]
have you looked at [#373](https://github.com/marmelab/admin-on-rest/issues/373) ?

**Comment by fzaninotto** [comment]
Yep, that's a duplicate.

**Comment by stanisfun** [comment]
sry :|

**Comment by mamadOuologuem** [comment]
The above link seems broken

Updated link here --> #373
