### ISSUE TITLE
Optimistic rendering of List may create errors due to outdated data

### ISSUE THREAD

**Issue by WangLarry** [marmelab/admin-on-rest#493]
test usage: 

aor 0.9.2,   latest admin-on-rest-demo

reproduce:

 - change code in data.js:   const cacheDuration = 10 * 60 * 1; // change to very short cache timeout
  - click ui: Customers -> Reviews -> Customers

throw:

>  index.js:44 Uncaught (in promise) TypeError: Cannot read property 'total_spent' of undefined(…)

problem: 
    Reviews call 'GET_MANY_REFERENCE', triger delete outdated records(customers data), but ids of customers resource still exists in redux state. When Customers page load again, it will load ids in redux state to init, but data have been deleted.

fix:
```
    in /mul/list/List.js, 
    componentWillUnmount() {
        ...
        this.props.clearListIDs(this.props.resource);  // delete my ids list in redux state
    } 
```

**Comment by fzaninotto** [comment]
I agree with the diagnostic, not with the solution. Clearing the list of ids on unmount kills the optimistic rendering. Instead, the list of ids should have the same caching strategy as the list of data.

**Comment by fzaninotto** [comment]
Reopening as i had to revert #659 because of side effects

**Comment by kopax** [comment]
How about correcting this with a `optimistic={false}` props and @WangLarry recon?
