### ISSUE TITLE
No horizontal scrollbar when the columns take long width

### ISSUE THREAD

**Issue by youknowone** [marmelab/admin-on-rest#496]
On the list, there are no horizontal scrollbar even when the columns are too many to look at once.
Shouldn't a scrollbar be automatically added to it ?

**Comment by fzaninotto** [comment]
Duplicate of #434

**Comment by data-server** [comment]
![image](https://user-images.githubusercontent.com/31848134/35762661-8f1533c4-08d5-11e8-886e-db24cb2acbf9.png)
we don't wont to use responsive list，i fund it isn't fix yet

**Comment by Martijncvv** [comment]
2023, still not fixed

**Comment by fzaninotto** [comment]
@Martijncvv Commenting here will have no effect. This very old issue is closed.

If you think the bug still exists, please open a new issue, including a reproduction.
