### ISSUE TITLE
About data management in aor

### ISSUE THREAD

**Issue by WangLarry** [marmelab/admin-on-rest#498]
In my opinion, aor is a SPA, is a UI library of data management.
So the data module of aor is importent, need we think seriously. 
Following thinking is just my opinion:

1. The data in the client should be synchronized with the server.

The client's data is just a snapshot of the server at a certain point in time. The traditional CGI HTML     page is generated by the server program is a reflection of the data at that time, the data displayed in the page is consistent. SPA should also like so, the data displayed on the page needs to be loaded at the same time. For example, data in the toolbar, sidebar, main content area needs to be consistent, need to synchronize with the server as much as possible in real time. However, we often get some part of the data in the SPA program, the lack of considering the associated data. On the client side, we do not know how the server side of the data is changing, we must also get all the relevant data. A small change in the client may change data of others table in server.

2.On the client side, do not attempt to manage and maintain relationships with different data.

Maintaining data relationships will only bring complexity and difficult to meet the point of view 1. Managing data is the responsibility of server-side programs, let server to send you what you need. So do not use one to many, many to many models in the client,  let server program to pack data.

3. About data in Redux

Redux can be used to store data snapshots, query conditions, etc.. And in the react program, Redux can also optimize the render.

Sorry for my poor english.

**Comment by fzaninotto** [comment]
Thanks for sharing your opinion. I don't understand it all, and it is not all actionable. But as explained in your previous issue, this is not in the scope of admin-on-rest. I advise you to develop your ideas in your own SPA.

**Comment by WangLarry** [comment]
Load all data that whole page need at same time. After loaded, the data of component  has been in single data structure, not relative to others resource. If create, edit, delete .. in a record, reload all data.

**Comment by WangLarry** [comment]
For example, a data of customer in APPBar, user edit her orders, server may change some data in others table. we need reload all data.

**Comment by WangLarry** [comment]
It is too difficult to express in english.:(

**Comment by WangLarry** [comment]
1. Stop using one to many, many to many models in the client, there are JOIN in SQL, Populate in mongoose ...
2. Define the relations with every resource each other, once a resource been changes, reload relative others resource.

**Comment by velociwabbit** [comment]
WangLarry I could not agree more. I have extracted all of the crud many or reference / reference many actions out of a version of aor and the core native complexity is slowly becoming manageable.

I also have removed Admin/ Layout and the complexity of jsonserverrestclient ( which is overwrought and unnecessarily complex   here is my verision below (i call it goFetch ) This is a great project in concept but needs a bit of editorial to get right. 

```
  const   goFetch = (apiUrl= defaultURL ) => { return (type, resource, params) =>   { 
        let url = '' ;
        const queryParameters = data => Object.keys(data).map(key => [key, data[key]].map(encodeURIComponent).join('=')).join('&')

        if  (type == 'GET_LIST'){  
                            resource                 = {   'sensors' : 'sensors' , 'temp' : 'sensors'  }[resource] || resource 
                            const { page, perPage }  =      params.pagination;  
                            const { field, order  }  =      params.sort;   
                            const query              = { ...params.filter, _sort: field, _order: order, _start: (page - 1) * perPage, _end: page * perPage, }
                            url                      =      `${apiUrl}/${resource}?${queryParameters(query)}`  
       }
        const options   =   (type == 'UPDATE')       ? {    method : 'PUT' , body :  JSON.stringify(params.data)}
                        :   (type == 'CREATE')       ? {    method : 'POST', body :  JSON.stringify(params.data) }
                        :   (type == 'DELETE')       ? {    method : 'PUT' , }
                        :   {}

               url      =  (type == 'GET_ONE')       ?     `${apiUrl}/${resource}/${params.id}/one`                          
                        :  (type == 'UPDATE')        ?     `${apiUrl}/${resource}/${params.id}/update`                  
                        :  (type == 'CREATE')        ?     `${apiUrl}/${resource}/add`                       
                        :  (type == 'DELETE')        ?     `${apiUrl}/${resource}/${params.id}/delete` : url
       
      const   rHeaders  =  new Headers({ Accept: 'application/json',  });

      if (!   (options && options.body && options.body instanceof FormData))         
                          rHeaders.set('Content-Type', 'application/json');
      if      (options.user && options.user.authenticated && options.user.token)     
                          rHeaders.set('Authorization', options.user.token);
 
            return        fetch(url, { ...options, headers: rHeaders }).then( response => response.text().then( body => { let json;
                          try {  json = JSON.parse(body);  } catch (e) {}
                              return (response.status < 200  || response.status >= 300)      
                               ?     Promise.reject(new Error((json && json.message) || response.statusText))
                               :     (type == 'GET_LIST')  ? {   data: (json && json.length) ? json.map(x => x) : '',   total: parseInt(response.headers.get('x-total-count').split('/').pop(), 10),   }  
                               :     (type == 'CREATE' )   ? { ...params.data, id: json.id } 
                               :     json } ) )
         }

```
 Truly this entire library can be reduced down to about 750 loc of useful code.
