### ISSUE TITLE
Enhancement Request Separate internal vs External Routing path definitions

### ISSUE THREAD

**Issue by velociwabbit** [marmelab/admin-on-rest#500]
Right now if i setup a crudRoute with a path="/xxx"  and a   <  Link / > to that route using that same "/xxx" path  the internal routing mandates that my rest url have  will always have that same path.  

There is no place to map internal url's to external urls that is supplied with enough information to do the routing in all cases without resorting to software butchery.

I have a requirement for using the same classes with different external data as well as using the same external data against different options in the same class (for example one tab is designed to present graphs of data on a per row item basis while the next tab enables me to select a subset of all the same records for viewing as  a report.)

So far there is no way to piggy back the correct data in the options category because the options that are passed along are based on the path name not on the particular crudRoute (see below) 

```
 
CrudRoute key={ "sensors"      } path={"sensors"     } list={SensList} options={{type: "sensors"    }} />               
<CrudRoute key={ "temp"        } path={"sensors"     } list={SensList} options={{type: "temp"       }}/>               
<CrudRoute key={ "humidity"    } path={"sensors"     } list={SensList} options={{type: "humidity"   }}/>               
<CrudRoute key={ "airmonitor"  } path={"airmonitor"  } list={SensList} options={{type: "airmonitor" }}/>               
<CrudRoute key={ "airpressure" } path={"airpressure" } list={SensList} options={{type: "airpressure"}}/>               
<CrudRoute key={ "airspeed"    } path={"airspeed"    } list={SensList} options={{type: "airspeed"   }}/>               
<CrudRoute key={ "particle"    } path={"particle"    } list={SensList} options={{type: "particle"   }}/> 
 
```
First three of these CrudRoutes transfer the wrong option ({{Type= "sensors"}} in all three cases)   while the last three will transfer the correct options but then send the wrong URL to the server.

IMHO the double stacking of meaning (paths, names, titles etc.) so that things will automatically render and look good is not the optimal solution.  The optimal solution is for external and internal paths/names etc to be specifiable and only default to the same value if the are not specified.

Shouldn't there  be   internalPath and externalPath crudRoute variables.  (he said longingly :)  )

**Comment by fzaninotto** [comment]
> There is no place to map internal url's to external urls that is supplied with enough information to do the routing in all cases without resorting to software butchery.

You're wrong: this is exactly what the `restClient` is for.
