### ISSUE TITLE
Test for ReferenceManyField

### ISSUE THREAD

**Issue by leesei** [marmelab/admin-on-rest#505]
The test feeds `data` and `ids` to `<ReferenceManyField>`, which is not the typical use case.
I suggest we implement the `crudGetManyReference()` to do a local object lookup.

Also, should we also check `this.props.reference` for refetch?
```js
componentWillReceiveProps(nextProps) {
    if (this.props.reference !== nextProps.reference ||
        this.props.record.id !== nextProps.record.id) {
        this.fetchReferences(nextProps);
    }
}
```
vs
```js
// current
componentWillReceiveProps(nextProps) {
    if (this.props.record.id !== nextProps.record.id) {
        this.fetchReferences(nextProps);
    }
}
```

**Comment by fzaninotto** [comment]
The test is a unit test. If you want to test object lookup, that's an e2e test. Contributions are welcome for this!

As for the fact that `reference` may change, I don't see the use case for that.
