### ISSUE TITLE
Dynamical show / hidden EditButton

### ISSUE THREAD

**Issue by mingchen** [marmelab/admin-on-rest#506]
I have a list table and I want to only show Edit button for super user. for example, I would like something as following
 
   <TextField>
   isSuperUser && <EditButton />

Is it possible to implement this in list view ?

Thanks.

**Comment by fzaninotto** [comment]
Yes, it's possible, but you'll have to do it yourself. My advice is to use React Context, and a special component that you should write called `OnlyForRole`, something like:

```js
class OnlyForRole extends Component {
    render() {
        const { name, children, ...rest } = this.props;
        const { roles } = this.context;
        return roles.includes(name) ? React.cloneElement(children, rest) : null;
    }
}

OnlyForRole.contextTypes = {
  roles: React.PropTypes.ArrayOf(React.PropTypes.string),
};
```

Then use it as a wrapper around Field and Input components:

```js
const PostList = (props) => (
    <List ...props>
        <Datagrid>
           <TextField source="id">
           <OnlyForRole name="manager">
                <EditButton>
           </OnlyForRole>
         </Datagrid>
    </List>
);
```

The `roles` array stored in context is your responsibility - initialize it on login.

**Comment by mingchen** [comment]
Thank you. It make sense.
