### ISSUE TITLE
SelectInput uncaught Error when editing customer in demo

### ISSUE THREAD

**Issue by amite** [marmelab/admin-on-rest#507]
When I try to edit segments by clicking on the pencil icon...

<img width="1070" alt="screen shot 2017-03-24 at 10 55 40 am" src="https://cloud.githubusercontent.com/assets/1308947/24281684/94091a24-1080-11e7-906d-aa6c2c3f8851.png">

...I get this error:

<img width="1453" alt="screen shot 2017-03-24 at 10 55 17 am" src="https://cloud.githubusercontent.com/assets/1308947/24281695/a4625160-1080-11e7-9cc3-a3ea648d5d46.png">

Everything freezes and crashes

**Comment by fzaninotto** [comment]
Confirmed. The regression was introduced by 6542c726db24dfe8d2e9dc9b058f787b40c40d60
