### ISSUE TITLE
Unable to find translation for nested resource field

### ISSUE THREAD

**Issue by nik-lampe** [marmelab/admin-on-rest#510]
I'm having trouble translating my field names.
The way described in https://marmelab.com/admin-on-rest/Translation.html#translating-resource-and-field-names works perfectly fine for fields which are direct children of the resource, 

For example I have a resource `users` and the field `<TextInput source="name" />`.
The translation with 
`{ resources: { users: { fields: { name: 'Name' } } } }`
works fine.

But let's say I have a nested resource with fields in my users resource `<TextInput source="primary_address.street" />`

Then I don't know how to add a translation for this field. I tried many different approaches, but none of them worked...

**Comment by cytomich** [comment]
You can do it like this

```
{
  resources: {
    users: {
      fields: {
        name: 'Name',
        primary_address: {
          street: 'Street'	
        }
      }
    } 
  } 
}
```
