### ISSUE TITLE
Checking Credentials During Navigation

### ISSUE THREAD

**Issue by faviouz** [marmelab/admin-on-rest#511]
I'm a bit confused by the documentation in https://marmelab.com/admin-on-rest/Authentication.html#checking-credentials-during-navigation

```
if (type === AUTH_CHECK) {
    return localStorage.getItem('username') ? Promise.resolve() : Promise.reject();
}
```

The `username` item comes out of nowehre. Shouldn't it be `localStorage.getItem('token')`? If the `token` item isn't set, that means you haven't logged in (or have logged out).

This is most likely a typo, but I just wanted to check I'm not misunderstanding anything.

**Comment by fzaninotto** [comment]
Yes, it's a typo. Would you like to open a PR fixing it?
