### ISSUE TITLE
Reopen  #434: Too many columns can not view all columns

### ISSUE THREAD

**Issue by mingchen** [marmelab/admin-on-rest#512]
This reopen issue https://github.com/marmelab/admin-on-rest/issues/434

It is still reproducible in the latest code.

To reproduce, open following page:

https://marmelab.com/admin-on-rest-demo/#/commands?_k=wi0hso

Then change window size to make it small in width, you will see some part of right table can not be viewed and it can not horizontal scroll.

 
![image](https://cloud.githubusercontent.com/assets/1002838/24380564/dea6f402-1300-11e7-9b8d-54259a426cdd.png)

**Comment by leesei** [comment]
It has been stated in #434 that the fix landed on `next` branch, not `master`.

**Comment by mingchen** [comment]
I see, It has been stated fixed for a while. when can be merged to master and released ?

**Comment by fzaninotto** [comment]
We usually release once a month, around the 15th. Watch https://github.com/marmelab/admin-on-rest/releases for details.

**Comment by mingchen** [comment]
Thank you so much.
