### ISSUE TITLE
[FEATURE REQUEST] Add a TabbedView component

### ISSUE THREAD

**Issue by remi13131** [marmelab/admin-on-rest#515]
As TabbedForm exists, it would be very nice to have exactly the same component but without the SaveButton

In fact, my use case is really simple ; 
I would like to display almost the same information on EditView and ShowView, one being used by admins and one being used by non-admins, with the only difference that one would contain inputs and being save-able, and the other fields and not being save-able

**Comment by remi13131** [comment]
And if that was accepted it would sound easy enough for a first try of mine to contribute !
(in fact I can re-use most of TabbedForm / FormTab components)

**Comment by fzaninotto** [comment]
Sure, please do!

**Comment by chemitaxis** [comment]
Hi, how is that? :) Can I help? Thanks!

**Comment by remi13131** [comment]
It is done now we are only waiting for @fzaninotto to come back from holliday (and I think he deserved it looking at how he is committed to this project !) to accept (or not ^^) the changes and merge it to next. 
Then we will have to wait for next to be merged to master for the next release. 
I hope this will be 1.0 :p

**Comment by chemitaxis** [comment]
Thanks @remi13131 I will try to help to this project!

**Comment by fzaninotto** [comment]
Fixed by #569
