### ISSUE TITLE
Is it possible to use ReferenceInput with SelectInput in Custom Input Component?

### ISSUE THREAD

**Issue by s33m4nn** [marmelab/admin-on-rest#524]
My User model has many Addresses with Country. I have created a custom address input component as you explain in [documentation](https://marmelab.com/admin-on-rest/Inputs.html#writing-your-own-input-component). I add TextInput almost for all attributes of the address (zip, town, street). It's woking,
but I can not add ReferenceInput with SelectInput for Country and AddressType resources. 
Can you explain how to use ReferenceInput?

**Comment by fzaninotto** [comment]
We don't provide support through GitHub issues. If you need advice on using or debugging your own project based on admin-on-rest, please use [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest).
