### ISSUE TITLE
Empty content on first load with RichTextInput

### ISSUE THREAD

**Issue by DjLeChuck** [marmelab/admin-on-rest#528]
First, sorry for the double post: https://github.com/marmelab/aor-rich-text-input/issues/3

I don't know if this issue is related to aor in general or is specific to RichTextInput...

Coming from the listing, the field is empty. After hitting refresh button, the field is filled.

If I log the value received in `componentDidMount`, I see it's empty the first time and not the second one.

![demo](https://media.giphy.com/media/xUPGcdJejn3pIleTJu/giphy.gif)

**Comment by DjLeChuck** [comment]
The bug only appear if we come from the listing. Using a direct link to the edit page is OK (that's why a reload works...)

**Comment by DjLeChuck** [comment]
After digging more, I see the component receive the value after his initialization. So, if I use `componentWillReceiveProps` I can fill Quill:

```
  componentWillReceiveProps(nextProps) {
    const {
      input: {
        value,
      },
    } = nextProps;

    this.quill.pasteHTML(value);
  }
```

**Comment by fzaninotto** [comment]
Yes, this is a bug for marmelab/aor-rich-text-input, closing this one.
