### ISSUE TITLE
SimpleList with ReferenceField ?

### ISSUE THREAD

**Issue by sfenollosa** [marmelab/admin-on-rest#530]
I would like to do something like this :
```javascript
<SimpleList primaryText={record => <ReferenceField label="Name" source="productCode" reference="product">
	<TextField source="name" />
</ReferenceField>}
secondaryText={record => record.type}/>
```
but it complains about basePath not being passed to ReferenceField.

Is it something that could be improved or SimpleList will only be able to display record direct elements ?

**Comment by leesei** [comment]
You should use `<ReferenceManyField>` or `<ReferenceArrayField>` (#536) to wrap `<SimpleList>` as a child.

**Comment by sfenollosa** [comment]
Yes, but I want to use a reference only for primary text, not for secondary and tertiary ...

**Comment by leesei** [comment]
Then you are using 2 records in a field, the calls for a custom implementation of `<MyList>` which will fetch referenced record to prop on mount and then use both `record` and `referenceRecord` in `render()`.
See implementation of `<ReferenceField>`.

**Comment by sfenollosa** [comment]
Basically, you are telling me that simpleList won't be improved in that way.
I will build my own implementation then.
Thank you.

**Comment by christiaanwesterbeek** [comment]
@sfenollosa Have you come up with an implementation of it in the meantime? I'm interested to see it. Somebody else on SO needed it too: https://stackoverflow.com/questions/47097137/how-can-i-put-reference-field-in-simplelist-in-admin-on-rest

**Comment by seeMzack** [comment]
Was trying to do the same thing and found this discussion. Perhaps just need to add `basePath="productCode"` and `record={record}` inside `<ReferenceField/>` so it will be something like this:

```
<SimpleList primaryText={record => <ReferenceField label="Name" source="productCode" reference="product" basePath="productCode" record={record}>
	<TextField source="name" />
</ReferenceField>}
secondaryText={record => record.type}/>
```

**Comment by Trezorro** [comment]
I can confirm that the solution posed bu @seeMzack actually works! It even seems that deduplications, as described in the starters tutorial, still functions as well. 

I am wondering whether this is not a hack, since we need to specify a basepath where this is normally not needed. I hope the developers will specify some "correct" usage soon.

**Comment by saysmaster** [comment]
Is this officially supported by the framework at this moment?
