### ISSUE TITLE
Missing menu dock for dashborad

### ISSUE THREAD

**Issue by sfenollosa** [marmelab/admin-on-rest#532]
In responsive small mode, Appbar is replaced by current menuItem, that's fine :
![image](https://cloud.githubusercontent.com/assets/22961911/24507802/c931b720-1561-11e7-8563-f965ec0ac3ea.png)

But when the dashboard is displayed, the menu completly dissapears : 
![image](https://cloud.githubusercontent.com/assets/22961911/24507882/06fb386a-1562-11e7-943e-97541e0517b9.png)

I tried to understand why, but did not ...

**Comment by fzaninotto** [comment]
You have to use the `<ViewTitle>` component inside your dashboard. But I agree with you that it should be documented, so I mark it as a (documentation) bug.

**Comment by sfenollosa** [comment]
You are right, it works perfectly with a viewTitle.
Just for those who would be looking for how to do it : 
```javascript 
import React from 'react';
import {ViewTitle} from 'admin-on-rest/lib/mui';
import { Card, CardHeader, CardText } from 'material-ui/Card';
export default (props) => (
<div>
 <ViewTitle title="Hello"/>
<Card style={{ margin: '2em' }}>
...
</Card>
</div>
)
`
