### ISSUE TITLE
What is the latest stable version?

### ISSUE THREAD

**Issue by PolyPik** [marmelab/admin-on-rest#535]
If I am to use this framework, then I want to use the latest stable production-ready release.

Looking at the releases, all I've seen are pre-releases and not a single stable official release.

But reading past issues suggests that the `master` branch is the de-facto stable release.

So tell me what is the stable release, if any.

**Comment by DjLeChuck** [comment]
As you said, the `master` branch is not marked as *stable* but can be used in your project. 
If I'm not wrong, the `next` branch contains the **future** *stable* release (probably 1.0).

Anyway, the `master` branch receive bugfixes and the `next` branch receive bugfixes **and** new features.

**Comment by fzaninotto** [comment]
No stable release yet, but 1.0 (stable) should be released within 2 weeks
