### ISSUE TITLE
Add a demo

### ISSUE THREAD

**Issue by fzaninotto** [marmelab/admin-on-rest#55]

**Comment by iyobo** [comment]
Agreed. I don't think using fakerest mocks is a meaningful demo.
It will answer a lot of questions and issues with setting up an actual REST server for admin-on-rest,
like 

#159

**Comment by fzaninotto** [comment]
Oh, the demo will use FakeRest indeed.

**Comment by fzaninotto** [comment]
The demo is being built at https://github.com/marmelab/admin-on-rest-demo

**Comment by ngonhan2k5** [comment]
Cannot do Create on the demo: http://marmelab.com/admin-on-rest-demo/#/customers/create
`Uncaught TypeError: Cannot read property 'pathname' of undefined(…)`

**Comment by fzaninotto** [comment]
Ah yes, this is very very early ;)

**Comment by fzaninotto** [comment]
Consider it done!

![image](https://cloud.githubusercontent.com/assets/99944/22761931/21c75038-ee5d-11e6-90a8-b6a060d8df00.png)
