### ISSUE TITLE
Field Content Translation Support?

### ISSUE THREAD

**Issue by StephenOTT** [marmelab/admin-on-rest#551]
Is there support for doing field content translations?

**Comment by fzaninotto** [comment]
In some components where it makes sense (like components based on an enumeration - `SelectInput` or `SelectField`), yes, but most of the time it's your responsibility to translate your own content. 

See https://marmelab.com/admin-on-rest/Translation.html#translating-your-own-components for details.

**Comment by StephenOTT** [comment]
@fzaninotto thanks
