### ISSUE TITLE
Suggestion for DOC <ImageInput>

### ISSUE THREAD

**Issue by Rulox** [marmelab/admin-on-rest#552]
I've trying to make my ImageInput field able to transform the File to base64 but I wasn't sure on where to do it, after reading the doc, I found that that example is under this section.

https://marmelab.com/admin-on-rest/RestClients.html#decorating-your-rest-client-example-of-file-upload

I'd say it would be nice to add a link to that example in the `ImageInput` section of the doc, as it just says "you have to take care of it" but it doesn't give any other hint for beginners. 

What do you think? It may be useful for others I guess.

Thank you!

**Comment by fzaninotto** [comment]
+1, would you like to open a PR about i?
