### ISSUE TITLE
[Feature Request] redux-offline 

### ISSUE THREAD

**Issue by vysakh0** [marmelab/admin-on-rest#554]
It would be great to have offline feature built into this library. But I'm not sure if there are any cases where some people don't want it. So wondering if I can go ahead work on this feature to be part of `admin-on-rest` or is there a way to decorate the existing crud redux actions ?

redux-offline: https://github.com/jevakallio/redux-offline 

[Blog](https://hackernoon.com/introducing-redux-offline-offline-first-architecture-for-progressive-web-applications-and-react-68c5167ecfe0)

**Comment by fzaninotto** [comment]
Feel free to give it a try!
