### ISSUE TITLE
Use List or DataGrid view in other resources Edit view.

### ISSUE THREAD

**Issue by driesvancraen** [marmelab/admin-on-rest#558]
I'm looking for a way to add Products to the Basket as in the demo.
Is it possible to integrate a List view into another resources Edit view, with some custom actions.
So search and filtering would be available?

**Comment by fzaninotto** [comment]
We don't provide support through GitHub issues. If you need advice on using or debugging your own project based on admin-on-rest, please use [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest).
