### ISSUE TITLE
React Native with AoR

### ISSUE THREAD

**Issue by velociwabbit** [marmelab/admin-on-rest#559]
I am in the process of porting my AOR (ish) application to react native. I have checked online and it seems that I might be the canary in this coal mine.

Has anyone else tried to get aor working with react native?

If not, it might be worthwhile to open up a Project to track and enhance my efforts if the maintainers are so inclined.

**Comment by fzaninotto** [comment]
Supporting react-native isn't in the scope of admin-on-rest. Feel free to fork it and create your own repository for react-native.

**Comment by lakano** [comment]
Hi !
This could be really useful to add support of react native 👍 
Could you tell us @velociwabbit if you have started something to support RN please?
This will be awesome if this could works directly with Expo!
Regards,

**Comment by velociwabbit** [comment]
There are a number of issues related to material ui and transitions (as well as AOR and all the dependent libraries)  that are  a bit tricky.   So to get around that problem I rewrote most of material ui and aor to be more specific.  The end result has performed well as a browser based app.   

I am reticent to offer more info here (the last time i did  I was admonished by fzannito for "trolling" (whatever that means)).   He also punitively locked the thread for reasons that are still unclear to me.

So If you provide a link to 'expo'  (is this a website ? a technology? )  i can finish the conversation there.

**Comment by lakano** [comment]
@velociwabbit Thanks for your answer. 
I'm sorry to read your misadventure with fzannito... I hope this misunderstood could be solved. 
I don't have started the project, but I'm looking to use AoR or writing the mine, because the goal is to also permit to use it from a mobile app.

**Comment by velociwabbit** [comment]
I figured out what you were referring to with expo and i downloaded yesterday and will play with it  over the weekend.

My next generation-ish  ( lots of changes , performance improvement,  normalization , footprint reduction etc)  aor/material-ui code base should be portable to this architecture...

Will provide and update here (that is if this thread is not locked by monday!)

**Comment by fzaninotto** [comment]
@velociwabbit I won't block this thread, but instead invite you to start a new project in GitHub and continue the conversation there.

**Comment by velociwabbit** [comment]
Just to let everyone know there are non trivial porting issues (like the
fact that div and span do not exist ) that are making it a bit tiresome to
port to react native.  I should have a better feel for it next week.

**Comment by fzaninotto** [comment]
@velociwabbit Last warning, don't use this issue or this repo to speak about non-aor related stuff. The Internet is large enough to accommodate your creativity, so create your own repo, and let the conversation about your own work happen there.

**Comment by lakano** [comment]
@fzaninotto : I don't understood your bad reaction and I suppose I'm not the only one.
Velociwabbit don't speak about "non-aor related stuff"... he speak about doing stuff you don't want to do (or you don't have the skills for), to make AoR compatible on a mobile application.

Is it AoR-related stuff ? Yes,
Is your AoR project is REALLY open-source ? Yes,
Is it really in MIT licence ? Yes,
Is it hosted on github to permit others developers to help ? Yes,

So, in french « Mais pourquoi il est si méchant ?!! » ;-)

Please, let people help to make AoR a better project. The help of Velociwabbit will help your project to be more used, loved, and everybody will be happy !

**Comment by fzaninotto** [comment]
@lakano look at the guy's history of comments in this project: he's just wasting everyone's time bragging about rewriting aor in 100 lines of code and making it much better without ever showing a anything remotely serious. To my opinion, this is troll. If @velociwabbit is serious about porting aor to React Native, nothing prevents him from doing so. Except, not in this repository, where he has already discredited himself.

**Comment by velociwabbit** [comment]
Yeah I am all talk that must be it

​[image: Inline image 1]

**Comment by velociwabbit** [comment]
Let me be clear.

I have offered to help AOR and with every single suggestion I get a rude
comment back about it being out of scope or a corner case or other snide
comments. Then when someone else asks for the same set of functions I am
told to make another repository instead of adding it to a wider AOR eco
system. Ok why not just say  F___ Off?

The issue for me is that we have some IP and non-disclosures  that are a
concern for some of the less enlightened participants in the companies that
i am helping.  So i have to tread carefully about what and how to release.

Also React native is to React what javascript is to Java ... (kindof) Which
means that it is likely to be an entire rewrite which takes time.

I was willing to help AOR ... but, perhaps it is that you are French and i
am taking your demeanor more rudely than i should . After awhile I became
demoralized and decided to distill what i needed and discarded  the rest
(pun intended!)

I am very appreciative of the excellent education I was afforded by your
efforts, especially in the area of functional programming which I really
love now that i have a better understanding of it (thanks to deep diving
into AOR).

That being said you should count the number of dependencies that are part
of this package.... And the total path length of code to do anything...

It is a great educational tool, but there are so many terrifying code
dependencies that make it high risk for serious apps. (IMHO)

If you want my help making a more opinionated and focused version let me
know.

But please know that I have offered to help countless times and I am tired
of getting the Heisman! (American expression look it up)

/jpr

**Comment by velociwabbit** [comment]
As far as I can tell this is what is unique about AOR (rewritten into about
200 loc with no dependencies)

[image: Inline image 1]

**Comment by djhi** [comment]
If you are so eager to help, then please contribute by making small incremental pull requests improving AOR so that we can discuss it. So far, we only have seen messages like your last one, claiming that you did a better job than our team and the material-ui team but no single line of code.

I haven't seen any pull request from you on the material-ui repository either btw.

**Comment by fzaninotto** [comment]
This conversation is now locked.
