### ISSUE TITLE
Invalid children supplied to FlatButton

### ISSUE THREAD

**Issue by rowanhill** [marmelab/admin-on-rest#560]
Hi there,

I've been playing with admin-on-rest for a few weeks now - it seems great! However, I'm (as of today) seeing an issue with the display of FlatButtons (see below for a screenshot). I suspect it might be something local to me, but I'm not sure what, so I thought I'd raise an issue just in case it's wider spread.

I tried to update an admin-on-rest project from 0.7.2 to 0.9.4 (simply by updating package.json and running npm update). Once I'd resolved the few backwards compatibility breaks mentioned in the releases notes (filter -> filters, and the rest client needing to return a data property), everything largely worked, but the text and icons was missing from the various components that use FlatButton (specifically EditButton, the create / refresh buttons, and custom action buttons I'd written), and there are warning messages in the console about invalid children being passed to EnhancedButton and TouchRipple (see below).

I assumed there was some kind of version conflict (e.g. with material-ui), so I've tried a few different versions of both admin-on-rest and material-ui, but the problem persists. Ditto after nuking node_modules and updating from scratch.

Finally, I've just cloned the admin-on-rest-demo repo locally and spun that up, and I'm seeing exactly the same issue.

Any thoughts?

Thanks!
Rowan

**Warnings printed to console:**

> Warning: Failed prop type: Invalid prop `children` supplied to `EnhancedButton`, expected a ReactNode.
    in EnhancedButton (created by FlatButton)
    in FlatButton (created by ListButton)
    in ListButton (created by getContext(ListButton))
    in getContext(ListButton) (created by EditActions)
    in div (created by CardActions)
    in CardActions (created by EditActions)
    in EditActions (created by Edit)
    in div (created by Card)
    in div (created by Paper)
    in Paper (created by Card)
    in Card (created by Edit)
    in div (created by Edit)
    in Edit (created by getContext(Edit))
    in getContext(Edit) (created by Connect(getContext(Edit)))
    in Connect(getContext(Edit)) (at index.js:69)
    in VisitorEdit (created by RouterContext)
    in div (created by pure(Component))
    in pure(Component) (created by RouterContext)
    in div (created by Layout)
    in div (created by Layout)
    in div (created by Layout)
    in div (created by Layout)
    in MuiThemeProvider (created by Layout)
    in Layout (created by WithWidth)
    in EventListener (created by WithWidth)
    in WithWidth (created by Connect(WithWidth))
    in Connect(WithWidth) (created by Connect(Connect(WithWidth)))
    in Connect(Connect(WithWidth)) (created by withProps(Connect(Connect(WithWidth))))
    in withProps(Connect(Connect(WithWidth))) (created by RouterContext)
    in RouterContext (created by Router)
    in Router (created by Admin)
    in TranslationProvider (created by withContext(TranslationProvider))
    in withContext(TranslationProvider) (created by Connect(withContext(TranslationProvider)))
    in Connect(withContext(TranslationProvider)) (created by Admin)
    in Provider (created by Admin)
    in Admin (at App.js:38)
    in App (at index.js:16)

> Warning: Failed prop type: Invalid prop `children` supplied to `TouchRipple`, expected a ReactNode.
    in TouchRipple (created by EnhancedButton)
    in EnhancedButton (created by FlatButton)
    in FlatButton (created by ListButton)
    in ListButton (created by getContext(ListButton))
    in getContext(ListButton) (created by EditActions)
    in div (created by CardActions)
    in CardActions (created by EditActions)
    in EditActions (created by Edit)
    in div (created by Card)
    in div (created by Paper)
    in Paper (created by Card)
    in Card (created by Edit)
    in div (created by Edit)
    in Edit (created by getContext(Edit))
    in getContext(Edit) (created by Connect(getContext(Edit)))
    in Connect(getContext(Edit)) (at index.js:69)
    in VisitorEdit (created by RouterContext)
    in div (created by pure(Component))
    in pure(Component) (created by RouterContext)
    in div (created by Layout)
    in div (created by Layout)
    in div (created by Layout)
    in div (created by Layout)
    in MuiThemeProvider (created by Layout)
    in Layout (created by WithWidth)
    in EventListener (created by WithWidth)
    in WithWidth (created by Connect(WithWidth))
    in Connect(WithWidth) (created by Connect(Connect(WithWidth)))
    in Connect(Connect(WithWidth)) (created by withProps(Connect(Connect(WithWidth))))
    in withProps(Connect(Connect(WithWidth))) (created by RouterContext)
    in RouterContext (created by Router)
    in Router (created by Admin)
    in TranslationProvider (created by withContext(TranslationProvider))
    in withContext(TranslationProvider) (created by Connect(withContext(TranslationProvider)))
    in Connect(withContext(TranslationProvider)) (created by Admin)
    in Provider (created by Admin)
    in Admin (at App.js:38)
    in App (at index.js:16)

**Screenshot of the demo app misbehaving, where I'm hovering over an action button:**

<img width="943" alt="screen shot 2017-04-08 at 17 21 37" src="https://cloud.githubusercontent.com/assets/2607287/24830528/ec947a98-1c7f-11e7-96ea-f04f37ef5528.png">

**Comment by luizguilherme5** [comment]
Same problem here, i believe that this is related to the React upgrade to 15.5.3 version. If you had any solution please share here!

**Comment by downup2u** [comment]
try to remove 'node_modules' directory and 'npm install' again instead of 'npm update'.good luck!

**Comment by luizguilherme5** [comment]
I've updated with 'npm install', but the problem was the same. When I've updated, my project wasn't running, data property error, so i listed React versions with 'npm ls | grep react', and found two React versions. So I set only one version to run, and now invalid prop error is going on. Even deleting and downloading again keep the error. When I made an new project, the error was the same.

**Comment by kakoli4109** [comment]
I am also facing same problem.

![image](https://cloud.githubusercontent.com/assets/22863514/24835541/a42643ce-1d22-11e7-9d67-f61632abfb9b.png)

**Comment by rowanhill** [comment]
Hi again,

I've tried nuking node_modules and running npm update again this morning and both the aor demo and my project are displaying fine (and no longer logging the warnings).

Sounds like some downstream dependency had an issue which has since been fixed. I don't know which dependency, though - if anyone is about to do the same, it might be interesting to diff the output of `npm list` before and after regenerating node_modules, and post the result here.

I'm going to close this issue, as I think it's resolved now.

Thanks,
Rowan

**Comment by luizguilherme5** [comment]
Thanks Rowan! Really must be a conflict caused by some dependency. I've made what you said and it's working again. 

The diff was that:
`< │ ├── react-addons-create-fragment@15.5.2
< │ ├── react-addons-transition-group@15.5.1
---
> │ ├── react-addons-create-fragment@15.5.3
> │ ├── react-addons-transition-group@15.5.2
602c602
< │ │ ├─┬ html-minifier@3.4.2
---
> │ │ ├─┬ html-minifier@3.4.3
615c615
< │ │ │ └── uglify-js@2.8.21
---
> │ │ │ └── uglify-js@2.8.22
`

But is working now!

**Comment by rowanhill** [comment]
Great!

Looks like it's to do with react-addons-create-fragment, but I can't find any release notes for that (or even find the source on Github).

FWIW, there are some related issues over at the material-ui repo: an [issue automatically created from a build failure](https://github.com/callemall/material-ui/issues/6547), plus [a user-raised issue](https://github.com/callemall/material-ui/issues/6552).

**Comment by mbrookes** [comment]
The source is here: https://github.com/facebook/react/tree/15.5-dev/addons/react-addons-create-fragment

Looks like they fixed something 15 hours ago.

**Comment by mbrookes** [comment]
Tested the new version and it fixes the issue.
