### ISSUE TITLE
Add e2m tests with fake-rest and selenium js driver

### ISSUE THREAD

**Issue by joma74** [marmelab/admin-on-rest#562]
Would appreciate if you would integrate and document some e2m(end-to-mock ahaha) tests. 

Am following your companies blog regarding fake-rest and selenium js driver. My brain still tries to wrap around bootstrapping in a proper sequence per test, mock data, usage of frameworks and the like. So would be glad to find some solution from an experienced engineer in that field.

BTW, in my pet project i am experimenting with a generational jsdom to index.html approach, see https://github.com/joma74/vuejs-one-starter/blob/master/episode18-rest-axios/bin/transformHtmlFake.js

**Comment by fzaninotto** [comment]
Other than https://marmelab.com/blog/2017/01/04/e2e-selenium-no-server.html (which I advise against), our test setup is either similar to the one of admin-on-rest, or uses a test API. 

It's outside of the scope of this project to teach you how to test SPAs. But I wish you good luck!
