### ISSUE TITLE
NumberField, BooleanField wrong position in TabbedForm and SimpleShowLayout

### ISSUE THREAD

**Issue by remi13131** [marmelab/admin-on-rest#570]
Hi, 

While developping the #515 Feature, I found out that NumberField and BooleanField (at least, maybe more components act like this) were not displayed correctly in TabbedForm and in SimpleShowLayout (at least in other views as well it might not display well).

What is strange is that it only happens to me in the example from the admin-on-rest repo, but not in my personnal project... 

I'm using admin-on-rest 0.9.4

Steps to reproduce : 
* ```> git clone https://github.com/marmelab/admin-on-rest.git```
* ```> make intall```
* ```> make run```
* Edit example/posts.js and change TextFields or TextInputs or BooleanInputs that are used to NumberFields and BooleanFields

Look at the result, the inputs will be displayed in the wrong position (BooleanField at the center of the div and NumberField at extreme right of the div)

Screenshots :
![image](https://cloud.githubusercontent.com/assets/11832241/25004621/92d13d82-2055-11e7-921c-b64497ab8aa6.png)

![image](https://cloud.githubusercontent.com/assets/11832241/25004854/b2b002ea-2056-11e7-8b36-4c5353dd9975.png)

**Comment by remi13131** [comment]
didn't know about the custom style we can apply when I posted this issue, but still ```text-align: left;``` should be default behavior IMHO. 

And here Numberfield is also clearly overflowing

**Comment by remi13131** [comment]
Same behavior in List Datagrid, with number field aligned at right by default, which is pretty ugly when all the others are aligned to right.

**Comment by remi13131** [comment]
I found out that the same behavior applies in List Datagrid

However, when it is possible to set the proper left position by hand even if it is not default with 
```headerStyle={{ textAlign: 'left' }} style={{ textAlign: 'left' }}``` for Nuberfield element, these props doesn't work on BooleanField because the resulting SVG box doesn't align as text. 

I ended with this HTMl : 

```
<tr style="border-bottom: 1px solid rgb(224, 224, 224); color: rgba(0, 0, 0, 0.87); height: 48px;">
   <td style="padding: 0px 12px 0px 16px; height: 48px; text-align: left; font-size: 13px; overflow: hidden; white-space: normal; text-overflow: ellipsis; background-color: rgba(127, 221, 233, 0.4);"><span>smagnies</span></td>
   <td style="padding: 0px 12px; height: 48px; text-align: left; font-size: 13px; overflow: hidden; white-space: normal; text-overflow: ellipsis; background-color: rgba(127, 221, 233, 0.4);"><span>Stephane Magnies</span></td>
   <td style="padding: 0px 12px; height: 48px; text-align: left; font-size: 13px; overflow: hidden; white-space: normal; text-overflow: ellipsis; background-color: rgba(127, 221, 233, 0.4);">
      <svg viewBox="0 0 24 24" style="display: block; color: rgba(0, 0, 0, 0.87); fill: currentcolor; height: 24px; width: 24px; transition: all 450ms cubic-bezier(0.23, 1, 0.32, 1) 0ms; margin: auto;">
         <path d="M9 16.2L4.8 12l-1.4 1.4L9 19 21 7l-1.4-1.4L9 16.2z"></path>
      </svg>
   </td>
</tr>
```

So the correct ```text-align: left;``` is applied, but this is what is rendered : 

![image](https://cloud.githubusercontent.com/assets/11832241/25184130/d435075e-2519-11e7-83b4-b8f7f747a3a4.png)

**Comment by remi13131** [comment]
Sorry but I really have to reopen this. 
In fact, the only way I found to have BooleanField left side in Edit or Show was to do this : 
```
<BooleanField source="shell" style={{ float: 'left' }} />
<span style={{ clear: 'both' }} />
<BooleanField source="sysadmin" style={{ float: 'left' }} />
```

Because doing simply 
```
<BooleanField source="shell" style={{ float: 'left' }} />
<BooleanField source="sysadmin" style={{ float: 'left' }} />
``` 
breaks alignment : 
![image](https://cloud.githubusercontent.com/assets/11832241/25957669/22ea07da-366f-11e7-89e3-8375312b19ae.png)

I think this is really counter-intuitive.

**Comment by djhi** [comment]
```js
<BooleanField source="shell" elStyle={{ margin: 0 }} />
```

**Comment by djhi** [comment]
That's because by default, Material-ui apply `auto` margins to the svg icons, thus centering them

**Comment by djhi** [comment]
I'm not in favor of applying the `0` margin by default as it is better to have them centered in Datagrid imo

**Comment by djhi** [comment]
ping @fzaninotto your opinion about this ?

**Comment by fzaninotto** [comment]
The primary function of fields is to be used in `<Datagrid>`. If we can't have a formatting that works both for `<Datagrid>` and `<Show>`, my opinion is that it should work primarily on `<Datagrid>` and not on `<Show>`.

**Comment by remi13131** [comment]
Thanks for the tip, didn't thought about margin ! 

Will be using this then. For NumberField (see OP) I think it is really strange in Show/Edit that it is ```text-align: right;``` and thus overflowing.
