### ISSUE TITLE
Access store value in restApiClient or external function  

### ISSUE THREAD

**Issue by vysakh0** [marmelab/admin-on-rest#571]
I've my custom restApiClient.js. I'm using firebase and I need to know the last data in my resource list to do the pagination.

The store is not exported, otherwise I could do
```js
// restApiClient.js
const { store } from 'admin-on-rest'

export default (type, resource, params) => {
   // ...
   store.getState();
}
```

How could I access my store from restApiClient.js? 

Will there be any issue in exporting the store: https://github.com/marmelab/admin-on-rest/compare/master...vysakh0:store-export

P.S Originally asked in [Stackoverflow](http://stackoverflow.com/questions/43371522/access-store-value-in-restapiclient-or-external-function) reposting.

**Comment by fzaninotto** [comment]
We don't provide support through GitHub issues. If you need advice on using or debugging your own project based on admin-on-rest, please use [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest).

**Comment by vysakh0** [comment]
@fzaninotto I did ask a question in stackoverflow, I have linked it too. I also linked to a change, so that store is exported by default, I could give a PR if you give a go ahead
