### ISSUE TITLE
Tabs are overflowing when there are too many

### ISSUE THREAD

**Issue by remi13131** [marmelab/admin-on-rest#577]
AOR v 0.9.4 but I guess any prior versions too
When too many tabs are added in TabbedForm (or the coming soon TabbedShowLayout), tabs overflow from the div it is contained : 
* With 11 tabs it is still ok : 
![image](https://cloud.githubusercontent.com/assets/11832241/25046288/eec7dac0-2130-11e7-93f7-cc87acc3fdf6.png)
* With 12 / 13 it is barely readable : 
![image](https://cloud.githubusercontent.com/assets/11832241/25046318/1a95ba14-2131-11e7-8b07-eaf46014e45c.png)
* Then at 14 it totally breaks the design (it goes beyond the screen at right) : 
![image](https://cloud.githubusercontent.com/assets/11832241/25046431/a5c219c0-2131-11e7-8698-dea4e47acf11.png)

I suggest that the tabs should start making a second line when there are 10+ 
OR it could also switch to another component at this point (for example a selectable list)

**Comment by fzaninotto** [comment]
This is a material-ui issue. Besides, I think you can fix it by using the `contentContainerStyle` prop.

**Comment by remi13131** [comment]
Okay thank you for the tip !

**Comment by remi13131** [comment]
I can see in AOR next branch's package.json :
```"material-ui": "~0.17.3"```

And in Material-Ui changelog : 
0.17.3 : Apr 10, 2017

v1.0.0-alpha.11 : Apr 14, 2017
[Tabs] Add scrollable behavior (#6502) @shawnmcknight

So it is not possible (even with contentContainerStyle to my knowledge) but it will in the next release of material-ui. 
This package was merged to the alpha : https://www.npmjs.com/package/material-ui-scrollable-tabs

When Material-Ui will ship this new release, this would be great to add support for ```tabType``` as well as ```isMultiligne``` in our TabbedForm and TabbedShowLayout components

**Comment by fzaninotto** [comment]
The 1.0.0 is a major rewrite that will require more than a couple changes in admin-on-rest (including rewriting the entire CSS).

when it's released, we'll update - after a couple weeks/months of settling down. In the meantime, I advise you to open an issue on the mui repo for them to fix it in the 0.x branch.

**Comment by remi13131** [comment]
It seems compromised for the 0.x fix : 
https://github.com/callemall/material-ui/issues/1148#issuecomment-296612892

But why not switching to 1.0.0Alpha at some point ? It is

**Comment by fzaninotto** [comment]
Far from it. Many components aren't ported yet, see https://github.com/callemall/material-ui/projects/1
