### ISSUE TITLE
[Question] Disable filter on List

### ISSUE THREAD

**Issue by chemitaxis** [marmelab/admin-on-rest#579]
Hi, how can I disable filter in columns on ListView component? Thanks.

**Comment by chemitaxis** [comment]
Hi, any news about it? I have tried many things without result... thanks! I need to disable the order option of List or DataGrid component

**Comment by djhi** [comment]
What you mean by `disable filter in columns` ?

By `disable the order option`, do you mean you don't want the sort feature at all ?

**Comment by chemitaxis** [comment]
Exactly, I don't want the sort feature at all in some resources.

**Comment by djhi** [comment]
Then it's your responsibility to ignore the sorting parameters inside your rest client.

Btw, we usually don't provide support through github issue. Please use Stackoverflow next time

**Comment by chemitaxis** [comment]
Thanks, @djhi, I can understand that you say, but I want to disable the click button, in the release 0.8.0 I can read that:

> "Add ability to disable sorting on Datagrid headers"

But I can find in the documentation how can achieve that... thanks again.

**Comment by chemitaxis** [comment]
I can make a question in StackOverflow, but I think this is a problem in the documentation :)

**Comment by djhi** [comment]
Agreed, we should add documentation about this.

You can add a `sortable={false}` to the datagrid children and it will disable the sorting feature for this field. However, it seems we have a bug which forces you to also specify a `label` prop on this children.

**Comment by chemitaxis** [comment]
Thanks! it works with label ;)

**Comment by fzaninotto** [comment]
Fixed by #580
