### ISSUE TITLE
Upgrade to latest redux-form

### ISSUE THREAD

**Issue by katyaas** [marmelab/admin-on-rest#581]
Please, upgrade dependencies to latest redux-form, because with current version I have trouble with form validation (like that https://github.com/erikras/redux-form/issues/1385), with v6.6.3 there is no problem.
So save button in edit form doesn't save data and always show errors

**Comment by valueshimoda** [comment]
https://github.com/marmelab/admin-on-rest/pull/420

**Comment by fzaninotto** [comment]
Already in `next`
