### ISSUE TITLE
Integrate Login with Redux

### ISSUE THREAD

**Issue by blindsteal** [marmelab/admin-on-rest#582]
## Use Case
I stumbled upon this problem when trying to solve what I thought is a pretty common use case: extracting information from the `AUTH_LOGIN` response and putting it into the store. In my case, I am retrieving a JWT and have to extract the current user ID and put it into the store in order to be able to display data of the current user inside my custom components (display username in app bar, change locale based on user settings etc).

## Current Implementation
Currently when using the `Admin` component, there is no way to access the store from the `authClient`. No actions are dispatched on successful login, so it is impossible to handle this with a custom reducer or saga. This forces people to go down the custom app route for what seems to me a pretty basic use case.
Also, the official docs recommend setting and reading auth tokens from localStorage which is a side effect and should probably be avoided in order to stick with the Redux way™ of doing things.

## Possible Solutions
Easy way: Dispatch `AUTH_LOGIN_SUCCESS` action (or any `AUTH` actions for that matter) from `Login` component and recommend handling those with a custom saga to set the token or perform other actions in the docs.
Hard way: Remove `fetch` logic (and by extension `authClient`) from login completely and handle things with a login/auth saga and reducer.

Thoughts on this?

**Comment by fzaninotto** [comment]
This is almost already done in the `next` branch:

https://github.com/marmelab/admin-on-rest/blob/next/src/sideEffect/saga/auth.js

What's missing is passing the result from the `authClient` promise as payload of the `USER_LOGIN_SUCCESS` action. Would you like to open a PR with that?

By the way, I think you should store your tokens in the `authClient` itself, not in the global store.

**Comment by blindsteal** [comment]
Great work, I hadn't been looking at the next branch! Will do a PR for passing the payload, but probably not before next week.

Why do you think storing the token in `authClient` is preferable? Currently I have a saga to handle persisting and loading it from `localStorage`, fetching the current user details based on a JWT field and setting the locale from user details. This way I have my (testable) saga and since the JWT is in the state I can also dump/restore states easily. I'm open to any improvements though! :)

**Comment by fzaninotto** [comment]
Well, you can use a saga-like side effect library for that, but IMO it's not Redux's job - because it's pure side effect.

**Comment by blindsteal** [comment]
Except in my case it isn't, I derive my application state from the token. It is used in 2 places:
*  to decorate requests in `httpClient`
*  inside the `getCurrentUserId` selector in conjunction with `jwtDecode`

I realize I could just parse it into the state once on retrieval, but why do that when reselect memoizes the function call anyway and I might have more properties coming from there later on... But yeah I guess it's a matter of preference and probably not really something that `admin-on-rest` should be concerned with.

**Comment by fzaninotto** [comment]
Done in #542
