### ISSUE TITLE
A question about handling errors in Login form

### ISSUE THREAD

**Issue by anhldbk** [marmelab/admin-on-rest#583]
I'm sorry for this question but I'm struggling hard to use `redux-form` with server validations.

At line [80]( https://github.com/marmelab/admin-on-rest/blob/master/src/mui/auth/Login.js#L80), we have:

```js
const { handleSubmit, submitting, theme, translate } = this.props;
const { signInError } = this.state;
```

Doesn't we have field `error` in `this.props`? If server validations fail, why don't we use `this.props.error` instead of using another state variable?

**Comment by fzaninotto** [comment]
We don't provide support through GitHub issues. If you need advice on using or debugging your own project based on admin-on-rest, please use [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest).
