### ISSUE TITLE
AutocompleteInput in ReferenceInput list of choices not fetched when field is already populated

### ISSUE THREAD

**Issue by remi13131** [marmelab/admin-on-rest#588]
When using a AutocompleteInput in ReferenceInput, the dropdown list of choices is not requested if we are in edit page and the field already have a value. IMO the list should should be narrowed down to the only choice possible : the one already provided. 

To fire the request and update the dropdown list, one needs to make some changes to the field (eg delete a character for example). The request should be made straight after populating the field, or when clicking on the field. 
Here looking at network access, it seems that the component uses some sort of cache to populate itself since no request is made.

Gif better than words : 
![out](https://cloud.githubusercontent.com/assets/11832241/25281610/2df99968-26ae-11e7-948e-758794cef740.gif)

**Comment by fzaninotto** [comment]
I don't understand the problem. Your GIF shows the correct behavior: The comment Edition form shows the related post, and when clicked, the autocomplete field shows suggestions. The network panel shows requests for suggestion when the form first loads, and when the user types in the autocomplete.

Can you reformulate the problem you have identified?

**Comment by remi13131** [comment]
In the above gif, as the field is already populated with ```Sed quo et et fugiat modi``` the only result showing in the suggestion list when clicking in the field should be this one. (or variations if they exist such as ```Sed quo et et fugiat modi 1```  ```Sed quo et et fugiat modi 2```, etc.) 

Here, I have to delete the last character to fire a request to the API, but IMO this request should be made at the component's creation time. 

ATM the component is using some sort of cache containing the posts lists since no request is made at ceation time.

**Comment by djhi** [comment]
Confirmed, that's a bug

**Comment by fzaninotto** [comment]
I'm not sure it's a bug. The autocomplete also plays as a dropdown for very long lists, so it's important to have a list of suggestions even though there is a perfect match. In the example of posts for comments, I WANT that the dropdown shows other suggestions. 

Besides, I think this behavior comes from material-ui's `AutoComplete` component, so it's not an admin-on-rest issue.

**Comment by djhi** [comment]
As explained by @fzaninotto, this is actually a feature. We are aware of some corner cases such as yours. However, if you're not satisfied with the current implementation, you can easily duplicate the `AutoCompleteInput` and add the following `componentDidMount` to achieve the desired behavior:

```js
componentDidMount() {
    const { input: { value }, choices, optionValue } = this.props;

    if (value) {
        const choice = choices.find(c => c[optionValue] === value);
        const filter = this.getSuggestion(choice);
        this.props.setFilter(filter);
    }
}
```

If you don't want to duplicate the component, just add a decorator component around it.

Note that this will result in two requests as one will have been made by the ReferenceInput first.
