### ISSUE TITLE
[Feature] Allow custom List component

### ISSUE THREAD

**Issue by hchilbule** [marmelab/admin-on-rest#594]
My project needs me to render a tree grid to display groups or subgroups of items and also to show a drop-down select a grouping field. A typical example will be group order by regions or language. I am unable to pass my custom list component to 'Resource' component as it breaks the whole app and events logic ( my list does not receive the props ). 

It will be great to have a possibility to write a custom List component to allow adding custom actions on the list and also introduce REST query parameters.

**Comment by fzaninotto** [comment]
You should be able to use any custom `List` component with no bug. can you be more specific about the "it breaks the whole app"?

**Comment by hchilbule** [comment]
@fzaninotto thanks for response. Here is what I am trying to do:

```
<MyList {...this.props} perPage={40} title={this.props.title} actions={<Actions />}>
            <Datagrid {...this.props} />
</MyList>
```
MyList does not receive some props which fails the rendering of the whole component. I could not find any documents about this. MyList is plain copy pasted version of the original List.js with changed name, import paths. I plan to replace the List::render() method so that I can handle the grouping widget and also add a '_groupby' param to the REST call if a grouping is selected.

Here is sample code ( I have truncated some parts identical to source in List.js for brevity )
```
import React, { Component, PropTypes } from 'react';
...
export class MyList extends Component {
    ... [ as in List.js ]
}
MyList.propTypes = {
    title: PropTypes.any,
    ... [ as in List.js ]
}
MyList.defaultProps = {
    filter: {},
    ...[ as in List.js ]
}

function mapStateToProps(state, props) {
    const resourceState = state.admin[props.resource];
    ... [ as in List.js ]
}

const enhance = compose(
    connect(
        mapStateToProps,
        {
            crudGetList: crudGetListAction,
            changeFormValue: changeFormValueAction,
            changeListParams: changeListParamsAction,
            push: pushAction,
        },
    ),
    translate,
);

export default enhance(MyList);
```

When App runs, these PROPS are not received by MyList:
- changeFormValue
- changeListParams
- crudGetList
- isLoading
- push
- query
- total
- translate

That generates these warnings for the above field and code fails when it access any of these param
```
warning.js:36 Warning: Failed prop type: The prop `changeFormValue` is marked as required in `MyList`, but its value is `undefined`.
    in MyList (at DynamicList.jsx:30)
    in DynamicList (created by RouterContext)
    in div
    in pure(Component) (created by RouterContext)
    in div (at Layout.jsx:88)
    in div (at Layout.jsx:87)
    in div (at Layout.jsx:86)
    in div (at Layout.jsx:85)
    in MuiThemeProvider (at Layout.jsx:84)
    in Layout (created by WithWidth)
    in EventListener (created by WithWidth)
    in WithWidth (created by Connect(WithWidth))
    in Connect(WithWidth) (created by withProps(Connect(WithWidth)))
    in withProps(Connect(WithWidth)) (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in TranslationProvider (created by withContext(TranslationProvider))
    in withContext(TranslationProvider) (created by Connect(withContext(TranslationProvider)))
    in Connect(withContext(TranslationProvider))
    in Provider
    in Admin (at App.js:35)
    in App (at index.js:7)
```

PS: Please excuse my limited knowledge of React / Redux, this is my first project with React. Its possible that I am doing some stupid mistake. I would greatly appreciate if there are any examples or docs I can refer for providing my own rendering code for List component.

**Comment by hchilbule** [comment]
As per my understanding this is related to dispatchToProps bindings but unable to resolve it. I would appreciate if there is an example or doc.

**Comment by edorivai** [comment]
Are you sure your import of changeFormValueAction is correct? Perhaps you could paste the entire imports section?

Just from the error you're pasting, I'm guessing that perhaps you have a typo or something.

**Comment by djhi** [comment]
Bump, please post the whole file if possible

**Comment by hchilbule** [comment]
import React, { Component, PropTypes } from 'react';
import { connect } from 'react-redux';
import { push as pushAction } from 'react-router-redux';
import { Card } from 'material-ui/Card';
import compose from 'recompose/compose';
import inflection from 'inflection';
import { change as changeFormValueAction, getFormValues } from 'redux-form';
import debounce from 'lodash.debounce';
import queryReducer, { SET_SORT, SET_PAGE, SET_FILTER, SORT_DESC } from 'admin-on-rest/lib/reducer/resource/list/queryReducer';
import ViewTitle from 'admin-on-rest/lib/mui/layout/ViewTitle';
import Title from 'admin-on-rest/lib/mui/layout/Title';
import DefaultPagination from 'admin-on-rest/lib/mui/list/Pagination';
import DefaultActions from 'admin-on-rest/lib/mui/list/Actions';
import { crudGetList as crudGetListAction } from 'admin-on-rest/lib/actions/dataActions';
import { changeListParams as changeListParamsAction } from 'admin-on-rest/lib/actions/listActions';
import translate from 'admin-on-rest/lib/i18n/translate';

const filterFormName = 'filterForm';

export class MyList extends Component {
    constructor(props) {
        super(props);
        this.debouncedSetFilters = debounce(this.setFilters.bind(this), 500);
        this.state = { key: 0 };
    }

    componentDidMount() {
        this.updateData();
        if (Object.keys(this.props.query).length > 0) {
             this.props.changeListParams(this.props.resource, this.props.query);
        }
    }

    componentWillReceiveProps(nextProps) {
        if (nextProps.resource !== this.props.resource
         || nextProps.query.sort !== this.props.query.sort
         || nextProps.query.order !== this.props.query.order
         || nextProps.query.page !== this.props.query.page
         || nextProps.query.filter !== this.props.query.filter) {
            this.updateData(Object.keys(nextProps.query).length > 0 ? nextProps.query : nextProps.params);
        }
        if (nextProps.data !== this.props.data && this.fullRefresh) {
            this.fullRefresh = false;
            this.setState({ key: this.state.key + 1 });
        }
        if (Object.keys(nextProps.filterValues).length === 0 && Object.keys(this.props.filterValues).length === 0) {
            return;
        }
        if (nextProps.filterValues !== this.props.filterValues) {
            const nextFilters = nextProps.filterValues;
            Object.keys(nextFilters).forEach(filterName => {
                if (nextFilters[filterName] === '') {
                    // remove empty filter from query
                    delete nextFilters[filterName];
                }
            });
            this.debouncedSetFilters(nextFilters);
        }
    }

    shouldComponentUpdate(nextProps, nextState) {
        if (
            nextProps.isLoading === this.props.isLoading
         && nextProps.width === this.props.width
         && nextState === this.state) {
            return false;
        }
        return true;
    }

    componentWillUnmount() {
        this.debouncedSetFilters.cancel();
    }

    getBasePath() {
        return this.props.location.pathname;
    }

    refresh = (event) => {
        event.stopPropagation();
        this.fullRefresh = true;
        this.updateData();
    }

    /**
     * Merge list params from 3 different sources:
     *   - the query string
     *   - the params stored in the state (from previous navigation)
     *   - the props passed to the List component
     */
    getQuery() {
        const query = Object.keys(this.props.query).length > 0 ? this.props.query : { ...this.props.params };
        if (!query.sort) {
            query.sort = this.props.sort.field;
            query.order = this.props.sort.order;
        }
        if (!query.perPage) {
            query.perPage = this.props.perPage;
        }
        return query;
    }

    updateData(query) {
        const params = query || this.getQuery();
        const { sort, order, page, perPage, filter } = params;
        const permanentFilter = this.props.filter;
        this.props.crudGetList(this.props.resource, { page, perPage }, { field: sort, order }, { ...filter, ...permanentFilter });
    }

    setSort = sort => this.changeParams({ type: SET_SORT, payload: sort });

    setPage = page => this.changeParams({ type: SET_PAGE, payload: page });

    setFilters = filters => this.changeParams({ type: SET_FILTER, payload: filters });

    showFilter = (filterName, defaultValue) => {
        this.setState({ [filterName]: true });
        if (typeof defaultValue !== 'undefined') {
            this.props.changeFormValue(filterFormName, filterName, defaultValue);
            this.setFilters({ ...this.props.filterValues, [filterName]: defaultValue });
        }
    }

    hideFilter = (filterName) => {
        this.setState({ [filterName]: false });
        this.props.changeFormValue(filterFormName, filterName, '');
        this.setFilters({ ...this.props.filterValues, [filterName]: undefined });
    }

    changeParams(action) {
        const newParams = queryReducer(this.getQuery(), action);
        this.props.push({ ...this.props.location, query: { ...newParams, filter: JSON.stringify(newParams.filter) } });
        this.props.changeListParams(this.props.resource, newParams);
    }

    render() {
        const { filters, pagination = <DefaultPagination />, actions = <DefaultActions />, resource, hasCreate, title, data, ids, total, children, isLoading, translate } = this.props;
        const { key } = this.state;
        const query = this.getQuery();
        const filterValues = query.filter;
        const basePath = this.getBasePath();

        const resourceName = translate(`resources.${resource}.name`, {
            smart_count: 2,
            _: inflection.humanize(inflection.pluralize(resource)),
        });
        const defaultTitle = translate('aor.page.list', { name: `${resourceName}` });
        const titleElement = <Title title={title} defaultTitle={defaultTitle} />;

        return (
            <div>
                <Card style={{ opacity: isLoading ? 0.8 : 1 }} key={key}>
                    {actions && React.cloneElement(actions, {
                        resource,
                        filters,
                        filterValues,
                        basePath,
                        hasCreate,
                        displayedFilters: this.state,
                        showFilter: this.showFilter,
                        refresh: this.refresh,
                    })}
                    <ViewTitle title={titleElement} />
                    {filters && React.cloneElement(filters, {
                        resource,
                        hideFilter: this.hideFilter,
                        filterValues,
                        displayedFilters: this.state,
                        context: 'form',
                    })}
                    {React.cloneElement(children, {
                        resource,
                        ids,
                        data,
                        currentSort: { field: query.sort, order: query.order },
                        basePath,
                        isLoading,
                        setSort: this.setSort,
                    })}
                    {pagination && React.cloneElement(pagination, {
                        total,
                        page: parseInt(query.page, 10),
                        perPage: parseInt(query.perPage, 10),
                        setPage: this.setPage,
                    })}
                </Card>
            </div>
        );
    }
}

MyList.propTypes = {
    // the props you can change
    title: PropTypes.any,
    filter: PropTypes.object,
    filters: PropTypes.element,
    pagination: PropTypes.element,
    actions: PropTypes.element,
    perPage: PropTypes.number.isRequired,
    sort: PropTypes.shape({
        field: PropTypes.string,
        order: PropTypes.string,
    }),
    children: PropTypes.element.isRequired,
    // the props managed by admin-on-rest
    changeFormValue: PropTypes.func.isRequired,
    changeListParams: PropTypes.func.isRequired,
    crudGetList: PropTypes.func.isRequired,
    data: PropTypes.object, // eslint-disable-line react/forbid-prop-types
    filterValues: PropTypes.object, // eslint-disable-line react/forbid-prop-types
    hasCreate: PropTypes.bool.isRequired,
    hasEdit: PropTypes.bool.isRequired,
    ids: PropTypes.array,
    isLoading: PropTypes.bool.isRequired,
    location: PropTypes.object.isRequired,
    path: PropTypes.string,
    params: PropTypes.object.isRequired,
    push: PropTypes.func.isRequired,
    query: PropTypes.object.isRequired,
    resource: PropTypes.string.isRequired,
    total: PropTypes.number.isRequired,
    translate: PropTypes.func.isRequired,
};

MyList.defaultProps = {
    filter: {},
    filterValues: {},
    perPage: 10,
    sort: {
        field: 'id',
        order: SORT_DESC,
    },
};

function mapStateToProps(state, props) {
    const resourceState = state.admin[props.resource];
    const query = props.location.query;
    if (query.filter && typeof query.filter === 'string') {
        // if the List has no filter component, the filter is always "{}"
        // avoid deserialization and keep identity by using a constant
        query.filter = props.filters ? JSON.parse(query.filter) : resourceState.list.params.filter;
    }

    return {
        query,
        params: resourceState.list.params,
        ids: resourceState.list.ids,
        total: resourceState.list.total,
        data: resourceState.data,
        isLoading: state.admin.loading > 0,
        filterValues: props.filters ? getFormValues(filterFormName)(state) : resourceState.list.params.filter,
    };
}

const enhance = compose(
    connect(
        mapStateToProps,
        {
            crudGetList: crudGetListAction,
            changeFormValue: changeFormValueAction,
            changeListParams: changeListParamsAction,
            push: pushAction,
        },
    ),
    translate,
);

export default enhance(MyList);

**Comment by hchilbule** [comment]
Sorry about the formatting, here is the file which is right now a plain copy paste of original. I did not notice any issues in jslint or building bundle.js. I not sure if I am doing some silly mistake.

**Comment by djhi** [comment]
I updated your comment to get correct formatting ;)

**Comment by djhi** [comment]
Well, I just copy/pasted your code in the example app and used it with Posts. It works fine

**Comment by djhi** [comment]
I just fixed the query string parsing as in the original List component
