### ISSUE TITLE
ReferenceInput only supports certain resources

### ISSUE THREAD

**Issue by wesley6j** [marmelab/admin-on-rest#595]
`ReferenceInput` only support resources that are "registered" in Admin component. It looks for data at `state.admin[props.reference]`.

**Comment by bodo22** [comment]
not quite sure if [custom actions](https://marmelab.com/admin-on-rest/Actions.html) are a possible way to go here. Maybe someone with more knowledge could comment? :)

**Comment by leesei** [comment]
That's by design.
All data referenced in AOR are resources that resides in `state.admin`.

**Comment by wesley6j** [comment]
I think this can be a really useful feature. And it is quite easy to hack:
change [this line](https://github.com/marmelab/admin-on-rest/blob/master/src/Admin.js#L39) to
`const resources = (React.Children.map(children, ({ props }) => props) || []).concat([{name: 'cities'}]);` 

will make `city` a valid `ReferenceInput` resource.


I think we can add an option in admin component called `otherResource`:
```
<Admin
  title="Marmelab"
  restClient={restClient}
  authClient={authClient}
  otherResource=[{name: 'cities'}, {name: 'country'}]
...
```

**Comment by wesley6j** [comment]
I get a warning after selecting a value:
```
warning.js:36 Warning: Exception thrown by hook while handling onSetChildren: Invariant Violation: Expected onBeforeMountComponent() parent and onSetChildren() to be consistent (183 has parents 182 and 171).
Invariant Violation: Expected onBeforeMountComponent() parent and onSetChildren() to be consistent (183 has parents 182 and 171).
```
Here is the code: 
```
<ReferenceInput source="city_id" label="city" reference="cities" allowEmpty>
    <SelectInput optionText="name" />
</ReferenceInput>
```

**Comment by leesei** [comment]
I don't get what are you trying to do.

The typical way is to add resource as [`<Resource>`](https://marmelab.com/admin-on-rest/AdminResource.html#the-resource-component).
You can do without using any attribute as such `<Resource name="tags" />`.

Do you want to refer to resources that the server does not provides endpoint?
If so, it's better to implement your own `RestServer` and return those resources.
