### ISSUE TITLE
[Feature] ViewButton

### ISSUE THREAD

**Issue by chemitaxis** [marmelab/admin-on-rest#598]
We have EditButton component, can we create a ViewButton component? If you are ok with this, I can work on it, thanks.

**Comment by fzaninotto** [comment]
Do you mean [`<ShowButton>`](https://github.com/marmelab/admin-on-rest/blob/f18c05669fbc8386b0b45e8a73f72689c9aad504/src/mui/button/ShowButton.js)? It's already there.

**Comment by chemitaxis** [comment]
Yes, sorry!
