### ISSUE TITLE
Authentication and OAuth2 implementation in admin-on-rest

### ISSUE THREAD

**Issue by stelioschar** [marmelab/admin-on-rest#601]
First of all I would like to thank you for the awesome work!!

Sorry for posting this here, violating the repo's guidelines, but the stackoverflow(for admin-on-rest) community seems to be idle.

First of all I would like to thank you for the awesome work in [admin-or-rest](https://github.com/marmelab/admin-on-rest) that you have done for this template.

I would like to ask if there is an easy workaround in order to implement `oauth2` authentication.

There is an example on how we can implement a [basic JWT Authentication](https://marmelab.com/admin-on-rest/Authentication.html) but I cannot figure out how I’m going to handle the 401 errors in order to handle to refresh the token as described in oAuth2.

Is there any way to apply a middleware? I’ve tried in the past [redux-api-middleware](https://www.npmjs.com/package/redux-api-middleware) in order to have full control of my action and http handling, but this cannot been applied to this system once all the calls except the login are being handled automagically.

There also a related [stackoverflow issue](http://stackoverflow.com/questions/43627177/authentication-and-oauth2-implementation-in-admin-on-rest)

**Comment by fzaninotto** [comment]
We don't provide support through GitHub issues. If you need advice on using or debugging your own project based on admin-on-rest, please use [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest).
