### ISSUE TITLE
ReferenceField translation ?

### ISSUE THREAD

**Issue by sfenollosa** [marmelab/admin-on-rest#608]
Hi,

it seems that ReferenceField label is not translated like other text fields when used in a Datagrid.
Am I missing something or must I deal with the translate() thing ?

**Comment by sfenollosa** [comment]
I got it working with the higher order translate component, but It would be nice if it would work like the other fields.

**Comment by fzaninotto** [comment]
There is nothing special with `<ReferenceField>` concerning the datagrid label  - it is translated just like the other fields. It works on the demo by the way: if you navigate to https://marmelab.com/admin-on-rest-demo/#/commands, then change the language to French and get back to that page, you'll see that the header of the Customer column is properly translated (see the translation there: https://github.com/marmelab/admin-on-rest-demo/blob/643ce8ec17efd0257c8d255ba77fe1bc07a50715/src/i18n/fr.js#L72).
