### ISSUE TITLE
Invalid display of pagination when no items returned from API

### ISSUE THREAD

**Issue by djhi** [marmelab/admin-on-rest#61]
With items returned from API:
![screen](https://sc-cdn.scaleengine.net/i/0a97fc9ef97ba96568b813e3e63f2083.png)

With no items returned from API:
![screen](https://sc-cdn.scaleengine.net/i/a7db2067d08256aa4c61d9e21be068a6.png)

**Comment by fzaninotto** [comment]
You don't know NaN? It's Indian for: "Nothing here, take a break and eat some bread".

**Comment by fzaninotto** [comment]
Can't reproduce the issue: 

![image](https://cloud.githubusercontent.com/assets/99944/19455386/23e9cd04-94bd-11e6-828a-6ad6937d21ef.png)

Can you give me a scenario to reproduce based on the example?

**Comment by fzaninotto** [comment]
ping @djhi

**Comment by djhi** [comment]
Yes, you can see it on the boilerplate

**Comment by djhi** [comment]
nvm, the problem was on the boilerplate side
