### ISSUE TITLE
admin on rest custom login page

### ISSUE THREAD

**Issue by kodmanyagha** [marmelab/admin-on-rest#612]
I searched in internet but I didn't find example code. Then I looked your codes and I made a little example. Please can you add example code to this page: https://github.com/marmelab/admin-on-rest/blob/master/docs/Authentication.md

My example code is here: https://gist.github.com/kodmanyagha/2ee0546413ebbbe1d8d6e4dee5d73872

**Comment by leesei** [comment]
Try:
https://github.com/marmelab/admin-on-rest-demo/blob/master/src/Login.js

**Comment by kodmanyagha** [comment]
I opened this issue becouse I didn't find any example in google. This post will be index in google and other people can find. Thx.

**Comment by fzaninotto** [comment]
We don't provide support through GitHub issues. If you need advice on using or debugging your own project based on admin-on-rest, please use [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest).
