### ISSUE TITLE
Unable to install from fork

### ISSUE THREAD

**Issue by popaulina** [marmelab/admin-on-rest#616]
I forked the project in order to add support for uploading audio files (it's entirely necessary for my application) and after installing from npm (after adding `"admin-on-rest": "popaulina/admin-on-rest"` to my `package.json`), the package is in my node_modules folder but is missing its `lib` folder. I found a similar issue on another repo [here](https://github.com/ReactTraining/history/issues/52). Does anyone know a work-around/can this be patched/am I doing something wrong?

I was able to get this to run locally by running `babel -d ./lib ./src` but this produces an error if added to a postinstall script.

**Comment by popaulina** [comment]
Some more things that I have uncovered:
After installing the package `postinstall-build`, I was able to make some progress, but it hasn't been pretty.

Adding `"postinstall": "postinstall-build lib \"babel -d ./lib ./src` to the `package.json` scrips works locally but still errors out with the git repo.

I found that this was because the `.babelrc` file seemed to be ignored.

Adding `"postinstall": "postinstall-build lib \"babel -d ./lib ./src --presets es2015,stage-0,react\""` actually built the github repo package, but errored out while running with: 
`Uncaught ReferenceError: regeneratorRuntime is not defined`.

This seemed to also stem from the rest of the `.babelrc` not being included in the script, so I tried: `"postinstall": "postinstall-build lib \"babel -d ./lib ./src --presets es2015,stage-0,react --plugins transform-react-jsx,add-module-exports,babel-plugin-transform-builtin-extend,transform-runtime \""` which, again, allowed the git repo to build but errored out while running with `Uncaught SyntaxError: Unexpected token import`.

So I seem to be back at square one. If anyone has any input, I'd highly appreciate it.

**Comment by edorivai** [comment]
This is probably really not the answer you're hoping for, but did you consider publishing to NPM under your own account? Like `@popaulina/admin-on-rest`. Not even sure if that's allowed at all, but I guess it should work.

**Comment by popaulina** [comment]
@edorivai That's likely what I'll end up doing, either that or committing the lib folder on my forked project.

**Comment by jpetitcolas** [comment]
We had a similar issue on another project. We installed our modules using a script like:

```
yarn install --no-progress --cache-folder=/.yarn
cd node_modules/admin-on-rest/
make install
make build
rm -Rf node_modules
```

**Comment by popaulina** [comment]
@jpetitcolas @fzaninotto I have no makefile included in the project when installed, I thought this may have been because I was running 0.9.4 but updating to 1.0.1 does not include the makefile either. Running the install and build commands by hand produces the same issue that I was having earlier: babel does not recognize es6 and it does not even recognize the presets given. The error is: `SyntaxError: src/Admin.js: Unexpected token (45:8)` (...customReducers).

**Comment by fzaninotto** [comment]
@popaulina You have to install from git if you want to make your own build.

**Comment by popaulina** [comment]
...Obviously? What in the world did I say to make you think I somehow did it otherwise? What I say 'updated' I mean that I forked the new copy, when I started this it was still on `0.9.4`. 

Anyway, the `Makefile` wasn't included in the list of files on your `package.json` and after adding it I've been able to at least use that. But the `.babelrc` config file is ignored whether or not it's listed in the files, so sadly the only way I've been able to get this to work is by copying `.babelrc` to another file and then using a script similar to the one above, but also copying the file back.

**Comment by fzaninotto** [comment]
> What in the world did I say to make you think I somehow did it otherwise?

Because I don't see how you *can't* have a makefile by using a checkout, since it's obviously [in the repository](https://github.com/marmelab/admin-on-rest/blob/master/Makefile).

I don't understand why you would have to add the `makefile` to the list of included files in `package.json`. Just run a `make build` before `npm publish` and you should be OK.

**Comment by popaulina** [comment]
Because I'm not publishing to npm. It's using the git repo as the source. Which is why I needed the script as @jpetitcolas posted above.

**Comment by djhi** [comment]
Hi @popaulina,

Why forking the entire projet to support upload of audio file ? Can't you just create a new package which would only include fields and inputs necessary for audio file uploads ?

See:
- [Writing Your Own Field Component](https://marmelab.com/admin-on-rest/Fields.html#writing-your-own-field-component)
- [Writing Your Own Input Component](https://marmelab.com/admin-on-rest/Inputs.html#writing-your-own-input-component) 

We would be very happy to include it in the third party contributions !

**Comment by djhi** [comment]
@fzaninotto, when adding admin-on-rest with npm by referencing the repository directly, you don't get the Makefile (among others).

This is the problem that @popaulina is facing

**Comment by fzaninotto** [comment]
I'm not sure we understand each other - @popaulina just said that she installed from git and not from npm. Am I right?

Also, did you try the `npm link` trick [described in the readme](https://github.com/marmelab/admin-on-rest#contributing)?

**Comment by djhi** [comment]
No she said she didn't publish her fork to npm and that she is using the repository as source (I suppose source for `npm install`)

**Comment by djhi** [comment]
That's the only way to reproduce her prb

**Comment by popaulina** [comment]
No, I'm using my fork of the repo as source. As in my package.json uses `popaulina/admin-on-rest`. After installing the package from git, there is no lib folder. It has to be made manually. But there is also no makefile, so it can't be made manually unless that's added to the `files` list in the package.json.

**Comment by djhi** [comment]
Yea that's what I meant. The point is, you're not cloning the repository, npm does

**Comment by djhi** [comment]
Btw, this is really not a good practice, I suggest you publish the package as suggested by @edorivai until we possibly include the Makefile. 

But still, why forking when you can supply the fields and inputs as a separate package ?

**Comment by popaulina** [comment]
Mainly I just needed a quick fix as this is for a project for university. When I have time, I may make a contribution. For now I just need something working, as it is, even if it's not the best way.

**Comment by djhi** [comment]
Just my 2 cents but it will most probably be faster to implement the fields and inputs required without forking. You don't even have to create a package for that. Just create them inside your project (eventually by copy pasting others and quick fix them) then use them as usual

**Comment by fzaninotto** [comment]
Now I understand better: you've installed using `npm install <yourfork>`, not using `git clone` and `npm link` (as described in the readme). 

Please use the method described in the readme, it works. As for other methods, they are not supported.

And as @djhi said, you shouldn't need to fork this repo to add a component.
