### ISSUE TITLE
Pass redux-form's change prop to SimpleForm's children

### ISSUE THREAD

**Issue by edorivai** [marmelab/admin-on-rest#618]
Hi!

Would you consider passing the [change prop](http://redux-form.com/6.2.0/docs/api/Props.md/#-change-field-string-value-any-function-) through to the children of `SimpleForm`?

I have a case where I want to implement a relatively complex custom `Field`, and I think I need the `change` prop to make this work.

I would be willing to submit a PR if you guys are open for this change.

Cheers!

**Comment by fzaninotto** [comment]
As `SimpleForm` is decorated by the `reduxForm` higher-order component, you can already pass a custom `change` prop on it.

**Comment by edorivai** [comment]
I understand that I can pass a custom `change` prop to `SimpleForm`, but I want something different; I want `SimpleForm` to pass the `change` prop (that is decorated by `reduxForm`) through to the child `Field`s.

Something like this:

```js
export const SimpleForm = ({ children, handleSubmit, invalid, record, resource, basePath, change }) => (
	<form onSubmit={handleSubmit} className="simple-form">
		<div style={{ padding: '0 1em 1em 1em' }}>
			{React.Children.map(children, input => input && (
				<div key={input.props.source} className={`aor-input-${input.props.source}`} style={input.props.style}>
					<FormField input={input} change={change} resource={resource} record={record} basePath={basePath} />
				</div>
			))}
		</div>
		<Toolbar invalid={invalid} />
	</form>
);
```

Note the `change` prop received by `SimpleForm`, and passed on to `FormField`.

**Comment by fzaninotto** [comment]
You'll have to write your own Form component for that, this is not something admin-on-rest will support.

**Comment by edorivai** [comment]
Understood. I already have my own Form component (which is basically a copy from the SimpleForm :) ). I was just curious if this is perhaps a general case that others are trying to solve as well.

Any way. Thanks for the awesome lib, having a lot of fun with it!
