### ISSUE TITLE
Simple actions example; refreshing list/record

### ISSUE THREAD

**Issue by edorivai** [marmelab/admin-on-rest#632]
The [docs on writing a simple action](https://marmelab.com/admin-on-rest/Actions.html#the-simple-way) seem to indicate that pressing the `ApproveButton` will refresh the list, by calling `push('/comments')`. However, when rendering the `ApproveButton` in the comments list at `/comments`, `react-router-redux` will complain with:
```
Hash history cannot PUSH the same path; a new entry will not be added to the history stack
```

Which makes sense, what we really want is a refresh of the current route, we don't really want to push a new history state. I'm currently working around this with the following (really nasty) hack:

```js
push('/'); // Navigate to the root (or any other page that you like)
push(`/comments`); // Navigate back to the comments list.
```

This is a quick and dirty way. which works reasonably well. But I would rather use a more reasonable approach. I see two clean options:

- Write my own `List` component
- Pass `refresh` down from `List` to it's children (like it's currently passed to `actions`).

I would prefer the second way, because the first solution would basically turn out in me copying `List.js`, and applying option 2 manually. I think allowing List children to refresh the list itself would be a useful feature to include in the library.

Please let me know what you think. I'll be willing to supply a PR if you like.

**Comment by fzaninotto** [comment]
I think the solution isn't to use `push`, but to use a refresh action - that's what's currently being implemented in #590.

I suggest you continue the discussion there.

**Comment by edorivai** [comment]
Looks like it's exactly what I need. Thanks!

**Comment by felixprojekt** [comment]
The mentioned PR was abandoned. How to solve this in 2019?

**Comment by fzaninotto** [comment]
See #942

**Comment by felixprojekt** [comment]
Indeed. Thank you very much :)
