### ISSUE TITLE
How can I custom the sidebar width?

### ISSUE THREAD

**Issue by whyuan1976** [marmelab/admin-on-rest#634]
When I change menu width by style, it not work for sidebar. 

![image](https://cloud.githubusercontent.com/assets/14135520/25770885/2126930e-3274-11e7-9ea2-e6ac90f0297f.png)

**Comment by wesley6j** [comment]
Replace `16em` with something like `26em`? It works for me.

**Comment by whyuan1976** [comment]
@wesley6j 
Thank for your answer.
Your meaning is I need change admin-on-rest source ?
My question is how to change it in my app.

**Comment by wesley6j** [comment]
You can create [custom layout](https://marmelab.com/admin-on-rest/Theming.html#using-a-custom-layout) if you don't want to change aor source code.

**Comment by djhi** [comment]
@wesley6j is right, it's not possible to customize the sidebar currently so you'll have to go the custom layout way. I'll keep this issue open as enhancement. Might be a good first contribution if you'd like to do it ;)

**Comment by whyuan1976** [comment]
Thanks. I had alread used custom layout to realize it.

```
<div style={{ maxWidth:'220px',order:-1}}>
    <Sidebar theme={theme}>                                
          {menu}
    </Sidebar>
</div>
```
I just study aor for 1 week.Now , I  have no ability to fix it. If I have time , I can try to enhance aor source.
