### ISSUE TITLE
[Question] Handling array of items

### ISSUE THREAD

**Issue by SidFerreira** [marmelab/admin-on-rest#640]
I have a small project that has something like:
```
{
   id: 123,
   details: [
      { title: 1, description: 1 },
      { title: 2, description: 2 },
      { title: 3, description: 3 },
   ]
}
```

My question is: What's the best approach to display this content? What about `add detail` / `remove detail` buttons?

**Comment by fzaninotto** [comment]
We don't provide support through GitHub issues. If you need advice on using or debugging your own project based on admin-on-rest, please use [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest).

Besides, a simple search on the Pull Requests in this repo would reveal the (work in progress) solution to your problem.

**Comment by wedneyyuri** [comment]
@fzaninotto Sorry for the noise, but it took me minutes to discover the related issue: #232. I have hope this will help someone in the future.
