### ISSUE TITLE
Custom REST client - GET ONE documentation

### ISSUE THREAD

**Issue by tilastokeskus** [marmelab/admin-on-rest#641]
Is the documentation for [writing your own rest client](https://marmelab.com/admin-on-rest/RestClients.html#writing-your-own-rest-client) up to date? Specifically the **Response Format** section, where it says that the format for `GET_ONE` is `{ data: {Record} }` seems to be wrong.

The admin redux tree had resources with `undefined` keys when I returned data in the documented format: `{data: { id: 123, title: "hello, world", author_id: 12 }}`. My issues went away when I simply changed the response format to: `{ id: 123, title: "hello, world", author_id: 12 }`.

To get my app working with the documented response format, I had to make a slight modification to [reducer/resource/data.js](https://github.com/marmelab/admin-on-rest/blob/master/src/reducer/resource/data.js#L36):

Change this:
```js
const newRecordsById = newRecords.reduce((prev, record) => {
    prev[record.id] = record; // eslint-disable-line no-param-reassign
    return prev;
}, {});
```

to this:
```js
const newRecordsById = newRecords.reduce((prev, record) => {
    if (!record.id && record.data && record.data.id) {
        prev[record.data.id] = record.data; // eslint-disable-line no-param-reassign
    } else {
        prev[record.id] = record; // eslint-disable-line no-param-reassign
    }
    return prev;
}, {});
```

**Comment by djhi** [comment]
It is, check the [jsonServer implementation](https://github.com/marmelab/admin-on-rest/blob/master/src/rest/jsonServer.js#L92). 

Are you suer you're using the latest version ?

**Comment by tilastokeskus** [comment]
I have the latest version: **1.0.1**.

I'm baffled as to why your jsonServer implementation would work, since if I respond with `{data: { id: 123, title: "hello, world", author_id: 12 }}`, then `record` in the code I pasted obviously doesn't have the property `id`.

**Comment by djhi** [comment]
Can you post your custom restClient ?

**Comment by tilastokeskus** [comment]
It's a bit lengthy, so here's the stripped down portion of the relevant GET_ONE route.

```js
// express route
app.get('/api/:modelName/:recordId', async(req, res) => {
	const {modelName, recordId} = req.params;

	// fetch data from microservice.

        const response = {id: 12, name: 'example'}; // example response
        res.send(response);
});
```

**Comment by djhi** [comment]
That's your api code, I meant the custom restClient

**Comment by djhi** [comment]
I think you misunderstood the documentation. We do not expect your API to return `{ data: { ... } }`. We expect the restClient to return `{ data: yourApiDataFromResponse }`

**Comment by tilastokeskus** [comment]
Oh, sorry, misunderstood you. I'm using `jsonServerRestClient`

```js
import React from 'react';
import {jsonServerRestClient, Admin, Resource} from 'admin-on-rest';

import ModelFactory from '../lib/modelFactory';

const App = ({apiUrl, apimap}) => {
	const factory = new ModelFactory(apimap);
	return (
		<Admin restClient={jsonServerRestClient(apiUrl)}>
			{apimap.map((model, index) => {
				return (
					<Resource
						key={index}
						name={model.name}
						list={factory.createModelList(model.fields)}
						edit={factory.createModelEdit(model)}
					/>
				);
			})}
		</Admin>
	);
};

export default App;
```

**Comment by tilastokeskus** [comment]
Well that explains it. Is it documented anywhere what the client expects from the api? I couldn't find it.

**Comment by djhi** [comment]
We expect your resource(s)
