### ISSUE TITLE
Sidebar in mobile(responsive small mode) selects the first item on its own( without user clicking it )

### ISSUE THREAD

**Issue by astriskit** [marmelab/admin-on-rest#642]
Hello there.

When I was browsing the demo site(https://marmelab.com/admin-on-rest-demo/) in my mobile( chrome browser latest up-to-date ), I saw, whenever the sidebar was opened, the first item (the dashboard) got itself selected without any tapping.

Also, while tapping on the other items in the list, it was not always that the results were loaded( the page remained unchanged i.e. no action ) and the sidebar as usual closed. 

Please see into it.

**Comment by djhi** [comment]
Can't reproduce any of those issues

**Comment by astriskit** [comment]
It is strange because I have tried in atleast two different devices. One of them is Yu Yuphoria.

**Comment by djhi** [comment]
Have you tried a sample material-ui app on these phones ?

**Comment by astriskit** [comment]
Taking your advice, I browsed http://www.material-ui.com/ (demo) in my mobile and though the UI was not that quickly working but was working as expected( without any functional disruption like admin-on-rest ).

**Comment by fzaninotto** [comment]
I can confirm the issue with Chrome in simulated device mode.

**Comment by astriskit** [comment]
So, it is a bug. Thanks to @fzaninotto.

**Comment by djhi** [comment]
> whenever the sidebar was opened, the first item (the dashboard) got itself selected without any tapping.

In fact, I can only reproduce this prb when we are on the dashboard page. Opening the Sidebar from any other page does not select the first item automatically

**Comment by djhi** [comment]
Moreover, if I try to log the onTouchTap event inside the DashboardMenuItem, I do not get any log from this auto selection

**Comment by astriskit** [comment]
hello there!

I thought it would be nice if I could add pictures of what I faced.

So here are the gifs -

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/28564247/26105901/a013e848-3a61-11e7-92b7-30cbc8bf79b0.gif)
![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/28564247/26105902/a03f3e26-3a61-11e7-848f-38e83e18e02b.gif)

**Comment by djhi** [comment]
Thanks but we finally reproduced it. I have spent several hours on this already but haven't find why it is happening yet.

**Comment by astriskit** [comment]
Hello there!
Any update guys ??
BTW thanks for the efforts. :+1:

**Comment by djhi** [comment]
Not yet

**Comment by astriskit** [comment]
Hello guys! Any update ?!

**Comment by wesley6j** [comment]
On a Chrome in simulated device mode, if you click quickly, the page stays (yeah, the bug). However, if your click stays a little bit longer, you go to the selected page (no bug)!
Therefore, short tap and long tap are handled differently if current page is dashboard.

**Comment by wesley6j** [comment]
The cause is that sometimes (on dashboard and products page) the touch event is sent to the MenuItem. This can be confirmed by moving down all the menu items with edited css.

A 200ms delay to show the drawer prevented this on Chome simulation.

I am not 100% sure the 200 ms works for all devices. if it doesn't, try increase it.

#698

**Comment by astriskit** [comment]
It worked, but I increased that too 300 since 200 wasn't making any difference. That's cool.

**Comment by wesley6j** [comment]
@astriskit Please increase it to a very large value just to verify the problem is related to "the touch event sent to menu icon is also sent to the first item of the drawer". 

If the delay has to be very large for some devices, then we can only fix it by not allowing drawer and its children nodes to accept events when animation is happening.

**Comment by astriskit** [comment]
@wesley6j  Increased it till 2000 ms and the effect seems to be same, i.e., the auto-click is not triggering. But, the menu options are not loaded in chromium.

**Comment by astriskit** [comment]
@wesley6j  Increased it till 2000 ms and the effect seems to be same, i.e., the auto-click is not triggering. But, the menu options are not loaded in chromium.

**Comment by djhi** [comment]
Can't reproduce it on the `next` branch anymore. Feel free to reopen.

**Comment by djhi** [comment]
Reopened as I reproduced it on the demo with the `next` branch
