### ISSUE TITLE
URL customization

### ISSUE THREAD

**Issue by panna-ahmed** [marmelab/admin-on-rest#645]
I had to change in the restclient like this:
case GET_MANY_REFERENCE: {
                const { page, perPage } = params.pagination;
                const { field, order } = params.sort;
                const query = {
                    orderBy: field + " " + order.toLowerCase(),
                    pageNumber: page,
                    pageSize: perPage
                };

                **var parentresource = '';
                switch (resource) {
                    case 'details':
                        parentresource = `products/${params.id}/${resource}`;
                        break;
                    default:
                        parentresource = `${resource}`;
                }**

                url = `${apiUrl}/${**parentresource**}?${fetchUtils.queryParameters(query)}`;
                break;

I have a EditView where in one tab I have got:
<ReferenceManyField addLabel={false} reference="details" target="id">
                    <Datagrid>                        
                        <EditButton />
                    </Datagrid>
                </ReferenceManyField>

When I click EditButton the url in the browser needs to needs to be http://localhost:5000/#/details/1?_k=5f7qc1 but the url to grab data from should be http://localhost:5000/api/products/2/details/1

Any easier way to do this?

**Comment by fzaninotto** [comment]
We don't provide support through GitHub issues. If you need advice on using or debugging your own project based on admin-on-rest, please use [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest).
