### ISSUE TITLE
ImageField component for displaying via API example?

### ISSUE THREAD

**Issue by jackywhlee** [marmelab/admin-on-rest#648]
None of the examples here has `ImageField` for displaying pictures via API calls, all of them are Image Upload examples (used together with ImageInput). I'm following https://marmelab.com/admin-on-rest/Fields.html#imagefield and I cannot get ImageField working. Below is a sample code:

```
<Edit title={<AcceptedTitle />} {...props}>
      <TabbedForm>
        <FormTab label="status">
          <ImageField source="photos.idPhoto.data" title="picture.title" />
          <ImageField source="http://lorempixel.com/628/1837/transport/10" title="picture.title" />
        </FormTab>
     </TabbedForm>
</Edit>
```

The "photos.IdPhoto.data" value is a 64bit image in data form retrieved from an API call. I added a lorempixel image link as well, but neither of these two ImageField components are rendering anything.

I can't confirm if this is a bug, since there are no working example code to compare it with.

**Comment by jackywhlee** [comment]
It seems that the record inside ImageField is using the GET_ALL api call, which doesn't include images. But I have written a GET_ONE api call, and when I console.log it out, the response is the one that I need for images inside the Edit component.

So I'm wondering why the record value inside ImageField doesn't use the GET_ONE api call... is there a solution?

**Comment by djhi** [comment]
We don't provide support through GitHub issues. If you need advice on using or debugging your own project based on admin-on-rest, please use StackOverflow.
