### ISSUE TITLE
Error on clean filter

### ISSUE THREAD

**Issue by chemitaxis** [marmelab/admin-on-rest#650]
How to reproduce the error:

- In a list resource, select a filter, and filter by a field (Ok)
- Remove the filter clicking in cross button (Ok)
- Go other resource (Ok)
- Go back to the previous resource where you apply the filter (BAD, the value is "undefined" for the filter).

The problem is in the REMOVE FILTER button. 

Query Output:

> GET /api/users?UserName=**undefined**&_sort=id&_order=DESC&_start=0&_end=10

**Comment by djhi** [comment]
Which version are you using ? I believe this has been fixed recently. If not using master, can you try with it ?

**Comment by chemitaxis** [comment]
Hi @djhi I'm using 1.0.1 Thanks.

**Comment by djhi** [comment]
Have you tried with `master`. I can't reproduce this bug with it

**Comment by chemitaxis** [comment]
Importan, the filter must be without propery AlwaysOn... I was confused, and I removed the node_modules, and reinstall all changing the version again...

**Comment by djhi** [comment]
Are you sure ? There are no cross buttons on alwaysOn filters

**Comment by djhi** [comment]
Can't reproduce the problem on the demo

**Comment by chemitaxis** [comment]
![image](https://cloud.githubusercontent.com/assets/1420409/25907077/b174b550-35a6-11e7-8020-551fc24156b5.png)

I can reproduce ;)

**Comment by chemitaxis** [comment]
You can test on this way: 
- Go to post list, and add a filter (Title Filter)
- The list is refreshed automatically
- Press the close button of the filter
- Go to comments
- Back to POST and you will see Not results founds

**Comment by djhi** [comment]
When I said the demo, I meant https://marmelab.com/admin-on-rest-demo. 

I do reproduce it on the inner example though.

**Comment by chemitaxis** [comment]
Hi @djhi in the example you don't have an "exact" use case... ;)

**Comment by chemitaxis** [comment]
Is fixed in the master? Thanks!

**Comment by fzaninotto** [comment]
Normally yes.
