### ISSUE TITLE
[BUG] RTL menu issue

### ISSUE THREAD

**Issue by cyclops24** [marmelab/admin-on-rest#654]
Hi after change `<body>` to `<body dir="rtl">` menu not close when I click on menu button and crash.
Open menu (It's OK):
![aor_menu1](https://cloud.githubusercontent.com/assets/8266479/25909624/012c7116-35c3-11e7-8add-6670162d28e2.png)

Close menu (menu not closed and go in behind of main content):
![aor_menu2](https://cloud.githubusercontent.com/assets/8266479/25909676/296b3ca2-35c3-11e7-9452-b5e5239c7602.png)

**Comment by djhi** [comment]
Have you tried with a "classic" material-ui app ?

**Comment by djhi** [comment]
I just tried and can reproduce the problem. Fix won't be easy though. In the meantime, you'll have to use a custom layout to address it.

**Comment by djhi** [comment]
@fzaninotto I can only think of one solution for this. Adding an `rtl` prop to the `Admin` component, which would pass it to the Sidebar so that we can invert the margin (using right instead of left).

**Comment by djhi** [comment]
Another one would be to extend the drawer MUI theme to include an `rtl` property and use it in the Sidebar directly

**Comment by djhi** [comment]
The last option works fine but it's not enough to make the app looks good in rtl mode.

You also have to customize the MUI theme by adding `isRtl: true` to it. See the MUI [documentation](http://www.material-ui.com/#/customization/themes)

**Comment by djhi** [comment]
@cyclops24, in fact we don't have anything to do in Admin-on-rest to support this:

1. Add the `dir` attribute as you did to the `body` element
2. Customize the Material-UI theme as explained in their [documentation](http://www.material-ui.com/#/customization/themes)

Side bar shown:
![menu open](http://i.imgur.com/7D0a3X8.png)

Side bar hidden:
![menu closed](http://i.imgur.com/vhETS3W.png)

**Comment by cyclops24** [comment]
Thanks for your attention @djhi ,
Can you explain where you add `isRtl: true`? (which file)

**Comment by djhi** [comment]
Follow the material-ui documentation to create a custom theme.

Then follow the Admin-on-rest documentation to pass this custom theme to the Admin component

**Comment by alijabbari72** [comment]
@djhi my theme didnt make RTL with your guid :-( 
could you help me more?

**Comment by mohamad-n** [comment]
just create your theme and style it
you can do it like this in root file (app.js) :

import { createMuiTheme } from '@material-ui/core/styles';
const myTheme = createMuiTheme({
//also you can use your persian font also
    typography: {
        fontFamily: [
            'your custom font',
        ].join(','),
    },
    direction : 'rtl',
});

// use it in yout root component
class App extends Component {
  render() {
    return (
      <Admin theme={myTheme}    dataProvider={dataProvider}>
        <Resource name="posts"  list={PostList} />
        <Resource name="users"  list={UserList} />
      </Admin>
    );
  }
}

**Comment by mohas** [comment]
my problem is that for example every grid cell has `text-align: left` set, so setting `dir: rtl` and changing direction in theme does nothing

**Comment by djhi** [comment]
Please open a new issue as this one specifically mentionned the menu.
