### ISSUE TITLE
Issues with ReferenceInput inside List view

### ISSUE THREAD

**Issue by kodepareek** [marmelab/admin-on-rest#656]
Following is code for a basic editor dashboard. I want to assign editors (who are users with special privileges) from the list view. 
```

export const EditorAssignView = (props) => {
  return (
    <List {...props} title="Fresh Tales" perPage={20} >
      <Datagrid>
        <TextField source="taleTitle" label="Title"/>
        <TextField source="taleText" label="Content" style={{maxWidth: '150px'}}/>
        <ReferenceField label="Writer" source="writer_id" reference="appUsers">
          <ChipField source="name" />
        </ReferenceField>
        <ReferenceInput label="Editors" source="id" reference="appUsers">
          <SelectInput  optionText="name" />
        </ReferenceInput>
        <EditButton />
      </Datagrid>
    </List>
  )
}

```
However using the ReferenceField component inside the dataGrid view causes the page to not render the list view and also pings the API repeatedly with a blank request. 

```
uncaught at handleFetch TypeError: Cannot read property 'value' of undefined
    at Function.mapStateToProps [as mapToProps] (http://localhost:3000/static/js/bundle.js:95847:35)
    at mapToPropsProxy (http://localhost:3000/static/js/bundle.js:37530:47)
    at Function.detectFactoryAndVerify (http://localhost:3000/static/js/bundle.js:37539:20)
    at mapToPropsProxy (http://localhost:3000/static/js/bundle.js:37530:47)
    at handleFirstCall (http://localhost:3000/static/js/bundle.js:37720:19)
    at pureFinalPropsSelector (http://localhost:3000/static/js/bundle.js:37768:82)
    at Object.runComponentSelector [as run] (http://localhost:3000/static/js/bundle.js:35714:26)
    at Connect.initSelector (http://localhost:3000/static/js/bundle.js:35866:24)
    at new Connect (http://localhost:3000/static/js/bundle.js:35807:16)
    at http://localhost:3000/static/js/bundle.js:26434:19
```

Moving the ReferenceField to within a tale's edit view leads to the component working as expected. Is the ReferenceField not meant to be used within lists? If so then could someone suggest what I do to give users a dropdown selector in the list where they can select from users. (basically want to give users ability to assign an editor to a tale)

**Comment by kodepareek** [comment]
On further investigation removing the ReferenceField from above list view stops the repeated pinging of the API. However the page still does not render. 

```
export const EditorAssignView = (props) => {
  return (
    <List {...props} title="Fresh Tales" perPage={20} >
      <Datagrid>
        <TextField source="taleTitle" label="Title"/>
        <TextField source="taleText" label="Content" style={{maxWidth: '150px'}}/>
        <ReferenceInput label="Editors" source="id" reference="appUsers">
          <SelectInput  optionText="name" />
        </ReferenceInput>
        <EditButton />
      </Datagrid>
    </List>
  )
}


```

**Comment by djhi** [comment]
We don't provide support through GitHub issues. If you need advice on using or debugging your own project based on admin-on-rest, please use [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest).

**Comment by kodepareek** [comment]
Hi @djhi  

I was reporting what I think might be a bug. I can remove the request for a solution if you wish.

**Comment by djhi** [comment]
> I can remove the request for a solution if you wish.
 What do you mean ?

**Comment by kodepareek** [comment]
I have updated the above to sound more like a bug report than support request.

**Comment by djhi** [comment]
It is not possible currently to have edition fields inside a List. See #335

**Comment by kodepareek** [comment]
Aah I see. 

Thanks a lot for your time.

**Comment by kodepareek** [comment]
Perhaps this could be documented better in the list view.
