### ISSUE TITLE
Best way to implement login screen

### ISSUE THREAD

**Issue by alexborisov** [marmelab/admin-on-rest#66]
Any suggestions of the best way to go about a login screen? Obviously I can throw it behind an HTTP auth rule, but thats a little lame.

Looking at the code it seems like i might have to implement a custom layout (dashboard doesn't seem flexible enough), but perhaps there is a better way? All I need is to post a user/pass and get back a JWT token to store in local storage. I've written a REST adapter to handle this, but I'm passing it as a hardcoded prop on `restClient`.

**Comment by fzaninotto** [comment]
Until admin-on-rest handles it natively, you'll have to use a [custom app](http://marmelab.com/admin-on-rest/CustomApp.html) for that. A good example can be found in our [javascript boilerplate](https://github.com/marmelab/javascript-boilerplate/blob/master/src/admin/js/Admin.js).

**Comment by fzaninotto** [comment]
Fixed by #257
