### ISSUE TITLE
input  base on some field value

### ISSUE THREAD

**Issue by limin9988** [marmelab/admin-on-rest#660]
function Form(props) {
  var objBarCode;
  if (props.record && props.record.type === "STOCK") {
    objBarCode = <TextInput source="barcode" label="Bar Code" />;
  }
  return (
    <SimpleForm {...props}>
      <TextInput source="item" label="item" validate={[required]} />
      <TextInput source="name" label="Name" validate={[required]} />
      <SelectInput
        source="type"
        label="Type"
        validate={[required]}
        choices={[
          { id: "STOCK", name: "Stock" },
          { id: "RMK", name: "Remark" },
          { id: "SVR", name: "Services" }
        ]}
      />
      {objBarCode}
    </SimpleForm>
  );
}

hi,how to achieve something like this??which some input are only appear by some conditions, the above code does not rerender when the condition value change , the goal was the Textinput Bar Code  only appear when type="STOCK"

**Comment by djhi** [comment]
We don't provide support through GitHub issues. If you need advice on using or debugging your own project based on admin-on-rest, please use [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest).
