### ISSUE TITLE
Customize existing Inputs

### ISSUE THREAD

**Issue by eddyLazar** [marmelab/admin-on-rest#661]
I don't wont to always include `parse` and `format` in `DateInput` Component so i wrote a simple abstraction

```javascript
const ParseDateInput = (props) => (
    <DateInput 
      {...props}
      format={/*muCustomFormatFunction*/}
      parse={/*muCustomFParseFunction*/}
    />
)
```

When i use it  i have this error
`uncaught at handleFetch TypeError: Cannot read property 'touched' of undefined`

**Comment by djhi** [comment]
We don't provide support through GitHub issues. If you need advice on using or debugging your own project based on admin-on-rest, please use [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest).

**Comment by eddyLazar** [comment]
Isn't it a bug?

**Comment by fzaninotto** [comment]
No, it isn't a bug. If you look carefully, `DateField`declares a default value for the `addField`prop. This tells admin-on-rest to decorate it with redux-form's `Field`component, and this component injects a `meta` prop to its child. 

To make your custom component work, you mus set the `addField`component default value to true, too.

This is explained in the documentation: 

https://marmelab.com/admin-on-rest/Inputs.html#writing-your-own-input-component

**Comment by eddyLazar** [comment]
Thanks, didn't notice it at first
