### ISSUE TITLE
Question: authClient removed from Admin component seems to break loginPage functionality

### ISSUE THREAD

**Issue by AndrewBresee** [marmelab/admin-on-rest#662]
On commit https://github.com/marmelab/admin-on-rest/commit/544e08ae3d7aa9ede21eb7f9c0f1964e8a4e21c8 authClient was removed from Admin.js 

**Admin-on-rest version**: ^1.0.1
**React version**: ^15.5.4
**Browser version**: Version 58.0.3029.110 (64-bit)

**Observed:**
On a recent upgrade from admin-on-rest 0.9.3 to 1.0.1, our loginPage stopped working because authClient became undefined

**Code snippets that cause the error:**
We import loginPage and authClient properly into Admin component
```
// App.js
 <Admin messages={messages} loginPage={Login} authClient={authClient} dashboard={Dashboard} restClient={myApiRestClient}>
... 
  </Admin>
```

We are using react-google-login. Previously we were able to grab authClient from props in this component. 
```
...
class Login extends Component {
  constructor (props) {
    super(props)
    this.state = { signInError: false }
  }

  success = (resp) => {
    const token = resp.accessToken
    const { authClient, push, location } = this.props
    if (!authClient) return
    return authClient(AUTH_LOGIN, { token })
        .then(() => push(location.state ? location.state.nextPathname : '/'))
        .catch(e => this.setState({ signInError: e }))
  }
...
```
In the code snippet above, authClient is undefined with the new version of admin-on-rest. This was working on version 0.9.3.

However, it *DOES* work when authClient is re-added where it was removed from Admin.js
```
...

    return (
        <Provider store={store}>
            <TranslationProvider messages={messages}>
                <ConnectedRouter history={history}>
                    <div>
                        <Switch>
                            <Route exact path="/login" render={({ location }) => createElement(loginPage || Login, {
                                location,
                                title,
                                authClient,
                                theme,
                            })} />
                            <Route path="/" render={() => createElement(appLayout || DefaultLayout, {
                                dashboard,
                                customRoutes,
                                menu: createElement(menu || Menu, {
                                    logout,
                                    resources,
                                    hasDashboard: !!dashboard,
                                }),
                                resources,
                                title,
                                authClient,
                                theme,
                            })} />
                        </Switch>
                    </div>
                </ConnectedRouter>
            </TranslationProvider>
        </Provider>
    );
...
``` 

**The potential fix:**

Without changing admin-on-rest code, this can be solved by importing our authClient into the file that contains the loginPage component, instead of grabbing it from props. 
```
import authClient from './authClient'
```

**Question:**

Is this how you intend custom login page to be used?

**Comment by fzaninotto** [comment]
No, you're supposed to dispatch a `userLogin` action that's then passed to the authClient by Redux, as [explained in the authentication documentation](https://marmelab.com/admin-on-rest/Authentication.html#customizing-the-login-and-logout-components).
