### ISSUE TITLE
Is there any way to add role access control?

### ISSUE THREAD

**Issue by xueliang** [marmelab/admin-on-rest#663]
Amazing interface!
And in my problem, I need to show different view by user role. Any suggestion to add role access control in admin-on-rest? thanks in advance.

**Comment by djhi** [comment]
Something like the `Responsive` component but checking role instead of resolution?

**Comment by kodepareek** [comment]
Hi @djhi could you please elaborate a bit. Thanks.

**Comment by djhi** [comment]
Not here now. We don't provide support through GitHub issues. If you need advice on using or debugging your own project based on admin-on-rest, please use [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest).
