### ISSUE TITLE
[Fork request] Russian localizations for admin-on-rest

### ISSUE THREAD

**Issue by RomanShumikhin** [marmelab/admin-on-rest#666]
Hey guys,

I am using admin-on-rest in one of my pet projects I am currently building and would like to contribute Russian localizations which I made based on aor-language-french
https://github.com/RomanShumikhin/aor-language-russian

Could you please fork and create a npm package?

Thanks!

**Comment by djhi** [comment]
Hi!

There is already a package for Russian: https://github.com/cytomich/aor-language-russian.
It has been published on npm.

**Comment by RomanShumikhin** [comment]
Ha-ha, awesome, thanks! I was just checking the official repos so I didn't notice it. Closing.
