### ISSUE TITLE
Filters include empty inputs that use dot notation for their source prop

### ISSUE THREAD

**Issue by AmrN** [marmelab/admin-on-rest#667]
If I have the following filter which contains an input using dot notation to handle a nested property:
```jsx
  <Filter {...props}>
    <TextInput label="Search" source="name.first" alwaysOn />
  </Filter>
```
Now if I enter some input, the query gets sent successfully, but then if I clear the input text the query ends up containing the filter with an empty string.

**Comment by djhi** [comment]
What version of Admin-on-rest are you using ? This should have been fixed in `1.0.2`

**Comment by AmrN** [comment]
I'm using 1.0.2
Looking at the source code for filter, it doesn't seem to take nested objects into accound when removing empty values, only strings.
https://github.com/marmelab/admin-on-rest/blob/fcfbfce3422d61ef833bd146cc4c08bdc1a2db9d/src/mui/list/Filter.js#L27-L33

**Comment by djhi** [comment]
Good catch!
