### ISSUE TITLE
[question] Custom id/primary key

### ISSUE THREAD

**Issue by fcarreiro** [marmelab/admin-on-rest#670]
Hello! I've been looking through the docs and I couldn't find how to define a model and datagrid that can use a primary key which is not named "id". For example, we have a Location resource with

```
code: zipcode, primary key
name: some string
```

The REST endpoint is still `/locations/:code/` and works ok, acting on the `code` attribute.

Is this possible? Thanks!

**Comment by wesley6j** [comment]
From what I know, admin-on-rest requires an id field for each item. It can be integer or string, but it is definitely required. It may be much easier to change backend or your restClient to rename `code` field into `id`.

**Comment by nickrobillard** [comment]
I'm looking for this too. Something like backbone's [idAttribute](http://backbonejs.org/#Model-idAttribute) would be really nice here.

It looks like this would take a bit of work. The rest server(s), reducers and actions seem to be closely tied to the "id" key. However, I'm not very familiar with this project yet so it would be nice to hear from someone who is.

**Comment by tacoo** [comment]
https://github.com/marmelab/admin-on-rest/issues/373

**Comment by fzaninotto** [comment]
And the tutorial for doing this is online: https://marmelab.com/admin-on-rest/FAQ.html#can-i-have-custom-identifiers-primary-keys-for-my-resources

**Comment by fcarreiro** [comment]
Thank you!
