### ISSUE TITLE
Move "Available Locales" from "Translation" to "Ecosystem"

### ISSUE THREAD

**Issue by leesei** [marmelab/admin-on-rest#677]
I propose to move 
https://marmelab.com/admin-on-rest/Translation.html#available-locales
to 
https://marmelab.com/admin-on-rest/Ecosystem.html#translations

**Comment by fzaninotto** [comment]
As a developer, I prefer to find it in `Translation.html`, which is where I'll look for it in the first place. 

But I agree that the repetition is error prone. So I vote for the opposite: remove the translations from `Ecosystem.html`, and replace them by a link to the relevant section in `Translation.html`.

Any other opinion?

**Comment by leesei** [comment]
Ha, I was thinking of adding link to in Ecosystem in Translation.
Anyway either way will do.
