### ISSUE TITLE
Previous filters are being applied without being added to the URL/addressbar

### ISSUE THREAD

**Issue by MhdSyrwan** [marmelab/admin-on-rest#678]
## Description:
Open a resource's list and select some filters, then change to another one. Then when you open the previously opened one you will see that your old filters are set but the URL in the addressbar doesn't reflect that.

## Scenario / Steps to reproduce:

1. Open https://marmelab.com/admin-on-rest-demo/#/reviews
2. Click "Add Filter", Choose "Status" and Set it to "Accepted"
3. The filter will be applied and you can see that also in the URL "#/reviews?filter=%7B%22status%22%3A%22accepted%22%7D&.........."
4. Click on "Categories" from the sidebar
5. Click on "Reviews" from the sidebar
6. Now, you will see that the "Status: Accepted" filter is still applied there but the URL is not updated to reflect that.
![2017-05-17 15-37-26 ekran goruntusu](https://cloud.githubusercontent.com/assets/730201/26154543/967bcd02-3b18-11e7-8aeb-c6500251190a.png)

7. (optional) As a result, if you refresh the page the filter will be removed

## Possible bugs

- Maybe the previous filters should not be re-applied.
- Maybe there is a bug preventing the the filter from updating the URL.

**Comment by fzaninotto** [comment]
Which version are you using? I think it's already fixed in 1.0.3

**Comment by MhdSyrwan** [comment]
I'm using `1.0.1`, I thought the online demo is using the latest version.
I will update my local version and check.

**Comment by MhdSyrwan** [comment]
BTW, `1.0.2` is the latest version available in [npm](https://www.npmjs.com/package/admin-on-rest).

**Comment by MhdSyrwan** [comment]
Tried the same scenario on `1.0.2`. it's also not working.

**Comment by fzaninotto** [comment]
Sorry, I meant 1.0.2

**Comment by fzaninotto** [comment]
Oh, sorry, that's not a but, that's a feature. Admin-on-rest "remembers" the list parameters and reapplies them when you come back to the list. It doesn't need to change the URL for that (or else that would cause another redraw).

**Comment by MhdSyrwan** [comment]
OK, so is there anyway i can disable this feature ?

**Comment by djhi** [comment]
Nope

**Comment by djhi** [comment]
The only way you could do that would be by creating your own `List` component (by copying the existing one) and make sure it does not keep the filters (should be easy).

**Comment by MhdSyrwan** [comment]
@djhi Thanks for the suggestion

Actually, i highly respect your decision to not to consider this a bug. 
I learned from you that it's a feature you've done to enhance user experience by remembering last applied filters, but it causes an undesired behavior (indirectly) because, as a user, if i saw a filter applied i would expect the URL reflect that. and moreover (as a non-technical user) i might copy the URL and give it to a friend expecting that he will see the same view i have now.

So, I suggest to reconsider treating this as an issue.
