### ISSUE TITLE
ImageInput doesn't pass useful properties to children

### ISSUE THREAD

**Issue by s-nel** [marmelab/admin-on-rest#680]
From code inspection it appears the intent of `ImageInput` is to pass properties of the underlying file objects to children

```
transformFile = (file) => {
        if (!(file instanceof File)) {
            return file;
        }

        const { source, title } = React.Children.toArray(this.props.children)[0].props;

        const transformedFile = { ...file }; // Here we extend from the enumerable properties of file
        transformedFile[source] = file.preview;

        if (title) {
            transformedFile[title] = file.name;
        }

        return transformedFile;
    };
```

But a lot of useful properties don't come through because they're not enumerable properties of `file`. Things like modification date, file size, and mime type are useful, but don't come through. 

Can we introduce a change so that the raw file object comes through the props? Or another way to get the useful properties of file through to children?

```
...
const transformedFile = { ...file }; // Here we extend from the enumerable properties of file
transformedFile[source] = file.preview;
transformedFile.raw = file;
...
```

**Comment by fzaninotto** [comment]
Fixed by #684
