### ISSUE TITLE
ImageInput not cleaning up object urls

### ISSUE THREAD

**Issue by s-nel** [marmelab/admin-on-rest#681]
The [dropzone library documentation](https://react-dropzone.netlify.com/#proptypes) states that 
> You need to destroy the object URL yourself whenever you don't need the preview by calling `window.URL.revokeObjectURL(file.preview)` to avoid memory leaks.

Currently `ImageInput` is not revoking urls.

I think admin-on-rest should take care of this because `onRemove` is not exposed to clients, so it would be more difficult for clients to perform this cleanup for themselves.

I suggest adding object url cleanup to the `onRemove()` method of `ImageInput` and adding cleanup when `ImageInput` is unmounted.

**Comment by fzaninotto** [comment]
Fixed by #684
