### ISSUE TITLE
[Question] DELETE may not contain a data key ?

### ISSUE THREAD

**Issue by paulsouche** [marmelab/admin-on-rest#683]
This commit c5af78a399a15da82a558235bd0adf117f185f65 force us to provide response content for the DELETE method. Is it really needed ? Is it possible to identify DELETE verb in this case ?

Thanks for the great work anyway

**Comment by wedneyyuri** [comment]
This format is also documented here: https://marmelab.com/admin-on-rest/RestClients.html#response-format

**Comment by fzaninotto** [comment]
Yes, it's a requirement of the REST client. If your API doesn't return the record, just return an empty object with the id property.
