### ISSUE TITLE
DateInput for german locale not parsing correctly

### ISSUE THREAD

**Issue by nik-lampe** [marmelab/admin-on-rest#691]
When adding the options property to an DateInput Component like

 `<DateInput source="startDate" options={{locale: 'de'}} />`

It displays the Date correcty in the german locale "D.M.YYYY" but when I click in the field to edit it, the value is parsed like "M.D.YYYY". So May, 1st becomes January, 5th. When I then select a date in the date picker, it is transformed and stored correctly. But next time I click in it, it is parsed like described again. 

I tried to reproduce it in the [sandbox](https://codesandbox.io/s/ElxGNxBY0), but it seems to be broken.

**Comment by wesley6j** [comment]
I can confirm the bug. The `datify` function that parses date does not wok.

**Comment by fzaninotto** [comment]
Fixed by #693
