### ISSUE TITLE
Make it works with UUID

### ISSUE THREAD

**Issue by Kmaschta** [marmelab/admin-on-rest#7]
As discussed on [a precedent PR](https://github.com/marmelab/admin-on-rest/pull/6#discussion_r77509324) about identifier parsing, admin-on-rest doesn't support UUID as entities identifier.

**Comment by VaclavSir** [comment]
What is the issue with UUID identifiers? I am trying to use UUIDs and I haven't found any problem yet other than the prop type warning on Datagrid.

**Comment by Kmaschta** [comment]
It'll not work with a `ReferenceManyField` because of a [`parseInt` in its rendering](https://github.com/marmelab/admin-on-rest/blob/deaf2c6bc1b701546a5d93dfb3a349ff2d93aa6b/src/mui/field/ReferenceManyField.js#L53).

**Comment by fzaninotto** [comment]
Fixed by #67
