### ISSUE TITLE
Empty response body is not supported

### ISSUE THREAD

**Issue by andreysaksonov** [marmelab/admin-on-rest#700]
It is valid case for DELETE method, however this check will throw error:

https://github.com/marmelab/admin-on-rest/pull/489/files

I'm not sure how to fix it actually (make exclusion for delete verb or remove the check completely?).

**Comment by stefsava** [comment]
Also for me on DELETE method the 204 (No Content)  http response is the most appropriate response and should not raise an exception.

**Comment by fzaninotto** [comment]
Your REST API can return anything or nothing for a DELETE request - no constraint on that. But admin-on-rest expects the `restClient` to always return a `data` key in the response. That means that your `restClient` must provide one (make it empty if the HTTP response for DELETE doesn't contain any data).
