### ISSUE TITLE
Responsive mobile view(list) with material's Tabs component

### ISSUE THREAD

**Issue by astriskit** [marmelab/admin-on-rest#701]
Hello there!
When using List inside Tabs->Tab material-ui component, the desktop version( the large screen ) works as expected, but when it is in the small screen, **the tabs bar would render above the title bar** ( may be because the list is rendering the ViewTitle component from admin-on-rest ). Also, the tab where there is no admin-on-rest component( for ex.: a div tag ), there is no title bar (I think I'll have to use ViewTitle).
Something like this - 
```
<Tabs>
<Tab label="Listing">
<List>...</List>
</Tab>
<Tab label="anything other">
<div>something</div>
</Tab>
</Tabs>

```
Any ideas ?! Thanks.

**Comment by djhi** [comment]
We don't provide support through GitHub issues. If you need advice on using or debugging your own project based on admin-on-rest, please use [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest).

**Comment by fzaninotto** [comment]
If it's a bug, feel free to reopen, but with a screenshot. Here is one that shows that it works fine:

![image](https://cloud.githubusercontent.com/assets/99944/26637300/6d813010-461f-11e7-9b45-a4423343f711.png)
