### ISSUE TITLE
Can I use a ReferenceField in a custom field component?

### ISSUE THREAD

**Issue by mikaoelitiana** [marmelab/admin-on-rest#706]
I have an api that returns something like this : 

```
[{
    "created_date": "2016-12-07T13:57:30.896Z",
    "id": 650,
    "project": 7,
    ...
  },
  {
    "created_date": "2016-12-07T13:57:30.897Z",
      "id": 392,
      "project": 7,
     ....
    },
...
]
```

Now I have a custom field component to display each of these items and there is a REST endpoint to get `/projects` where I can get info about each project (here with id `7`). 

Is there a way I can include such reference in my custom field component as I can only get the `7` value there instead of data from `GET /posts/7` that I would like to display : 

```
{
   "id": 7,
    "title": "Something cool",
    "slug": "lorem-ipsum", 
    ...
}
```

Thanks

**Comment by fzaninotto** [comment]
We don't provide support through GitHub issues. If you need advice on using or debugging your own project based on admin-on-rest, please use [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest).
