### ISSUE TITLE
ReferenceInput Issue with parse prop

### ISSUE THREAD

**Issue by eddyLazar** [marmelab/admin-on-rest#709]
I need to save reference input value as an object, so according to the docs i'm using `parse` function
```jsx
const parse => id => {/*some object with */}
<ReferenceInput 
  label='post'
  source='post_id'
  reference='posts'
  allowEmpty
  parse={parse}
>
  <SelectInput optionText='title' />
</ReferenceInput>
```

Now, when I'm selecting something the option is not selected when I click on it, I assume because option is selected by id from value, where i have an object. Couldn't find anything in both admin-on-rest and material-ui

**Comment by wesley6j** [comment]
You might not need `parse`. `SelectInput` with object as choices' value is totally fine.

**Comment by eddyLazar** [comment]
But i don't have choices, choices are fetched by reference

**Comment by wesley6j** [comment]
If your backend can provide a field, for example `information`, with the desired object inside, then you can set optionValue to `information`. Otherwise, you have to modify ReferenceInput.

**Comment by fzaninotto** [comment]
Check out redux-form: in addition to `parse`, you probably have to use `normalize`.

http://redux-form.com/6.7.0/docs/api/Field.md/
