### ISSUE TITLE
Warning: Failed prop type: Required prop `source` was not specified in `SelectInput`.

### ISSUE THREAD

**Issue by bjet007** [marmelab/admin-on-rest#71]
Hi, when following the example using a SelectInput inside a ReferenceInput, there is a warning in the console log saying that the 'source' property is missing.  

Since the ReferenceInput clone its children and add the source, it seem to work properly, but it would be great to remove that warning.  

Removing the required in the SelectInput doesn't seem to be the appropriate solution, do you have a better idea?

**Comment by fzaninotto** [comment]
Fixed by #81
