### ISSUE TITLE
Broken link inside documentation

### ISSUE THREAD

**Issue by dili91** [marmelab/admin-on-rest#713]
Not really an issue, but I noticed a broken link inside the documentation, at the 
**Overriding A Component Style** chapther [here](https://marmelab.com/admin-on-rest/Theming.html). The "their styling documentation" link is broken

**anyway AMAZING job!**

<img width="1093" alt="schermata 2017-05-30 alle 17 29 32" src="https://cloud.githubusercontent.com/assets/10221348/26591346/ab334208-455d-11e7-9e5f-efa315b547fd.png">

**Comment by djhi** [comment]
Can you send us a pr ?

**Comment by martjanz** [comment]
#715 should fix it

**Comment by fzaninotto** [comment]
Fixed by #715
