### ISSUE TITLE
AutocompleteInput should do something after leaving the input

### ISSUE THREAD

**Issue by wesley6j** [marmelab/admin-on-rest#720]
Currently, if user enter a string and leave the input without selecting any value, the following happens:
1. the input textfield keeps the user entered string.
2. the redux-form keeps its value before user entered the string.
3. if you submit the form the value you see is not the value you submit.

I am sure AutocompleteInput should appear differently in this case? Or it can restore to previous value onBlur?

**Comment by remi13131** [comment]
As a side effect, when you delete the content from the input, the the redux-form keeps its value before user deleted the string. (so it is impossible to send "null" when deleting AutocompleteInput in an already populated Edit)

**Comment by wesley6j** [comment]
If AutocompleteInput is considered as TextInput and allows arbitrary value, then form value should be updated to displayed value.

If it is considered alternative to SelectInput, then displayed value should be restored to previous display value if no item is selected. And in this case, @remi13131 's edge case should be considered as well.

I wonder what everyone thinks about it. Personally, I would like to treat it as SelectInput.

**Comment by remi13131** [comment]
I forgot to mention that part of this issue was already discussed there : https://github.com/marmelab/admin-on-rest/issues/592

**Comment by wesley6j** [comment]
I really like the idea of this [superselectfield](https://github.com/Sharlaan/material-ui-superselectfield) with autocomplete enabled: [demo](https://sharlaan.github.io/example3).

In short, it's a searchable selectfield with react-infinite. It's really powerful when the select field has too many options.

However, the design does not seem compatible with material-ui...

**Comment by fzaninotto** [comment]
As we're using material-ui's `<AutoComplete>` component without any tweak, I guess it's a mui issue. Testing the scenario you describe on http://www.material-ui.com/#/components/auto-complete shows the same behavior. 

I suggest you open a bug on their tracker.

**Comment by wesley6j** [comment]
@fzaninotto I found an interesting fact. Almost all other input components in Material-UI accept `value` prop while `AutoComplete` doesn't (it uses `searchText` instead). Maybe `AutoComplete` is not meant to be used the same way as other components?

**Comment by wesley6j** [comment]
`AutoComplete`'s dataSource can be either an array of strings or an array of objects. Maybe this corresponds to two main use cases:
1. text field with suggestions: dataSource is an array of strings; field value is the string displayed. 
2. select field with searchable options: dataSource is an array of objects; field value equals selected option value.

If this makes sense, I can make a PR so that `AutocompleteInput` works well for both cases.

**Comment by fzaninotto** [comment]
I think it should be another component, `<AutoCompleteTextInput>`
