### ISSUE TITLE
ImageInput always returns array

### ISSUE THREAD

**Issue by mzgnr** [marmelab/admin-on-rest#723]
is this normal even without multiple = true ?

**Comment by jpetitcolas** [comment]
I indeed faced the issue. Not sure what should be the intended purpose, but from a practical point of view, I find it cumbersome when uploading a single file. Yet, you can however do something like the following in your REST client:

```
const pictures = Array.isArray(params.data.picture) ? params.data.picture : [params.data.picture];
```

This way, if your API returns a single picture, it would be arrayized for AOR. As AOR always returns an array, you can handle all your upload process to deal only with arrays, eventually retrieving first element before sending it to your server.

**Comment by fzaninotto** [comment]
The documentation is misleading, we should make it more explicit

**Comment by mzgnr** [comment]
@jpetitcolas I'm using a third party aor client. If it's always returning an array what is the point of multiple option ?

**Comment by jpetitcolas** [comment]
@mzgnr: yes, it is probably related to what React DropZone returns. We'll keep current behavior (always an array).

**Comment by mzgnr** [comment]
@jpetitcolas thanks, i was able to change my server's behaviour for image uploads.
