### ISSUE TITLE
[Question] Is it possible to create items inline using ReferenceArrayInput?

### ISSUE THREAD

**Issue by AmrN** [marmelab/admin-on-rest#728]
I'm using ReferenceArrayInput for choosing tags, but the problem is that they need to be created beforehand in order to be able to select them, that means if I need to select a new tag for a post I have to first go to the tags resource page, click on create, fill form, submit and then finally go back to post and select the new tag...this process is obviously a bit tedious and not so user friendly.

So is there any way to use ReferenceArrayInput to create the tag if it doesn't exist from the posts resource form directly? If not, are there any plans to add such functionality? and how do you guys deal with this kind of problem? 
Thanks.

**Comment by wesley6j** [comment]
I think this may be job for another input `TextArrayInput` which does not exist yet. ;)

**Comment by fzaninotto** [comment]
@wesley6j is right, there is no built-in component for doing that in the core yet, so you'll have to create it yourself.

**Comment by AmrN** [comment]
@fzaninotto Yes, I understand. I tried making an implementation for that, please have a look at #735 
To me, it feels like this is a natural job for ReferenceArrayInput / SelectArrayInput, but feel free to suggest an alternative design.
