### ISSUE TITLE
Custom headers are not added to the request

### ISSUE THREAD

**Issue by dtitov** [marmelab/admin-on-rest#731]
Hi.

I followed the instructions to add some custom headers to jsonServerRestClient, but it didn't work. I've tried both ways:
```
const httpClient = (url, options = {}) => {
    if (!options.headers) {
        options.headers = new Headers({ Accept: 'application/json' });
    }
    // add your own headers here
    options.headers.set('X-Custom-Header', 'foobar');
    return fetchUtils.fetchJson(url, options);
}
```
and
```
const httpClient = (url, options) => {
    options.user = {
        authenticated: true,
        token: 'SRTRDFVESGNJYTUKTYTHRG'
    }
    return fetchUtils.fetchJson(url, options);
}
```
Here what do I see in Chrome Console. 

For the first approach:

> OPTIONS /rest/posts?_sort=id&_order=DESC&_start=0&_end=10 HTTP/1.1
> Host: localhost:8080
> Connection: keep-alive
> Access-Control-Request-Method: GET
> Origin: http://localhost:3000
> User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
> **Access-Control-Request-Headers: x-custom-header,content-type**
> Accept: */*
> DNT: 1
> Referer: http://localhost:3000/home
> Accept-Encoding: gzip, deflate, sdch, br
> Accept-Language: en-US,en;q=0.8,ru;q=0.6,uk;q=0.4

For the second one:
> OPTIONS /rest/posts?_sort=id&_order=DESC&_start=0&_end=10 HTTP/1.1
> Host: localhost:8080
> Connection: keep-alive
> Access-Control-Request-Method: GET
> Origin: http://localhost:3000
> User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
> **Access-Control-Request-Headers: authorization,content-type**
> Accept: */*
> DNT: 1
> Referer: http://localhost:3000/home
> Accept-Encoding: gzip, deflate, sdch, br
> Accept-Language: en-US,en;q=0.8,ru;q=0.6,uk;q=0.4

So, as you can see, the header-names are added to the 'Access-Control-Request-Headers', but they are not present as headers themselves and I can't get them on the server-side:

> header = host
> header = connection
> header = access-control-request-method
> header = origin
> header = user-agent
> header = access-control-request-headers
> header = accept
> header = dnt
> header = referer
> header = accept-encoding
> header = accept-language

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
React version: 15.5.4
admin-on-rest version: 1.1.0

I'm not sure if it's really a bug, but I'm following provided instructions, so...

**Comment by djhi** [comment]
We don't provide support through GitHub issues. If you need advice on using or debugging your own project based on admin-on-rest, please use [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest).

**Comment by dtitov** [comment]
Hmmm... I don't need an advice: I've already found the necessary snippet in your documentation. And since I copy-pasted it and it didn't work, that makes me think this functionality is buggy. Isn't it a reason for opening an issue?

**Comment by fzaninotto** [comment]
I think this is a CORS problem: you have to declare your custom headers on the server-side, using a `Access-Control-Allow-Headers` header in the response to the `OPTIONS` preflight request.

This has nothing to do with admin-on-rest, please google "CORS" for help on this matter.

**Comment by dtitov** [comment]
You are right, it was all about `OPTIONS`-request (it was prohibited by server-side security). Sorry for the issue.
P.S. But actually you can add this point to the docs to make it more clear.

**Comment by fzaninotto** [comment]
If we document HTTP and REST and CORS here, we'll end up writing too much documentation and no code. Instead, we assume that developers have basic knowledge of API centric architectures.
