### ISSUE TITLE
No redirect after saving in Edit

### ISSUE THREAD

**Issue by edorivai** [marmelab/admin-on-rest#733]
I would like to have the option to save changes, and stay on the Edit page. If I've read the source code correctly, this could be achieved by passing `false` as the last param to `crudUpdate`.

Would you guys be open to a PR that allows configuring `redirect` as a prop to `Edit`?

```js
<Edit redirect={false}>
    ...
</Edit>
```

**Comment by djhi** [comment]
Does #692 address your issue ?

**Comment by edorivai** [comment]
I don't think it does, in it's current form. But I'll ask around in that issue.

**Comment by fzaninotto** [comment]
#692 will address this issue.
