### ISSUE TITLE
[Feature Proposal] Inline Forms for creating items with ReferenceArrayInput / SelectArrayInput

### ISSUE THREAD

**Issue by AmrN** [marmelab/admin-on-rest#735]
Related to #728
I tried making this feature which allows for creating referenced items directly from the parent's create page:

![gifrecord_2017-06-07_032439](https://user-images.githubusercontent.com/11032286/26857629-9a05598a-4b34-11e7-9965-86b128d43689.gif)

## Changes made

- Modified `ReferenceArrayInput` to receive a form prop, which it renders inside a dialog when the user chooses to create a new item.

- Modified `SelectArrayInput` to add the create button to the choices if they don't contain an item matching the current text, and when that button is pressed it invokes a callback function passed as a property by `ReferenceArrayInput` which causes the dialog with the form to be displayed.

- Added a simple reducer to obtain the newly created record to add it to the list of chips values.

So what do you guys think, is this something you might be interested in adding to AOR?

**Comment by djhi** [comment]
Hey, thanks for taking time to try this. Can you make a PR ?

**Comment by iamsimakov** [comment]
Where new values be saved?

**Comment by djhi** [comment]
I'm closing this issue because this can be achieved in userland with custom inputs.

See https://codesandbox.io/s/pp0o4x40p0. The relevant code parts are:

* the `CreateCommentButton` component inside `src/posts.js`
* the `CommentCreate` component inside `src/comments.js` (note how we set the `defaultValue` prop on `SimpleForm`)

**Comment by furaiev** [comment]
Hi @djhi , could you please refresh the codesandbox?
Thank you.

**Comment by djhi** [comment]
@furaiev done :)

**Comment by furaiev** [comment]
@djhi could you please check the codesandbox. It seems like there are no mentioned feature.
Thank you

**Comment by HTMHell** [comment]
> I'm closing this issue because this can be achieved in userland with custom inputs.
> 
> See https://codesandbox.io/s/2393m2k5rj. The relevant code parts are:
> 
> * the `AddCommentButton` component inside `src/posts.js`
> * the `CommentCreate` component inside `src/comments.js` (note how we set the `defaultValue` prop on `SimpleForm`)

I'm facing the same issue, but there is no such feature in the link you provided.
Can you update the link?
