### ISSUE TITLE
Best approach to redirect user if is authenticate

### ISSUE THREAD

**Issue by thiagoterleski** [marmelab/admin-on-rest#737]
Hi! I need to check auth on some custom pages, for example, I created a custom LoginPage and I'd like to redirect the user if he tries to access login page already authenticated.
```
componentWillMout() {
  if (myHelper.isUserLogged()) {
   // redirect to dashboard
 }
}
 ```
In my opinion, the correct approach for handle this should be on Route config, following this example *(https://reacttraining.com/react-router/web/example/auth-workflow)*:
```
<Route {...rest} render={props => (
    fakeAuth.isAuthenticated ? (
      <Component {...props}/>
    ) : (
      <Redirect to={{
        pathname: '/login',
        state: { from: props.location }
      }}/>
    )
  )}/>
```

**The problem is I'm not using custom Login route because the original config for login is like:**
```
<Route exact path="/login" render={({ location }) => createElement(loginPage || Login, {
  location,
  title,
  theme,
})} />
```

This route is using some props defined in Admin.js.

Any idea or opinion about what would be the best way to do this?

Thanks!

**Comment by fzaninotto** [comment]
We don't provide support through GitHub issues. If you need advice on using or debugging your own project based on admin-on-rest, please use [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest).
