### ISSUE TITLE
Adding a header to all requests

### ISSUE THREAD

**Issue by Deliganli** [marmelab/admin-on-rest#74]
Hi all,

is there a way to add a header  ( such as X-Auth-Token) to all requests? My authorization depends on this header area so it needs to be put in the request.

Thanks in advance.

**Comment by mstmustisnt** [comment]
Hi, yes, you can do that. 
At least if you're using admin-on-rest components in custom app. In this case you can add any headers in your rest-client.

**Comment by djhi** [comment]
Yes you have to implement your own rest client

**Comment by Deliganli** [comment]
i have followed the guides, created the react app and the admin panel.

there is a scala rest api server of mine, so i needed to write a custom rest client for that. I did as in the [examples](https://github.com/marmelab/admin-on-rest/blob/master/docs/Tutorial.md) and for the sake of testing i put my custom header to the options variable in method `convertRESTRequestToHTTP`. Like this;

`options.headers['X-Auth-Token'] = token;`

Then i used this custom rest client on the requests, like this;

`<Admin restClient={scalaRestClient}>
              <Resource name="agents" list={AgentList}/>
  </Admin>`

but there weren't this header on my reqeust when i open the chrome dev console and check the request (Also my api server returns unauthorized which should be happen when there were no or invalid header, i am sure token is valid)

I am new to the react so sorry for terms i used above.

**Comment by djhi** [comment]
Can you put the rest client code on a codepen ?

**Comment by Deliganli** [comment]
[this](http://codepen.io/deliganli/pen/ozqvjY) is the rest client i am using, exactly same in the examples except the header part

**Comment by djhi** [comment]
If you look at the [fetch code](https://github.com/marmelab/admin-on-rest/blob/master/src/util/fetch.js#L8) you'll notice that authorization header like this will be handled for you, you just have to pass a `user` option like this:

```js
const token = "token";

const options = {
    user: {
        authenticated: true,
        token,
    },
};
```
