### ISSUE TITLE
Logout button placement and hash simple on url

### ISSUE THREAD

**Issue by hotrice** [marmelab/admin-on-rest#746]
Even though I have import BrowserRouter from react-router-dom and place `<BrowserRouter>
    <App />
  </BrowserRouter>` The URL still display a hash symbol. Another is how to place the logout button at the bottom of the sidebar like this https://marmelab.com/admin-on-rest/img/login.gif without using custom layout.

**Comment by fzaninotto** [comment]
For the hash on URL, the solution is in #741

For the logout button, duplicate of #525
