### ISSUE TITLE
how to edit and save resource image-url with ajax upload

### ISSUE THREAD

**Issue by gastrodia** [marmelab/admin-on-rest#748]
```javascript
                <ImageInput source="img"
                    label="Related pictures" accept="image/*"
                    input={{
                        onChange: function (files) {
                            var that = this;
                            uploadFiles('http://localhost:3001/upload', { file: files[0] }, (err, res) => {
                                var url = res.url;
                                //and then how to update source img  ????
                            })
                        }
                    }}

                >
                    <ImageField source="img" title="title" />
                </ImageInput>
```

**Comment by fzaninotto** [comment]
The admin-on-rest core team doesn't provide support or advice on debugging your own project. We need to focus on writing documentation, fixing bugs, and adding new features. 

Instead, we've decided to offload that charge to the community, by moving support to [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest). Ask your question there, you will find helpful people (sometimes from the core team, too). Besides, the response to your question will be easy to find for future developers with a similar problem.

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise. 

http://stackoverflow.com/questions/tagged/admin-on-rest
