### ISSUE TITLE
<Show> lacked refresh and translate props

### ISSUE THREAD

**Issue by leesei** [marmelab/admin-on-rest#749]
Comparing to `<Edit>`:
1. <Show> did not have `this.refresh()` for action component
    I'm not sure if `state.key` mechanism is needed.
2. `translate` not passed to `children`

Aside, now that all the layouts support `actions` prop, should we pass all `has*` bools to it so we can reuse the action component?

Please give direction on 1 and I'll submit PR.

**Comment by leesei** [comment]
BTW, I think 2 is critical and should land in 1.2.0.

**Comment by fzaninotto** [comment]
1. isn't critical, it's a nice to have. 2. Is more urgent. Feel free to open 2 different PRs, with a priority for 2.

**Comment by wesley6j** [comment]
Please remove `import translate from '../../i18n/translate';` from TabbedShowLayout and TabbedForm after 1.
