### ISSUE TITLE
Syntax error: Unexpected token

### ISSUE THREAD

**Issue by bluengreen** [marmelab/admin-on-rest#75]
Great work BTW. This actually has helped me learn tons about react. After spending weeks playing with other peoples boiler plates, this got me going where I could stay interested enough to learn more.  

Firstly I was trying to get the theming working which sadly didn't do anything. I included the themes and pass into the Admin component but no joy. 

I figured I'd go ahead and follow the custom layout docs. But then after copying the code for Notifications, Title, Menu, Layout I get this error: 
```
Failed to compile.

Error in ./src/Notification.js
Syntax error: Unexpected token (23:28)

  21 |             message={this.props.message}
  22 |             autoHideDuration={4000}
> 23 |             onRequestClose={::this.handleRequestClose}
     |                             ^
  24 |             bodyStyle={style}
  25 |         />);
  26 |     }

 @ ./src/myLayout.js 32:20-45
```

Apologize in advance if its obvious but I am new to ES6. Not sure what :: is doing and its kinda impossible to google such a thing. Could anyone help point me in the right direction?  

Thanks in advance.

**Comment by djhi** [comment]
You need to configure babel correctly for it to handle this syntax. It's a shortcut for `this.handleRequestClose.bind(this)`

**Comment by bluengreen** [comment]
Thanks for the insight. I installed like the docs as suggested - using create-react-app. What is the correct way to configure babel? Doesn't create-react-app configure babel when creating a new app? Also, could this be the reason why theming isn't working correctly? 

Thanks again.

**Comment by djhi** [comment]
Can you share your webpack configuration in a code pen along with the App component showing how you specify the theme ?
