### ISSUE TITLE
Filter form - fields are rendered twice

### ISSUE THREAD

**Issue by hagaisela** [marmelab/admin-on-rest#750]
Hi,
I want to display a list with a filter, and the filter fields should be displayed when the list appears without an "add filter" button. I am trying to do this on the posters galore example, I changed all the filter fields to alwaysOn and added "context=form" to the filter definition. After these changes the list appears with the form but all the filter fields are rendered twice, see attached screenshot.

[https://i.stack.imgur.com/V1TJD.png](url)

**Comment by wesley6j** [comment]
Not sure how you managed to do this `added "context=form"` but you are not supposed to set `context` by yourself.

**Comment by hagaisela** [comment]
Do you have another suggestion how to display a filter form without the "Add Filter" Button?
This is from Filter.js, maybe I was mistaken to think that I should add "context='form'"

`Filter.propTypes = {
    children: PropTypes.node,
    context: PropTypes.oneOf(['form', 'button']),
    debounce: PropTypes.number.isRequired,
    displayedFilters: PropTypes.object,
    filterValues: PropTypes.object,
    hideFilter: PropTypes.func,
    setFilters: PropTypes.func,
    showFilter: PropTypes.func,
    resource: PropTypes.string.isRequired,
};
`

**Comment by wesley6j** [comment]
set `alwaysOn` for all the inputs inside `Filter`:
```jsx
const PostFilter = ({ ...props }) => (
    <Filter {...props}>
        <TextInput label="post.list.search" source="q" alwaysOn />
        <TextInput source="title" defaultValue="Qui tempore rerum et voluptates" alwaysOn />
    </Filter>
);
```

**Comment by hagaisela** [comment]
Works. Thanks!
