### ISSUE TITLE
How to Change value of DisabledInput when ReferenceInput change?

### ISSUE THREAD

**Issue by SkyVento** [marmelab/admin-on-rest#751]
I have a business when change a ReferenceInput value the total amount will re-calculate. How can I do it?

**Comment by wesley6j** [comment]
If your problem is that `DisabledInput`'s value does not reflect your form state, then it has been fixed  #729.

**Comment by SkyVento** [comment]
can you give me the sample to set value for DisabledInput when ReferenceInput onChange event?
Thanks!

**Comment by wesley6j** [comment]
I had a similar situation. I used redux-form's `formValueSelector` to get related values from the form, do the calculation inside renderer. Because the result is not inside form state, I could not use any input component.

You should probably ask in stackoverflow.

**Comment by fzaninotto** [comment]
The admin-on-rest core team doesn't provide support or advice on debugging your own project. We need to focus on writing documentation, fixing bugs, and adding new features. 

Instead, we've decided to offload that charge to the community, by moving support to [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest). Ask your question there, you will find helpful people (sometimes from the core team, too). Besides, the response to your question will be easy to find for future developers with a similar problem.

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise. 

http://stackoverflow.com/questions/tagged/admin-on-rest
