### ISSUE TITLE
Filter, Date Range

### ISSUE THREAD

**Issue by Reymor334** [marmelab/admin-on-rest#753]
How to make range of date for filter?(Date since, date before)

**Comment by fzaninotto** [comment]
The admin-on-rest core team doesn't provide support or advice on debugging your own project. We need to focus on writing documentation, fixing bugs, and adding new features. 

Instead, we've decided to offload that charge to the community, by moving support to [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest). Ask your question there, you will find helpful people (sometimes from the core team, too). Besides, the response to your question will be easy to find for future developers with a similar problem.

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise. 

http://stackoverflow.com/questions/tagged/admin-on-rest

**Comment by RWOverdijk** [comment]
@Reymor334 Did you find your answer? I'm trying to do the same thing.

@fzaninotto I know that issues aren't for solving this, but I'm planning on contributing to this project, and filters are part of that. Any pointers (or documentation) on filters, in general, would be greatly appreciated.

**Comment by omeraplak** [comment]
@RWOverdijk i have a question for dateinput filters.

I want to add timestamp date range filter example sqlQuery

select * from reservation where
between '2018-02-15' and '2018-02-16'

but i can't find how can do this? Have you an idea?

Thanks

**Comment by RWOverdijk** [comment]
@omeraplak That really depends on the server you're using.

**Comment by omeraplak** [comment]
@RWOverdijk 
Thanks for reply,
I use [postgrest](https://postgrest.com/en/v4.4/) and [aor-postgrest-client](https://github.com/tomberek/aor-postgrest-client) for driver.

**Comment by RWOverdijk** [comment]
@omeraplak I'm sorry, I didn't mean I'll help you build a server. I meant to just say that. I made 2 fields and sent those to the server. The server handles it properly.

Good luck :)

**Comment by omeraplak** [comment]
@RWOverdijk 
Okay i can handle this on server but i hava a question.

I can write custom field component (for daterange picker) and  custom endpoint on server but how can i update DataGrid data?. I think i can do this by updating with admin on rest's redux state. Is it correct way for this? Do you have any idea?

Thanks

**Comment by djhi** [comment]
This type of questions should be posted on StackOverflow :)

**Comment by RWOverdijk** [comment]
@omeraplak By dispatching a refresh for example. If you write a custom filter (regular one) and use the same base it should just work without touching anything. But @djhi is right.
