### ISSUE TITLE
[Question] SingleAPI support

### ISSUE THREAD

**Issue by Phocea** [marmelab/admin-on-rest#755]
Hello,

Are you planning to allow calling singleAPI for bulk operation, as existing in ng-admin?
Thanks!

**Comment by djhi** [comment]
Hi @Phocea ! It's nice to see you here too :)
See #65

**Comment by Phocea** [comment]
Thanks ... Dont tell @fzaninotto that I keep dropping by ;)

**Comment by fzaninotto** [comment]
I saw you!

**Comment by djhi** [comment]
![](https://media.giphy.com/media/fbBDhlw5pPAYg/giphy.gif)
