### ISSUE TITLE
Custom Notification Component Support

### ISSUE THREAD

**Issue by kodepareek** [marmelab/admin-on-rest#757]
Hello 

The snackbar component is too small for some kind of errors that I need to display to users. 

It appears that implementing a custom notification component will need a custom Layout which would be a lot of work. Would be super if Notification component could also be set. 

I am envisioning something like this. 

1) Set the notification type in the calling action. 
2) Create a switch notification based on AOR-Dependent-Input - or just a switch

// in custom notification
```
import defaultNotification from 'admin-on-rest'
import customNotification from './customNotification.js

const Notification = (props) => {
  let type = props.type
  let component;
  switch (type) {
    case "custom":
      component = ( < CustomNotification props={props} /> )
      break;
    default:
      component = (
        <Notification props={props} />
        )
      break;
  }
  return component
}


``` 

Above can now be passed to Admin which passes it to Layout. 

Above is just an idea I had. It may be far from ideal. Would just find the functionality useful. 

Thanks a lot for Admin-On-Rest.

**Comment by fzaninotto** [comment]
Hi, that's a nice idea, but I don't want to complexify the `<Admin>` component with even more props. The ability to provide a custom Layout was thought for the kind of requirement you're describing.

**Comment by kodepareek** [comment]
I see. Fair point.
