### ISSUE TITLE
Disable missing Translation Warnings?

### ISSUE THREAD

**Issue by thochi** [marmelab/admin-on-rest#758]
Is it possible to disable the translation warnings if we don't use i18n?

**Comment by djhi** [comment]
Not possible currently. Polyglot does support allowing undefined translations (see its [options](https://github.com/airbnb/polyglot.js#options-overview)) however. This would requires an additional prop to disable custom translations.

This babel plugin might be useful: [babel-plugin-transform-dev-warning](https://github.com/oliviertassinari/babel-plugin-transform-dev-warning)

**Comment by fzaninotto** [comment]
Which translation warnings are you seeing? It must be on your custom components, because aor components don't throw translation warnings in case of missing translation for a field label. It uses the (non-documented- default translation everywhere:

```js
translate(label, { _: label }
```

As for the interface labels ("Save", "Filter", etc), they must always be in your translation dictionary. If they are not, that's a bug, and the warning should not be silenced.

**Comment by onka13** [comment]
Temporary you can override console.error.

```
var originalLog = console.error
console.error = function log(...args) {
	if (args.length > 0 && typeof args[0] === "string" && /^Warning: Missing translation/.test(args[0])) {
		return
	}
	originalLog.apply(console, args)
}
```

**Comment by fvoordeckers** [comment]
Solved it by adding a custom i18nProvider that allows missing keys:
```
const i18nProvider = polyglotI18nProvider(locale => i18nMessages[locale], 'en', { allowMissing: true });

<Admin
    i18nProvider={i18nProvider}
    ...
 >
```

More details: https://marmelab.com/react-admin/Translation.html
and: https://www.npmjs.com/package/node-polyglot#options-overview

**Comment by caiquejjx** [comment]
Which package gives me the "i18nMessages" instance?

**Comment by fvoordeckers** [comment]
> Which package gives me the "i18nMessages" instance?

@caiquejjx  That's a dict you build containing all the locales you want to support

**Comment by dkocich** [comment]
it would be good to see one line entries instead of printing the whole stack trace with each one missing translation
