### ISSUE TITLE
Field for <VideoInput>

### ISSUE THREAD

**Issue by ceddyb** [marmelab/admin-on-rest#765]
I went through your docs but couldn't find a field for videos, 

Would you kindly share some sample <VideoInput> component and maybe add it to the library later

**Comment by djhi** [comment]
A `FileInput` component will be released in next version. It's a more generic version of the `ImageInput` component.

You'll only need to implement a custom `VideoField` component. The [ImageField](https://github.com/marmelab/admin-on-rest/blob/master/src/mui/field/ImageField.js) should be a good starting point.

Then you''ll have to pass this `VideoField` component as a child for the preview with the [FileInput](https://github.com/marmelab/admin-on-rest/blob/master/src/mui/input/FileInput.js) component.
