### ISSUE TITLE
implement create user form

### ISSUE THREAD

**Issue by mnlbox** [marmelab/admin-on-rest#766]
Hi,
I try to implement a page for create new users. I want to add two fields for `Password` and `Repeat Password` Can you guide me. I use `<TextInput source="password" type="password" validate={ required }/>` for `Password` field but what about `Repeat Password` ? 
Please help me to finish it.

**Comment by djhi** [comment]
The admin-on-rest core team doesn't provide support or advice on debugging your own project. We need to focus on writing documentation, fixing bugs, and adding new features. 

Instead, we've decided to offload that charge to the community, by moving support to [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest). Ask your question there, you will find helpful people (sometimes from the core team, too). Besides, the response to your question will be easy to find for future developers with a similar problem.

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise. 

http://stackoverflow.com/questions/tagged/admin-on-rest

**Comment by mnlbox** [comment]
OK man. I asked it there. 😉
