### ISSUE TITLE
multi-part example

### ISSUE THREAD

**Issue by ceddyb** [marmelab/admin-on-rest#769]
Is it possible to write a small function for a custom restClient that loops through specific fields and turns them to multi-part data when form submitted.

For example, this function can have an array of defined fields where it needs to loop.

     let finputs = ["first_field", "second_field", "Other_fields"];

     function covertTomutiPart(finput)

We can add this to our restClient?

**Comment by djhi** [comment]
The admin-on-rest core team doesn't provide support or advice on debugging your own project. We need to focus on writing documentation, fixing bugs, and adding new features. 

Instead, we've decided to offload that charge to the community, by moving support to [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest). Ask your question there, you will find helpful people (sometimes from the core team, too). Besides, the response to your question will be easy to find for future developers with a similar problem.

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise. 

http://stackoverflow.com/questions/tagged/admin-on-rest

**Comment by sbatururimi** [comment]
@ceddyb Did you get a chance to use a multipart for data to send a request?

**Comment by kopax** [comment]
How do I set the form type ?
