### ISSUE TITLE
[Question]: How to transform values between store and form?

### ISSUE THREAD

**Issue by anuragagarwal561994** [marmelab/admin-on-rest#779]
I have an edit form where I require some extra fields like confirm_password, but my server doesn't accept these fields. Also there can be certain cases where I want to transform the keys of the form values to something else as required by my server. How would one do these transformations?

**Comment by djhi** [comment]
The admin-on-rest core team doesn't provide support or advice on debugging your own project. We need to focus on writing documentation, fixing bugs, and adding new features. 

Instead, we've decided to offload that charge to the community, by moving support to [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest). Ask your question there, you will find helpful people (sometimes from the core team, too). Besides, the response to your question will be easy to find for future developers with a similar problem.

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise. 

http://stackoverflow.com/questions/tagged/admin-on-rest
