### ISSUE TITLE
Adding custom middleware

### ISSUE THREAD

**Issue by anuragagarwal561994** [marmelab/admin-on-rest#785]
Is there a way to add custom store middleware?
Right now I making custom Admin component to do so.

**Comment by djhi** [comment]
No, there isn't. Can you explain your use case ?

**Comment by anuragagarwal561994** [comment]
So when I am building my application I require logger or it becomes very confusing while managing states. For adding a logger right now I made an exact copy of the Admin from the source code and then just added `redux-logger` in it. There can be other middlewares which can be used in similar way.

**Comment by djhi** [comment]
For the logger part, isn't the redux devtools enough ?
![screen](http://i.imgur.com/YMGF85J.png)

**Comment by fzaninotto** [comment]
If you need a custom store, you'll have to swap the `<Admin>` component for a component of your own. Since `<Admin>` only has like 5 components, it shouldn't be too hard.

**Comment by llioor** [comment]
@fzaninotto do you have a good example for implementing the whole admin component with in a custom app? On docs I can see just AppBar and Routes example but when I try to implement the "MyLayout" things became to be complicated.
