### ISSUE TITLE
Filter in <ReferenceInput> not taken into account when <AutocompleteInput> is filled

### ISSUE THREAD

**Issue by remi13131** [marmelab/admin-on-rest#786]
When using ```<ReferenceInput>```, the initial list is filtered as intended. 
For instance : 

```
<ReferenceInput
     source="post_id"
     reference="posts"
     filter={{ is_published: true }}>
    <AutocompleteInput optionText="title" />
</ReferenceInput>
```

Will retrieve the list of published books when ```AutocompleteInput``` is not filled, making this request : 

```/posts?is_published=true``` 

as soon as we click on the input. This is the expected behavior. 

However, when text is typed in the  ```AutocompleteInput```, this filter is no longer taken into account and unpublished book will appear in the list. In fact, this is because the request made is that one : 

```/posts?q=FooBar``` 

Instead of that one :

```/posts?is_published=true&q=FooBar``` 

The most annoying with this unexpected behavior is that when the whole search text is erased, the full list of books (wether published or unpublished) will be retrieved and displayed, instead of acting as the initial list (first example), making this request : 

```/posts?q=```

Instead of :

```/posts?is_published=true&q=``` 

or even better when no text, as what the initial click fire

```/posts?is_published=true```

**Comment by remi13131** [comment]
Here a gif, using the example app from next, changing comments resource ```<Create>``` with an ```<AutocompleteInput>``` in ```<ReferenceInput>``` instead of ```<SelectInput>``` : 

```
export const CommentCreate = ({ ...props }) => (
    <Create {...props}>
        <SimpleForm defaultValue={{ created_at: new Date() }} >
            <ReferenceInput source="post_id" reference="posts" filter={{commentable: true}} allowEmpty validation={{ required: true }}>
                <AutocompleteInput optionText="title" />
            </ReferenceInput>
            <DateInput source="created_at" />
            <LongTextInput source="body" />
        </SimpleForm>
    </Create>
);
```
I set ```filter={{commentable: true}}``` so for example at first the 2 post that are not commentable in data.js that have title _Culpa possimus quibusdam nostrum enim tempore rerum odit excepturi_ and _Maiores et itaque aut perspiciatis_ are not in the list. Hoever when I type "Mai" I will find the latter. 

Then when I delete the text in the input, I find back those two posts that are not commentable. Confusing.

![out](https://user-images.githubusercontent.com/11832241/27441707-a37a6866-576e-11e7-8970-dac7e36afc4a.gif)

**Comment by fzaninotto** [comment]
Confirmed, this is a serious bug.
