### ISSUE TITLE
restclient header check should be case insensitive

### ISSUE THREAD

**Issue by jsimonetti** [marmelab/admin-on-rest#79]
The current available rest clients use a reponse header to extract the total amount

-  https://github.com/marmelab/admin-on-rest/blob/master/src/rest/jsonServer.js#L93
and
- https://github.com/marmelab/admin-on-rest/blob/master/src/rest/simple.js#L106

As there is no quarantee that headers are always lower case or canonical, this should check for the header in a case insensitive way as not to break.

FYI Golang's stdlib actually automatically changes headers to use Canonical MIME format.
https://golang.org/pkg/net/textproto/#CanonicalMIMEHeaderKey

**Comment by fzaninotto** [comment]
We're now exposing the `Headers` object directly. Its `get()` method is case-insensitive.
