### ISSUE TITLE
Admin component should re-render when a correct login occurs.

### ISSUE THREAD

**Issue by torresandres** [marmelab/admin-on-rest#790]
So I working with users with specific roles and permissions. Two of this roles have is own Dashboard but the rest doesn't. So basically i'm doing something like this on my `App.js`:

    const AdminProps = {
      title: <Header />,
      theme: getMuiTheme(SnapbackTheme),
      locale: 'en',
      restClient,
      authClient: AuthClient,
      loginPage: LoginPage
    }

    let AppLayout = <Admin {...AdminProps } />

    if (userRoleIs(USER_ROLE_1)) {
      AppLayout = (
        <Admin {...AdminProps } dashboard={CustomDashboardForThisRole}>
          <Resource name="resource1" list={resource1List} />
        </Admin>
      )
    }
      
    if (userRoleIs(USER_ROLE_2)) {
      AppLayout = (
        <Admin {...AdminProps }>
          <Resource name="resource1" list={resource1List} />
        </Admin>
      )
    }

    return AppLayout

As you can see, depending of the user that is logged in I can choose which props `Admin` should have. This is working, kind of, the problem with this is that when you log in with a user and find out which role has I don't have a proper way to update the `Admin` props and re-render it.

That causes a empty content screen when logging in with users that have custom dashboard until I refresh the page and `Admin` render correctly with the correct dashboard for the user.

My ugly workaround at the moment: a `window.location.reload()` when the login was successful but you can see the empty content screen for a second and it looks awful.

My question is: Is there a proper way to re-render the `Admin` component from the `authClient`?

Thanks in advance! 👋🏼

**Comment by djhi** [comment]
The admin-on-rest core team doesn't provide support or advice on debugging your own project. We need to focus on writing documentation, fixing bugs, and adding new features. 

Instead, we've decided to offload that charge to the community, by moving support to [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest). Ask your question there, you will find helpful people (sometimes from the core team, too). Besides, the response to your question will be easy to find for future developers with a similar problem.

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise. 

http://stackoverflow.com/questions/tagged/admin-on-rest

**Comment by torresandres** [comment]
I asked a really simple question at the end strongly related to the framework and I wondering if there is a more simple solution and extending/ejecting from admin-on-rest.

**Comment by fzaninotto** [comment]
Yes, it's a simple question, and StackOverflow is the best place to ask it. This issue tracker is for issues (like bugs).
