### ISSUE TITLE
<ReferenceArrayInput> Documentation error

### ISSUE THREAD

**Issue by remi13131** [marmelab/admin-on-rest#796]
In the Docs, I can read about [```<ReferenceArrayInput>```](https://marmelab.com/admin-on-rest/Inputs.html#referencearrayinput)

> Then <ReferenceArrayInput> would fetch a list of tag resources from these two calls:
> ```http://myapi.com/tags?id=[1,23,4] ```
> ```http://myapi.com/tags?page=1&perPage=25```

However the first assessment is not true since when using it, I have the following calls that are made (using jsonServerRestClient) : 
```http://myapi.com/tags?page=1&perPage=25```
```http://myapi.com/tags/1 ```
```http://myapi.com/tags/23```
```http://myapi.com/tags/4 ```

**Comment by wesley6j** [comment]
Because [json-server](https://github.com/typicode/json-server) does not support `GET_MANY`. See [this](https://github.com/marmelab/admin-on-rest/blob/master/src/rest/jsonServer.js#L118).

**Comment by remi13131** [comment]
Ah yes indeed ! Thanks for pointing this :) 

Then it is quite confusing to give examples using the final request instead of the REST request only, since all the different REST client might implement this differently.

**Comment by fzaninotto** [comment]
Right, but we must somehow cross the gap between what the user sees and what the user knows (REST). Tanks for the report anyway.
