### ISSUE TITLE
Support React 15.6

### ISSUE THREAD

**Issue by dunglas** [marmelab/admin-on-rest#802]
Would it be possible to support React 15.6? It's the current version installed with `create-react-app` and not supporting it creates problems such as https://github.com/api-platform/admin/issues/26.

If you're ok to build Admin On Rest with this new version, I can open a PR.

**Comment by wesley6j** [comment]
I think you need to wait for callemall/material-ui#7129.

**Comment by oliviertassinari** [comment]
@wesley6j Material-UI support for that version seems to be just fine.

**Comment by wesley6j** [comment]
Tested react@15.6.1 in AOR's example, nothing wrong so far.

**Comment by FDiskas** [comment]
https://github.com/callemall/material-ui/issues/7129#issuecomment-314545711

**Comment by oliviertassinari** [comment]
We are going to support react@16 in material-ui@0.19.0

**Comment by fzaninotto** [comment]
aor 1.3.2 supports react 15.6.
