### ISSUE TITLE
how to do unit test

### ISSUE THREAD

**Issue by heinhoang** [marmelab/admin-on-rest#803]
I try to test Login.js (https://github.com/marmelab/admin-on-rest/blob/master/src/mui/auth/Login.js) as follow but it's not work:
```js
import { shallow } from 'enzyme';
import expect from 'expect';
import configureStore from 'redux-mock-store';

const mockStore = configureStore();
const initialState = {
    locale: 'en',
};
const messages = {
    en: {
        aaa: 'bbb',
    },
};
const store = mockStore(initialState);
const context = {
    store,
    locale: 'en',
    translate: f => (f),
};
let container;

describe('<Login /> test', () => {
    beforeEach(() => {
     container = shallow(<Login />, {context});
    });

    it('=> should render itself & children', () => {
        expect(container.length).toEqual(1); // this work
        expect(container.find('form').length).toEqual(1); // not work
        expect(container.find('RaisedButton').length).toEqual(1); // not work
    });
});
```
how to do unit test on Login.js and similar components?

**Comment by fzaninotto** [comment]
The admin-on-rest core team doesn't provide support or advice on debugging your own project. We need to focus on writing documentation, fixing bugs, and adding new features. 

Instead, we've decided to offload that charge to the community, by moving support to [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest). Ask your question there, you will find helpful people (sometimes from the core team, too). Besides, the response to your question will be easy to find for future developers with a similar problem.

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise. 

http://stackoverflow.com/questions/tagged/admin-on-rest
