### ISSUE TITLE
Add Label to <ReferenceField>

### ISSUE THREAD

**Issue by remi13131** [marmelab/admin-on-rest#804]
When using ```<ReferenceField>```, it is rendering fine with ```<Datagrid>``` and the right title is added to the column. 

However, in ```<Edit>``` or ```<Show>```, where it can be useful to make a link to an associated resource, no Label is added to the field and this results in a pretty ugly output : 
![image](https://user-images.githubusercontent.com/11832241/27684649-2648100c-5ccb-11e7-8556-9c1e9432276c.png)

I have the same result whether I add a ```label="Post"``` prop to ```<ReferenceField>``` or not.

I think this would be good to have a label when it is specified.

**Comment by bilguun** [comment]
Had a same problem. If you add `<TextField source="post_id" />` before the `<ReferenceField>` it looks little bit better :D

**Comment by pimschaaf** [comment]
Define addLabel on the ReferenceField as follows:

```
    <ReferenceField label="Type" source="id" reference="resource" addLabel>
        <TextField source="field" />
    </ReferenceField>
```

**Comment by remi13131** [comment]
Oh gosh I feel dumb, I had read the code and thought that something was not working because it seemed to me that the Label was taken into account in the code but somehow not working. 

I understand now that I was missing something. 

However, as it wasn't in the Docs, I made a PR to document this prop that apparently many were missing like me !

**Comment by christhomas** [comment]
I have a similar problem now, where in the edit mode I get the label, but in the show mode I don't get the label. I've already added addLabel to my element. Any ideas?
