### ISSUE TITLE
Add 'onEmpty' property to the Field components

### ISSUE THREAD

**Issue by mjanos10** [marmelab/admin-on-rest#805]
Hi!

First, let me say I love what you've done here. This framework is amazing!

However I was thinking it would be nice if an 'onEmpty' (or something like that) property would be added to some Fields, like DateField, or TextField and so on.

The use case for this would be pretty simple. When we don't have a value for something, we might want to show a standard message to the user:
For example I have a task, that has an endDate attribute, and when it's set I'd like to show them the date in a DateField. But when it's not set (i.e. the task is not closed yet), I would want to show a message to the user, something like "This task is not yet closed".

Like I said, it would'nt be probably too much work to do this (since I'm doing this already) and it would be a great additional feature of this repo!

Thanks in advance!

**Comment by fzaninotto** [comment]
Thanks, we're happy to hear that our work helps you and that you like it!

You can already do this by *composing* aor components with your own components. For instance:

```jsx
const EmptyOrField = ({ message, record, source, children, ...rest }) => record[source] ? React.cloneElement(children, { record, ...rest }) : <span>{message}</span>;

const PersonList = (props) => (
    <List {...props}>
        <Datagrid>
            <EmptyOrField source="last_name" message="No name">
                <TextField source="last_name" />
            </EmptyOrField>
        </Datagrid>
    </List>
);
```

Our objective is not to build components that cover all your needs, but to build components that are easy to use and compose with your own components to cover all your needs ;)

**Comment by djhi** [comment]
https://github.com/marmelab/aor-dependent-input ?
