### ISSUE TITLE
Add support for accessors on <Fields>

### ISSUE THREAD

**Issue by temsa** [marmelab/admin-on-rest#807]
let imagine I have this kind of data :
```
{
    id: 123,
    firstName: 'John',
    lastName: 'Doe'
}
```

I'd want to have a computed `fullName` column in my datagrid.

I can use what is described in the documentation, a custom Field : https://marmelab.com/admin-on-rest/Fields.html#writing-your-own-field-component

```
import React from 'react';
import { List, Datagrid, TextField } from 'admin-on-rest';

const FullNameField = ({ record = {} }) => <span>{record.firstName} {record.lastName}</span>;
FullNameField.defaultProps = { label: 'Name' };

export const UserList = (props) => (
    <List {...props}>
        <Datagrid>
            <FullNameField source="lastName" />
        </Datagrid>
    </List>
);
```

but I have both this one and different case, and one thing I've been trying to find in the api, is a way to compute directly for any type of field the data.

Here was originally what I wrote as an api (d3 style: you can either have functions or values), I expected something like that could work, given a text value was working:
```
<TextField source={(record)=>`${record.firstName} ${record.lastName}`}/>
```

Is this something that could be done ? Or is there anything else that could manage the same kind of behavior ?

**Comment by temsa** [comment]
:+1: works well for text, but not as well for another case with an image, I have a `/path/to/image.jpg` to transform in `http://server.com/path/to/image.jpg`, I'll still use the `<FunctionField>` but being able to use a function as source (etc.) would still be better more comfortable and more natural imo, what do you think ?

Would you be open to a PR for implementing it ?

**Comment by fzaninotto** [comment]
You already have 2 options to deal with that case:

1. Write a custom component, which can be a simple wrapper on top of the `<ImageField>` component
2. Transform the data when receiving it, in your REST client

We won't add a third way.
