### ISSUE TITLE
404 error on datagrid stop other references

### ISSUE THREAD

**Issue by chemitaxis** [marmelab/admin-on-rest#811]
Hi, I'm using the version 1.2.0 and now we have a problem:

```
<List title="List of Invoices" {...props} filters={<InvoiceFilter />}>
    <Datagrid>
      <TextField label="InvoiceId" source="InvoiceId" />
      <DateField source="DateInvoce" label="Date Invoice" />
      <TextField label="Payer Email" source="PayerEmail" />
      <TextField label="Total" source="Total" />
      <ReferenceField
        label="User"
        source="IdUser"
        reference="users"
        linkType="show"
      >
        <TextField source="UserName" />
      </ReferenceField>
      <ShowButton label="View Invoice" />
    </Datagrid>
  </List>;
```

If I don't have a record in my database with this IdUser, or my REST API return a 404 in the reference field, the ReferenceField stop looking for the others IdUser referenced.

Any ideas? Thanks.

**Comment by chemitaxis** [comment]
Hi! Can I help with this issue? Thanks ;)

**Comment by fzaninotto** [comment]
Is it a regression dating from 1.2? If yes, it can be caused either by #647 or #596.

**Comment by chemitaxis** [comment]
Exactly, in the last version we don't have this problem... thanks

**Comment by fzaninotto** [comment]
Just to make sure I understand:

- The datagrid displays references up to a certain line, and then, once it hits the line where `IdUser` is null, it stops looking for the reference on the following lines?
- Do you see an error message in the console?
- Which rest client are you using?
- Which is the last version where it used to work?

**Comment by chemitaxis** [comment]
Hi @fzaninotto here you have my responses:
- Exactly. 
- crudResponse.js:145 Not Found
- jsonServerRestClient
- I'm not totally sure... but I think that in 1.0.0 all works fine.

Thank you so much!

**Comment by chemitaxis** [comment]
I have test to add alloEmpty too, but it not works.

**Comment by chemitaxis** [comment]
Hi, any news about this issue? Thanks

**Comment by djhi** [comment]
Can't reproduce on `1.3.4` anymore. Feel free to reopen if needed
