### ISSUE TITLE
Access row value in DataGrid component

### ISSUE THREAD

**Issue by cmrabet** [marmelab/admin-on-rest#814]
In my Datagrid component, I'd like to make some logic operations based on the value that a certain column has. I have found no way to reference the current row values, record doesn't seem to be passed to the fields, nor data or resource. How can do this?

This is what I'm trying to achieve:

 ```
 <List title="Sales Inquiries" filter={{ request_type: 'sales' }}  {...props}>
      <Datagrid>
          <TextField source="id" />
          <TextField source="firstname" label="First Name" />
          <TextField source="lastname" label="Last Name" />
          <TextField source="company" />
          <TextField source="email" />
          <DateField source="timestamp" label="Received" />

          {processed &&
            <ReferenceField label="Processed By" source="processedBy_id" reference="Users">
              <TextField source="username" />
            </ReferenceField>
          }

          <ShowButton />
      </Datagrid>
  </List>
```

Sometimes the records might not be "processed" and therefore the ReferenceField will show nothing but a loading progress bar (because the source is null). I'd like to hide it based on the source value.

Thanks.

**Comment by fzaninotto** [comment]
The admin-on-rest core team doesn't provide support or advice on debugging your own project. We need to focus on writing documentation, fixing bugs, and adding new features. 

Instead, we've decided to offload that charge to the community, by moving support to [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest). Ask your question there, you will find helpful people (sometimes from the core team, too). Besides, the response to your question will be easy to find for future developers with a similar problem.

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise. 

http://stackoverflow.com/questions/tagged/admin-on-rest

**Comment by cmrabet** [comment]
My question is very generic and simple: how to access to the row data inside the Datagrid object?

I see other people asking here, that's why I posted my question too.

**Comment by fzaninotto** [comment]
Your question is perfectly valid, but as stressed out in the [Contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md) that was prominently displayed when you opened that issue, the right place to ask it, for this project, is StackOverflow.

We appreciate that you take the time to reach the community to get help. Please don't be offended if we ask you to do it in a website that supports voting, searching, gamification, smart notifications, and with good SEO - unlike GitHub.
