### ISSUE TITLE
Warning: Each child in an array or iterator should have a unique "key" prop.

### ISSUE THREAD

**Issue by cmrabet** [marmelab/admin-on-rest#815]
I get this warning whenever I'm using the Datagrid component.

Any clue why the key property of each row is not properly populated? And yes, my REST Api is returning the record's ID. As a matter of fact, I'm displaying it in the same Datagrid, see picture attached (ID column).

![image](https://user-images.githubusercontent.com/5342225/27773385-792ea448-5f46-11e7-82d6-f3f6b31c7965.png)

**Comment by kamalk333** [comment]
I am facing the same problem. What's the fix, can you please share?
