### ISSUE TITLE
FileInput clears files when using multiple on drop

### ISSUE THREAD

**Issue by natrim** [marmelab/admin-on-rest#822]
When you use multiple, then the files list get cleared and displays only the droped file.

Gets cleared in call of onChange:
https://github.com/marmelab/admin-on-rest/blob/master/src/mui/input/FileInput.js#L79

to reproduce: 

use `<FileInput source="files" label="common.files" accept="application/pdf" multiple>`
add and save some files, then open edit to see the saved files and try to add one more - it will clear the list

(which is bad if you use the list to delete files as it deletes all files)

**Comment by djhi** [comment]
Can't reproduce this bug. Can you provide a repository reproducing it ?

**Comment by natrim** [comment]
hm, tried it again now, and it seems to have been fixed between my report and now, so i am closing it
