### ISSUE TITLE
RadioButtonGroupInput does not apply value after CREATE redirects to EDIT page

### ISSUE THREAD

**Issue by qoalu** [marmelab/admin-on-rest#823]
0. Have a RadioButtonGroupInput with 2 Radio Inputs for a resource
1. Create an entry
2. Get redirected to Edit page for new entry that has been created

**Expected result:**
All fields are prefilled with defined values

**Actual result:**
The RadioButtonGroupInput does not prefill the value received from the API.

**Preview of the page**
![image](https://user-images.githubusercontent.com/1624045/27794420-6c1fb122-6002-11e7-85d6-283b10d1c2e3.png)

**Here are the props and state:**

After after POST redirects to Edit page
![image](https://user-images.githubusercontent.com/1624045/27794588-0d217f2e-6003-11e7-8d56-1910a554606b.png)

When just reloading the same Edit page again:
![image](https://user-images.githubusercontent.com/1624045/27794591-103dab24-6003-11e7-833e-253c56614867.png)

It looks like the state is not set from the received props.

**Comment by fzaninotto** [comment]
I can't reproduce the bug, it must be something with how your REST client handles the creation data.

**Comment by qoalu** [comment]
in my understanding after CREATE returns and object, that object is then used to fill fields on the subsequent edit screen. Is that correct?

**Comment by qoalu** [comment]
Trying to figure this out further it seems that there might be an issue with the RadioButtonGroup of materialUI and somewhat related to this: https://github.com/callemall/material-ui/issues/5087

Looking at redux flow I noticed that both forms on the `/create` page and on the `/edit` page have the same name in the redux state which is `record-form`. My create fields do not correspond to the fields I get on Edit. In particular the "status" field does not exist on the `/create` page and only appears after creating the entry.

So here are the steps:
0. User submits in `/create`
1. The location changes to `/edit`
2. New Form Inputs (for the edit page) are created with the values in the state still from the `create` page.
3. New Form does not have a 'status' field and is therefore not filled with a value.
4. async response comes back with a value for 'field' after the `201 CREATED` comes back from the API
🚨. defaultValue is set in RadioGroup but does not update the value of the Radio button inside because it has been already rendered.

**Comment by qoalu** [comment]
@fzaninotto any comment on this?

**Comment by fzaninotto** [comment]
Even if AOR defaults to displaying the data you just entered in the `Create` form, the `Edit` view does send a request for reading the newly created entity.

So a race condition is possible:

1. in the `Create` view, you press Submit
2. An async creation request (R1) is sent to the rest API
3. You are redirected to the `Edit` view
4. An async read request (R2) is sent to the rest API
5. The response for R2 arrives, and is used for display. *it does not contain the updated data, as R1 has not completed yet*.
6. The response for R1 arrives, and somehow doesn't update the form...

But again, I wasn't able to reproduce, so I can't qualify it as a bug, unless you provide a failing test case.
