### ISSUE TITLE
SelectInput binding is no longer bidirectional

### ISSUE THREAD

**Issue by jdemangeon** [marmelab/admin-on-rest#828]
Since [this PR](https://github.com/marmelab/admin-on-rest/pull/705/files) was merged, SelectInput does not benefit from external changes anymore.

Indeed, given that the input value is stored into the component state at construct time and only changed from the component itself, even if input value change, it will not update the value inside the component.

For example, if we use `enableReinitialize` from redux-form and we update a value inside the connected "initialValues", inputs (other than SelectInput) are all updated except it.

```javascript
export const UserForm = () => (
  <div>
    <TextInput name="pseudo" >                             <--- THIS FIELD IS UPDATED
    <SelectInput name="grade" choices={grades} />          <--- NOT THIS FIELD
  </div>
);

export const mapStateToProps = state => ({
    initialValues: { pseudo: 'foo', grade: 'bar' }
});

const userForm = reduxForm({
    form: 'user-form',
    enableReinitialize: true,
});

export default compose(
   connect(mapStateToProps),
  userForm,
)(UserForm);

...

// Trigger redux-form "change" action (from redux-saga... or an other source)

yield put(change('user-form', 'pseudo', 'baz'));
yield put(change('user-form', 'grade', 1));

```

**Comment by wesley6j** [comment]
True. 
And other inputs that have internal state (`FileInput` and `SelectArrayInput`) may have this problem too. 

`BooleanInput` might have this problem too because the input does not take value from redux-form state after it is initialized.

**Comment by wesley6j** [comment]
For `SelectInput`, we can wait for erikras/redux-form#3081

**Comment by jdemangeon** [comment]
Right :+1:

**Comment by fzaninotto** [comment]
The aforementioned redux-form ticket was published in redux-form 7.0.0. So is it still an issue?

**Comment by djhi** [comment]
Nope, the aforementioned redux-form ticket only consider `undefined`, not `null`. I tested with latest version (`7.0.3`) and can confirm the prb is still here. 

I have a fix incoming though

**Comment by djhi** [comment]
FYI, I checked the other inputs which use state for their values and they are fine
