### ISSUE TITLE
Upgrade to material ui 0.16

### ISSUE THREAD

**Issue by fzaninotto** [marmelab/admin-on-rest#83]
It breaks styling on tables, so this won't be immediate.

**Comment by ArnaudD** [comment]
Hi,

I tried upgrading to 0.16.1 and didn't noticed anything broken on tables, what was the issue ? Did you tried on 0.16.0 ?

I've only fixed CircularProgress in the Layout component.

Here is my branch https://github.com/marmelab/admin-on-rest/compare/master...fizix-io:material-ui-0.16?expand=1

I can send a PR if you want.

**Comment by djhi** [comment]
Great news! Indeed, we would appreciate a PR :)

**Comment by ArnaudD** [comment]
you were faster than me :) #105

I've only tested the sample projet, I will try other fields/inputs to see if nothing else breaks.

**Comment by fzaninotto** [comment]
Fixed by #105.

I don't see the table styling issues anymore, great work guys!
