### ISSUE TITLE
Chip field with multiple values display into one chip

### ISSUE THREAD

**Issue by Dr8g0n** [marmelab/admin-on-rest#833]
`{
  ...
   tag_names: ['aaa', 'bbb', 'ccc']
}
<ChipField source="tag_names">
`
It should display 3 individual chips instead of cluster into one single chip (like attached screenshot below)
![screen shot 2017-07-05 at 4 37 20 pm](https://user-images.githubusercontent.com/22249579/27890424-76d8cbd4-61a7-11e7-9e2d-f33f8e6d7843.png)

**Comment by wesley6j** [comment]
Nope, this is not `ChipsField`. Each `ChipField` renders one chip.
But it should be simple to create `ChipsField` or `ChipArrayField`.

**Comment by Dr8g0n** [comment]
Thanks!
