### ISSUE TITLE
What is `ConnectedReferenceArrayField`?

### ISSUE THREAD

**Issue by christianpbrink** [marmelab/admin-on-rest#836]
Seen here:

https://github.com/marmelab/admin-on-rest/blob/master/src/mui/field/ReferenceArrayField.js#L106

I'm tinkering with the code, considering contributing, and am just curious.

**Comment by wesley6j** [comment]
A decorated version of [ReferenceArrayField](https://github.com/marmelab/admin-on-rest/blob/master/src/mui/field/ReferenceArrayField.js#L42) and the component you actually get when you import from AOR.

**Comment by christianpbrink** [comment]
Thanks. I'm a novice in both React and Redux but am picking it up quickly.
