### ISSUE TITLE
GET_ONE response data not available in edit view

### ISSUE THREAD

**Issue by cloudtracer** [marmelab/admin-on-rest#837]
The application I'm working with can sometimes have a lot of data per record, sometimes several MB's worth of plain text (don't ask). I'm trying to limit the amount of data pushed down from the REST server, so I've removed the fields that can contain large amounts of data for list responses, but I'd still like to be able to edit these fields sometimes in the edit view.  

The problem is, that if this source field is not available in the list view, it doesn't appear to be loaded when changing to the edit view, even though I can see the API request/response for the GET_ONE record.  Is this a known limitation?

**Comment by cloudtracer** [comment]
Nevermind, figured it out.

**Comment by ghost23** [comment]
What was the solution, I am having the same problem?!

**Comment by cloudtracer** [comment]
Not sure if it helps, but I think it had to do with my REST Client which is customized for PouchDB. I was using both _id and id parameters and I had them mixed up either in the REST client code or the source field in the list. I doubt that is helpful, but if you're having the same issue its worth double checking the id fields.
