### ISSUE TITLE
CustomInput field not calling form validate fucntion

### ISSUE THREAD

**Issue by prakashjais99** [marmelab/admin-on-rest#838]
I have created custom location component using MuiGeoSuggest. But  form validate()  function not including location values for validation. Any help on this will be great

```js
import React from 'react';
import MuiGeoSuggest from 'material-ui-geosuggest';

const Location = (props) => (<MuiGeoSuggest
    {...props}
    style={{
    width: "100%"
}}
    hintText="Enter your location"
    errorText={props.meta.touched && props.meta.error}
    floatingLabelText="Your Location *"
    onPlaceChange={props.onPlaceChange}
    options={{
    componentRestrictions: {
        country: "ind"
    }
}}/>);

Location.defaultProps = {
    source: 'location',
    addField: true
};

export default Location;
```

**Comment by djhi** [comment]
The admin-on-rest core team doesn't provide support or advice on debugging your own project. We need to focus on writing documentation, fixing bugs, and adding new features. 

Instead, we've decided to offload that charge to the community, by moving support to [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest). Ask your question there, you will find helpful people (sometimes from the core team, too). Besides, the response to your question will be easy to find for future developers with a similar problem.

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise. 

http://stackoverflow.com/questions/tagged/admin-on-rest
