### ISSUE TITLE
Custom REST errors handling

### ISSUE THREAD

**Issue by dili91** [marmelab/admin-on-rest#843]
Hi, 
Is it possible to add in future release a custom and simplified error handling within a custom rest client? 

I read [#180](https://github.com/marmelab/admin-on-rest/issues/180), but personally I think it's a very heavy task for such a simple requirement. Wouldn't be worth it to simplify custom errors handling ? I Think it's a common problem

**Comment by leesei** [comment]
I've the same need. Here's my finding:

1. default `crudResponse.js` will render `message` in `HttpError` object or `'aor.notification.http_error'`
```js
case CRUD_GET_LIST_FAILURE:
case CRUD_GET_MANY_FAILURE:
case CRUD_GET_MANY_REFERENCE_FAILURE:
case CRUD_CREATE_FAILURE:
case CRUD_UPDATE_FAILURE:
case CRUD_DELETE_FAILURE: {
    console.error(error);
    const errorMessage = typeof error === 'string'
        ? error
        : (error.message || 'aor.notification.http_error');
    return yield put(showNotification(errorMessage, 'warning'));
}
```
2. `HttpError` object is generated by `fetchUtil.js`
```js
if (status < 200 || status >= 300) {
    return Promise.reject(new HttpError((json && json.message) || statusText, status));
}
```
3. we can catch and throw a different error if we implement our `restClient`
```js
const { url, options } = convertRESTRequestToHTTP(type, resource, params);
return httpClient(url, options)
  .then(response =>
    convertHTTPResponseToREST(response, type, resource, params)
  )
  .catch(error => {
    // error is HttpError object
    console.log(error, error.message, error.status);
    throw error; // rethrow it
  });
```

---

However the body of my error response is `{ _erorr: "..." }` so it is not assigned to `HttpError.message`.
`HttpError` only stores "Internal Server Error", 500, which is not particularly useful.
I call for passing `json` as 3rd parameter to `HttpError` so we can do custom remapping.

```js
// fetchUtil.js
if (status < 200 || status >= 300) {
    return Promise.reject(new HttpError((json && json.message) || statusText, status, json));
}
```
```js
  .catch(error => {
    // error is HttpError object
    console.log(error, error.message, error.status, error.body);
    throw { message: error.body._error };
  });
```

@fzaninotto what do you think?

**Comment by fzaninotto** [comment]
There is no standard in REST land about passing error messages. I suggest you use your own `fetch` function instead of the one from `fetchUtils` in your case.

**Comment by fzaninotto** [comment]
But I agree that passing the `json` to the `HttpError` constructor makes it easier, so I'm +1 for that change. Feel free to send us a PR abut it.

**Comment by Phocea** [comment]
should this be closed by https://github.com/marmelab/admin-on-rest/commit/57dbd86128037096a445f152f4f339113c0aada7#diff-af187ae2de6c59a4ec26814f04fddacd ?

**Comment by fzaninotto** [comment]
Absolutely, thanks for pointing!

**Comment by oliviertassinari** [comment]
Oh great, it's what I needed :).
