### ISSUE TITLE
[idea] admin on graphql

### ISSUE THREAD

**Issue by sibelius** [marmelab/admin-on-rest#85]
This repo is awesome!

Would be really cool to have an admin-on-graphql, it could be a different repo

I think apollo stack is a good fit for this project

**Comment by fzaninotto** [comment]
Hi Sibelius,

And thanks for your feedback. If you like admin-on-rest, tell your friends about it!

Admin-on-rest is built with REST in mind. Furthermore, we don't have real GraphQL projects to test. If you want to build something similar on GraphQL, be our guest! But we won't be able to run the two ourselves.

**Comment by fzaninotto** [comment]
If someone ever fins this thread in the future, you should know that today using admin-on)rest with GraphQL is as simple as using [marmelab/aor-simple-graphql-client](https://github.com/marmelab/aor-simple-graphql-client) as REST client.
