### ISSUE TITLE
Nested create-route not recognized

### ISSUE THREAD

**Issue by MrAvantiC** [marmelab/admin-on-rest#851]
hello,
I'm using admin-on-rest version 1.1.1 with a setup that looks like this:

***httpClient.js:***

    import { fetchUtils } from 'admin-on-rest'
    
    const HttpClient = (url, options = {}) => {
        if (!options.headers) {
            options.headers = new Headers({ Accept: 'application/json' })
        }
    
        // ...handle authorization and set some header
    
        return fetchUtils.fetchJson(url, options)
    }
    
    export default HttpClient

***restClient.js***

    import { jsonServerRestClient } from 'admin-on-rest'
    import HttpClient from './httpClient.js'
    
    export default jsonServerRestClient('', HttpClient)

...so I'm pretty basic in that department.

What I now have is a couple of ***routes*** looking like this:

    <Route exact path="/stream" render={(routeProps) => <StreamList hasCreate resource="stream" {...routeProps} />} />,
    <Route exact path="/stream/create" render={(routeProps) => <StreamCreate resource="stream" {...routeProps} />} />,
    <Route exact path="/stream/:id" render={(routeProps) => <StreamEdit hasDelete resource="stream" {...routeProps} />} />,
    <Route exact path="/stream/:id/delete" render={(routeProps) => <Delete resource="stream" {...routeProps} />} />,
    <Route exact path="/stream/query/:id" component={StreamQueryEdit} />,

...this is all pretty standard as well and works fine.

***My problem*** now is that I have another route `/config/what`, where I want to have nested routes for one of the resources. The routing looks like this:

    <Route exact path="/config/how/antonym" render={(routeProps) => <AntonymList hasCreate resource="antonym" {...routeProps} />} />
    <Route exact path="/config/how/antonym/create" render={(routeProps) => <AntonymCreate resource="antonym" {...routeProps} />} />
    <Route exact path="/config/how/antonym/:id" render={(routeProps) => <AntonymEdit resource="antonym" {...routeProps} />} />
    <Route exact path="/config/how/antonym/:id/delete" render={(routeProps) => <Delete resource="antonym" {...routeProps} />} />

Inside the `/config/how/` these nested routes are rendered like this:

    if (this.props.children) {
        return this.props.children
    }

The List-, Edit- and Delete-Route all work like expected here. The only problem is that once I navigate to the Create-Route I get a 500-error from the server.

Turns out that after some investigating, the framework does not recognize this route as a create Route but instead thinks of it as a `GET` request for the id of "create".

Here is what I tracked the issue down to:
[![AOR debug][1]][1]

This suggests that for some reason admin-on-rest thinks of this request as a GET request. This also causes the code to go through `Edit.js` (instead of "Create"?) And I'm really not sure why.

I tried to find the place where the `type` parameters are being set to see what might cause this behaviour ...but no luck so far.

It's especially weird that both the list and the edit route work fine in these cases. It's just the create-route...

  [1]: https://i.stack.imgur.com/qch8W.png

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by MrAvantiC** [comment]
Hi @fzaninotto ,

actually I started yesterday by posting a queestion on stackoverflow because I was not sure if this behaviour is a bug or I'm just doing something wrong:
https://stackoverflow.com/questions/45015394/admin-on-rest-nested-create-route-not-working

...and the first response that I got was basically that I should open an issue here because the poster had a similiar issue with nested routes before and suggested it being a bug.

So can you maybe confirm this behaviour is as intended and the mistake is on my part?

**Comment by fzaninotto** [comment]
From my point of view, this is a request for support. If this was a bug description, you should remove all the code that is specific to your use case, and write it so we could easily understand it in the general way. It's not the case of this issue.

Besides, I simply don't understand this sentence:

> Turns out that after some investigating, the framework does not recognize this route as a create Route but instead thinks of it as a GET request for the id of "create".

You're mixing up react-router routes and rest client in the same sentence, where they have nothing to see with each other.
