### ISSUE TITLE
Translate title

### ISSUE THREAD

**Issue by rdubigny** [marmelab/admin-on-rest#853]
Hi,

Didn't find a simple way to translate the app title.

I suggest to add a label props to the Admin component like so:

```jsx
const messages = {
    en: {
        title: "My Custom Admin",
    }
}

<Admin label="title" messages={messages}>
    // ...
</Admin>
```

@fzaninotto is this API OK for you ?

**Comment by djhi** [comment]
The existing `title` prop accepts a node so you can create a `<Title>` component and apply the [translate](https://marmelab.com/admin-on-rest/Translation.html#translating-your-own-components) HOC provided by admin-on-rest.
