### ISSUE TITLE
Using randomuser.me api with admin-on-rest

### ISSUE THREAD

**Issue by anandchida** [marmelab/admin-on-rest#86]
I'm pleasantly surprised with admin-on-rest which makes things super easy to build backend admin interfaces.  I'm using 0.4.0 and need some help on restClient for consuming https://randomuser.me/api?results=5 

I've looked at examples in Rest clients doc and got them for jsonplaceholder working. I'm not a javascript or react programmer and couldn't figure out how to get admin-on-rest to parse the response.

Any help is appreciated

**Comment by fzaninotto** [comment]
Hi anandchida,

Thanks for the feedback. If you're new to JavaScript and React, building a custom REST client won't be your only showstopper. Knowledge of JavaScript is mandatory to start hacking with admin-on-rest, and we can't use our time to teach you that (or we wouldn't have time to develop such awesome projects).

I suggest you buy a book and take some online courses about JavaScript and React. Egghead.io is a good starting point. Then, in a month or two, come back here and try again. I'm sure you'll find the answer by yourself!
