### ISSUE TITLE
Module parse failed

### ISSUE THREAD

**Issue by marcw** [marmelab/admin-on-rest#861]
I have an app created with `create-react-app` that refuses to compile for some weird reason.  

```
./~/admin-on-rest/src/mui/form/TabbedForm.js
Module parse failed: /path/to/app/Resources/backend/node_modules/admin-on-rest/src/mui/form/TabbedForm.js Unexpected token (20:17)
You may need an appropriate loader to handle this file type.
|     }
| 
|     handleChange = (value) => {
|         this.setState({ value });
|     };
```

I ejected the app, I added `transform-class-properties`,`stage-0` and `es-2015` plugins, presets with yarn and changed my `package.json` file to mimick AOR babel configuration like below. The error is still present and I don't understand why. 

Is it related to AOR or to my configuration?  

<details>
<summary>package.json</summary>
<code><pre>
{
  "name": "backend",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@navjobs/upload": "^3.0.7",
    "admin-on-rest": "^1.2.1",
    "api-platform-admin": "^0.1.8",
    "autoprefixer": "7.1.1",
    "babel-core": "6.25.0",
    "babel-eslint": "7.2.3",
    "babel-jest": "20.0.3",
    "babel-loader": "7.0.0",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react-app": "^3.0.1",
    "babel-preset-stage-0": "^6.24.1",
    "babel-runtime": "6.23.0",
    "case-sensitive-paths-webpack-plugin": "2.1.1",
    "chalk": "1.1.3",
    "css-loader": "0.28.4",
    "dotenv": "4.0.0",
    "eslint": "3.19.0",
    "eslint-config-react-app": "^1.0.5",
    "eslint-loader": "1.7.1",
    "eslint-plugin-flowtype": "2.34.0",
    "eslint-plugin-import": "2.2.0",
    "eslint-plugin-jsx-a11y": "5.0.3",
    "eslint-plugin-react": "7.1.0",
    "extract-text-webpack-plugin": "2.1.2",
    "file-loader": "0.11.2",
    "fs-extra": "3.0.1",
    "html-webpack-plugin": "2.29.0",
    "immutable": "^3.8.1",
    "jest": "20.0.4",
    "object-assign": "4.1.1",
    "postcss-flexbugs-fixes": "3.0.0",
    "postcss-loader": "2.0.6",
    "promise": "7.1.1",
    "query-string": "^4.3.4",
    "react": "~15.5.4",
    "react-dev-utils": "^3.0.2",
    "react-dom": "~15.5.4",
    "react-error-overlay": "^1.0.9",
    "react-howler": "^3.6.2",
    "redux-saga": "^0.15.4",
    "style-loader": "0.18.2",
    "sw-precache-webpack-plugin": "0.11.3",
    "url-loader": "0.5.9",
    "webpack": "2.6.1",
    "webpack-dev-server": "2.5.0",
    "webpack-manifest-plugin": "1.1.0",
    "whatwg-fetch": "2.0.3"
  },
  "devDependencies": {
    "enzyme": "^2.9.1",
    "react-test-renderer": "~15.5.4"
  },
  "scripts": {
    "start": "node scripts/start.js",
    "build": "node scripts/build.js",
    "test": "node scripts/test.js --env=jsdom"
  },
  "jest": {
    "collectCoverageFrom": [
      "src/**/*.{js,jsx}"
    ],
    "setupFiles": [
      "<rootDir>/config/polyfills.js"
    ],
    "testMatch": [
      "<rootDir>/src/**/__tests__/**/*.js?(x)",
      "<rootDir>/src/**/?(*.)(spec|test).js?(x)"
    ],
    "testEnvironment": "node",
    "testURL": "http://localhost",
    "transform": {
      "^.+\\.(js|jsx)$": "<rootDir>/node_modules/babel-jest",
      "^.+\\.css$": "<rootDir>/config/jest/cssTransform.js",
      "^(?!.*\\.(js|jsx|css|json)$)": "<rootDir>/config/jest/fileTransform.js"
    },
    "transformIgnorePatterns": [
      "[/\\\\]node_modules[/\\\\].+\\.(js|jsx)$"
    ],
    "moduleNameMapper": {
      "^react-native$": "react-native-web"
    },
    "moduleFileExtensions": [
      "web.js",
      "js",
      "json",
      "web.jsx",
      "jsx"
    ]
  },
  "babel": {
    "presets": [
      "es2015",
      "stage-0",
      "react-app"
    ],
    "plugins": [
      "transform-react-jsx",
      "transform-class-properties"
    ]
  },
  "eslintConfig": {
    "extends": "react-app"
  }
}
</pre></code></details>

**Comment by wedneyyuri** [comment]
Looks like you are using ES6 class syntax, so it should be:
```json
handleChange (value) {
  this.setState({ value });
};
```

**Comment by ewnd9** [comment]
You may want to use transpilled version from `admin-on-rest/lib` instead of `admin-on-rest/src`

**Comment by marcw** [comment]
@ewnd9 oh wow. I didn't see that my IDE added the imports from "src" and not from the transpilled version. 😓

**Comment by marcw** [comment]
@ewnd9 thanks !
