### ISSUE TITLE
BooleanInput not being colored in red when trying to save without it being checked

### ISSUE THREAD

**Issue by natrim** [marmelab/admin-on-rest#863]
I have `<BooleanInput source="check_me_or" validate={[required]} />`
ie. i want to save the form only if user checks the checkbox.

But the checkbox is not colored red as error on clicking form submit.
This looks like error, as user has no indication that he should check the box.

(this is somewhat same as issue #439, trough for different reasons)

It does not even work if i set some error trough 
`const checkForm = (values) => { const errors = {};if (!values.check_me) {errors.check_me = ['Check me!'];  } return errors; };`
`<SimpleForm validate={checkForm}>`
`<BooleanInput source="check_me" />`
`</SipleForm>`

(no error is shown when clicking on submit and form is not submitted)

**Comment by wesley6j** [comment]
You can use a `SelectInput` to have error message. 

I doubt BooleanInput will support this as its dependent component [Toggle](http://www.material-ui.com/#/components/toggle) does not.

**Comment by fzaninotto** [comment]
Use `<NullableBooleanInput>` instead. A normal `<BooleanInput>` cannot distinguish between `null` and `false`.

**Comment by natrim** [comment]
@fzaninotto i don't need to distinguish between null and false i just want the user see error on checkbox when i set it.
@wesley6j the Toggle supports styling though so it can be at least colored red

I just make it colored red by myself, i just though to report this as the Checkbox is inconsistent with other inputs and it can suprise users that it doesn't work the same way.

**Comment by fzaninotto** [comment]
There can't be an error on a non-nullable boolean input, because it can only have two values true and false. It turns out that the default value from aor (`undefined`) and the default value from your restClient (usually `undefined`) all equal to `false`, and therefore are valid values.

**Comment by natrim** [comment]
i already handled it by wrapping the BooleanInput.

Posting the custom solution here, in case someone needs something similar

```
import React from 'react';
import PropTypes from 'prop-types';
import { BooleanInput } from 'admin-on-rest';

const getStyles = ({ elStyle, meta: { touched, invalid } }, { muiTheme }) => {
  const errColor = muiTheme.textField.errorColor;

  let borderBottom;
  if (touched && invalid) {
    borderBottom = `2px solid ${errColor}`;
  }

  return ({
    ...elStyle,
    margin: '1rem 0',
    maxWidth: 250,
    borderBottom,
  });
};

export const RequiredBooleanInput = (props, context) => {
  const style = getStyles(props, context);
  return <BooleanInput elStyle={style} {...props} />;
};

RequiredBooleanInput.propTypes = BooleanInput.propTypes;
RequiredBooleanInput.defaultProps = BooleanInput.defaultProps;
RequiredBooleanInput.contextTypes = {
  ...BooleanInput.contextTypes,
  muiTheme: PropTypes.object.isRequired,
};

export default RequiredBooleanInput;
```

(can be even used for `RadioButtonGroupInput`, just replace `BooleanInput` for `RadioButtonGroupInput`)

**Comment by fzaninotto** [comment]
Again, this is a bad solution. If you want to validate the presence of a user entry in a Boolean input, you must use `NullableBooleanInput` with the `required` validator.

**Comment by natrim** [comment]
`NullableBooleanInput` is not checkbox but select though....
