### ISSUE TITLE
[Feature Proposal] a PhoneField for a good presentation of phone numbers

### ISSUE THREAD

**Issue by thomas-cleany** [marmelab/admin-on-rest#868]
Hi !

I've wrote a field for phone numbers which displays it as a `<a href="tel:" />` link.

If the number is from the phone locale it'll be formatted like a national number, if not international formatting will be set. The default phone locale is 'FR' (french) but it can be changed by setting a prop (see the example below).

It's based on the  phone lib of halt-hammerzeit based itself on the _"Google Android's famous libphonenumber library"_
For more information about the lib : https://github.com/halt-hammerzeit/libphonenumber-js

## Example :

`<PhoneField source="personal_phone" />`
renders a french number as national:
`<a href="tel:+33623456789">06 23 45 67 89</a>`  => <a href="tel:+33623456789">06 23 45 67 89</a>
and an US number as international:
`<a href="tel:+12344565656">+1 234 456 5656</a>` => <a href="tel:+12344565656">+1 234 456 5656</a>

`<PhoneField source="personal_phone" locale="US" />`
// renders a french number as international:
`<a href="tel:+33623456789">+336 23 45 67 89</a>` => <a href="tel:+33623456789">+336 23 45 67 89</a>
and an US number as national:
`<a href="tel:+12344565656">(234) 456-5656</a>` => <a href="tel:+12344565656">(234) 456-5656</a>

So what do you guys think, is this something you might be interested in adding to AOR?

**Comment by djhi** [comment]
That's great! It's very specific though and I remember libphonenumber to be quite heavy. Would you mind publishing it as an add-on ?

**Comment by djhi** [comment]
And make a documentation pull request?

**Comment by thomas-cleany** [comment]
Thank's ! 

Ok then I'll do that.
