### ISSUE TITLE
Add custom middlewares to redux store

### ISSUE THREAD

**Issue by vantox** [marmelab/admin-on-rest#869]
It would be nice feature for Admin component to support custom store middlewares. I'm writing custom reducer and action. I want to fetch data in action then return pure action object but i can't inject redux-thunk in store middlewares.

**Comment by fzaninotto** [comment]
Admin-on-rest won't support that out of the box, you'll have to take the [custom app](https://marmelab.com/admin-on-rest/CustomApp.html) route.

**Comment by ngocketit** [comment]
It's a surprise for me that react-admin is not using `redux-thunk`. Is there any reason for that?

**Comment by fzaninotto** [comment]
we're using redux-saga, which supports more sophisticated use cases than redux-thunk.
