### ISSUE TITLE
Checkboxes get reordered when used with ReferenceArrayInput

### ISSUE THREAD

**Issue by toniov** [marmelab/admin-on-rest#870]
When I use `ReferenceArrayInput` component with `CheckboxGroupInput`, each time a checkbox is checked it gets reordered and goes to the top.
Is it the intended behaviour? When `CheckboxGroupInput` is used passing the `choices` manually, the checkboxes stay in the same place even after checking them.

**Admin-on-rest version**
1.2.0

**React version**
15.6.1

**Browser version**
Chrome 59.0.3071.115

**Code example**

```js
<ReferenceArrayInput source="location_ids" reference="locations" allowEmpty>
    <CheckboxGroupInput />
 </ReferenceArrayInput>
```

**Comment by fzaninotto** [comment]
Confirmed, it's a bug
