### ISSUE TITLE
<ImageInput> regardless of the 'multiple' attribute always takes multiple files

### ISSUE THREAD

**Issue by MaxAlex666** [marmelab/admin-on-rest#874]
In version 1.2.1 <ImageInput> regardless of the attribute 'multiple' always accepts (and sends further) many files.

**Comment by metamaker** [comment]
I made FileInput component that accepts only one file and immediately calculates base64 content. Snippet is here https://gist.github.com/metamaker/285fc877e2712dea6aedd9a9d4184e89, you can freely use it in your projects, or if someone will have time, to include it into admin-on-rest providing me a credit. Sadly, I don't have that much time to clean it up :( , but it should be good enough.
