### ISSUE TITLE
Add a scrollbar for the SelectArrayInput component.

### ISSUE THREAD

**Issue by Mikael1006** [marmelab/admin-on-rest#875]
Hello,

I'm using admin on rest for my REST app and I have a many to many relationship between two entities. For the creation of an element, I have used ReferenceArrayInput and SelectArrayInput where I set perPage={100}.

The problem is that when I want to create a element,  I have lot of elements inside the list and I can't see them all.

![bug_select_multiple](https://user-images.githubusercontent.com/26187016/28310490-ee07e2bc-6bac-11e7-8f26-adbcc962532d.jpg)

The <SelectInput> component implements a scrollbar but the <SelectArrayInput> component does not.

I tried  to adjust a CSS rule (overflow-y: auto) but it doesn't works.

```js
<ReferenceArrayInput source="units" reference="units" perPage={100} allowEmpty>
    <SelectArrayInput optionText="name" elStyle={{ overflowY: 'auto' }} style={{ overflowY: 'auto' }} />
</ReferenceArrayInput>
```

**Comment by djhi** [comment]
I advise you to use the [autocomplete](https://marmelab.com/admin-on-rest/Inputs.html#autocompleteinput) input when you have too many options.

**Comment by fzaninotto** [comment]
I agree with @gildas, the `SelectArrayInput` is not a good fit for that use case. Apart from that, I suggest you open an issue on the `material-ui` repository, since admin-on-rest simply uses [their `<SelectField>` component](http://www.material-ui.com/#/components/select-field).
