### ISSUE TITLE
Can't set crudDelete on <Delete>?

### ISSUE THREAD

**Issue by Jc2k** [marmelab/admin-on-rest#876]
I want to change how the delete flow works for one of my resource types (see [here](https://stackoverflow.com/questions/45150050/overriding-crud-delete-success-reducer-for-non-immediate-deletes/45158258#45158258). I want the UI to be the same but the side effects will be different (don't want it to disappear from the list immediately).

I want to use as much of the existing delete experience as possible (especially the confirmation screen).

It looks like `<Delete>` can take a custom action (https://github.com/marmelab/admin-on-rest/blob/master/src/mui/delete/Delete.js#L112) but I can't seem to pass it from a `<Resource>` or via a custom `<Route>`?

Is this something that should work?

**Comment by djhi** [comment]
Please don't duplicate questions from StackOverflow here. We only track bugs and feature requests in github

**Comment by djhi** [comment]
And to answer your question, no, you can't override the `crudDelete` prop as we don't export the `Delete` component directly but an enhanced version through redux connect function.

**Comment by Jc2k** [comment]
It was a feature request/bug - it sounded liked a question because i wasn't sure which you considered it.
