### ISSUE TITLE
[Question | Feature Request] Force redirect to login on all routes that are not declared in resources

### ISSUE THREAD

**Issue by mjanos10** [marmelab/admin-on-rest#877]
Hi!

Here's the scenario:

You have resources like "posts" and "users". When you visit the /posts or the /users urls and you are not authenticated you are redirected to the login screen. That's shiny.

But when you visit other urls, like /asd or something, the complete app is shown and the user is not redirected to the login screen, and nor your AuthClient nor the RestClient (why would it?) are called so you don't have a way to check credentials or redirect manually. Also note, that since these routes won't trigger any rest communication, your server can't send a 401 or 403 either.

I don't really see a security concern here, but visually and in terms of UX I think we should redirect the user somehow to the login page when this occures.
Any opinion or suggestions how to accomplish this?

To test how this looks you can just visit the demo site, logout if your logged in and append a custom url to it, like [https://marmelab.com/admin-on-rest-demo/#/asdasd](https://marmelab.com/admin-on-rest-demo/#/asdasd)

**Comment by djhi** [comment]
You can use a custom saga and listen to the route change action

**Comment by fzaninotto** [comment]
This is solved by #824 in 1.3.0
