### ISSUE TITLE
Control the data passed through the APIs

### ISSUE THREAD

**Issue by rouflak** [marmelab/admin-on-rest#88]
Hi!

I'm stuck with the edition form.

I have an entity which has the following properties:
``` 
- id
- name
- services (many to one)
```
My form is only handling the `name` property. I'd like this field to be the only one passed through the API and not the `id` and `services` properties.

Is there any way to have control on the properties passed through the APIs when using the `Edit` component?
If no, is it planned?

Thx

**Comment by fzaninotto** [comment]
Admin-on-rest will pass all the data you include in the `<Edit>` component to the rest client. If you want only part of this data to be passed further (to the HTTP client), the best place to put that logic in is a custom rest client.
