### ISSUE TITLE
Can it be possible to allow filters on a show page?

### ISSUE THREAD

**Issue by snesmith** [marmelab/admin-on-rest#881]
I want to know if you guys could possibly make it possible to use the filter button/ filters on a show page?
I am doing this:

```
export const archivedShow = ({ ...props }) => (
        <Show title="Log" {...props} filters={<LogFilter/>}>
            <SimpleShowLayout>
            <ReferenceManyField label="Log" reference="archivedfiles" target="id">
                <Datagrid>
                    <TextField source="id" label="Line" />
                    <TextField source="timestamp" label="Timestamp" />
                    <TextField source="severity" label="Severity" />
                    <TextField source="message" label="Message" />
                </Datagrid>
            </ReferenceManyField>
        </SimpleShowLayout>
        </Show>
        );
```
Here is my LogFilter:

```
const LogFilter = (props) => (
     <Filter {...props}>
        <TextInput label="Search" source="q" alwaysOn />
        <ReferenceInput label="User" source="id" reference="archivedfiles" allowEmpty>
           <SelectInput optionText="name" />
        </ReferenceInput>
     </Filter>
);
```

But I cannot get the FilterButton to render on the page, I believe it is because filter can only be used on the List component.

**Comment by snesmith** [comment]
for some reason my code didn't copy right, but I am using the filter just as I would in List:
<List {...props} perPage={100} title="Logs and Reports" filters={< FileFilter/>}>

**Comment by djhi** [comment]
No, the filter components are meant to be used in the list only. You'll have to make a custom Show component or layout for that

**Comment by snesmith** [comment]
Okay, but I do think this is a feature many people would want to use.
