### ISSUE TITLE
[Feature Proposal] Generic action confirmation view

### ISSUE THREAD

**Issue by Jc2k** [marmelab/admin-on-rest#882]
It would be great if there was a MUI component for confirmation of an action.

 * It should be able to return you to the list view
 * It should take a custom title
 * It should optionally a custom are you sure? message
 * It should have a confirm button that fires a custom action specified by the user
 * There should be a cancel button that returns the user to the previous screen

Perhaps a generalised version of `<Delete />` that can emit a custom action? It's currently impossible to reuse the existing Delete component because it is already wrapped in react magic.

**Comment by iamsimakov** [comment]
This component could also be responsive to the keystroke `Enter`.

**Comment by djhi** [comment]
Great idea for an addon! Feel free to open a PR with a link to it in the documentation :)

**Comment by fzaninotto** [comment]
Just to make it clear: It's a good idea for an *external* addon, i.e. something you would host on your own repository, but not something we would like to put in the aor core and maintain oursleves. So I'm closing this issue.
