### ISSUE TITLE
404Page handling

### ISSUE THREAD

**Issue by natrim** [marmelab/admin-on-rest#887]
Hello, i noticed some lil problem.

There is no 404 page handling, so if i access ie. https://marmelab.com/admin-on-rest-demo/#/custogew

then there is only empty page shown (with layout).

The same happens when there is used login paged from examples:
- it just displays empty page and even does not redirect to login if not logged

i tried adding default route trough customRoutes on Admin
`<Route path='*' component={Page404} />`

But the problem is that custom routes are added before resource routes, so it will catch all resource routes and breaks the admin.

**Comment by fzaninotto** [comment]
Fixed by #824 (to be released in next minor version).
