### ISSUE TITLE
SubmissionError not handled properly

### ISSUE THREAD

**Issue by Sindbag** [marmelab/admin-on-rest#888]
In redux-form in order to mark form' fields as incorrect you are able to throw SubmissionError from crud with payload {'field1': 'error1', ...}, which is automatically set as error for field by STOP_SUBMIT action.

When I am trying to do so in admin-on-rest I just receive notification "Submit Validation Failed", but no data stored in redux store for form.

Is there any way to make submission (on-server) validation per field with proper visualization of errors in form?

**Comment by fzaninotto** [comment]
Does #871 solve your problem?

**Comment by Sindbag** [comment]
Yeah, seems to be the best way to solve the problem, thanks :)
