### ISSUE TITLE
Missing 'quill' package dependency

### ISSUE THREAD

**Issue by alexborisov** [marmelab/admin-on-rest#89]
Hey I've just updated to the latest 0.4.0 release and my app now fails to start due to a missing `package.json` dependency:

```
Failed to compile.

Error in ./~/admin-on-rest/lib/mui/input/RichTextInput.js
Module not found: 'quill' in [...]/node_modules/admin-on-rest/lib/mui/input

 @ ./~/admin-on-rest/lib/mui/input/RichTextInput.js 31:13-29
```

**Comment by Kmaschta** [comment]
Since the package `quill` is heavy and only needed by the RichTextInput, it is referenced as peer dependencies, so that you can install it only if you need it.

**Comment by alexborisov** [comment]
ok, however i dont use (or need) RichTextInput anywhere and my app fails to start with the above error anyway.
