### ISSUE TITLE
[RFR] Remove `addField` prop in Input components

### ISSUE THREAD

**Issue by fzaninotto** [marmelab/admin-on-rest#896]
## How `addField` currently works

Currently, all the aor Input components create their own redux-form `<Field>` component. Or rather, they express that they want to be decorated by a redux-form `<Field>`, thanks to the `addField: true` default Prop. For instance:

```js
// in LongTextInput.js
// simplified for this explanation
const LongTextInput = ({ input, isRequired, label, meta: { touched, error }, options, source, elStyle, resource }) => (
    <TextField {...input} multiLine fullWidth errorText={touched && error} style={elStyle}
        floatingLabelText={<FieldTitle label={label} source={source} resource={resource} isRequired={isRequired} />}
        {...options}
    />
);

LongTextInput.propTypes = {
    addField: PropTypes.bool.isRequired,
    // ...
};

LongTextInput.defaultProps = {
    addField: true,
    // ...
};

export default LongTextInput;
```

What happens is that `<SimpleForm>` and `<TabbedForm>` iterate over all their children, and pass them to a `<FormField>` component as the `input` prop:

```js
// in SimpleForm.js
// simplified for this explanation
export class SimpleForm extends Component {
    render() {
        const { children, invalid, record, resource, basePath } = this.props;
        return (
            <form>
                <div>
                    {Children.map(children, input => input && (
                        <div key={input.props.source}>
                            <FormField input={input} resource={resource} record={record} basePath={basePath} />
                        </div>
                    ))}
                </div>
            </form>
        );
    }
}
```

Then `<FormField>` inspects its `input` prop props. If the `addField` prop is detected, FormField decorates the input with a redux-form field.

```js
// in FormField.js
// simplified for this explanation
const FormField = ({ input, ...rest }) => {
    if (input.props.addField) {
        return (
            <Field
                {...rest}
                {...input.props}
                name={input.props.source}
                component={input.type}
                isRequired={isRequired(input.props.validate)}
            />
        );
    }
    return (typeof input.type === 'string') ? input : React.cloneElement(input, rest);
};
```

The great advantage of this is that we don't have to repeat the `<Field>` decoration for every input component. 

## The problem

Every time a developer decorates one of aor components, e.g. to customize the style, or set a prop always the same, like so:

```js
const RedLongTextInput = (props) => <div style={{ backgroundColor: 'red' }}>
    <LongTextInput {...props} />
</div>
```

They get this horrible error:

> Cannot read property 'touched' of undefined

That's because their component don't have the `addField` prop, and therefore `<FormField>` doesn't decorate the input with a `<Field>`, and therefore the input never receives the `meta` prop, which is injected by `<Field>`.

## Proposed solution

I've tried to mitigate the problem with #819, but I think that ultimately, it's not a matter of education. The library should not try to outsmart the developer. 

I suggest that we remove `addField` altogether, and *duplicate the `<FormField>` logic inside every Input component* instead.

So for example, `<LongTextInput>` would be modified like so:

```js
// in LongTextInput.js
// simplified for this explanation
const LongTextInput = ({ input, isRequired, label, meta: { touched, error }, options, source, elStyle, resource }) => (
            <Field name={source}
                component={<TextField {...input} multiLine fullWidth errorText={touched && error} style={elStyle}
                     floatingLabelText={<FieldTitle label={label} source={source} resource={resource} isRequired={isRequired} />}
                    {...options}
                />}
                isRequired={isRequired(input.props.validate)}
            />
);

LongTextInput.propTypes = {
    // no more addField
};

LongTextInput.defaultProps = {
    // no more addField
};

export default LongTextInput;
```

So we would repeat code to reduce WTF.

What's your opinion on this?

**Comment by djhi** [comment]
I would say that the same applies for `addLabel`: See https://stackoverflow.com/questions/46492471/admin-on-rest-customizing-inputs/46492620

**Comment by fzaninotto** [comment]
Done in the `next` branch.
