### ISSUE TITLE
Adding non list components out of queue causes list components to not get rendered

### ISSUE THREAD

**Issue by kodepareek** [marmelab/admin-on-rest#899]
Consider the following admin structure

```
<Admin>
    <Resource name="clients" list={ClientList} edit={ClientEdit} create={ClientCreate} />
    <Resource name="genres" />
    <Resource name="appUsers" list={UserList} edit={AdminUserEdit} />
</Admin>
```
This when one navigates to the appUsers link, nothing is displayed

However if I do this

```
<Admin>
    <Resource name="clients" list={ClientList} edit={ClientEdit} create={ClientCreate} />
     <Resource name="appUsers" list={UserList} edit={AdminUserEdit} />
    <Resource name="genres" />
</Admin>
```
The appUsers page is now rendered and is usable. This is definitely a bug, but can be resolved by adding the above info to the docs.

**Comment by fzaninotto** [comment]
Really? There is not reason for that. I'm curious to see a failing test case for that bug. Could you create one based on [this sandbox](https://codesandbox.io/s/ElxGNxBY0)?

**Comment by kodepareek** [comment]
I can try reproducing at the sandbox, but that will take tomorrow (have to run at the moment)

I have simplified the component greatly in the code above to highlight the issue. However just moving around that 1 resource entry makes the difference between the component rendering or not. I wish I could share the github link with you but its a private repo.

**Comment by kodepareek** [comment]
So I couldn't really make it work in the sandbox. But I have some more details from my current codebase. 

```
<Admin>
     <Resource name="clients" list={ClientList} edit={ClientEdit} create={ClientCreate} />
     <Resource name="appUsers" />
     <Resource name="appUsers/usersByRole" list={UserList} edit={AdminUserEdit} />
</Admin>

```

When a resource with a matching first part of the path is before in the resource queue, AOR is somehow stripping the route by the / and then even though the menu points to the route -> /appUsers/usersByRole
AOR is loading the component for 'appUsers' which does not really exist.

**Comment by kodepareek** [comment]
On more investigation I can say that this is because the 
exact: true 
prop is not being passed to react router in AdminRoutes.js.

A very simple fix would be to make exact: true a default prop to this part of the code in AdminRoutes.js


```
        {resources.map(resource =>
            <Route
                exact: true
                path={`/${resource.name}`}
                key={resource.name}
                render={() => <CrudRoute
                    resource={resource.name}
                    list={resource.list}
                    create={resource.create}
                    edit={resource.edit}
                    show={resource.show}
                    remove={resource.remove}
                    options={resource.options}
                />}
            />
        )}

```
Please do advise.

**Comment by kodepareek** [comment]
Interestingly enough. Adding exact: true to this comp also results in all CRUD routes to NOT get rendered. So supersimple fix may not be that easy.

**Comment by fzaninotto** [comment]
Now I understand. That's a limitation of react-router and the way you use it: if you have several resources that start with the same letters, you must place the longest first. I don't consider it as a bug, and this won't be fixed.

As for resources with a `/` in their name, they are not supported.

**Comment by kodepareek** [comment]
> As for resources with a / in their name, they are not supported.

I feel that this should be made part of the docs then. I am yet to work at a place where single word rest routes sufficed.
