### ISSUE TITLE
When will Material UI be updated to version 1?

### ISSUE THREAD

**Issue by jordanranson** [marmelab/admin-on-rest#9]
The current version of Material UI, while technically still in beta, is what is recommended to use in production (according to their site).

When will we see an upgrade to v1? The problem is the current version being used in Admin on Rest is too restrictive to properly brand.

Thanks.

**Comment by djhi** [comment]
See the project's README:

> Admin-on-rest 1.x is in maintenance mode. Version 2.x lives at [marmelab/react-admin](https://github.com/marmelab/react-admin).

**Comment by jordanranson** [comment]
Oops, sorry. Thanks.
