### ISSUE TITLE
Redirect to the latest valid page when displaying an empty page after the last one

### ISSUE THREAD

**Issue by MaxAlex666** [marmelab/admin-on-rest#900]
![example](https://user-images.githubusercontent.com/16526424/28717747-77addd2a-73bc-11e7-8702-9ece8e84018f.png)
AOR 1.2.1 When you delete the last entry on the page to go to the previous page does not happen, a blank page is displayed without any entries.

**Comment by fzaninotto** [comment]
Let's make it more general: if the user displays a page that is not the first, and the page has empty results, then the interface should redirect to the latest page. 

Doable with a saga, and a great idea for an enhancement.

**Comment by fzaninotto** [comment]
Fixed by #1451
