### ISSUE TITLE
create muliple records 

### ISSUE THREAD

**Issue by eslamtahoon** [marmelab/admin-on-rest#901]
i'm here to ask to availability of create multiple records in once?. and the availability to import csv file to import multiple record and then let user filter them ? is that applicable ?

**Comment by djhi** [comment]
About creating multiple records at the same time: how would you image that in terms of UI?

About importing a CSV file: you'll have to create a [custom action button](https://marmelab.com/admin-on-rest/List.html#actions) and implement the importation logic yourself.

Once imported, you can use the existing [filters on list](https://marmelab.com/admin-on-rest/List.html#filters)

**Comment by eslamtahoon** [comment]
but in this case i have to create custom action for every resource . i need to generalize that behavior for all resources

**Comment by fzaninotto** [comment]
The good new is: you have React. Tou can do anything you want with it, including configurable actions.

**Comment by eslamtahoon** [comment]
@fzaninotto  is there any way to contact you in private?

**Comment by fzaninotto** [comment]
yep, email me at my first name (francois) at my company domain (marmelab.com)
