### ISSUE TITLE
Empty value filters

### ISSUE THREAD

**Issue by NikitaVlaznev** [marmelab/admin-on-rest#909]
Is there any way to force list to refresh when a new filter field becomes visible?

It is not clear how to filter by boolean values and null reference filters.

If the filter is hidden, records with the both boolean values are shown, if you add a boolean filter it will indicate "false", that makes me to expect that only records with the 'false' value are shown, but it is not, there are still records with both values.

If i switch filter to the 'true' value and back then the correct list will be shown, records will have only the 'false' value.

The problem with the booleans can be solved by setting 'true' as the defaultValue, but what can be done for a reference filters? How to make the list component to display only the records with null reference value right after the reference filter appeared?

**Comment by fzaninotto** [comment]
Use a `NullableBooleanInput` to disable the filter on appearance. As for reference filters, use `allowEmpty`.

**Comment by NikitaVlaznev** [comment]
Wow, thanks! Did not noticed it somehow.
