### ISSUE TITLE
Allow changing autoHideDuration for <Notification>

### ISSUE THREAD

**Issue by natrim** [marmelab/admin-on-rest#911]
Right now the autoHideDuration is hardcoded to 4s https://github.com/marmelab/admin-on-rest/blob/master/src/mui/layout/Notification.js#L41

It would be nice to change it though.

ie. 4s is too little for ppl to read the notification sometimes so i want it longer

**Comment by fzaninotto** [comment]
Do you mean you want some messages to have a longer duration, or you want all messages to have a long duration?

**Comment by natrim** [comment]
Well, it depends on situation.

But for me this issue is about adding prop to <Notification> to set the delay.
As i want it set globally for now.

Would not mind being able to set it from the notification action per message too though.

**Comment by fzaninotto** [comment]
Fixed by #1097
