### ISSUE TITLE
Custom callback before form submit

### ISSUE THREAD

**Issue by natrim** [marmelab/admin-on-rest#915]
Right now the form is saved by `handleSubmitWithRedirect = (redirect = this.props.redirect) => this.props.handleSubmit(values => this.props.save(values, redirect));`

It would be nice to have some callback that would be called before submit, capable of aborting the submission. (preferably Promisable)
ie. `beforeSubmit: PropTypes.function`

(Why: well sometimes you really need to abort the submission because of "reasons")

**Comment by djhi** [comment]
Can't you use the `validate` prop for your use case ? If not, please elaborate

**Comment by djhi** [comment]
Or `asyncValidate`

**Comment by natrim** [comment]
validate is being triggered on every form change

**Comment by fzaninotto** [comment]
This is redux-form's job. Any property passed to `<SimpleForm>` is also passed to redux-form, so you can configure the form as you want.

**Comment by natrim** [comment]
i need some callback in handleSubmitWithRedirect which is passed to **toolbar** not the **redux-form**

if i try to use onSubmit prop on the form, it gets overriden by admin-on-rest

**Comment by jagrawat** [comment]
@natrim did u figureout any way  for callback ?

**Comment by natrim** [comment]
@jagrawat 

i used custom `<HiddenInput>` component
i do check using `validate` on form and set error on the `<HiddenInput>`, which will prevent form from being valid and being submitted

the other way is to have custom form component and override the `handleSubmitWithRedirect`
