### ISSUE TITLE
Plans to new material-ui

### ISSUE THREAD

**Issue by thiagoterleski** [marmelab/admin-on-rest#924]
Hi!

There are some plans to implements the new **material-ui** lib (currently in v1.0.0-beta.4) ?
I think they style `CSS-in-JS` solution with `createStyleSheet` function is amazing and will solve the performance problems with currently inline-style approach. 
More details:

[Material UI v1 beta](https://material-ui-1dab0.firebaseapp.com/customization/css-in-js)

**Comment by fzaninotto** [comment]
Already answered in #639 - no plans yet, we're waiting for a stable release.
