### ISSUE TITLE
Access fields of List / Resources in RestClient

### ISSUE THREAD

**Issue by fab1an** [marmelab/admin-on-rest#929]
Is there a way to communicate to the REST client to select only certain fields in the query (the ones being displayed in list)?

**Comment by marcw** [comment]
Nope, not to my knowledge.

**Comment by fzaninotto** [comment]
No, this level of detail isn't passed to the REST client.

**Comment by fab1an** [comment]
I need this with postgrest so that it would deliver computed/virtual columns.

**Comment by djhi** [comment]
Can't you achieve that by checking the resource and verb in a custom rest client ?

**Comment by fab1an** [comment]
Yes, I'm doing that now, I just figured it would be a fitting addition to the API. 
Your choice.
