### ISSUE TITLE
App crashed due to high memory consumption

### ISSUE THREAD

**Issue by astriskit** [marmelab/admin-on-rest#930]
Hello there.
I have a chart based "List" view in my app(a SPA), where I am fetching 10000 data points( each record/point is a complex object ) at once. The component takes a few seconds, I guess, but the data is loaded in the view. But after refreshing( 'refresh' button in the List component ) the view quite some times and/or after loading the same resource for different parameters frequently, the app crashes, evidently due to memory issue. 
Taking note of the memory using the task manager, while testing the above fact, it was found that memory kept on increasing until the app was crashed. 
Any ideas/directions/suggestions on how to resolve it !?!

**Comment by fzaninotto** [comment]
Use pagination ;)

**Comment by astriskit** [comment]
@fzaninotto Thanks for the suggestion, but I am already done with the pagination as the specs are to make all the points appear in the same view. Do you think there can be any optimization done at core-level ??

**Comment by fzaninotto** [comment]
Sure, write your own `<Datagrid>` based on one of [the gazillion React Infinite Grid components](https://devarchy.com/react/need/list-virtualization).

**Comment by astriskit** [comment]
@fzaninotto Hey thanks for that link. Also, do you think my issue could be related with the redux store ?

**Comment by fzaninotto** [comment]
No idea, you should profile your code to know.

**Comment by djhi** [comment]
This might help you: https://marmelab.com/blog/2017/02/06/react-is-slow-react-is-fast.html
