### ISSUE TITLE
How can I implement Cascading Select?

### ISSUE THREAD

**Issue by motro** [marmelab/admin-on-rest#934]
I'm trying to build a create form where the user has to choose a department in a way of cascading select.

Say the data is modeled like this:
- Account
- - Company
- - - Department
- - - - Employee

In my "Create Employee" form I want to have a cascading select for the _Department_ so that I first have to choose the _Account_, then the _Company_ filtered by the selected _Account_ and lastly the _Department_ filtered by the selected _Company_.

I tried implementing it with the filter prop on _ReferenceInput_ and the component's state but it only works for the initial state. Any suggestions?

Thanks!

**Comment by Balipeace** [comment]
https://github.com/marmelab/aor-dependent-input

**Comment by motro** [comment]
Thanks @Balipeace, but I wanted to know if there's an AOR way of doing this, one which takes into consideration the resources and applies the filters on the dependent select.

[aor-dependent-input](https://github.com/marmelab/aor-dependent-input) offers a possible ad-hoc implementation but is there any chance of adding such a feature soon?

**Comment by fzaninotto** [comment]
aor-dependent-input was created and is maintained by the same team as aor. We don't intend to bring it into core.
