### ISSUE TITLE
[RFC] Pass additional properties to MuiAppBar

### ISSUE THREAD

**Issue by MrAvantiC** [marmelab/admin-on-rest#938]
Hi,

I recently wanted to edit the AppBar.
Following the documentation I created a custom layout.
When I wanted to add a property from the mui-docs to the `AppBar` component I noticed they were not passed through.

To get around this I had to write my own AppBar component like this:
```
const AppBar = ({ title, toggleSidebar, muiTheme, ...rest }) => (
    <MuiAppBar
        title={title}
        onLeftIconButtonTouchTap={toggleSidebar}
        {...rest}
    />
);
```

This is pretty much the same as the aor-AppBar except for the additional properties and therefore feels redundant to me.

Is there a specific reason these properties were excluded in aor? 
Would you guys be open to a PR that passes them through?

**Comment by djhi** [comment]
A PR would be welcome :)

**Comment by djhi** [comment]
This is done in `next`
