### ISSUE TITLE
Create actions isn't passed refresh etc

### ISSUE THREAD

**Issue by fab1an** [marmelab/admin-on-rest#939]
I registered a custom "actions" component in `<Create/>`. 
It doesn't received any of the "interesting" props like the `refresh()`-function that is avaialbe in `<Edit/>`.

**Comment by djhi** [comment]
It doesn't because you can't refresh a non existing resource. Can you explain your usecase ?

**Comment by fab1an** [comment]
I have a Create which gets submitted on Enter.
Then I want to clear the form to be able to input the next element.
Redirecting Create to Create doesn't work, see #941.

I've learned that redux-router isn't able to refresh a page by going to the same URL, so I thought I could leverage the `refresh()` action passed to the actions.

**Comment by djhi** [comment]
I'll close this one in favor of #941 then. As explained, you can't refresh a non existing resource.

**Comment by fab1an** [comment]
Ok, thanks.
