### ISSUE TITLE
Eternal Loading State of Admin Store After Update/Delete Actions

### ISSUE THREAD

**Issue by mstmustisnt** [marmelab/admin-on-rest#95]
Can be reproduced in example project.
Steps to reproduce in example project of this repo:
1. `make run`
2. Open any list.
3. Click Edit button.
4. Click `Save` (or `Delete` and confirm the action)/

State of admin store contains `{loading: 1}`

**Comment by fzaninotto** [comment]
I can reproduce the bug. It's probably a regression due to https://github.com/marmelab/admin-on-rest/pull/59/files#diff-f655f87781f45b395da3013151ef2dc1. I'll investigate.

**Comment by mstmustisnt** [comment]
thank you very much @fzaninotto
