### ISSUE TITLE
Feature Request: Avatar and Name of current login user to AppBar

### ISSUE THREAD

**Issue by Dr8g0n** [marmelab/admin-on-rest#950]
Thanks!

**Comment by djhi** [comment]
You can do it by yourself by following the [custom application documentation](https://marmelab.com/admin-on-rest/CustomApp.html).

I leave this open until we decide whether it should be included by default but I doubt it will.

**Comment by fzaninotto** [comment]
If it's hard, we'll make it easier, but it won't be part of the core. There are too many ways to display the connected user (with or without avatar, username, name or email, showing a logout button and/or a preferences pane...). It's outside of aor's scope to deal with user authentication.
