### ISSUE TITLE
how to show the SelectArrayField in list page

### ISSUE THREAD

**Issue by passionguy** [marmelab/admin-on-rest#951]
when i want to show SelectArrayField or CheckboxGroup field in list page，i fund ReferenceArrayField、ReferenceManyField，but these is not suit for local arrays , maybe i need to use FunctionField ？

best regards to aor!

**Comment by djhi** [comment]
This is not supported right now. However, @MhdSyrwan started a PR about it: https://github.com/marmelab/admin-on-rest/pull/697

**Comment by djhi** [comment]
A custom component could do the work too

**Comment by passionguy** [comment]
@djhi yes , we implement this component like this by custom. Thanks.

```
const styles = {
    chip: {
        margin: 4,
    },
    wrapper: {
        display: 'flex',
        flexWrap: 'wrap',
    },
};
const SelectArrayField = ({source, record, choices, elStyle, optionValue, optionText, translate, translateChoice = {}}) => {
    const value = record[source];
    if (!value) return null;
    return <div style={styles.wrapper}>{value.map(v => {
        const choice = choices.find(c => c[optionValue] === v);
        return <Chip style={styles.chip}>{choice[optionText]}</Chip>
    })}</div>;
};
```
