### ISSUE TITLE
page didn't redirect to login page when fobidden

### ISSUE THREAD

**Issue by ickma** [marmelab/admin-on-rest#958]
I am using admin-on-rest, now everything is fine, except authentication: in my backend, I have permission controls, user without token will get 403 forbidden response, but , when browser received 403 (401)status code , it din't redirect to login page itself.      
How to fix?Should I describe more details?

**Comment by djhi** [comment]
Have you read the [documentation](https://marmelab.com/admin-on-rest/Authentication.html#catching-authentication-errors-on-the-api) about this ?

**Comment by ickma** [comment]
It worked!Thanks!My fault!
