### ISSUE TITLE
Not able to set title on Delete view

### ISSUE THREAD

**Issue by natrim** [marmelab/admin-on-rest#961]
Well this one is not really bug, but there seems to be no (easy) way to set title in Delete View

example can be found in the demo:
go to https://marmelab.com/admin-on-rest-demo/#/categories/0
click `edit` it will open product and you will see custom Title
then click `Delete` and you see no custom title

There seems to be no way to set it, as `Delete` view is created directly in `CrudRoute` and no custom props are passed.

The only way seems to be to make custom `Delete` view:
```
const DeleteTitle = ({ record }) => {
  return (<span>Delete {record ? `"${record.name}"` : ''}</span>);
};
const CustomDelete = (props) => <Delete {...props} title={<DeleteTitle />} />;
```
And pass custom delete to `Resource` remove

**Comment by djhi** [comment]
Actually, that's the way to do it

**Comment by djhi** [comment]
See https://github.com/marmelab/admin-on-rest/issues/963
