### ISSUE TITLE
Auto-refresh

### ISSUE THREAD

**Issue by RWOverdijk** [marmelab/admin-on-rest#964]
I'm to implement auto-refresh (every x seconds) in the List. Unless I missed it, I don't think that's currently possible.

Would this be a welcome feature? If so, do you have any pointers as to how I can implement this?

**Comment by djhi** [comment]
Yes, it is possible with a [custom saga](https://marmelab.com/admin-on-rest/Admin.html#customsagas). We also made an addon to ease this: [aor-realtime](https://github.com/marmelab/aor-realtime)

**Comment by RWOverdijk** [comment]
ffff......... 😅

**Comment by djhi** [comment]
Let me know how it goes, we only used it for an old graphql client implementation and haven't really used it since

**Comment by RWOverdijk** [comment]
@djhi Will do. It looks a tad complex for what I want, but it's a great start to learn more about the way aor works. 👍  Thanks!

**Comment by RWOverdijk** [comment]
Sorry for the spam.

I looked into this solution, and I'm pretty sure it can be made easier. For example, I just want to call this method every x seconds https://github.com/marmelab/admin-on-rest/blob/master/src/mui/list/List.js#L137

If I use the approach used in aor-realtime, I need to perform my own fetch (and apply filters to it etc). Or am I missing something?

**Comment by djhi** [comment]
As you can see in the readme, you can inject the `restClient` in a factory function creating the `observer`.

The observer will be called with the exact same parameters expected by the `restClient` so you just have to pass them through. Those parameters will include the filters.

**Comment by RWOverdijk** [comment]
@djhi Ah, alright. I missed that.

I'm checking the type now so I only watch Lists I want to watch. but how can I tell it to proceed as normal if it's not the list I want to watch? If I don't want to subscribe?

It also now keeps watching even when I'm on another page (makes sense as it's an interval). How do I stop watching when I navigate away? I found unsubscribe in the example, but it's not being called. I literally copy pasted the example in the readme to make sure I couldn't mess up.

It seems to work for the rest. The only other thing I found was:

> [...effects] has been deprecated in favor of all([...effects]), please update your code

**Comment by djhi** [comment]
> I'm checking the type now so I only watch Lists I want to watch. but how can I tell it to proceed as normal if it's not the list I want to watch? If I don't want to subscribe?

Not possible currently, that would be a nice addition to it though. I think there are two ways of doing it:
- Add an optional `filter` as the last parameter of the `realtimeSaga` factory function. It would be a function returning either `true` or `false`, determining whether to start real time update for a restClient request. It would receive the same parameters as the `restClient`
- Allow the `observeRequest` function  to returns `null` (maybe simpler)

> It also now keeps watching even when I'm on another page

Looks like a bug. If I remember correctly, a route change should make the observer unsubscribe. I'll look into it ASAP. If you're faster, make a pull request ;)

About the effects warning, we have to upgrade redux-saga and our usage of it. No big deal though, that's just a deprecation warning. Pull requests are welcome too here :p

**Comment by RWOverdijk** [comment]
@djhi Alrighty :) I'll try to figure it out.

Doe custom sagas overwrite all default sagas? Or add to them? If they get added you can just opt to do nothing so the next saga picks it up? Otherwise I can just proxy them and call the restClient myself (without the interval).

I'll just play with it to find out what's what.

**Comment by djhi** [comment]
> Doe custom sagas overwrite all default sagas?
They are added

> If they get added you can just opt to do nothing so the next saga picks it up?
Can you elaborate ? You mean outside of `aor-realtime` right ?
