### ISSUE TITLE
previousData on update (and delete)

### ISSUE THREAD

**Issue by grahamlyus** [marmelab/admin-on-rest#968]
I see `previousData` is passed in `params` to the Rest Clients on the `UPDATE` action, but i don't see it in the documentation. It would also be useful to have this on `DELETE` (could be named `data` or `previousData`).

My primary motivation for needing this is for replacing/removing files that may be uploaded to a Firebase bucket when records are updated/deleted, otherwise it would require a re-read of Firebase data within the Rest Client.

It looks like this would be easy to add, as the `Delete` component has the `data` prop, just like `Edit` has for update. I think I could create a PR.

**Comment by djhi** [comment]
That looks like a nice addition. Please, go for it :+1:

**Comment by fzaninotto** [comment]
Fixed by #975
