### ISSUE TITLE
Remove event from refresh in list

### ISSUE THREAD

**Issue by RWOverdijk** [marmelab/admin-on-rest#970]
https://github.com/marmelab/admin-on-rest/blob/master/src/mui/list/List.js#L113

I think this event doesn't belong on this function. Its job is to refresh the content. I'd move it to the RefreshButton. Which is a button that triggers a refresh and is where the propogation should be stopped.

Thoughts? If you agree I'll PR this change.

**Comment by RWOverdijk** [comment]
**Update**

The reason I'd like to see this change is for a plugin I'm writing:

```jsx
import React from 'react';
import propTypes from 'prop-types';
import Actions from 'admin-on-rest/lib/mui/list/Actions';

export class ListActions extends React.Component {
  refreshTimer = null;

  static propTypes = {autoRefreshInterval: propTypes.number};

  static defaultProps = {autoRefreshInterval: 2000};

  render() {
    return <Actions {...this.props} />
  }

  triggerRefresh() {
    this.refreshTimer = setTimeout(() => {
      this.props.refresh({stopPropagation: () => {}});

      this.triggerRefresh();
    }, this.props.autoRefreshInterval);
  }

  componentDidMount() {
    // Start refreshing
    this.triggerRefresh();
  }

  componentWillUnmount() {
    // Stop refreshing
    clearTimeout(this.refreshTimer);
  }
}
```

Which I'm using:

```jsx
<List {...this.props} perPage={99999} actions={<ListActions autoRefreshInterval={5000} />}>
  ...
</List>
```

It works now, but I feel like I shouldn't have to pass in the noop.

**Comment by djhi** [comment]
Agreed. Please open a PR :) However, in `1.3.0`, we're going to use a redux action for refresh anyway: https://github.com/marmelab/admin-on-rest/pull/942

**Comment by RWOverdijk** [comment]
@djhi That's what this does, too, right? So it's essentially the same thing (regardless of the action) or am I missing something? Because if it's completely different there's no need to fix this.

**Comment by djhi** [comment]
In #942, we removed the `refresh` function altogether from the `List` component (and `Edit` and `Show`). So yes, the click event is completely managed by the button itself

**Comment by djhi** [comment]
However, your proposed fix does not introduce any changes from a user point of vue, apart for allowing better usage, so your PR would be welcome

**Comment by RWOverdijk** [comment]
But if the function gets removed completely, my PR wouldn't make sense.

**Comment by djhi** [comment]
It will for the `1.2.3` release ;)

**Comment by RWOverdijk** [comment]
Ah but then I'd rather hold off for 1.3.0. I can live with the noop argument then :) It's a tiny workaround for something that will already be removed. Thanks!
