### ISSUE TITLE
Handling of 403 Forbidden

### ISSUE THREAD

**Issue by Download** [marmelab/admin-on-rest#974]
The docs on Authentication state that:

> Upon receiving a 403 response, the admin app shows the Login page. 

This is wrong isn't it?

My understanding has always been:

* Anon tries to access restricted page
   * Is user authenticated?  No?  => **401 Unauthorized**  (should be: Unauthenticated)
* User logs in as 'John'
* John tries to access restricted page
   * Is user authenticated?  Yes, as 'John'
   * Does 'John' have permissions?  No? => **403 Forbidden**  (meaning: Unauthorized)

Sending to a login page is only sensible if the user is not logged in yet. If 403 is returned, it means the user is logged in, but still not allowed access. He should first log out and then log in **as a different user**.

**Comment by djhi** [comment]
**By default**, if you provided an `authClient` a failed fetch will redirect to the login page.

However, you can customize it easily. See [Catching Authentication Errors On The API](https://marmelab.com/admin-on-rest/Authentication.html#catching-authentication-errors-on-the-api).

**Comment by Download** [comment]
My point was more that 403 effectively means 'you are logged in but do not have permission', so an error page might be more appropriate then a login page. But thanks anyway!

**Comment by angshuman-agarwal** [comment]
I agree with @Download . In my case, there is not loginPage and I would like to show a pop-up / custom page saying user is not entitled. Is that possible ?

**Comment by fzaninotto** [comment]
Everything is possible, since it's your `authClient` that conveys the logout logic.

**Comment by angshuman-agarwal** [comment]
I did promise.reject(redirect to...). But it always goes to my login page and not to custom redirected page. Any sample.please ?

**Comment by fzaninotto** [comment]
Whenever you reject a promise in the `authClient`, it goes to the login page. If you want to add a custom redirection in reaction to a custom event, you'll have to add a custom saga.

**Comment by angshuman-agarwal** [comment]
OK thanks, I commented on an already asked question on SO - https://stackoverflow.com/a/47527414/763026

Could you please answer that ?

How and where do you define this custom action ? Also in the [sample link](https://marmelab.com/admin-on-rest/Admin.html#customsagas), where is definition for BITCOIN_RATE_RECEIVED i.e. how is this action being registered with Admin app ?

**Comment by fzaninotto** [comment]
StackOverflow is the right place to ask "How To" questions, please don't cross-post here.

**Comment by angshuman-agarwal** [comment]
OK, may be 2nd part is !How to" but could please clarify this (related to your earlier response) ?

_**Redirection in reaction to a custom event**_

I am not reacting to custom event. I am reacting to AUTH_ERROR and this type is a valid type in authClient. So, in AUTH_ERROR I want to redirect to custom page. How is the `custom event` related here  to 'AUTH_ERROR' type ? I am sorry - I am not very clear.

**Comment by fzaninotto** [comment]
You can't have a side effect in the `authClient`. The only way is to react to *actions* in a custom saga. `AUTH_ERROR` isn't an action, it's an auth verb. The action you should react to is `FETCH_ERROR`.

This is definitely a "how to" question, so please go to SO for further details.

**Comment by Download** [comment]
@fzaninotto 
My original issue still stands however:

> Upon receiving a 403 response, the admin app shows the Login page.

This is simply wrong/unexpected behaviour.
Redirect to login page is expected upon 401 response:

> #### 10.4.2 401 Unauthorized
> The request requires user authentication.
https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.2

The meaning of 403 is that access is simply denied for the current credentials:

> #### 10.4.4 403 Forbidden
> The server understood the request, but is refusing to fulfill it. **Authorization will not help** and the request SHOULD NOT be repeated.
https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.4 
*(emphasis mine)*

**Comment by fzaninotto** [comment]
I've already answered that: handling of HTTP error codes is done by the `authClient`, therefore it's on your side. Admin-on-rest lets you do whatever you want. See e.g. 

https://github.com/marmelab/admin-on-rest/blob/05ecacddfe2efbb492d6d096d5d25ad11e9d9084/example/authClient.js#L38-L41

There is no instance of 401 or 403 in the admin-on-rest code.

**Comment by Download** [comment]
I see this behavior with the default auth client.

**Comment by fzaninotto** [comment]
Thanks a lot, much appreciated!
