### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by RWOverdijk** [marmelab/admin-on-rest#979]
I'm getting the following deprecation warning:

> [...effects] has been deprecated in favor of all([...effects]), please update your code

Ref: https://github.com/marmelab/aor-realtime/issues/4

**Comment by fzaninotto** [comment]
Can you give a test case to reproduce it?

**Comment by RWOverdijk** [comment]
This has been a while. I'll close it until/if I find it again.
