### ISSUE TITLE
Logo / image in header (custom title)

### ISSUE THREAD

**Issue by RWOverdijk** [marmelab/admin-on-rest#980]
> **Q: I'd like to be able to add a logo in the header. Would this involve a custom theme, or is there a less invasive way of doing this?**

------

I found the answer to this and thought I'd open & close an issue for archiving and feature searchers.

The title prop on `<Admin />` accepts a node. So this works:

```jsx
const App = () => (
  <Admin title={<AppTitle />}>
    // Resources
  </Admin>
);

// Default styles
const appTitleStyles = {
  whiteSpace        : 'nowrap',
  overflow          : 'hidden',
  WebkitTextOverflow: 'ellipsis',
  textOverflow      : 'ellipsis',
  margin            : 0,
  letterSpacing     : 0,
  fontSize          : 24,
  fontWeight        : '400',
  color             : 'rgb(255, 255, 255)',
  height            : 44,
  paddingTop        : 10,
  paddingBottom     : 10,
  WebkitFlex        : '1 1 0%',
  MsFlex            : '1 1 0%',
  flex              : '1 1 0%'
};

const AppTitle = () => (
  <img style={appTitleStyles} src="./my-cool-logo.png" />
);

export default App;
```

**Comment by djhi** [comment]
> I found the answer to this and thought I'd open & close an issue for archiving and feature searchers.

StackOverflow would be even better ! ;)

**Comment by RWOverdijk** [comment]
@djhi Of course!

https://stackoverflow.com/questions/45916762/custom-title-with-image-in-admin-on-rest/45916763#45916763
