### ISSUE TITLE
Filter loses focus after reloading list

### ISSUE THREAD

**Issue by fab1an** [marmelab/admin-on-rest#984]
I have a simple textinput field like described here: https://marmelab.com/admin-on-rest/List.html

When I enter something and wait a bit, the list filters correctly, but focus is lost on the TextInput.

I've checked out the demo-application as well, where that isn't the case.

**Comment by fab1an** [comment]
Ok I realized this happens when you pass the ReactElement of `<Filter>` directly to `filters=` instead of wrapping it in `React.createElement` first. Man… react can be confusing.

**Comment by thanh-mk1** [comment]
@fab1an I have same issue. Could you post an example what did you do?
