### ISSUE TITLE
DateInput Filter first passed as String, then as Date

### ISSUE THREAD

**Issue by fab1an** [marmelab/admin-on-rest#989]
1. add a DateInput filter (without any custom options, parsing or formatting) 
2. Select  something: the selected filter value is passed as `String` to the rest-client.
3. it works
4. navigate away to a different resource and navigate back
5. the selected value is now passed as `Date` to the rest-client, which breaks the filtering

![screen shot 2017-08-31 at 12 53 53](https://user-images.githubusercontent.com/55547/29920001-c9e2e69a-8e4b-11e7-962d-36ee841b9d96.png)

**Comment by djhi** [comment]
IMO, the `DateInput` should always returns a `Date` object.

**Comment by fab1an** [comment]
Strange.
Is the filter serialised and reconstructed via the URL when switching navigation?

**Comment by fab1an** [comment]
Can you reproduce this?

**Comment by fab1an** [comment]
I think the problem lies here. When value is copied twice (once a couple of lines further up) this occurs 

https://github.com/marmelab/admin-on-rest/blob/84f452b4e5f6c224bf4b6db7ec617b22f3d15610/src/mui/input/DateInput.js#L47

**Comment by djhi** [comment]
You noticed the [MUI DatePicker](http://www.material-ui.com/#/components/date-picker) requires a Date object ?

**Comment by fab1an** [comment]
What do you mean?

**Comment by djhi** [comment]
If it does require a Date object, we must transform the value to a date before passing it to it

**Comment by fab1an** [comment]
Oh, yes, of course, that is not what I meant. I just noticed that the bug went away when I removed the `{...input}` copying of props further up. I figured `input.value` was passed twice, once via spread, once directly.
