### ISSUE TITLE
Using bootstrap instead of material ui

### ISSUE THREAD

**Issue by gantir** [marmelab/admin-on-rest#992]
I am working on a project where I will need AOR to work with bootstrap. I am looking at the code to get it working with bootstrap. I was thinking of abstracting ui components so that we can wrap it with bootstrap components, but I see that it is not as straight forward.
If you can guide me with on how to go about (sample code/ direction). I would like to first get it working for me and subsequently submit a PR.

**Comment by fzaninotto** [comment]
Duplicate of #249
