### ISSUE TITLE
camelCase Field source naming doesn't produce readable labels like snake_case does

### ISSUE THREAD

**Issue by zifnab87** [marmelab/admin-on-rest#994]
for example `is_resolved` in field source creates `IS RESOLVED`
while `isResolved` creates `ISRESOLVED` 

`<BooleanField source="isResolved" />`
vs
`<BooleanField source="is_resolved" />`

any plans for supporting camelCase and PascalCase?

Thanks!

**Comment by djhi** [comment]
Unfortunately, inflection does not humanize camelCase strings. I remember having tried another lib which did. I'll investigate

**Comment by mattaylor** [comment]
https://lodash.com/docs/4.17.4#startCase

**Comment by djhi** [comment]
@fzaninotto Are you ok with replacing inflection by pluralize (which can singularize too and is used on aor-graphql) and lodash.startCase which handle the humanization better ?

**Comment by fzaninotto** [comment]
I suggest we rather open a PR on https://github.com/dreamerslab/node.inflection to support CamelCase

**Comment by Kmaschta** [comment]
Actually, `inflection` does support CamelCase -> underscore and underscore to -> humanize.
See the PR linked above!

**Comment by djhi** [comment]
Fixed by #1546 (will be released in 2.0)
