### ISSUE TITLE
Unexpected token, expected {

### ISSUE THREAD

**Issue by shenshouer** [marmelab/admin-on-rest#996]
./src/posts.js
Syntax error: Unexpected token, expected { (3:7)

  1 | import React from 'react';
  2 | import { List, Datagrid, Edit, Create, SimpleForm, DateField, TextField, EditButton, DisabledInput, TextInput, LongTextInput, DateInput } from 'admin-on-rest';
> 3 | export PostIcon from 'material-ui/svg-icons/action/book';
    |        ^
  4 |
  5 | export const PostList = (props) => (
  6 |     <List {...props}>

**Comment by wedneyyuri** [comment]
Probably your syntax is incorrect. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export for a reference.

**Comment by aansel** [comment]
@wedneyyuri What @shenshouer describes is the error you get by just following the admin-on-rest documentation. I have the same error.

**Comment by fzaninotto** [comment]
The `export from` syntax isn't standard ES6, and it requires an extension. We should use a more standard approach in the doc.
