### ISSUE TITLE
Integration with keystoneJS api

### ISSUE THREAD

**Issue by arturkasperek** [marmelab/admin-on-rest#997]
KeystoneJS is in my opinion awesome tool. You create collections and out of the box, you have API and admin view for that. But the problem is that keystoneJS give us admin panel with poor customization option, in that area better tool is admin on rest. Since keystone is using REST api I thoughted it would be awesome to make some adapter for that 2 tools to use admin view from admin on rest and backend stuff from keystoneJS ( creating collections, makeing rest API ). What do you think about that idea?

**Comment by djhi** [comment]
It would probably be but that's outside the scope of this project. Feel free to implement a custom [restClient](https://marmelab.com/admin-on-rest/RestClients.html#writing-your-own-rest-client) for it `KeystoneJS` first if possible and maybe a full integration later. We will gladly link it in the documentation
