### ISSUE TITLE
why List is not supported in ReferenceManyField?

### ISSUE THREAD

**Issue by giokokos** [marmelab/admin-on-rest#998]
I am trying to make something similar to https://marmelab.com/admin-on-rest-demo/#/customers/438 when I navigate to tab `Reviews`. I was able to replicate it and make it work for my case  with the following code:

```

<Show {...props}>
    <ReferenceManyField target="pvplantId" reference="damages"> 
        <Datagrid rowStyle={damageRowStyle}>
            <TextField source="id"/>
            <TextField source="name"/>
        </Datagrid>
    </ReferenceManyField>
</Show>
```
I would like to be able to add pager and filters so I guess I need to use a `List` within `ReferenceManyField` according to:
```
<Show {...props}>
    <ReferenceManyField target="pvplantId" reference="damages"> 
        <List title="All Damages" {...props} filters={<DamageFilter />} actions={<Actions />} sort={{field: 'id', order: 'DESC'}} perPage={5}>
            <Datagrid rowStyle={damageRowStyle}>
                <TextField source="id"/>
                <TextField source="name"/>
            </Datagrid>
        </List>
    </ReferenceManyField>
</Show>
```

but it makes two requests one returns the correct results and the other returns all results because of `List`.

Thanks in advance

**Comment by djhi** [comment]
The `List` component is not meant to be used anywhere except as prop in `Resource`. In order to have filters, pagination or any other advanced feature inside a `ReferenceManyField`, you'll have to implement a custom component

**Comment by zifnab87** [comment]
@giokokos this is related to https://github.com/marmelab/admin-on-rest/issues/561 - I guess a redirection to the prefiltered List component is a better choice
