### ISSUE TITLE
Show component displays "List" button even when no List component defined

### ISSUE THREAD

**Issue by dimitrovs** [marmelab/admin-on-rest#999]
Maybe this is more of a feature request, but if I define a Resource with Show component and no List component then the Show component still shows a button "List" in the action bar next to "Refresh". Clicking that button goes nowhere.

For my use case I have a Users resource but a User can see only their profile and not the list of all users, so I use the Show component as a profile page.

**Comment by djhi** [comment]
Actually, that's the behavior of `Edit` and `Create` too
